const test=require('node:test');
const {assert,D,E,fresh,put,fieldCard,use,trigger,source,act,drain}=require('./chronicle-2015-helpers.cjs');
const X=global.DuelChronicle;
const select=uid=>p=>p.kind==='choice'&&p.candidates.some(c=>c.uid===uid)?{type:'choose',uids:[uid]}:null;
for(const [name,series,expected]of [
 ['Heroic Challenger - Double Lance','HERO',false],['Hero Kid','HERO',false],['Skyscraper','Scrap',false],['XYZ-Dragon Cannon','Xyz',false],['Synchronized Realm','Synchron',false],['Cocoon of Evolution','Evol',false],
 ['Summoned Skull','Archfiend',true],['Lesser Fiend','Archfiend',true],['Celestial Sword - Eatos','Noble Arms',true],['Contrast HERO Chaos','Elemental HERO',true],['Invasion of Flames','Infestation',true],['Electric Virus','Worm',true],['Number 23: Lancelot, Dark Knight of the Underworld','Laundsallyn',true],['Steelswarm Cell','Evilswarm',true],['The Eye of Timaeus','Legendary Dragon',true],['The Fang of Critias','Legendary Dragon',true],['The Claw of Hermos','Legendary Dragon',true]
])test(name+' OCG membership: '+series,()=>{const c=D.cardByName(name);assert.ok(c,name);assert.equal(D.inArchetype(c,series),expected);assert.equal(X.series(c,series),expected);});
test('Stratos cannot search a Heroic Challenger masquerading as HERO',()=>{const e=fresh(),s=put(e,0,'hand','Elemental HERO Stratos'),bad=put(e,0,'deck','Heroic Challenger - Double Lance'),good=put(e,0,'deck','Destiny HERO - Malicious');act(e,{type:'summon',uid:s.uid});drain(e,p=>p.kind==='input'&&p.group.key==='mode'?{type:'choose',uids:['mode:search']}:select(good.uid)(p));assert.equal(e.find(good.uid).zone,'hand');assert.equal(e.find(bad.uid).zone,'deck');});
test('Generation Force searches Xyz spells but cannot search Xyz Agent',()=>{const e=fresh(),s=put(e,0,'hand','Generation Force');fieldCard(e,0,'Number 39: Utopia');const good=put(e,0,'deck','Xyz Unit'),bad=put(e,0,'deck','Xyz Agent');use(e,s,'cast',{},p=>{if(p.kind==='choice')assert.ok(!p.candidates.some(c=>c.uid===bad.uid));return select(good.uid)(p);});assert.equal(e.find(good.uid).zone,'hand');assert.equal(e.find(bad.uid).zone,'deck');});
test('Ophion uses Infestation membership and still excludes its monster member',()=>{const e=fresh(),x=fieldCard(e,0,'Evilswarm Ophion'),mat=put(e,0,'grave','Battle Ox'),q=put(e,0,'deck','Infestation Infection'),bad=put(e,0,'deck','Invasion of Flames');e.attach(x.uid,mat.uid,source(e));use(e,x,'era-effect',{},p=>{if(p.kind==='choice')assert.ok(!p.candidates.some(c=>c.uid===bad.uid));return select(q.uid)(p);});assert.equal(e.find(q.uid).zone,'hand');assert.equal(e.find(bad.uid).zone,'deck');});
test('Archfiend Heiress really searches a rule-treated member after being sent',()=>{const e=fresh(),h=fieldCard(e,0,'Archfiend Heiress'),q=put(e,0,'deck','Lesser Fiend');trigger(e,()=>e.move(h.uid,'grave',{kind:'effect-send',source:source(e)}),select(q.uid));assert.equal(e.find(q.uid).zone,'hand');});
test('Cyberload checks the printed Cyber Dragon material, not the Cyber deck theme',()=>{const e=fresh();for(const n of ['Cyber Twin Dragon','Cyber End Dragon','Chimeratech Rampage Dragon','Chimeratech Overdragon'])assert.equal(e.fusionAllowed(D.cardByName(n),'cyberload-fusion'),true,n);assert.equal(e.fusionAllowed(D.cardByName('Cyber Blader'),'cyberload-fusion'),false);});
test('Arsenal Summoner respects the five printed exceptions despite Guardian membership',()=>{const e=fresh(),s=fieldCard(e,0,'Arsenal Summoner'),good=put(e,0,'deck','Guardian Elma'),bad=put(e,0,'deck','Celtic Guardian');s.faceUp=false;trigger(e,()=>e.flipFaceUp(s.uid,{position:'attack'}),p=>{if(p.kind==='input')assert.ok(!p.group.candidates.some(c=>c.uid===bad.uid));return select(good.uid)(p);});assert.equal(e.find(good.uid).zone,'hand');assert.equal(e.find(bad.uid).zone,'deck');});
