import test from 'node:test';import assert from 'node:assert/strict';
import {parseFusion,parseSynchro} from '../scripts/lib/card-materials.mjs';
const options={norm:s=>s.toLowerCase(),byName:new Map([['nitro synchron','nitro'],['elemental hero neos','neos']]),races:{Dragon:'龙族',Warrior:'战士族',Machine:'机械族',Zombie:'不死族'},attributes:{DARK:'暗',LIGHT:'光',EARTH:'地',WATER:'水'}};
test('named Synchro Tuners use stable identities',()=>assert.deepEqual(parseSynchro('Nitro Warrior','"Nitro Synchron" + 1 or more non-Tuner monsters',options).synchro,{minTuners:1,maxTuners:1,minNon:1,tunerId:'nitro',namedSynchron:true}));
test('attribute-restricted Synchro materials preserve both sides',()=>{const s=parseSynchro('Naturia Beast','1 EARTH Tuner + 1+ non-Tuner EARTH monsters',options).synchro;assert.equal(s.tunerAttribute,'地');assert.equal(s.nonAttribute,'地');});
test('Synchro race and archetype restrictions are not discarded',()=>{assert.equal(parseSynchro('Zombie','1 Tuner + 1 or more non-Tuner Zombie-Type monsters',options).synchro.nonRace,'不死族');assert.equal(parseSynchro('Alien','1 Tuner + 1 or more non-Tuner "Alien" monsters',options).synchro.nonNameIncludes,'Alien');});
test('Fusion grammar supports variable Machines and minimum Levels',()=>{const f=parseFusion('Machine','1 Machine monster + 1+ Machine monsters',options);assert.equal(f.fusion.length,2);assert.deepEqual(f.fusionMore,{race:'机械族'});assert.equal(parseFusion('Fiend','1 Warrior monster + 1 Level 6 or higher Dragon monster',options).fusion[1].minLevel,6);});
test('NEX-only and Divine Neos have explicit procedures instead of invented material lists',()=>{assert.equal(parseFusion('Neo-Spacian Marine Dolphin','unparsed effect text',options).nexOnly,true);const d=parseFusion('Elemental HERO Divine Neos','special text',options);assert.equal(d.fusion.length,5);assert.equal(d.fusionDiversity.length,3);});
test('unknown Fusion and Synchro wording stops import',()=>{assert.throws(()=>parseFusion('Bad','anything can be used',options),/Unparsed/);assert.throws(()=>parseSynchro('Bad','1 Tuner + 1 non-Tuner monster',options),/Unknown/);assert.throws(()=>parseSynchro('Bad','"Unknown Tuner" + 1 or more non-Tuner monsters',options),/Missing/);});
