const test=require('node:test');
const {assert,D,E,DuelEngine,put,fresh,fieldCard,act,drain,use,trigger,source}=require('./chronicle-2015-helpers.cjs');
const Y=global.DuelChronicle.year2022,zone=(e,m)=>e.find(m.uid)?.zone;
const pick=(...ms)=>p=>p.kind==='choice'&&ms.some(m=>p.candidates.some(o=>o.uid===m.uid))?{type:'choose',uids:ms.filter(m=>p.candidates.some(o=>o.uid===m.uid)).slice(0,p.max).map(m=>m.uid)}:null;
for(const rank of [false,true])test('Carrot negates an effect with '+(rank?'Rank 2 optional destruction':'Level 2 without destruction'),()=>{const e=fresh(),pot=put(e,0,'hand','Pot of Greed'),carrot=fieldCard(e,1,'Spright Carrot'),cost=fieldCard(e,1,rank?'Gigantic Spright':'Spright Blue'),before=e.state.players[0].hand.length;act(e,{type:'activate',uid:pot.uid,key:pot.id+'::cast'});act(e,{type:'respond',uid:carrot.uid,key:carrot.id+'::y22-negate',choices:{cost:[cost.uid]}});drain(e,pick(pot));assert.equal(zone(e,cost),'grave');assert.equal(e.state.players[0].hand.length,before-1);const l=e.state.chainHistory.find(l=>l.uid===pot.uid);assert.equal(l.status,'negated');assert.equal(l.reason,'effect-negated');assert.equal(e.state.log.some(v=>v.kind==='destroy'&&v.uid===pot.uid),rank);});
test('Red tributes another real monster and negates a field monster effect',()=>{const e=fresh(),m=fieldCard(e,0,'Baronne de Fleur'),red=fieldCard(e,1,'Spright Red'),cost=fieldCard(e,1,'Spright Elf');act(e,{type:'activate',uid:m.uid,key:m.id+'::y21-destroy',choices:{target:[red.uid]}});act(e,{type:'respond',uid:red.uid,key:red.id+'::y22-negate',choices:{cost:[cost.uid]}});drain(e,pick(m));assert.equal(zone(e,cost),'grave');assert.equal(zone(e,m),'grave');assert.equal(zone(e,red),'monsters');});
test('Toad negates and sets a destroyed opponent spell under its own control',()=>{const e=fresh(),s=put(e,0,'hand','Pot of Greed'),t=fieldCard(e,1,'Toadally Awesome'),cost=put(e,1,'hand','Swap Frog');act(e,{type:'activate',uid:s.uid,key:s.id+'::cast'});act(e,{type:'respond',uid:t.uid,key:t.id+'::y22-negate',choices:{cost:[cost.uid]}});drain(e,pick(s));assert.equal(zone(e,cost),'grave');assert.equal(zone(e,s),'spells');assert.equal(e.find(s.uid).owner,1);assert.equal(s.faceUp,false);assert.equal(e.state.players[0].hand.length,0);});
test('Soul Release prevents the Toad send cost, while Spright tribute costs remain payable',()=>{const e=fresh();global.DuelRuleModes.install(e,'liberation');const s=put(e,0,'hand','Pot of Greed'),t=fieldCard(e,1,'Toadally Awesome'),cost=put(e,1,'hand','Swap Frog');act(e,{type:'activate',uid:s.uid,key:s.id+'::cast'});assert.ok(!e.state.pending?.options.some(a=>a.uid===t.uid&&a.key.endsWith('y22-negate')));assert.equal(Y.canSend(e,cost),false);});
test('Double Cross takes control into the chosen actual Link-2 arrow zone and restores the choice',()=>{const e=fresh(),elf=put(e,0,'extra','Spright Elf');trigger(e,()=>e.special(0,elf.uid,{via:'link'}));const s=put(e,0,'spells','Spright Double Cross',{faceUp:false}),m=fieldCard(e,1,'Battle Ox');act(e,{type:'activate',uid:s.uid,key:s.id+'::cast',choices:{mode:['control'],target:[m.uid]}});for(let n=0;e.state.pending?.operation!=='y22-cross-zone'&&n<40;n++)act(e,e.state.pending.kind==='window'?{type:'pass'}:e.chooseAI(e.state.pending));assert.equal(e.state.pending.operation,'y22-cross-zone');const z=Number(e.state.pending.candidates.at(-1).uid),copy=DuelEngine.restore(e.snapshot());for(const q of [e,copy]){act(q,{type:'choose',uids:[String(z)]});drain(q);}assert.equal(e.state.players[0].monsters[z].uid,m.uid);assert.deepEqual(copy.snapshot(),e.snapshot());});
test('Double Cross revives an opposing GY monster to its controller’s arrow zone',()=>{const e=fresh(),elf=put(e,0,'extra','Spright Elf');trigger(e,()=>e.special(0,elf.uid,{via:'link'}));const s=put(e,0,'spells','Spright Double Cross',{faceUp:false}),m=put(e,1,'grave','Battle Ox');use(e,s,'cast',{mode:['revive'],target:[m.uid]});assert.equal(e.find(m.uid).owner,0);assert.ok(e.linkedZones(0,elf.uid).some(z=>e.state.players[0].monsters[z]?.uid===m.uid));});
test('Keldo chains to a Tear fusion and removes the required physical material',()=>{const e=fresh(),m=put(e,0,'hand','Tearlaments Merrli'),a=put(e,0,'grave','Tearlaments Havnis'),x=put(e,0,'extra','Tearlaments Kitkallos'),k=put(e,1,'grave','Keldo the Sacred Protector');e.move(m.uid,'grave',{kind:'effect-send'});e.pump();assert.equal(e.state.pending.kind,'trigger');act(e,{type:'respond',uid:m.uid,key:m.id+'::fusion'});act(e,{type:'respond',uid:k.uid,key:k.id+'::y22-shuffle',choices:{target:[m.uid]}});drain(e);assert.equal(zone(e,m),'deck');assert.equal(zone(e,x),'extra');assert.equal(zone(e,a),'grave');assert.equal(zone(e,k),'banished');});
test('Gigantic detachment is effect sending and can trigger a Tear material',()=>{const e=fresh(),g=fieldCard(e,0,'Gigantic Spright'),m=put(e,0,'grave','Tearlaments Merrli'),a=put(e,0,'grave','Tearlaments Havnis');put(e,0,'extra','Tearlaments Kitkallos');put(e,0,'deck','Spright Red');e.attach(g.uid,m.uid);use(e,g,'y22-recruit',{},pick(m));assert.equal(zone(e,m),'grave');assert.equal(e.state.log.some(l=>l.key===m.id+'::fusion'),false,'Gigantic restriction prevents a Level 5 Fusion Summon');assert.ok(e.state.chainHistory.some(l=>l.uid===g.uid));assert.equal(zone(e,a),'grave');});
test('Mudora banishes from field as cost and Exchange increases the target cap to five',()=>{const e=fresh(),m=fieldCard(e,0,'Mudora the Sword Oracle'),s=put(e,0,'grave','Exchange of the Spirit'),qs=Array.from({length:4},()=>put(e,1,'grave','Sparks'));use(e,m,'y22-shuffle',{target:[s.uid,...qs.map(m=>m.uid)]});assert.equal(zone(e,m),'banished');assert.ok([s,...qs].every(m=>zone(e,m)==='deck'));});
test('Agido can revive a Level 4 EARTH Fairy after its opponent-GY trigger',()=>{const e=fresh(),a=put(e,0,'hand','Agido the Ancient Sentinel'),m=put(e,0,'grave','Mudora the Sword Oracle'),s=put(e,1,'hand','Sparks');trigger(e,()=>e.move(s.uid,'grave',{kind:'cost-discard'}),pick(m));assert.equal(zone(e,a),'monsters');assert.equal(zone(e,m),'monsters');});
test('Blast Held by Destiny recovers a real Fairy after a hand discard',()=>{const e=fresh(),s=put(e,0,'hand','Blast Held by Destiny'),m=put(e,0,'grave','Mudora the Sword Oracle');trigger(e,()=>e.move(s.uid,'grave',{kind:'cost-discard'}),p=>p.kind==='input'?{type:'choose',uids:[m.uid]}:null);assert.equal(zone(e,m),'hand');});
test('Predator Counter does not bypass Primal Torrent immunity',()=>{const e=fresh();global.DuelRuleModes.install(e,'primal');const m=fieldCard(e,0,'Predaplant Dragostapelia'),q=fieldCard(e,1,'Blue-Eyes White Dragon');use(e,m,'y22-counter',{target:[q.uid]});assert.equal(q.y22Predator,undefined);assert.equal(e.level(q),8);});
test('Tear reuse preserves one fusion trigger, identities, and three-language resolver states',()=>{const L=require('../src/card-locales.js');require('../src/card-catalog.js');const r=require('../src/card-resolver.js').create();for(const d of D.CARD_LIST.filter(c=>c.releaseYear===2022)){for(const l of ['zh-CN','en','ja'])assert.equal(r.resolve(L[d.id].locales[l].name,{fuzzy:false}).id,d.id);assert.ok(Array.isArray(d.setcodes));}assert.equal(r.resolve('Spright Blue').status,'playable');assert.equal(r.resolve('Runick Tip').status,'pending');assert.equal(r.resolve('Tenpai Dragon Paidra').status,'not-in-pool');const e=fresh(),m=put(e,0,'hand','Tearlaments Merrli');put(e,0,'grave','Tearlaments Havnis');put(e,0,'extra','Tearlaments Kitkallos');e.move(m.uid,'grave',{kind:'effect-send'});assert.equal(e.state.triggers.filter(t=>t.uid===m.uid&&t.key===m.id+'::fusion').length,1);});
test('compiled script payload decompresses deterministically without external scripts',async()=>{const {embeddedScripts}=await import('../scripts/lib/embedded-scripts.mjs'),{gunzipSync}=require('node:zlib'),text='globalThis.example="离线・オフライン";\n';const a=embeddedScripts(text),b=embeddedScripts(text);assert.equal(a.code,b.code);const encoded=a.code.match(/atob\('([^']+)'\)/)[1];assert.equal(gunzipSync(Buffer.from(encoded,'base64')).toString(),text);assert.ok(!a.code.includes('fetch('));});
test('Smashers banish branch offers neither Ash Blossom nor Rulkallos responses',()=>{const e=fresh(),s=put(e,0,'hand','Spright Smashers'),cost=put(e,0,'grave','Spright Jet');fieldCard(e,0,'Spright Blue');fieldCard(e,1,'Tearlaments Rulkallos');put(e,1,'hand','Ash Blossom & Joyous Spring');act(e,{type:'activate',uid:s.uid,key:s.id+'::cast',choices:{cost:[cost.uid],mode:['banish']}});assert.equal(e.state.pending.kind,'choice');assert.equal(e.state.pending.operation,'y22-smash-own');});
test('full fields and missing mandatory search cards prevent starting new summon effects',()=>{const e=fresh(),s=put(e,0,'hand','Spright Starter'),b=put(e,0,'hand','Spright Blue');put(e,0,'deck','Spright Jet');for(let i=0;i<5;i++)fieldCard(e,0,'Nimble Beaver');assert.ok(!e.allActions(0).some(a=>a.uid===s.uid&&a.key?.endsWith('::cast')||a.uid===b.uid&&a.key?.endsWith('y22-special')));const q=fresh(),k=put(q,0,'hand','Keldo the Sacred Protector');put(q,0,'hand','Agido the Ancient Sentinel');assert.ok(!q.allActions(0).some(a=>a.uid===k.uid&&a.key?.endsWith('y22-special')));});
test('new annual prompts load through the Node three-language entry point',()=>{const I=require('../src/i18n.js');for(const l of ['en','ja']){I.setLanguage(l);for(const text of ['雷精','选择结算时移除的超量素材','选择连接二指向的区域','2022 年效果待落实，不可编入正式构筑'])assert.notEqual(I.text(text),text);}I.setLanguage('zh-CN');});
test('Sprind cannot return a monster recruited by battle destruction during the Damage Step',()=>{
 const e=fresh(),sprind=fieldCard(e,0,'Spright Sprind'),xyz=fieldCard(e,0,'Gigantic Spright'),unit=put(e,0,'grave','Spright Jet'),attacker=fieldCard(e,0,'Blue-Eyes White Dragon'),rat=fieldCard(e,1,'Mother Grizzly'),recruit=put(e,1,'deck','Nimble Beaver');
 e.attach(xyz.uid,unit.uid);e.state.phase='battle';act(e,{type:'attack',uid:attacker.uid,target:rat.uid});drain(e,pick(recruit));
 assert.equal(zone(e,rat),'grave');assert.equal(zone(e,recruit),'monsters');assert.equal(zone(e,unit),'overlays');
 assert.ok(!e.state.chainHistory.some(l=>l.uid===sprind.uid&&l.key.endsWith('y22-return')));
});
for(const stage of ['calc','resolving','finished'])test('Ishizu hand triggers exclude the complete Damage Step: '+stage,()=>{
 const e=fresh(),agido=put(e,0,'hand','Agido the Ancient Sentinel'),kelbek=put(e,0,'hand','Kelbek the Ancient Vanguard'),sent=put(e,1,'hand','Sparks');fieldCard(e,1,'Battle Ox',{summonKind:'effect'});
 e.state.phase='battle';e.state.frame={kind:'attack',attack:{stage}};e.move(sent.uid,'grave',{kind:'effect-send'});
 assert.equal(zone(e,sent),'grave');assert.ok(!e.state.triggers.some(t=>[agido.uid,kelbek.uid].includes(t.uid)));
 assert.equal(zone(e,agido),'hand');assert.equal(zone(e,kelbek),'hand');
});
test('Sprind still detaches and returns a monster Special Summoned outside the Damage Step',()=>{
 const e=fresh(),sprind=fieldCard(e,0,'Spright Sprind'),xyz=fieldCard(e,0,'Gigantic Spright'),unit=put(e,0,'grave','Spright Jet'),foe=put(e,1,'hand','Battle Ox');e.attach(xyz.uid,unit.uid);
 trigger(e,()=>e.special(1,foe.uid,{via:'effect'}),p=>p.kind==='input'?{type:'choose',uids:[p.group.key==='cost'?unit.uid:foe.uid]}:null);
 assert.equal(zone(e,unit),'grave');assert.equal(zone(e,foe),'hand');assert.ok(e.state.chainHistory.some(l=>l.uid===sprind.uid&&l.key.endsWith('y22-return')));
});
