const test=require('node:test');
const {assert,D,E,DuelEngine,put,fresh,fieldCard,act,drain,use,trigger,source}=require('./chronicle-2015-helpers.cjs');
const Y=global.DuelChronicle.year2021,zone=(e,m)=>e.find(m.uid)?.zone;
const pick=(...ms)=>p=>p.kind==='choice'&&ms.some(m=>p.candidates.some(o=>o.uid===m.uid))?{type:'choose',uids:ms.filter(m=>p.candidates.some(o=>o.uid===m.uid)).slice(0,p.max).map(m=>m.uid)}:null;
test('Shthana restores its revived monster and optional destruction choice from JSON',()=>{
 let e=fresh();
 const s=put(e,0,'grave','Tenyi Spirit - Shthana'),m=fieldCard(e,0,'Blue-Eyes White Dragon'),foe=fieldCard(e,1,'Battle Ox');
 e.destroy(m.uid,source(e));e.pump();
 for(let n=0;e.state.pending&&e.state.pending.operation!=='y21-shthana-destroy'&&n<40;n++){
  const p=e.state.pending;act(e,pick(m)(p)||(p.kind==='window'?{type:'pass'}:e.chooseAI(p)));
 }
 assert.equal(e.state.pending?.operation,'y21-shthana-destroy');
 assert.equal(zone(e,s),'banished');assert.equal(zone(e,m),'monsters');
 const saved=e.snapshot(),restored=DuelEngine.restore(saved);
 drain(e,pick(foe));drain(restored,pick(foe));
 assert.equal(zone(e,foe),'grave');assert.deepEqual(restored.snapshot(),e.snapshot());
 const declined=DuelEngine.restore(saved);act(declined,{type:'choose',uids:[]});drain(declined);
 assert.equal(zone(declined,foe),'monsters');assert.equal(zone(declined,m),'monsters');
});
test('a lingering Maxx C draw outside chain resolution prevents Prosperity',()=>{
 const e=fresh(),m=put(e,0,'hand','Maxx "C"'),pot=put(e,0,'hand','Pot of Prosperity');
 for(let i=0;i<3;i++)put(e,0,'extra','Baronne de Fleur');
 use(e,m,'era-draw');assert.equal(e.state.resolvingLink,null);
 const foe=put(e,1,'hand','Battle Ox'),before=e.state.players[0].hand.length;
 trigger(e,()=>e.special(1,foe.uid,{via:'effect'}));
 assert.equal(e.state.players[0].hand.length,before+1);
 assert.equal(e.state.players[0].y21EffectDraw,e.state.turn);
 assert.equal(e.allActions(0).some(a=>a.uid===pot.uid&&a.type==='activate'),false);
});
test('Prosperity blocks lingering card draws and new draw activations without spending costs',()=>{
 const e=fresh(),m=put(e,0,'hand','Maxx "C"'),pot=put(e,0,'hand','Pot of Prosperity');
 const xs=[0,1,2].map(()=>put(e,0,'extra','Baronne de Fleur'));
 use(e,m,'era-draw');use(e,pot,'cast',{count:['3'],cost:xs.map(m=>m.uid)});
 const foe=put(e,1,'hand','Battle Ox'),before=e.state.players[0].hand.length;
 trigger(e,()=>e.special(1,foe.uid,{via:'effect'}));assert.equal(e.state.players[0].hand.length,before);
 for(const name of ['Pot of Desires','Card of Demise','Maxx "C"']){
  const q=put(e,0,'hand',name),saved=e.snapshot(),a=E.byCard[q.id].find(a=>a.mode==='cast'||a.mode==='era-draw');
  assert.equal(e.act({type:'activate',uid:q.uid,key:a.key}).ok,false,name);assert.deepEqual(e.snapshot(),saved);
 }
});
test('bitter and carnival rule rewards bypass Prosperity without becoming effect draws',()=>{
 for(const rule of ['bitter','carnival']){
  const e=fresh();global.DuelRuleModes.install(e,rule);
  const pot=put(e,0,'hand','Pot of Prosperity'),xs=[0,1,2].map(()=>put(e,0,'extra','Baronne de Fleur'));
  use(e,pot,'cast',{count:['3'],cost:xs.map(m=>m.uid)});const before=e.state.players[0].hand.length;
  if(rule==='bitter'){act(e,{type:'rule-action',key:'bitter'});drain(e);}
  else{e.state.ruleMode.carnival={chainId:999,total:3,draws:[1,0]};trigger(e,()=>e.emit({type:'chain-complete',chainId:999}));}
  assert.equal(e.state.players[0].hand.length,before+1,rule);assert.notEqual(e.state.players[0].y21EffectDraw,e.state.turn);
  assert.deepEqual(DuelEngine.restore(e.snapshot()).snapshot(),e.snapshot());
 }
});
test('2021 action captions, filters and adaptation notes have English and Japanese translations',()=>{const fs=require('fs'),acorn=require('acorn'),I=require('../src/i18n.js'),values=new Set();function walk(n){if(!n||typeof n!=='object')return;if(n.type==='Literal'&&typeof n.value==='string'&&/[\u3400-\u9fff]/.test(n.value))values.add(n.value);for(const v of Object.values(n))if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')walk(v);}for(const f of fs.readdirSync('src').filter(f=>/^effects-2021.*\.js$/.test(f)))walk(acorn.parse(fs.readFileSync('src/'+f,'utf8'),{ecmaVersion:'latest'}));for(const lang of ['en','ja']){I.setLanguage(lang);for(const text of values)assert.equal(I.translated(text).untranslated,false,lang+' '+text);}I.setLanguage('zh-CN');});
test('all three localized identities and passwords resolve to the same new playable card',()=>{const L=require('../src/card-locales.js');require('../src/card-catalog.js');const r=require('../src/card-resolver.js').create();for(const d of D.CARD_LIST.filter(c=>c.releaseYear===2021)){for(const lang of ['zh-CN','en','ja'])assert.equal(r.resolve(L[d.id].locales[lang].name,{fuzzy:false}).id,d.id,d.officialName+' '+lang);assert.equal(r.resolve(String(d.providerId)).id,d.id);assert.ok(Array.isArray(d.setcodes));}assert.equal(r.resolve('Swordsoul of Mo Ye').status,'playable');assert.equal(r.resolve('Mirrorjade the Iceblade Dragon').status,'pending');assert.equal(r.resolve('Spright Blue').status,'not-in-pool');});
test('Dreaming Town resolves in the opposing Main Phase without changing the active player or normal allowance',()=>{const e=fresh(),s=put(e,0,'spells','Floowandereeze and the Dreaming Town',{faceUp:false}),r=put(e,0,'hand','Floowandereeze & Stri'),spell=put(e,1,'hand','Sparks');e.state.active=1;e.state.normalUsed=true;act(e,{type:'activate',uid:spell.uid,key:spell.id+'::cast'});assert.ok(e.state.pending.options.some(o=>o.uid===s.uid));act(e,{type:'respond',uid:s.uid,key:s.id+'::cast'});drain(e,pick(r));assert.equal(e.state.active,1);assert.equal(e.state.normalUsed,true);assert.equal(zone(e,r),'monsters');});
test('Empen prevents effects of special summoned attack-position monsters but permits defense-position effects',()=>{const e=fresh();fieldCard(e,1,'Floowandereeze & Empen',{normalSummoned:true,tributeCount:2});const r=fieldCard(e,0,'Adamancipator Researcher',{summonKind:'effect'});assert.equal(e.allActions(0).some(a=>a.uid===r.uid&&a.type==='activate'),false);r.position='defense';assert.equal(e.allActions(0).some(a=>a.uid===r.uid&&a.type==='activate'),true);});
test('Snowl permits exactly three ordinary summons including the summon already spent',()=>{const e=fresh(),s=fieldCard(e,0,'Floowandereeze & Snowl',{normalSummoned:true,tributeCount:2});const ms=[0,1,2,3].map(()=>put(e,0,'hand','Battle Ox'));act(e,{type:'summon',uid:ms[0].uid});drain(e);use(e,s,'y21-normal');for(const m of ms.slice(1,3)){act(e,{type:'summon',uid:m.uid});drain(e);}assert.equal(e.canNormal(ms[3],0),false);assert.equal(e.state.players[0].y21Normals.count,3);});
test('Scary Sea negates an inherent special summon directly to hand and grants the correct player three normals',()=>{const e=fresh();fieldCard(e,0,'Floowandereeze & Empen',{normalSummoned:true,tributeCount:2});const sea=put(e,0,'spells','Floowandereeze and the Scary Sea',{faceUp:false}),m=put(e,1,'extra','Stardust Dragon'),t=fieldCard(e,1,'Junk Synchron'),n=fieldCard(e,1,'Cyber Dragon');e.state.active=1;act(e,{type:'extra-summon',uid:m.uid,materials:[t.uid,n.uid]});assert.equal(e.state.pending.context.kind,'summon-attempt');act(e,{type:'respond',uid:sea.uid,key:sea.id+'::cast'});drain(e);assert.equal(zone(e,m),'extra');assert.equal(global.DuelChronicle.locked(e,1,'noSpecial'),true);assert.equal(e.state.players[1].y21TripleNormal,e.state.turn);assert.equal(e.state.players[0].y21TripleNormal,undefined);});
test('small bird leave replacement applies to Tributes but stops while negated',()=>{const e=fresh(),a=fieldCard(e,0,'Floowandereeze & Robina'),b=fieldCard(e,0,'Floowandereeze & Eglen',{effectNegated:true});trigger(e,()=>{e.move(a.uid,'grave',{kind:'tribute'});e.move(b.uid,'grave',{kind:'tribute'});});assert.equal(zone(e,a),'banished');assert.equal(zone(e,b),'grave');});
test('Shifter and liberation reject real send costs before any resource is spent',()=>{for(const kind of ['shifter','liberation']){const e=fresh(),f=put(e,0,'hand','Tri-Brigade Fraktall'),d=put(e,0,'hand','Dimension Shifter');if(kind==='shifter')e.state.y21ShifterUntil=e.state.turn;else e.state.ruleMode={id:'liberation',version:1,players:[{},{}]};assert.equal(e.allActions(0).some(a=>a.uid===f.uid&&a.key?.endsWith('y21-send')),false);assert.equal(e.allActions(0).some(a=>a.uid===d.uid&&a.key?.endsWith('y21-banish')),false);assert.deepEqual([f,d].map(m=>zone(e,m)),['hand','hand']);}});
test('Longyuan sent as material under liberation does not inflict GY-trigger damage',()=>{const e=fresh(),m=fieldCard(e,0,'Swordsoul Strategist Longyuan'),lp=e.state.players[1].lp;e.state.ruleMode={id:'liberation',version:1,players:[{},{}]};trigger(e,()=>e.move(m.uid,'grave',{kind:'synchro-material'}));assert.equal(zone(e,m),'banished');assert.equal(e.state.players[1].lp,lp);});
test('Chixiao material grammar requires every non-Tuner to be a Wyrm',()=>{const e=fresh(),x=put(e,0,'extra','Swordsoul Grandmaster - Chixiao'),t=e.createTokens(0,'y21-swordsoul-token',1)[0],bad=fieldCard(e,0,'Battle Ox'),good=fieldCard(e,0,'Swordsoul of Mo Ye');assert.equal(e.synchroValid(0,x,[t,bad]),false);assert.equal(e.synchroValid(0,x,[t,good]),true);});
test('the Token restriction follows its summoner even if control changes',()=>{const e=fresh(),t=e.createTokens(0,'y21-swordsoul-token',1)[0],x=put(e,0,'extra','Link Spider');e.takeControl(t.uid,1,{source:source(e)});assert.equal(e.canSpecial(0,x,{via:'link'}),false);trigger(e,()=>e.move(t.uid,'grave',{kind:'rule-send'}));assert.equal(e.canSpecial(0,x,{via:'link'}),true);});
test('a restored Revolt material choice enforces the same sets and conserves every card',()=>{let e=fresh();const s=put(e,0,'spells','Tri-Brigade Revolt',{faceUp:false}),a=put(e,0,'grave','Tri-Brigade Fraktall'),b=put(e,0,'banished','Tri-Brigade Kerass'),x=put(e,0,'extra','Tri-Brigade Ferrijit the Barren Blossom');act(e,{type:'activate',uid:s.uid,key:s.id+'::cast'});let n=0;while(e.state.pending&&!e.state.pending.sets&&n++<25){const p=e.state.pending;act(e,p.kind==='window'?{type:'pass'}:pick(x)(p)||e.chooseAI(p));}assert.ok(e.state.pending?.sets);const before=e.snapshot();e=DuelEngine.restore(before);const bad=e.act({type:'choose',uids:[a.uid]});assert.equal(bad.ok,false);assert.deepEqual(e.snapshot(),before);act(e,{type:'choose',uids:[a.uid,b.uid]});drain(e);assert.ok(['monsters','extraMonster'].includes(zone(e,x)));e.assertState();});
test('Winda blocks Revolt because reviving a group and Link Summoning are two summons',()=>{const e=fresh();fieldCard(e,1,'El Shaddoll Winda');const s=put(e,0,'spells','Tri-Brigade Revolt',{faceUp:false});put(e,0,'grave','Tri-Brigade Fraktall');put(e,0,'grave','Tri-Brigade Kerass');put(e,0,'extra','Tri-Brigade Ferrijit the Barren Blossom');assert.equal(e.allActions(0).some(a=>a.uid===s.uid&&a.type==='activate'),false);});
test('Tri-Brigade material restriction is enforced by manual Link selections',()=>{const e=fresh(),a=fieldCard(e,0,'Battle Ox'),b=fieldCard(e,0,'Dark Magician'),x=put(e,0,'extra','Knightmare Phoenix');assert.equal(e.linkValid(0,x,[a,b]),true);global.DuelChronicle.lock(e,0,'y21BeastMaterials');assert.equal(e.linkValid(0,x,[a,b]),false);});
test('Chixiao cannot select its own physical card as negation target',()=>{const e=fresh(),m=fieldCard(e,0,'Swordsoul Grandmaster - Chixiao');put(e,0,'grave','Swordsoul Blackout');const c=e.abilityContext(m.uid,m.id+'::y21-negate','main',{owner:0});assert.equal(E.get(c.key).inputs(e,c)[1].candidates.some(o=>o.uid===m.uid),false);});
test('Baronne negates a real chain once while face-up, with the used flag surviving restore',()=>{let e=fresh();const b=fieldCard(e,0,'Baronne de Fleur'),s=put(e,1,'hand','Raigeki');e.state.active=1;act(e,{type:'activate',uid:s.uid,key:s.id+'::cast'});act(e,{type:'respond',uid:b.uid,key:b.id+'::y21-negate'});drain(e);assert.equal(zone(e,b),'monsters');assert.equal(e.find(b.uid).card.y21BaronneUsed,true);e=DuelEngine.restore(e.snapshot());e.state.turn++;const t=put(e,1,'hand','Sparks');act(e,{type:'activate',uid:t.uid,key:t.id+'::cast'});assert.equal(!!e.state.pending?.options?.some(o=>o.key===b.id+'::y21-negate'),false);drain(e);});
test('Crossout can respond to a matching hand effect and suppress it after the source leaves hand',()=>{const e=fresh(),s=put(e,0,'spells','Crossout Designator',{faceUp:false}),own=put(e,0,'deck','Maxx "C"'),foe=put(e,1,'hand','Maxx "C"');e.state.active=1;const a=e.allActions(1).find(a=>a.uid===foe.uid&&a.type==='activate');assert.ok(a);act(e,a);act(e,{type:'respond',uid:s.uid,key:s.id+'::cast',choices:{name:[own.id]}});drain(e);assert.equal(zone(e,own),'banished');assert.equal(zone(e,foe),'grave');const l=e.state.chainHistory.flatMap(c=>c.links||[]).find(l=>l.sourceId===foe.id);assert.ok(l&&l.resolutionStatus==='negated'||!e.state.players[1].maxxCTurn);});
test('Prosperity excavation selection and ordering resume identically from JSON',()=>{let e=fresh();const s=put(e,0,'hand','Pot of Prosperity'),xs=[0,1,2].map(()=>put(e,0,'extra','Baronne de Fleur'));act(e,{type:'activate',uid:s.uid,key:s.id+'::cast',choices:{count:['3'],cost:xs.map(m=>m.uid)}});let steps=0;while(e.state.pending&&e.state.pending.operation!=='y21-prosperity'&&steps++<30)act(e,e.state.pending.kind==='window'?{type:'pass'}:e.chooseAI(e.state.pending));assert.equal(e.state.pending?.operation,'y21-prosperity');const copy=DuelEngine.restore(e.snapshot());drain(e);drain(copy);assert.deepEqual(copy.snapshot(),e.snapshot());});
test('manual Prosperity input cannot pay four cards for the three-card branch',()=>{const e=fresh(),s=put(e,0,'hand','Pot of Prosperity'),xs=[0,1,2,3].map(()=>put(e,0,'extra','Baronne de Fleur')),before=e.snapshot();const r=e.act({type:'activate',uid:s.uid,key:s.id+'::cast',choices:{count:['3'],cost:xs.map(m=>m.uid)}});assert.equal(r.ok,false);assert.deepEqual(e.snapshot(),before);});
test('new Xyz attribute and nonstandard Synchro metadata fail closed',()=>{const x=D.cardByName('Rilliona, the Wondrous Magistus Witch Wardrobe'),u=D.cardByName('Ursarctic Polari');assert.equal(x.xyzDifferentAttributes,true);assert.equal(u.synchro.cannotSummon,true);assert.equal(u.levelDifferenceSummon.difference,1);const e=fresh(),a=fieldCard(e,0,'Breaker the Magical Warrior'),b=fieldCard(e,0,'Skilled Dark Magician'),c=fieldCard(e,0,'Skilled White Magician'),m=put(e,0,'extra',x.id),saved=x.implementationStatus;x.implementationStatus='implemented';try{assert.equal(e.xyzValid(0,m,[a,b]),false);assert.equal(e.xyzValid(0,m,[a,c]),true);}finally{x.implementationStatus=saved;}});
test('Anima equips only a pointed-to monster and uses the captured attack value',()=>{const e=fresh(),m=put(e,0,'extra','Relinquished Anima');trigger(e,()=>e.special(0,m.uid,{via:'link',zone:'extra'}));const foes=[0,1,2,3,4].map(()=>fieldCard(e,1,'Battle Ox')),q=foes.find(q=>e.pointsTo(m.uid,q.uid));assert.ok(q);use(e,m,'y21-equip',{target:[q.uid]});assert.equal(zone(e,q),'spells');assert.equal(e.attackValue(m),1700);assert.equal(e.find(q.uid).card.equipTarget,m.uid);});
