const test=require('node:test'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {assert,D,E,DuelEngine,put,fresh,fieldCard}=require('./gx-helpers.cjs');
const Decks=require('../src/deck-tools.js'),root=path.resolve(__dirname,'..'),id=n=>D.cardByName(n).id;
function act(e,a){const r=e.act(a);assert.equal(r.ok,true,JSON.stringify(a)+' / '+r.error);}
function drain(e,{triggers=[],pick}={}){let n=0;while(e.state.pending&&e.state.winner===null&&n++<220){const p=e.state.pending;let a=pick?.(p,e);if(!a){if(p.kind==='window')a={type:'pass'};else if(p.kind==='trigger'&&!p.trigger.mandatory&&!triggers.includes(p.trigger.uid))a={type:'pass'};else a=e.chooseAI(p);}act(e,a);}assert.ok(n<220,'bounded chain/choice resolution');e.assertState();}
function use(e,m,mode='era-effect',choices={},options={}){act(e,{type:'activate',uid:m.uid,key:m.id+'::'+mode,choices});drain(e,options);}
function extra(e,n,list){const m=put(e,0,'extra',n);act(e,{type:'extra-summon',uid:m.uid,materials:list.map(m=>m.uid)});drain(e);return m;}
function overlay(e,host,n='Battle Ox'){const m=put(e,host.originalOwner,'grave',n);assert.ok(e.attach(host.uid,m.uid));return m;}
function available(e,m){return E.available(e,e.find(m.uid)?.owner??0,{kind:'main'}).filter(a=>a.uid===m.uid);}

test('live card lookup preserves both Extra zones and overlay ownership after control, detach and restore',()=>{
  const e=fresh(),x=put(e,0,'extra','Wind-Up Zenmaines',{properlySummoned:true,extraSlot:1}),material=put(e,1,'grave','Battle Ox');
  e.remove(x.uid);e.state.players[0].extraMonster2=x;assert.ok(e.attach(x.uid,material.uid));
  assert.equal(e.find(x.uid).storageKey,'extraMonster2');assert.equal(e.find(x.uid).index,1);assert.equal(e.find(material.uid).owner,0);assert.equal(e.find(material.uid).parentUid,x.uid);assert.equal(e.find(material.uid).card.originalOwner,1);
  assert.ok(e.takeControl(x.uid,1));assert.equal(e.find(x.uid).zone,'monsters');assert.equal(e.find(x.uid).owner,1);assert.equal(e.find(material.uid).owner,1);
  e.detach(x.uid,[material.uid]);assert.equal(e.find(material.uid).zone,'grave');assert.equal(e.find(material.uid).owner,1);e.move(x.uid,'grave',{kind:'effect-send'});assert.equal(e.find(x.uid).owner,0);
  const before=e.find(x.uid).card;e.state=JSON.parse(JSON.stringify(e.state));assert.notEqual(e.find(x.uid).card,before);assert.equal(e.find(x.uid).card,e.state.players[0].grave.find(m=>m.uid===x.uid));
  const restored=DuelEngine.restore(JSON.parse(JSON.stringify(e.snapshot())));assert.equal(restored.find(x.uid).zone,'grave');assert.equal(restored.find(x.uid).owner,0);assert.equal(restored.find(material.uid).owner,1);assert.equal(restored.find('missing-card'),null);restored.assertState();
});
test('repeated suppression lookups immediately reflect visibility, negation, control and card movement',()=>{
  const e=fresh(),a=fieldCard(e,0,'Jinzo'),b=fieldCard(e,1,'Jinzo');assert.equal(e.rawEarly('Jinzo').length,2);
  a.faceUp=false;assert.deepEqual(e.rawEarly('Jinzo').map(f=>f.card.uid),[b.uid]);b.effectNegated=true;assert.equal(e.rawEarly('Jinzo').length,0);a.faceUp=true;a.pendingActivation=true;assert.equal(e.rawEarly('Jinzo').length,0);a.pendingActivation=false;assert.equal(e.rawEarly('Jinzo').length,1);b.effectNegated=false;
  assert.ok(e.takeControl(b.uid,0));assert.deepEqual(e.rawEarly('Jinzo').map(f=>f.owner),[0,0]);e.move(a.uid,'grave',{kind:'effect-send'});const found=e.rawEarly('Jinzo');assert.equal(found.length,1);assert.equal(found[0].card.uid,b.uid);assert.equal(found[0].index,e.find(b.uid).index);
  const restored=DuelEngine.restore(JSON.parse(JSON.stringify(e.snapshot())));assert.deepEqual(restored.rawEarly('Jinzo').map(f=>[f.owner,f.card.uid]),[[0,b.uid]]);assert.deepEqual(restored.rawEarly('a card that does not exist'),[]);
});

for(const [name,material] of [['Masked HERO Vapor','Elemental HERO Bubbleman'],['Masked HERO Goka','Elemental HERO Burstinatrix'],['Masked HERO Dian','Elemental HERO Clayman']])test(name+' retains its effect classification and can only enter through Mask Change',()=>{
  const e=fresh(),m=put(e,0,'extra',name),hero=fieldCard(e,0,material),s=put(e,0,'hand','Mask Change'),d=D.CARDS[m.id];
  assert.ok(d.effect,'single-line effect text must not import as a vanilla Fusion');assert.equal(d.masked,true);assert.equal(d.implementationStatus,'implemented');assert.equal(e.fusionValid(0,m,[hero]),false);assert.equal(e.canSpecial(0,m,{via:'effect'}),false);assert.equal(e.canSpecial(0,m,{via:'fusion'}),false);
  use(e,s,'cast',{target:[hero.uid]},{pick:p=>p.kind==='choice'&&p.operation==='special-selected'?{type:'choose',uids:[m.uid]}:null});
  assert.ok(['monsters','extraMonster'].includes(e.find(m.uid).zone));assert.equal(e.find(hero.uid).zone,'grave');assert.equal(e.find(s.uid).zone,'grave');
  e.move(m.uid,'grave',{kind:'effect-send'});assert.equal(e.canSpecial(0,m,{via:'revive'}),false);
});
test('Vapor resists effect destruction, loses that protection when negated, and can die in battle',()=>{
  const e=fresh(),m=fieldCard(e,0,'Masked HERO Vapor',{properlySummoned:true}),spell={owner:1,id:id('Raigeki'),effectType:'spell'},foe=fieldCard(e,1,'Blue-Eyes White Dragon');
  assert.equal(e.destroy(m.uid,spell),false);assert.equal(e.find(m.uid).zone,'monsters');assert.equal(e.destroy(m.uid,{owner:1,id:id('Inzektor Hornet'),effectType:'monster'}),false);
  e.state.phase='battle';e.state.active=1;act(e,{type:'attack',uid:foe.uid,target:m.uid});drain(e);assert.equal(e.find(m.uid).zone,'grave');
  const negated=fieldCard(e,0,'Masked HERO Vapor',{properlySummoned:true,effectNegated:true});assert.equal(e.destroy(negated.uid,spell),true);assert.equal(e.find(negated.uid).zone,'grave');
});
test('Goka gains exactly 100 ATK per HERO in its own GY and updates as cards leave it',()=>{
  const e=fresh(),m=fieldCard(e,0,'Masked HERO Goka',{properlySummoned:true}),a=put(e,0,'grave','Elemental HERO Avian');put(e,0,'grave','Destiny HERO - Diamond Dude');put(e,0,'grave','Battle Ox');put(e,1,'grave','Elemental HERO Clayman');
  assert.equal(e.attackValue(m),2400);e.move(a.uid,'banished',{kind:'effect-banish'});assert.equal(e.attackValue(m),2300);m.effectNegated=true;assert.equal(e.attackValue(m),2200);
});
test('Dian recruits only a Level 4 or lower HERO after its victim actually reaches the GY',()=>{
  for(const banished of [false,true]){const e=fresh(),m=fieldCard(e,0,'Masked HERO Dian',{properlySummoned:true}),enemy=fieldCard(e,1,'Battle Ox'),hero=put(e,0,'deck','Destiny HERO - Diamond Dude'),tooHigh=put(e,0,'deck','Destiny HERO - Malicious'),other=put(e,0,'deck','Heroic Challenger - Double Lance');let chose=false;if(banished)put(e,1,'spells','Macro Cosmos');e.state.phase='battle';
    act(e,{type:'attack',uid:m.uid,target:enemy.uid});drain(e,{triggers:[m.uid],pick:p=>{if(p.kind==='choice'&&p.operation==='gx-special'){chose=true;assert.ok(p.candidates.some(c=>c.uid===hero.uid));assert.ok(!p.candidates.some(c=>c.uid===tooHigh.uid||c.uid===other.uid));return {type:'choose',uids:[hero.uid]};}return null;}});
    assert.equal(chose,!banished);assert.equal(e.find(enemy.uid).zone,banished?'banished':'grave');assert.equal(e.find(hero.uid).zone,banished?'deck':'monsters');assert.equal(e.find(tooHigh.uid).zone,'deck');assert.equal(e.find(other.uid).zone,'deck');
  }
});

test('the annual source slices, preserved provider hashes and per-year counts agree',()=>{const slices=[['manifest-2009-2012.json',2093,[[2009,520],[2010,573],[2011,518],[2012,482]]],['manifest-2013-2013.json',528,[[2013,528]]]];for(const [file,total,years] of slices){const manifest=JSON.parse(fs.readFileSync(path.join(root,'data/yearly',file))),bytes=fs.readFileSync(path.join(root,manifest.catalogSnapshot));assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),manifest.catalogSHA256);assert.equal(manifest.cardCount,total);for(const [year,count] of years){const snapshot=JSON.parse(fs.readFileSync(path.join(root,`data/yearly/${year}/cards.json`))),cards=D.CARD_LIST.filter(c=>c.releaseYear===year&&c.early);assert.equal(cards.length,count);assert.equal(snapshot.cardCount,count);assert.deepEqual(new Set(cards.map(c=>c.providerId)),new Set(snapshot.cards.map(c=>c.providerId)));assert.ok(cards.every(c=>c.dateVerification==='provider_candidate'));}}});
test('seventeen distinct annual decks are valid, localized, within year and usable in both seats',()=>{const tables=['decks-2009-2012.json','decks-2013.json'].map(f=>JSON.parse(fs.readFileSync(path.join(root,'data',f))));assert.equal(tables.reduce((n,t)=>n+t.decks.length,0),17);for(const y of [2009,2010,2011,2012,2013]){const decks=Object.values(D.DECKS).filter(d=>d.year===y);const want=y===2013?5:3;assert.equal(decks.length,want);assert.equal(new Set(decks.map(d=>d.cards.slice().sort().join())).size,want);for(const d of decks){assert.equal(d.cards.length,40);assert.ok(d.extra.length<=15);assert.ok(Decks.analyze(d).valid,d.id);assert.ok([...d.cards,...d.extra].every(i=>D.CARDS[i].releaseYear<=y));assert.equal(d.sourceKind,'representative-adaptation');const e=new DuelEngine({deck:d.id,opponentDeck:d.id,seed:y,first:1}),copy=DuelEngine.restore(JSON.parse(JSON.stringify(e.snapshot())));assert.deepEqual(copy.snapshot(),e.snapshot());}}assert.equal(Object.values(D.DECKS).filter(d=>d.preset).length,43);});
test('Xyz import uses Rank, zero Level, and exact race/attribute/count restrictions',()=>{const e=fresh(),d=D.cardByName('Evolzar Laggia');assert.equal(d.type,'xyz');assert.equal(d.level,0);assert.equal(d.rank,4);const x=put(e,0,'extra',d.id),a=fieldCard(e,0,'Sabersaurus'),b=fieldCard(e,0,'Sabersaurus'),bad=fieldCard(e,0,'Battle Ox');assert.equal(e.xyzValid(0,x,[a,b]),true);assert.equal(e.xyzValid(0,x,[a,bad]),false);assert.equal(e.xyzValid(0,x,[a,a]),false);assert.equal(e.xyzValid(0,x,[a,b,bad]),false);});
test('a real Xyz Summon preserves physical identities and detaching Sangan is not leaving the field',()=>{const e=fresh(),a=fieldCard(e,0,'Sangan'),b=fieldCard(e,0,'Tour Guide From the Underworld'),m=extra(e,'Wind-Up Zenmaines',[a,b]);assert.equal(e.find(a.uid).zone,'overlays');assert.equal(e.find(a.uid).parentUid,m.uid);assert.equal(m.overlays.length,2);e.detach(m.uid,[a.uid]);e.pump();drain(e,{triggers:[a.uid]});assert.equal(e.find(a.uid).zone,'grave');assert.equal(e.state.players[0].hand.length,0);assert.ok(!e.state.log.some(l=>l.key===a.id+'::search'));});
test('Overlay Regen becomes a real material and is not cleaned up as a used Spell',()=>{const e=fresh(),x=fieldCard(e,0,'Number 39: Utopia',{properlySummoned:true}),s=put(e,0,'hand','Overlay Regen');use(e,s,'cast',{target:[x.uid]});assert.equal(e.find(s.uid).zone,'overlays');assert.equal(x.overlays[0].uid,s.uid);const copy=DuelEngine.restore(JSON.parse(JSON.stringify(e.snapshot())));assert.deepEqual(copy.snapshot(),e.snapshot());e.detach(x.uid,[s.uid]);assert.equal(e.find(s.uid).zone,'grave');});
test('Xyz Reborn revives a properly Summoned monster and attaches the actual Trap',()=>{const e=fresh(),x=put(e,0,'grave','Wind-Up Zenmaines',{properlySummoned:true}),s=put(e,0,'spells','Xyz Reborn',{faceUp:false});use(e,s,'cast',{target:[x.uid]});assert.ok(['monsters','extraMonster'].includes(e.find(x.uid).zone));assert.equal(e.find(s.uid).parentUid,x.uid);e.destroy(x.uid,{owner:1,effectType:'spell',id:id('Raigeki')});drain(e);assert.equal(x.overlays.length,0);assert.equal(e.find(s.uid).zone,'grave');});
test('unproper Extra monsters cannot be revived by Xyz Reborn',()=>{const e=fresh(),x=put(e,0,'grave','Wind-Up Zenmaines'),s=put(e,0,'spells','Xyz Reborn',{faceUp:false});assert.equal(e.canSpecial(0,x,{via:'revive'}),false);const before=e.snapshot();const r=e.act({type:'activate',uid:s.uid,key:s.id+'::cast',choices:{target:[x.uid]}});assert.ok(!r.ok||e.find(x.uid).zone==='grave');if(!r.ok)assert.deepEqual(e.snapshot(),before);});
test('Gaia Dragon transfers the previous Xyz monster and all of its materials',()=>{const e=fresh(),a=fieldCard(e,0,'Cyber Dragon'),b=fieldCard(e,0,'Cyber Dragon'),old=extra(e,'Tiras, Keeper of Genesis',[a,b]),gaia=put(e,0,'extra','Gaia Dragon, the Thunder Charger');assert.ok(e.xyzCombos(0,gaia).some(c=>c.rankUp&&c.materials[0]===old.uid));act(e,{type:'extra-summon',uid:gaia.uid,materials:[old.uid]});drain(e);assert.deepEqual(new Set(gaia.overlays.map(m=>m.uid)),new Set([a.uid,b.uid,old.uid]));assert.equal(old.overlays.length,0);});
test('Hazy Flame Basiltrice accepts two through five FIRE Level 6 materials, not six or WATER',()=>{const e=fresh(),x=put(e,0,'extra','Hazy Flame Basiltrice'),list=Array.from({length:5},()=>fieldCard(e,0,'Hazy Flame Griffin'));for(const n of [2,3,4,5])assert.ok(e.xyzValid(0,x,list.slice(0,n)));list[0].attributeOverride={value:'水'};assert.equal(e.xyzValid(0,x,list.slice(0,2)),false);});
test('Star Drawing may count as Level 5 while retaining its actual Level 4',()=>{const e=fresh(),a=fieldCard(e,0,'Star Drawing'),b=fieldCard(e,0,'Cyber Dragon'),x=put(e,0,'extra','Tiras, Keeper of Genesis'),before=e.state.players[0].deck.length;assert.equal(e.level(a),4);assert.ok(e.xyzValid(0,x,[a,b]));act(e,{type:'extra-summon',uid:x.uid,materials:[a.uid,b.uid]});drain(e);assert.equal(e.state.players[0].deck.length,before-1);});
test('Excalibur pays two materials and doubles original ATK for the specified turns',()=>{const e=fresh(),x=fieldCard(e,0,'Heroic Champion - Excalibur',{properlySummoned:true}),a=overlay(e,x),b=overlay(e,x);use(e,x);assert.equal(x.overlays.length,0);assert.equal(e.find(a.uid).zone,'grave');assert.equal(e.find(b.uid).zone,'grave');assert.equal(e.attackValue(x),4000);e.state.turn+=2;assert.equal(e.attackValue(x),2000);});
test('Xyz Unit can pay instead of an actual overlay without duplicating either card',()=>{const e=fresh(),x=fieldCard(e,0,'Superdreadnought Rail Cannon Gustav Max',{properlySummoned:true}),a=overlay(e,x),s=put(e,0,'hand','Xyz Unit');use(e,s,'cast',{target:[x.uid]});use(e,x,'era-effect',{cost:[s.uid]});assert.equal(e.find(s.uid).zone,'grave');assert.equal(e.find(a.uid).parentUid,x.uid);assert.equal(e.state.players[1].lp,6000);});
test('Freezadon substitutes one of its own real materials at most once per turn',()=>{const e=fresh(),x=fieldCard(e,0,'Superdreadnought Rail Cannon Gustav Max',{properlySummoned:true}),f=fieldCard(e,0,'Number 19: Freezadon',{properlySummoned:true}),a=overlay(e,x),b=overlay(e,f);use(e,x,'era-effect',{cost:[b.uid]});assert.equal(e.find(b.uid).zone,'grave');assert.equal(e.find(a.uid).parentUid,x.uid);assert.ok(e.wasUsed(0,f,'freezadon','card'));});
test('Road Synchron changes its material Level only when summoning another Synchro',()=>{const e=fresh(),t=fieldCard(e,0,'Road Synchron'),n=fieldCard(e,0,'Battle Ox'),x=put(e,0,'extra','Brionac, Dragon of the Ice Barrier');assert.equal(e.level(t),4);assert.ok(e.synchroValid(0,x,[t,n]));assert.equal(e.level(t),4);act(e,{type:'extra-summon',uid:x.uid,materials:[t.uid,n.uid]});drain(e);assert.equal(e.find(t.uid).zone,'grave');assert.ok(x.properlySummoned);});
test('T.G. Cyber Magician hand material appears in the actual material chooser and saves mid-choice',()=>{const e=fresh(),t=fieldCard(e,0,'T.G. Cyber Magician'),n=put(e,0,'hand','T.G. Rush Rhino'),x=put(e,0,'extra','T.G. Wonder Magician');assert.ok(e.synchroValid(0,x,[t,n]));act(e,{type:'extra-summon',uid:x.uid});assert.ok(e.state.pending.candidates.some(c=>c.uid===n.uid));const copy=DuelEngine.restore(JSON.parse(JSON.stringify(e.snapshot())));for(const game of [e,copy]){act(game,{type:'choose',uids:[t.uid,n.uid]});drain(game);}assert.deepEqual(copy.snapshot(),e.snapshot());assert.equal(e.find(n.uid).zone,'grave');});
test('Phantom King Hydride can be the non-Tuner alongside another Tuner',()=>{const e=fresh(),a=fieldCard(e,0,'Phantom King Hydride'),b=fieldCard(e,0,'Scrap Goblin'),x=put(e,0,'extra','Brionac, Dragon of the Ice Barrier');assert.ok(e.isTuner(a));assert.ok(e.isTuner(b));assert.ok(e.synchroValid(0,x,[a,b]));});
test('Gishki Shadow pays the entire WATER Ritual requirement without changing its Level',()=>{const e=fresh(),s=put(e,0,'hand','Gishki Aquamirror'),r=put(e,0,'hand','Evigishki Mind Augus'),m=put(e,0,'hand','Gishki Shadow');assert.equal(e.level(m),4);assert.ok(e.ritualValid(0,r,[m],s.id));use(e,s,'cast',{}, {pick:p=>p.purpose==='ritual'?{type:'choose',uids:[m.uid]}:p.kind==='choice'&&p.operation==='early-ritual-target'?{type:'choose',uids:[r.uid]}:null});assert.equal(e.find(r.uid).zone,'monsters');assert.ok(r.properlySummoned);assert.equal(e.find(m.uid).zone,'grave');});
test('Gishki Photomirror pays LP at resolution and needs no invented tribute cards',()=>{const e=fresh(),s=put(e,0,'hand','Gishki Photomirror'),r=put(e,0,'hand','Evigishki Mind Augus');assert.ok(e.ritualValid(0,r,[],s.id));use(e,s,'cast');assert.equal(e.state.players[0].lp,5000);assert.equal(e.find(r.uid).zone,'monsters');assert.deepEqual(r.eraRitualMaterials,[]);});
test('Forbidden Arts may use monsters on both fields and halves the summoned ATK',()=>{const e=fresh(),s=put(e,0,'hand','Forbidden Arts of the Gishki'),r=put(e,0,'hand','Evigishki Soul Ogre'),a=fieldCard(e,0,'Battle Ox'),b=fieldCard(e,1,'Battle Ox');assert.ok(e.ritualValid(0,r,[a,b],s.id));use(e,s,'cast',{}, {pick:p=>p.purpose==='ritual'?{type:'choose',uids:[a.uid,b.uid]}:null});assert.equal(e.find(a.uid).zone,'grave');assert.equal(e.find(b.uid).zone,'grave');assert.equal(e.find(b.uid).owner,1);assert.equal(e.attackValue(r),1400);assert.ok(e.attackBlocked(0));});
test('Djinn ritual material is banished and locks only the opposing player while its Ritual survives',()=>{const e=fresh(),s=put(e,0,'hand','Dawn of the Herald'),r=put(e,0,'hand','Herald of Perfection'),j=put(e,0,'grave','Djinn Releaser of Rituals'),m=put(e,0,'hand','Sangan'),other=put(e,1,'hand','Battle Ox');use(e,s,'cast',{}, {pick:p=>p.purpose==='ritual'?{type:'choose',uids:[j.uid,m.uid]}:null});assert.equal(e.find(j.uid).zone,'banished');assert.equal(e.canSpecial(1,other,{via:'effect'}),false);e.move(r.uid,'grave',{kind:'effect-send'});assert.equal(e.canSpecial(1,other,{via:'effect'}),true);});
test('Dawn of the Herald rejects an eight-Level tribute for its exact Level 6 requirement',()=>{const e=fresh(),s=put(e,0,'hand','Dawn of the Herald'),r=put(e,0,'hand','Herald of Perfection'),m=put(e,0,'hand','Blue-Eyes White Dragon');assert.equal(e.ritualValid(0,r,[m],s.id),false);assert.equal(available(e,s).length,0);});
test('Black Whirlwind retains one existing trigger, never two searches for the same Normal Summon',()=>{const e=fresh(),s=put(e,0,'spells','Black Whirlwind'),m=put(e,0,'hand','Blackwing - Shura the Blue Flame');put(e,0,'deck','Blackwing - Kalut the Moon Shadow');put(e,0,'deck','Blackwing - Blizzard the Far North');act(e,{type:'summon',uid:m.uid});drain(e,{triggers:[s.uid]});assert.equal(e.state.players[0].hand.length,1);assert.equal(e.state.log.filter(l=>l.key===s.id+'::search').length>0,true);assert.equal(e.state.log.some(l=>l.key===s.id+'::era-search'),false);});
test('Armed Wing uses one 500 ATK bonus and one piercing damage application',()=>{const e=fresh(),a=fieldCard(e,0,'Blackwing Armed Wing',{properlySummoned:true}),b=fieldCard(e,1,'Mystical Shine Ball',{position:'defense'});e.state.phase='battle';act(e,{type:'attack',uid:a.uid,target:b.uid});drain(e);assert.equal(e.state.players[1].lp,8000-(2800-500));});
test('Inzektor Hornet pays from its equip zone and Dragonfly recruits once after the chain',()=>{const e=fresh(),fly=fieldCard(e,0,'Inzektor Dragonfly'),hornet=put(e,0,'grave','Inzektor Hornet'),centipede=put(e,0,'deck','Inzektor Centipede'),enemy=fieldCard(e,1,'Blue-Eyes White Dragon');use(e,fly,'era-equip',{target:[hornet.uid]});assert.equal(e.find(hornet.uid).zone,'spells');assert.equal(hornet.equipTarget,fly.uid);use(e,hornet,'era-effect',{target:[enemy.uid]},{triggers:[fly.uid],pick:p=>p.kind==='choice'&&p.candidates?.some(o=>o.uid===centipede.uid)?{type:'choose',uids:[centipede.uid]}:null});assert.equal(e.find(hornet.uid).zone,'grave');assert.equal(e.find(enemy.uid).zone,'grave');assert.equal(e.find(centipede.uid).zone,'monsters');assert.equal(e.level(fly),3);assert.ok(!available(e,fly).some(a=>a.key.endsWith('era-equip')));});
test('Wind-Up face-up-once is distinct from a turn limit and resets after face-down',()=>{const e=fresh(),rat=fieldCard(e,0,'Wind-Up Rat'),hunter=put(e,0,'grave','Wind-Up Hunter');use(e,rat,'era-effect',{target:[hunter.uid]});assert.equal(e.find(hunter.uid).zone,'monsters');e.state.turn+=2;e.setPosition(rat.uid,'attack');assert.equal(available(e,rat).length,0);e.setPosition(rat.uid,'defense',null,true);e.flipFaceUp(rat.uid,{position:'attack'});e.move(hunter.uid,'grave',{kind:'effect-send'});assert.ok(available(e,rat).length>0);});
test('Maxx C draws once for Rescue Rabbit summoning two monsters simultaneously',()=>{const e=fresh(),maxx=put(e,0,'hand','Maxx "C"');use(e,maxx,'era-draw');const start=e.state.players[0].hand.length,rabbit=fieldCard(e,1,'Rescue Rabbit');put(e,1,'deck','Battle Ox');put(e,1,'deck','Battle Ox');e.state.active=1;use(e,rabbit);assert.equal(e.monsters(1).length,2);assert.equal(e.state.players[0].hand.length,start+1);});
test('Droll reacts to a real non-normal draw and stops subsequent additions from either Deck',()=>{const e=fresh(),bird=put(e,0,'hand','Droll & Lock Bird'),pot=put(e,1,'hand','Pot of Greed');e.state.active=1;use(e,pot,'cast',{}, {triggers:[bird.uid]});assert.equal(e.find(bird.uid).zone,'grave');const before=e.state.players[1].deck.length;assert.deepEqual(e.draw(1,2),[]);assert.equal(e.state.players[1].deck.length,before);assert.deepEqual(e.draw(0,1),[]);});
test('Herald pays one real Fairy to negate an opposing Spell',()=>{const e=fresh(),h=fieldCard(e,0,'Herald of Perfection',{properlySummoned:true}),fairy=put(e,0,'hand','Mystical Shine Ball'),pot=put(e,1,'hand','Pot of Greed'),n=e.state.players[1].deck.length;e.state.active=1;act(e,{type:'activate',uid:pot.uid,key:pot.id+'::cast'});act(e,{type:'respond',uid:h.uid,key:h.id+'::era-negate',choices:{cost:[fairy.uid]}});drain(e);assert.equal(e.find(fairy.uid).zone,'grave');assert.equal(e.state.players[1].deck.length,n);assert.equal(e.find(pot.uid).zone,'grave');});
test('Atlantean costs trigger through Mermail discards, while ordinary effect milling does not',()=>{const e=fresh(),megalo=put(e,0,'hand','Mermail Abyssmegalo'),marksman=put(e,0,'hand','Atlantean Marksman'),dragoons=put(e,0,'hand','Atlantean Dragoons'),set=put(e,1,'spells','Mirror Force',{faceUp:false});put(e,0,'deck','Abyss-sphere');put(e,0,'deck','Deep Sea Diva');use(e,megalo,'era-effect',{cost:[marksman.uid,dragoons.uid]},{triggers:[marksman.uid,dragoons.uid]});assert.ok(['monsters','extraMonster'].includes(e.find(megalo.uid).zone));assert.equal(e.find(set.uid).zone,'grave');assert.ok(e.state.players[0].hand.some(m=>D.CARDS[m.id].race==='海龙族'));const other=put(e,0,'deck','Atlantean Marksman'),set2=put(e,1,'spells','Mirror Force',{faceUp:false});e.move(other.uid,'grave',{kind:'effect-mill',source:{owner:0,id:id('Foolish Burial'),effectType:'spell'}});e.pump();drain(e,{triggers:[other.uid]});assert.equal(e.find(set2.uid).zone,'spells');});
test('the Frog cannon loop spends different Frogs and deals two exact 400 damage payments',()=>{const e=fresh(),driver=put(e,0,'spells','Mass Driver'),ronin=put(e,0,'grave','Ronintoadin'),a=put(e,0,'grave','Dupe Frog'),b=put(e,0,'grave','Treeborn Frog');for(const cost of [a,b]){use(e,ronin,'era-effect',{banish:[cost.uid]});use(e,driver,'burn',{cost:[ronin.uid]});assert.equal(e.find(cost.uid).zone,'banished');assert.equal(e.find(ronin.uid).zone,'grave');}assert.equal(e.state.players[1].lp,7200);});
test('Ronintoadin and Des Frog have independent deck copy limits but share the field name',()=>{assert.ok(Decks.analyze(D.DECKS['frog-ftk-2010']).valid);const e=fresh(),m=fieldCard(e,0,'Ronintoadin');assert.equal(e.cardNameId(m),id('Des Frog'));e.move(m.uid,'grave',{kind:'effect-send'});assert.equal(e.cardNameId(m),m.id);});
test('Grapha distinguishes effect discard from a discard paid as cost',()=>{const e=fresh(),g=put(e,0,'hand','Grapha, Dragon Lord of Dark World'),enemy=fieldCard(e,1,'Battle Ox');Hdiscard(e,g);e.pump();drain(e,{triggers:[g.uid]});assert.equal(e.find(enemy.uid).zone,'monsters');e.move(g.uid,'hand',{kind:'rule'});e.move(g.uid,'grave',{kind:'effect-discard',source:{id:id('Dark World Dealings'),owner:0,effectType:'spell'},byOwner:0});e.pump();drain(e,{triggers:[g.uid]});assert.equal(e.find(enemy.uid).zone,'grave');function Hdiscard(e,m){E.H.discard(e,{owner:0,source:{id:id('Raigeki Break'),owner:0,effectType:'trap'}},[m.uid]);}});
test('Royal Prison blocks graveyard revival but not hand summons, and its removal restores it',()=>{const e=fresh(),s=put(e,0,'spells','Royal Prison'),g=put(e,0,'grave','Battle Ox'),h=put(e,0,'hand','Battle Ox');assert.equal(e.canSpecial(0,g,{via:'revive'}),false);assert.equal(e.canSpecial(0,h,{via:'effect'}),true);e.move(s.uid,'grave',{kind:'effect-send'});assert.equal(e.canSpecial(0,g,{via:'revive'}),true);});
test('Forbidden Lance protects against Spells/Traps without protecting from monster effects',()=>{const e=fresh(),m=fieldCard(e,0,'Battle Ox'),s=put(e,0,'hand','Forbidden Lance');use(e,s,'cast',{target:[m.uid]});assert.equal(e.attackValue(m),900);assert.equal(e.destroy(m.uid,{owner:1,id:id('Raigeki'),effectType:'spell'}),false);assert.equal(e.destroy(m.uid,{owner:1,id:id('Inzektor Dragonfly'),effectType:'monster'}),true);});
test('a pending new multi-target cost and its random state survive JSON round trips',()=>{const e=fresh(),m=fieldCard(e,0,'Hieratic Dragon of Su'),cost=put(e,0,'hand','Hieratic Dragon of Eset');put(e,1,'spells','Mirror Force',{faceUp:false});act(e,{type:'activate',uid:m.uid,key:m.id+'::era-effect'});assert.ok(e.state.pending);const saved=e.snapshot(),copy=DuelEngine.restore(JSON.parse(JSON.stringify(saved)));drain(e);drain(copy);assert.deepEqual(copy.snapshot(),e.snapshot());assert.equal(e.find(cost.uid).zone,'grave');});
test('Hundred Eyes copies an actual activated effect with its own cost and target flow',()=>{const e=fresh(),eyes=fieldCard(e,0,'Hundred Eyes Dragon',{properlySummoned:true}),monk=put(e,0,'grave','Summoner Monk'),spell=put(e,0,'hand','Sparks'),bora=put(e,0,'deck','Blackwing - Bora the Spear');use(e,eyes,'era-effect',{cost:[monk.uid]});assert.equal(e.find(monk.uid).zone,'banished');const mode='copied:'+monk.id+'::recruit';assert.ok(available(e,eyes).some(a=>a.key===eyes.id+'::'+mode));use(e,eyes,mode,{cost:[spell.uid]},{pick:p=>p.kind==='choice'&&p.candidates?.some(c=>c.uid===bora.uid)?{type:'choose',uids:[bora.uid]}:null});assert.equal(e.find(spell.uid).zone,'grave');assert.equal(e.find(bora.uid).zone,'monsters');e.state.turn++;assert.ok(!available(e,eyes).some(a=>a.key===eyes.id+'::'+mode));});
test('the original Blackwing and Shining handlers remain the sole active trigger after annual reuse',()=>{for(const [cardName,mode] of [['Blackwing - Shura the Blue Flame','battle-win'],['Black Whirlwind','era-search'],['Elemental HERO The Shining','era-sent']]){const a=E.get(id(cardName)+'::'+mode);assert.equal(a.supersededByOriginal,true);assert.equal(a.condition(),false);}assert.equal(E.passives['hero-the-shining']?.stat,undefined);assert.equal(E.passives['bw-armed-wing']?.battleStat,undefined);});
test('incompatible copied abilities are filtered before constructing expensive rule contexts',()=>{const e=fresh(),copy=put(e,0,'extra','Hundred Eyes Dragon'),spell=put(e,0,'hand','Pot of Greed'),original=e.abilityContext;let copiedContexts=0;e.abilityContext=function(uid,...a){if(uid===copy.uid)copiedContexts++;return original.call(this,uid,...a);};const actions=E.available(e,0,{kind:'main'});assert.equal(copiedContexts,0);assert.ok(actions.some(a=>a.uid===spell.uid&&a.key===spell.id+'::cast'));assert.ok(!actions.some(a=>a.uid===copy.uid));});
