const test=require('node:test'),fs=require('node:fs'),crypto=require('node:crypto');
const {assert,D,E,DuelEngine,put,fresh,fieldCard,act,drain,use,trigger,source}=require('./chronicle-2015-helpers.cjs');
const pick=m=>p=>p.kind==='choice'&&p.max>0&&p.candidates?.some(o=>o.uid===m.uid)?{type:'choose',uids:[m.uid]}:null;
const onField=(e,m)=>['monsters','extraMonster'].includes(e.find(m.uid)?.zone),available=(e,m,mode)=>e.allActions(0).some(a=>a.uid===m.uid&&a.key===m.id+'::'+mode);
function link(e,n,zone='extra',pickFn){const m=put(e,0,'extra',n);trigger(e,()=>e.special(0,m.uid,{via:'link',zone}),pickFn);return m;}
function threeSpells(e){for(const n of ['Sparks','Raigeki','Dark Hole'])put(e,0,'grave',n);}
test('2018 source, exclusions, multilingual identities and five complete decks are preserved',()=>{
 const j=JSON.parse(fs.readFileSync('data/yearly/2018/cards.json')),m=JSON.parse(fs.readFileSync('data/yearly/manifest-2018-2018.json')),s=JSON.parse(fs.readFileSync('data/yearly/scope-2018-2018.json'));assert.equal(j.cardCount,672);assert.equal(j.sourceSnapshot,'data/providers/ocg-2018.json');assert.equal(crypto.createHash('sha256').update(fs.readFileSync(m.catalogSnapshot)).digest('hex'),m.catalogSHA256);assert.equal(s.excludedIdentities.length,4);
 const L=require('../src/card-locales.js');for(const c of j.cards){const d=D.CARD_LIST.find(d=>d.providerId===c.providerId);for(const l of ['zh-CN','en','ja'])assert.ok(L[d.id].locales[l].description);assert.ok(Array.isArray(d.setcodes));}
 const ds=Object.values(D.DECKS).filter(d=>d.year===2018);assert.equal(ds.length,5);for(const d of ds){assert.equal(d.extra.length,15);assert.equal(d.side.length,15);for(const id of [...d.cards,...d.extra,...d.side]){assert.notEqual(D.CARDS[id].implementationStatus,'pending');assert.ok(D.CARDS[id].releaseYear<=2018);}}
});
test('unfinished 2018 effects remain unavailable and do not leak through generic ritual handlers',()=>{for(const n of ['Impcantation Inception','Guardragon Pisty','Prank-Kids Battle Butler'])assert.equal(D.cardByName(n).implementationStatus,'pending');});
test('Kagari rejects FIRE material and Mermaid rejects itself',()=>{const e=fresh(),k=put(e,0,'extra','Sky Striker Ace - Kagari'),a=fieldCard(e,0,'Sky Striker Ace - Raye'),b=fieldCard(e,0,'Sky Striker Ace - Kagari');assert.equal(e.linkValid(0,k,[a]),true);assert.equal(e.linkValid(0,k,[b]),false);const mer=put(e,0,'extra','Knightmare Mermaid'),m=fieldCard(e,0,'Knightmare Mermaid'),p=fieldCard(e,0,'Knightmare Phoenix');assert.equal(e.linkValid(0,mer,[m]),false);assert.equal(e.linkValid(0,mer,[p]),true);});
test('Raye pays a tribute, summons to an Extra Monster Zone, and Kagari really recovers',()=>{const e=fresh(),r=fieldCard(e,0,'Sky Striker Ace - Raye'),k=put(e,0,'extra','Sky Striker Ace - Kagari'),s=put(e,0,'grave','Sky Striker Mobilize - Engage!');use(e,r,'y18-transform',{},p=>pick(k)(p)||pick(s)(p));assert.equal(e.find(r.uid).zone,'grave');assert.equal(e.find(k.uid).zone,'extraMonster');assert.equal(e.find(s.uid).zone,'hand');assert.equal(e.canSpecial(0,put(e,0,'extra','Sky Striker Ace - Kagari'),{via:'link'}),false);});
test('Raye revives when a friendly Ace leaves through an opposing effect, but not as material',()=>{const e=fresh(),r=put(e,0,'grave','Sky Striker Ace - Raye'),k=link(e,'Sky Striker Ace - Kagari');trigger(e,()=>e.move(k.uid,'grave',{kind:'link-material',byOwner:0}));assert.equal(e.find(r.uid).zone,'grave');const s=link(e,'Sky Striker Ace - Shizuku');trigger(e,()=>e.destroy(s.uid,source(e)));assert.ok(onField(e,r));});
for(const n of [2,3])test('Engage draws only with '+n+' other Spells already in GY',()=>{const e=fresh(),s=put(e,0,'hand','Sky Striker Mobilize - Engage!'),r=put(e,0,'deck','Sky Striker Ace - Raye');for(let i=0;i<n;i++)put(e,0,'grave','Sparks');use(e,s,'cast',{},pick(r));assert.equal(e.find(r.uid).zone,'hand');assert.equal(e.state.players[0].hand.length,n===3?2:1);});
test('Engage cannot activate with a monster in a Main Zone, but permits an Extra Zone Ace',()=>{const e=fresh(),s=put(e,0,'hand','Sky Striker Mobilize - Engage!');put(e,0,'deck','Sky Striker Ace - Raye');const m=fieldCard(e,0,'Battle Ox');assert.equal(available(e,s,'cast'),false);e.move(m.uid,'grave',{kind:'rule-send'});link(e,'Sky Striker Ace - Kagari');assert.equal(available(e,s,'cast'),true);});
test('Widow Anchor steals until the end phase and retains negation across JSON',()=>{let e=fresh();threeSpells(e);const s=put(e,0,'hand','Sky Striker Mecha - Widow Anchor'),m=fieldCard(e,1,'Trickstar Candina');use(e,s,'cast',{target:[m.uid]},pick(m));assert.equal(e.find(m.uid).owner,0);assert.equal(e.negated(m),true);e=DuelEngine.restore(e.snapshot());assert.equal(e.find(m.uid).owner,0);trigger(e,()=>e.endTurn());assert.equal(e.find(m.uid).owner,1);});
test('Eagle Booster shields against effects and battle at three Spells, then expires',()=>{const e=fresh();threeSpells(e);const s=put(e,0,'hand','Sky Striker Mecha - Eagle Booster'),m=fieldCard(e,1,'Battle Ox');use(e,s,'cast',{target:[m.uid]});assert.equal(e.destroy(m.uid,source(e)),false);assert.equal(e.destroy(m.uid,source(e),true),false);assert.equal(e.unaffected(m,null),false);e.state.turn++;assert.equal(e.destroy(m.uid,source(e)),true);});
test('Hornet Drones creates a real non-Tributable token that is valid Kagari material',()=>{const e=fresh();threeSpells(e);const s=put(e,0,'hand','Sky Striker Mecha - Hornet Drones'),k=put(e,0,'extra','Sky Striker Ace - Kagari');use(e,s);const m=e.monsters(0)[0];assert.equal(e.attackValue(m),1500);assert.equal(e.canTribute(m,0),false);assert.equal(e.linkValid(0,k,[m]),true);});
test('Area Zero uses only its actual top three and sends the target only on a hit',()=>{const e=fresh(),s=put(e,0,'fieldSpell','Sky Striker Airspace - Area Zero',{faceUp:true}),r=put(e,0,'deck','Sky Striker Ace - Raye'),m=fieldCard(e,0,'Battle Ox');const d=e.state.players[0].deck;d.unshift(d.splice(d.findIndex(q=>q.uid===r.uid),1)[0]);use(e,s,'y18-excavate',{target:[m.uid]},pick(r));assert.equal(e.find(r.uid).zone,'hand');assert.equal(e.find(m.uid).zone,'grave');});
test('Multirole counts activated Striker spells, sets different names and banishes on leaving',()=>{const e=fresh(),m=put(e,0,'spells','Sky Striker Mecha Modules - Multirole',{faceUp:true}),s=put(e,0,'hand','Sky Striker Mobilize - Engage!');put(e,0,'deck','Sky Striker Ace - Raye');use(e,s);assert.equal(m.y18Multirole.count,1);trigger(e,()=>e.emit({type:'end-phase',owner:0}),pick(s));assert.equal(e.find(s.uid).zone,'spells');assert.equal(s.faceUp,false);trigger(e,()=>e.destroy(s.uid,source(e)));assert.equal(e.find(s.uid).zone,'banished');});
test('Multifaker responds to a Trap activation and recruits only Altergeist for the whole turn',()=>{const e=fresh(),f=put(e,0,'hand','Altergeist Multifaker'),m=put(e,0,'deck','Altergeist Silquitous'),t=put(e,0,'spells','Jar of Greed',{faceUp:false});use(e,t,'cast',{},pick(m));assert.ok(onField(e,f));assert.ok(onField(e,m));assert.equal(m.position,'defense');assert.equal(e.canSpecial(0,put(e,0,'hand','Battle Ox'),{via:'effect'}),false);});
test('Multifaker cannot recruit after a non-Altergeist Special Summon this turn',()=>{const e=fresh(),m=put(e,0,'hand','Battle Ox');trigger(e,()=>e.special(0,m.uid,{via:'effect'}));const f=put(e,0,'hand','Altergeist Multifaker'),s=put(e,0,'deck','Altergeist Silquitous');trigger(e,()=>e.special(0,f.uid,{via:'effect'}));assert.equal(e.find(s.uid).zone,'deck');});
test('Marionetter sets an actual archetype Trap from the deck',()=>{const e=fresh(),m=put(e,0,'hand','Altergeist Marionetter'),t=put(e,0,'deck','Altergeist Protocol');trigger(e,()=>e.normalSummon({uid:m.uid}),pick(t));assert.equal(e.find(t.uid).zone,'spells');assert.equal(t.faceUp,false);assert.equal(t.setTurn,e.state.turn);});
test('Marionetter sends its field target as an effect, so Liberation prevents the revival',()=>{const e=fresh(),m=fieldCard(e,0,'Altergeist Marionetter'),t=put(e,0,'grave','Altergeist Meluseek');e.state.ruleMode={id:'liberation',version:1,players:[{},{}]};use(e,m,'y18-revive',{own:[m.uid],target:[t.uid]});assert.equal(e.find(m.uid).zone,'banished');assert.equal(e.find(t.uid).zone,'grave');});
test('Silquitous pays by returning another friendly card, then returns the opposing target',()=>{const e=fresh(),s=fieldCard(e,0,'Altergeist Silquitous'),a=fieldCard(e,0,'Altergeist Multifaker'),b=fieldCard(e,1,'Blue-Eyes White Dragon');use(e,s,'y18-return',{cost:[a.uid],target:[b.uid]});assert.equal(e.find(a.uid).zone,'hand');assert.equal(e.find(b.uid).zone,'hand');});
test('Meluseek searches when used as Link material and not when banished',()=>{const e=fresh(),m=fieldCard(e,0,'Altergeist Meluseek'),a=put(e,0,'deck','Altergeist Multifaker');trigger(e,()=>e.move(m.uid,'grave',{kind:'link-material'}),pick(a));assert.equal(e.find(a.uid).zone,'hand');});
test('Manifestation equips its revived monster and destroys it when the trap leaves',()=>{const e=fresh(),s=put(e,0,'spells','Altergeist Manifestation',{faceUp:false}),m=put(e,0,'grave','Altergeist Silquitous');use(e,s,'cast',{target:[m.uid]});assert.ok(onField(e,m));assert.equal(s.equipTarget,m.uid);trigger(e,()=>e.destroy(s.uid,source(e)));assert.equal(e.find(m.uid).zone,'grave');});
test('Gouki Suprex recruits a real Gouki and material search excludes the same name',()=>{const e=fresh(),s=put(e,0,'hand','Gouki Suprex'),m=put(e,0,'hand','Gouki Twistcobra'),r=put(e,0,'deck','Gouki Re-Match');trigger(e,()=>e.normalSummon({uid:s.uid}),pick(m));assert.ok(onField(e,m));trigger(e,()=>e.move(s.uid,'grave',{kind:'link-material'}),pick(r));assert.equal(e.find(r.uid).zone,'hand');});
test('Gouki Re-Match requires different Levels and really revives exactly two in defense',()=>{const e=fresh(),s=put(e,0,'hand','Gouki Re-Match'),a=put(e,0,'grave','Gouki Suprex'),b=put(e,0,'grave','Gouki Twistcobra'),c=put(e,0,'grave','Gouki Suprex');const ctx=e.abilityContext(s.uid,s.id+'::cast','main',{owner:0}),group=E.get(s.id+'::cast').inputs(e,ctx)[0];assert.notEqual(e.earlyValidateInput(ctx,group,[a.uid,c.uid]),true);use(e,s,'cast',{target:[a.uid,b.uid]});for(const m of [a,b]){assert.ok(onField(e,m));assert.equal(m.position,'defense');}assert.equal(e.find(c.uid).zone,'grave');});
test('Gouki Headbatt sends a different Gouki as a real GY cost and boosts the target',()=>{const e=fresh(),s=put(e,0,'hand','Gouki Headbatt'),c=put(e,0,'hand','Gouki Octostretch'),m=fieldCard(e,0,'Gouki Suprex');use(e,s,'y18-special',{cost:[c.uid],target:[m.uid]});assert.equal(e.find(c.uid).zone,'grave');assert.ok(onField(e,s));assert.equal(e.attackValue(m),2600);});
test('Dragondark hand search consumes the same name limit as its banish trigger through JSON',()=>{let e=fresh();const a=put(e,0,'hand','Thunder Dragondark'),b=put(e,0,'deck','Thunder Dragondark'),c=put(e,0,'deck','Thunder Dragon Fusion');use(e,a,'y18-hand',{},pick(b));assert.equal(e.find(a.uid).zone,'grave');assert.equal(e.find(b.uid).zone,'hand');e=DuelEngine.restore(e.snapshot());trigger(e,()=>e.move(a.uid,'banished',{kind:'effect-banish',source:source(e)}),pick(c));assert.equal(e.find(c.uid).zone,'deck');});
test('Face-down banishment does not trigger Thunder Dragon effects',()=>{const e=fresh(),a=fieldCard(e,0,'Thunder Dragondark'),s=put(e,0,'deck','Thunder Dragon Fusion');trigger(e,()=>globalThis.DuelChronicle.year2018.banishDown(e,{owner:1,source:source(e)},[a.uid]));assert.equal(a.faceUp,false);assert.equal(e.find(s.uid).zone,'deck');});
test('Thunder Dragonroar recruits in defense and returns during either player End Phase',()=>{const e=fresh(),a=put(e,0,'grave','Thunder Dragonroar'),b=put(e,0,'deck','Thunder Dragonmatrix');e.state.active=1;trigger(e,()=>e.move(a.uid,'banished',{kind:'effect-banish',source:source(e)}),pick(b));assert.ok(onField(e,b));assert.equal(b.position,'defense');trigger(e,()=>e.endTurn());assert.equal(e.find(b.uid).zone,'hand');});
test('Colossus requires a real hand Thunder effect, uses a tribute and blocks only searches',()=>{const e=fresh(),c=put(e,0,'extra','Thunder Dragon Colossus'),m=fieldCard(e,0,'Thunder Dragonmatrix'),a=put(e,0,'hand','Thunder Dragondark'),b=put(e,0,'deck','Thunder Dragondark');assert.equal(available(e,c,'y18-contact'),false);use(e,a,'y18-hand',{},pick(b));use(e,c,'y18-contact',{cost:[m.uid]});assert.ok(onField(e,c));const n=e.state.players[1].hand.length,s=put(e,1,'deck','Sangan');trigger(e,()=>e.search(1,[s.uid]));assert.equal(e.find(s.uid).zone,'deck');trigger(e,()=>e.draw(1,1));assert.equal(e.state.players[1].hand.length,n+1);});
test('Colossus substitutes one actual Thunder from GY for destruction',()=>{const e=fresh(),c=fieldCard(e,0,'Thunder Dragon Colossus'),m=put(e,0,'grave','Thunder Dragon'),b=put(e,0,'grave','Battle Ox');trigger(e,()=>e.destroy(c.uid,source(e)));assert.ok(onField(e,c));assert.equal(e.find(m.uid).zone,'banished');assert.equal(e.find(b.uid).zone,'grave');});
test('Thunder Dragon Fusion shuffles physical field, GY and face-up banished materials',()=>{const e=fresh(),s=put(e,0,'hand','Thunder Dragon Fusion'),t=put(e,0,'extra','Thunder Dragon Titan'),a=fieldCard(e,0,'Thunder Dragon'),b=put(e,0,'grave','Thunder Dragondark'),c=put(e,0,'banished','Thunder Dragonroar');use(e,s,'cast',{},p=>p.kind==='materials'?{type:'choose',uids:[a.uid,b.uid,c.uid]}:pick(t)(p));assert.ok(onField(e,t));for(const m of [a,b,c])assert.equal(e.find(m.uid).zone,'deck');});
test('Batteryman Solar sends Thunder and creates exactly one token for a later summon',()=>{const e=fresh(),s=put(e,0,'hand','Batteryman Solar'),m=put(e,0,'deck','Thunder Dragon'),b=put(e,0,'hand','Thunder Dragonmatrix');trigger(e,()=>e.normalSummon({uid:s.uid}),pick(m));assert.equal(e.find(m.uid).zone,'grave');trigger(e,()=>e.special(0,b.uid,{via:'effect'}));assert.equal(e.monsters(0).filter(m=>D.CARDS[m.id].type==='token').length,1);});
test('Called by the Grave negates Ash in the same chain and expires after the next turn',()=>{let e=fresh();const p=put(e,0,'hand','Pot of Greed'),a=put(e,1,'hand','Ash Blossom & Joyous Spring'),c=put(e,0,'hand','Called by the Grave');act(e,{type:'activate',uid:p.uid,key:p.id+'::cast'});act(e,{type:'respond',uid:a.uid,key:a.id+'::y17-negate'});act(e,{type:'respond',uid:c.uid,key:c.id+'::cast',choices:{target:[a.uid]}});drain(e);assert.equal(e.find(a.uid).zone,'banished');assert.equal(e.state.players[0].hand.length,2);e=DuelEngine.restore(e.snapshot());const m=fieldCard(e,1,'Ash Blossom & Joyous Spring');assert.equal(e.negated(m),true);e.state.turn++;assert.equal(e.negated(m),true);e.state.turn++;assert.equal(e.negated(m),false);});
test('Ghost Belle answers grave revival and not a pure Deck search',()=>{const e=fresh(),g=put(e,1,'hand','Ghost Belle & Haunted Mansion'),s=put(e,0,'hand','Monster Reborn'),m=put(e,0,'grave','Battle Ox');act(e,{type:'activate',uid:s.uid,key:s.id+'::cast',choices:{target:[m.uid]}});assert.ok(e.state.pending.options.some(o=>o.uid===g.uid));act(e,{type:'respond',uid:g.uid,key:g.id+'::y18-negate'});drain(e);assert.equal(e.find(m.uid).zone,'grave');});
test('Infinite Impermanence negates a monster and the mirrored opposing S/T column',()=>{const e=fresh(),s=put(e,0,'spells','Infinite Impermanence',{faceUp:false,slot:1}),m=fieldCard(e,1,'Trickstar Candina');use(e,s,'cast',{target:[m.uid]});assert.equal(e.negated(m),true);const p=put(e,1,'spells','Pot of Greed',{faceUp:false,slot:3});e.state.active=1;use(e,p);assert.equal(e.state.players[1].hand.length,0);});
test('hand Impermanence requires an empty field and creates no column lock',()=>{const e=fresh(),s=put(e,0,'hand','Infinite Impermanence'),m=fieldCard(e,1,'Trickstar Candina');use(e,s,'cast',{target:[m.uid]});assert.equal(e.negated(m),true);assert.equal(e.state.y18Impermanence,undefined);});
test('Red Reboot pays half LP, resets the trap, prevents activation but not its GY effect',()=>{const e=fresh(),s=put(e,0,'hand','Red Reboot'),t=put(e,1,'spells','Jar of Greed',{faceUp:false});e.state.active=1;act(e,{type:'activate',uid:t.uid,key:t.id+'::cast'});act(e,{type:'respond',uid:s.uid,key:s.id+'::cast'});drain(e);assert.equal(e.state.players[0].lp,4000);assert.equal(e.find(t.uid).zone,'spells');assert.equal(t.faceUp,false);assert.equal(e.state.players[1].hand.length,0);});
test('Eater banishes five face-down as cost and its restrictions still allow Link material',()=>{const e=fresh(),m=put(e,0,'hand','Eater of Millions');const us=Array.from({length:5},()=>put(e,0,'extra','Link Spider'));use(e,m,'y18-special',{cost:us.map(m=>m.uid)});assert.equal(e.attackValue(m),500);assert.equal(e.canTribute(m,0),false);assert.ok(us.every(m=>e.find(m.uid).zone==='banished'&&!m.faceUp));const k=put(e,0,'extra','Knightmare Phoenix'),b=fieldCard(e,0,'Battle Ox');assert.equal(e.linkValid(0,k,[m,b]),true);});
test('Megafleet sends a Cyber Dragon and opposing Extra Zone monster, preserving count-based ATK',()=>{const e=fresh(),m=put(e,0,'extra','Chimeratech Megafleet Dragon'),c=fieldCard(e,0,'Cyber Dragon'),t=put(e,1,'extra','Knightmare Phoenix');trigger(e,()=>e.special(1,t.uid,{via:'link',zone:'extra'}));use(e,m,'y18-contact',{cost:[c.uid,t.uid]});assert.ok(onField(e,m));assert.equal(e.find(t.uid).zone,'grave');assert.equal(e.attackValue(m),2400);});
test('Isolde searches but the acquired name cannot summon or activate this turn',()=>{const e=fresh(),m=put(e,0,'deck','Gouki Suprex');link(e,'Isolde, Two Tales of the Noble Knights','extra',pick(m));assert.equal(e.find(m.uid).zone,'hand');assert.equal(e.canNormal(m,0),false);assert.equal(e.canSpecial(0,m,{via:'effect'}),false);e.state.turn++;assert.equal(e.canNormal(m,0),true);});
test('Isolde sends differently named equips and summons the exact Level, with Liberation blocking cost',()=>{const e=fresh(),s=fieldCard(e,0,'Isolde, Two Tales of the Noble Knights'),a=put(e,0,'deck','Divine Sword - Phoenix Blade'),b=put(e,0,'deck','Autonomous Action Unit'),m=put(e,0,'deck','Gouki Headbatt');use(e,s,'y18-recruit',{cost:[a.uid,b.uid]},pick(m));assert.ok(onField(e,m));for(const q of [a,b])assert.equal(e.find(q.uid).zone,'grave');const e2=fresh(),s2=fieldCard(e2,0,'Isolde, Two Tales of the Noble Knights');put(e2,0,'deck','Divine Sword - Phoenix Blade');put(e2,0,'deck','Gouki Octostretch');e2.state.ruleMode={id:'liberation',version:1,players:[{},{}]};assert.equal(available(e2,s2,'y18-recruit'),false);});
test('Inspector Boarder counts actual monster categories and attempts while face-up',()=>{const e=fresh(),b=fieldCard(e,0,'Inspector Boarder'),s=put(e,0,'hand','Thunder Dragondark');put(e,0,'deck','Thunder Dragondark');assert.equal(available(e,s,'y18-hand'),false);fieldCard(e,1,'Knightmare Phoenix');assert.equal(available(e,s,'y18-hand'),true);use(e,s,'y18-hand');const a=put(e,0,'hand','Thunder Dragon');assert.equal(available(e,a,'hand-search'),false);});
test('Borrelsword battle protection and its second attack effect use real position changes',()=>{const e=fresh(),s=fieldCard(e,0,'Borrelsword Dragon'),m=fieldCard(e,1,'Blue-Eyes White Dragon');use(e,s,'y18-double',{target:[m.uid]});assert.equal(m.position,'defense');assert.equal(e.attackAllowance(s),2);assert.equal(e.destroy(s.uid,source(e),true),false);});
