const {chromium}=require('playwright'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url'),{createHash}=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.join(root,'output/gx-browser'),report={checks:[],errors:[]};
async function menu(page,action){if(await page.locator('#modal').evaluate(el=>el.open))await page.locator('#modal [data-action="close-modal"]').first().click();await page.locator('.site-header .brand').click();await page.locator('#home-screen [data-action="'+action+'"]').first().click();}
(async()=>{await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.DUEL_BROWSER||'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',args:['--mute-audio']});const context=await browser.newContext({viewport:{width:1440,height:900}});await context.route(/https?:\/\//,r=>r.abort());await context.addInitScript(()=>{localStorage.setItem('duel-sanctuary-prefs-v1',JSON.stringify({sound:false,music:false,reducedMotion:true,speed:'fast'}));localStorage.setItem('duel-sanctuary-online-art-v2','false');});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));const check=async(name,fn)=>{await fn();report.checks.push(name);console.log('OK',name);};
try{await page.goto(pathToFileURL(path.join(root,'index.html')).href);await page.waitForFunction(()=>window.duelApp&&document.documentElement.dataset.ready==='true');
 await check('6275 cards, 41 presets and every GX/5Ds module load offline',async()=>{assert.deepEqual(await page.evaluate(()=>({cards:DuelData.CARD_LIST.filter(c=>!c.notCollectible).length,decks:DuelDecks.list().length,loaded:DuelYearFinalLoaded,pending:DuelData.CARD_LIST.filter(c=>c.implementationStatus==='pending').length})),{cards:6275,decks:41,loaded:true,pending:320});});
 await check('2006, 2007 and 2008 archive counts and cumulative filters work in all languages',async()=>{await menu(page,'library');for(const lang of ['zh-CN','en','ja']){await page.evaluate(l=>duelApp.setLanguage(l),lang);for(const [year,count,total] of [[2006,312,2626],[2007,408,3034],[2008,537,3571]]){await page.selectOption('#library-year',String(year));assert.match(await page.locator('#library-count').textContent(),new RegExp('^'+count+' '));await page.selectOption('#library-year','through-'+year);assert.match(await page.locator('#library-count').textContent(),new RegExp('^'+total+' '));}}await page.selectOption('#library-year','2008');await page.screenshot({path:path.join(out,'01-2008-japanese.png'),animations:'disabled'});});
 await check('all nine annual presets are available and their names change with the language',async()=>{await menu(page,'new-game');const ids=await page.evaluate(()=>Object.values(DuelData.DECKS).filter(d=>d.year>=2006&&d.year<=2008).map(d=>d.id));assert.equal(ids.length,9);for(const lang of ['zh-CN','en','ja']){await page.evaluate(l=>duelApp.setLanguage(l),lang);for(const id of ids){const button=page.locator('[data-action="choose-deck"][data-deck="'+id+'"]');assert.equal(await button.count(),1);await button.click();assert.match(await button.textContent(),/200[678]/);}}await page.screenshot({path:path.join(out,'02-annual-decks.png'),animations:'disabled'});});
 await check('TeleDAD starts a real spectator game with the exact 40-card construction',async()=>{await page.click('[data-action="choose-deck"][data-deck="teledad-2008"]');await page.click('[data-action="choose-mode"][data-value="spectate"]');await page.selectOption('#opponent-deck','gladiator-2008');await page.click('[data-action="begin-game"]');await page.waitForFunction(()=>duelApp.engine.state.players[0].deckId==='teledad-2008'&&duelApp.spectate.active);await page.evaluate(()=>{if(!duelApp.spectate.paused)duelApp.spectateToggle();duelApp.skipChain();});assert.deepEqual(await page.evaluate(()=>duelApp.engine.deckInfo(0).cards),await page.evaluate(()=>DuelData.DECKS['teledad-2008'].cards));await page.screenshot({path:path.join(out,'03-teledad-duel.png'),animations:'disabled'});});
 await check('Gemini second Normal Summon is available through the real card popover',async()=>{await page.evaluate(()=>duelApp.setLanguage('en'));const uid=await page.evaluate(()=>{const e=new DuelEngine({deck:'blue',opponentDeck:'dark',first:0,seed:605});e.state.turn=6;e.state.phase='main1';for(const p of e.state.players){p.deck.push(...p.hand);p.hand=[];}const m=e.makeCard(DuelData.cardByName('Goggle Golem').id,0);Object.assign(m,{faceUp:true,position:'attack',summonTurn:0,changedTurn:0});e.state.players[0].monsters[0]=m;e.state.originalCardCount=e.physicalCards().filter(c=>DuelData.CARDS[c.id].type!=='token').length;duelApp.restore(e.snapshot());return m.uid;});await page.locator('[data-action="select-card"][data-card-uid="'+uid+'"]').first().click();await page.locator('#card-popover button').filter({hasText:'Gemini Summon'}).click();await page.waitForFunction(uid=>duelApp.engine.find(uid).card.geminiSummoned,uid);assert.equal(await page.evaluate(uid=>duelApp.engine.attackValue(duelApp.engine.find(uid).card),uid),2100);await page.reload();await page.waitForFunction(()=>window.duelApp);assert.equal(await page.evaluate(uid=>duelApp.engine.attackValue(duelApp.engine.find(uid).card),uid),2100);});
 await check('mobile 2008 archive, translated choices and saved preferences remain usable',async()=>{await page.setViewportSize({width:390,height:844});await menu(page,'library');await page.selectOption('#library-year','2008');await page.evaluate(()=>duelApp.setLanguage('en'));assert.match(await page.locator('#library-count').textContent(),/^537 /);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'04-mobile-2008.png'),animations:'disabled'});await page.reload();await page.waitForFunction(()=>window.duelApp);assert.equal(await page.evaluate(()=>DuelI18n.language),'en');});
 assert.deepEqual(report.errors,[]);report.buildSha256=createHash('sha256').update(await fs.readFile(path.join(root,'index.html'))).digest('hex');
}catch(error){report.failure=error.stack;console.error(error);await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});process.exitCode=1;}finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();}})();
