const test=require('node:test'),assert=require('node:assert/strict');
const {DuelEngine}=require('../src/advanced-engine.js'),D=globalThis.DuelData,T=globalThis.DuelDecks,E=require('../src/deck-editor.js'),M=require('../src/match-core.js'),AI=require('../src/match-ai.js');
const copy=v=>JSON.parse(JSON.stringify(v));
function deck(){const d=E.normalize(D.DECKS.blue);d.side=D.CARD_LIST.filter(c=>!c.notCollectible&&c.implementationStatus!=='pending'&&![...d.cards,...d.extra].some(id=>T.identity(id)===T.identity(c.id))).slice(0,15).map(c=>c.id);return d;}
test('all presets are valid including supported historical side cards',()=>{for(const d of T.list())assert.equal(T.analyze(d).valid,true,d.id);assert.ok(D.DECKS['blue-eyes-2016']?.side?.length||T.list().some(d=>d.year===2016&&d.side.length));});
test('side 15/16 and malformed sections fail without truncation',()=>{const d=deck();assert.equal(T.analyze(d).valid,true);d.side.push(d.side[0]);assert.equal(T.analyze(d).valid,false);assert.throws(()=>T.clean(d));d.side={};assert.equal(T.analyze(d).valid,false);});
test('side accepts both main and extra types, but active zones enforce natural type',()=>{const d=deck(),fusion=D.CARD_LIST.find(c=>D.isExtra(c)&&!c.notCollectible&&c.implementationStatus!=='pending'&&!d.extra.includes(c.id));d.side=[fusion.id];assert.equal(T.analyze(d).valid,true);assert.throws(()=>E.move(d,[{from:'side',index:0,to:'cards'}]));});
test('main 39/40/60/61 is checked with side in total name count',()=>{const d=deck();d.cards=d.cards.slice(0,39);assert.equal(T.analyze(d).valid,false);d.cards.push(d.side.pop());assert.equal(T.analyze(d).valid,true);while(d.cards.length<61){const id=D.CARD_LIST.find(c=>!c.notCollectible&&c.implementationStatus!=='pending'&&!D.isExtra(c)&&!E.zones.flatMap(z=>d[z]).some(id=>T.identity(id)===T.identity(c.id))).id;d.cards.push(id);assert.equal(T.analyze(d).valid,d.cards.length<=60);}});
test('full side at main minimum can exchange atomically and preserve source',()=>{const d=deck(),before=copy(d),n=E.move(d,[{from:'cards',index:0,to:'side'},{from:'side',index:0,to:'cards'}],{registered:d});assert.deepEqual(d,before);assert.equal(n.cards.length,40);assert.equal(n.side.length,15);assert.deepEqual(E.inventory(n),E.inventory(d));assert.throws(()=>E.move(d,[{from:'cards',index:0,to:'side'}]));});
test('pure insertion and removal are permitted at legal final counts',()=>{const d=deck();d.side=d.side.slice(0,3);const n=E.move(d,[{from:'side',index:0,to:'cards'}],{registered:d});assert.equal(n.cards.length,41);assert.equal(n.side.length,2);const back=E.move(n,[{from:'cards',index:40,to:'side'}],{registered:d});assert.deepEqual(E.inventory(back),E.inventory(d));});
test('full extra and full side exchange uses final bounds',()=>{const d=deck();for(const c of D.CARD_LIST.filter(c=>D.isExtra(c)&&!c.notCollectible&&c.implementationStatus!=='pending')){if(d.extra.length>=15)break;if(!E.zones.flatMap(z=>d[z]).includes(c.id))d.extra.push(c.id);}const spare=D.CARD_LIST.find(c=>D.isExtra(c)&&!c.notCollectible&&c.implementationStatus!=='pending'&&!E.zones.flatMap(z=>d[z]).includes(c.id));d.side[0]=spare.id;const n=E.move(d,[{from:'extra',index:0,to:'side'},{from:'side',index:0,to:'extra'}],{registered:d});assert.equal(n.extra.length,15);assert.equal(n.side.length,15);});
test('repeated selections, wrong zone and substituted cards reject',()=>{const d=deck();assert.throws(()=>E.move(d,[{from:'side',index:0,to:'cards'},{from:'side',index:0,to:'cards'}]));const fake=copy(d);fake.side[0]=fake.side[1];assert.equal(E.check(fake,d).valid,false);});
test('same name across three zones, unknown, token and pending are rejected',()=>{const d=deck();d.side=[d.cards[0],d.cards[0],d.cards[0]];assert.equal(T.analyze(d).valid,false);for(const id of ['unknown',D.CARD_LIST.find(c=>c.type==='token').id,D.CARD_LIST.find(c=>c.implementationStatus==='pending').id]){d.side=[id];assert.equal(T.analyze(d).valid,false);}});
test('JSON v3 roundtrip and v2 missing side compatibility',()=>{const d=deck();assert.deepEqual(T.parseJSON(T.exportJSON(d)).side,d.side);assert.equal(JSON.parse(T.exportJSON(d)).version,3);delete d.side;assert.deepEqual(T.parseJSON(JSON.stringify(d)).side,[]);});
test('side cards never become engine entities or alter physical card conservation',()=>{const d=deck(),e=new DuelEngine({deck:d.id,opponentDeck:'dark',deckSpecs:[d,E.normalize(D.DECKS.dark)],seed:12});assert.equal(e.physicalCards().length,d.cards.length+d.extra.length+D.DECKS.dark.cards.length+D.DECKS.dark.extra.length);assert.deepEqual(DuelEngine.restore(e.snapshot()).deckInfo(0).side,d.side);});
function match(format='bo3'){return M.create({decks:[deck(),E.normalize(D.DECKS.dark)],format,id:'test-match'});}
function win(m,winner){M.record(m,{winner,turn:4});if(m.phase==='choosing-first')M.choose(m,m.round.chooser,m.round.chooser);}
function next(m){M.submit(m,0,m.decks[0]);M.submit(m,1,m.decks[1]);M.next(m);}
test('BO3 2:0 and duplicate terminal delivery',()=>{const m=match();win(m,0);assert.equal(m.phase,'siding');assert.equal(M.record(m,{winner:0}),false);next(m);win(m,0);assert.equal(m.phase,'finished');assert.deepEqual(m.score,[2,0]);assert.equal(m.gameIndex,2);assert.equal(M.record(m,{winner:0}),false);});
test('BO3 2:1 and draws use real game indices',()=>{const m=match();for(const w of [0,'draw',1,0]){win(m,w);if(m.phase!=='finished')next(m);}assert.deepEqual(m.score,[2,1]);assert.equal(m.gameIndex,4);assert.equal(m.games.length,4);assert.deepEqual(M.restore(m),m);});
test('three consecutive draws finish, BO1 immediately finishes',()=>{const m=match();for(let i=0;i<3;i++){win(m,'draw');if(i<2)next(m);}assert.equal(m.result.status,'draw');const one=match('bo1');win(one,1);assert.equal(one.phase,'finished');});
test('loser chooses, wrong seat and repeated confirmations rejected',()=>{const m=match();M.record(m,{winner:0});assert.throws(()=>M.choose(m,0,1));M.choose(m,1,1);M.submit(m,0,m.decks[0]);assert.throws(()=>M.submit(m,0,m.decks[0]));assert.throws(()=>M.next(m));});
test('registration is immutable and next round uses prior submitted deck',()=>{const m=match(),initial=copy(m.registered);win(m,0);const d=E.move(m.decks[0],[{from:'cards',index:0,to:'side'},{from:'side',index:0,to:'cards'}]);M.submit(m,0,d);M.submit(m,1,m.decks[1]);M.next(m);assert.deepEqual(m.decks[0],d);assert.deepEqual(m.registered,initial);win(m,1);assert.deepEqual(m.decks[0],d);});
test('restore rejects forged score, inventory, round and game IDs',()=>{const m=match();win(m,0);for(const mutate of [x=>x.score[0]++,x=>x.decks[0].side.pop(),x=>x.round.id='bad',x=>x.gameId='bad']){const x=copy(m);mutate(x);assert.throws(()=>M.restore(x));}});
test('match surrender retains actual scores and does not fabricate games',()=>{const m=match();win(m,0);M.abandon(m,0);assert.deepEqual(m.score,[1,0]);assert.equal(m.games.length,1);assert.equal(m.result.winner,1);assert.deepEqual(M.restore(m),m);});
test('aborted game does not gain wins',()=>{const m=match();M.record(m,{winner:'draw',kind:'limit'});assert.equal(m.result.status,'aborted');assert.deepEqual(m.score,[0,0]);});
test('public projection contains no decks, inventory, side count or notes',()=>{const m=match();win(m,1);M.submit(m,0,m.decks[0]);const p=M.publicView(m,1);assert.deepEqual(p.score,[1,0]);assert.equal(p.round.ready[1],true);for(const key of ['registered','decks','submitted','side','cards','notes'])assert.equal(JSON.stringify(p).includes('"'+key+'"'),false);});
test('AI preserves an unknown matchup and uses only supplied public observations',()=>{const d=deck();assert.deepEqual(AI.plan(d,[]),d);assert.equal(E.check(AI.plan(d,['blue-eyes','dark-magician']),d).valid,true);});
test('AI actually sides in back-row removal using revealed spells and traps',()=>{
 const d=E.normalize(D.DECKS.blue),id=D.cardByName('Twin Twisters').id;d.side=[id];
 const next=AI.plan(d,[D.cardByName('Mirror Force').id,D.cardByName('Swords of Revealing Light').id]);
 assert.ok(next.cards.includes(id));assert.equal(next.side.includes(id),false);assert.equal(E.check(next,d).valid,true);
});
test('non-destructive v2 migration preserves IDs, notes and incomplete user data',()=>{
 const vm=require('node:vm'),fs=require('node:fs'),values=new Map(),old={...deck(),id:'custom-migration',notes:'keep me',updatedAt:123};delete old.side;
 const legacy=JSON.stringify([old]);values.set('duel-sanctuary-custom-decks-v2',legacy);
 const context=vm.createContext({DuelData:D,localStorage:{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)}});
 vm.runInContext(fs.readFileSync(require.resolve('../src/deck-tools.js'),'utf8'),context);const api=context.DuelDecks,loaded=api.load();
 assert.equal(loaded[0].id,old.id);assert.equal(loaded[0].notes,'keep me');assert.equal(loaded[0].side.length,0);assert.equal(values.get('duel-sanctuary-custom-decks-v2'),legacy);assert.equal(loaded[0].updatedAt,123);
 const bad='{"broken":';values.set(api.STORAGE,bad);api.load();assert.equal(api.getDiagnostics().length,1);api.save(deck());assert.equal(values.get(api.STORAGE+'-recovery'),bad);
 const before=values.get(api.STORAGE);context.localStorage.setItem=()=>{throw Error('quota');};assert.throws(()=>api.save({...deck(),name:'quota'}));assert.equal(values.get(api.STORAGE),before);
 delete D.DECKS['custom-migration'];
});
