const test=require('node:test');
const assert=require('node:assert/strict');
const {DuelEngine}=require('../src/advanced-engine.js');
const {CARDS,DECKS}=global.DuelData;
const Decks=require('../src/deck-tools.js');
function resolve(g){let n=0;while(g.state.pending&&g.state.winner===null&&n++<100){const a=g.aiNext(),r=g.act(a);assert.equal(r.ok,true,JSON.stringify(a)+' '+r.error);}assert.ok(n<100);return g;}
function act(g,a){const r=g.act(a);assert.equal(r.ok,true,r.error);return resolve(g);}
function fresh(deck='blue'){const g=new DuelEngine({deck,first:0,seed:73});g.state.turn=2;for(const p of g.state.players){p.hand=[];p.monsters=Array(5).fill(null);p.spells=Array(5).fill(null);p.grave=[];p.banished=[];p.extraMonster=null;}g.state.originalCardCount=g.physicalCards().filter(c=>CARDS[c.id].type!=='token').length;return g;}
function put(g,p,z,id,props={}){const c=Object.assign(g.makeCard(id,p),props);if(z==='monsters'||z==='spells')g.state.players[p][z][g.state.players[p][z].indexOf(null)]=c;else g.state.players[p][z].push(c);if(CARDS[id].type!=='token')g.state.originalCardCount++;return c;}
test('all presets satisfy real construction sizes and copy counts',()=>{assert.equal(Object.keys(DECKS).filter(k=>DECKS[k].preset).length,14);for(const d of Object.values(DECKS))assert.equal(Decks.analyze(d).valid,true,d.id);});
test('core spell chain draws, resolves and cleans up without losing cards',()=>{const g=fresh(),p=put(g,0,'hand','pot-of-greed');const before=g.state.players[0].deck.length;act(g,{type:'activate',uid:p.uid,key:'pot-of-greed::cast'});assert.equal(g.state.players[0].deck.length,before-2);assert.equal(g.find(p.uid).zone,'grave');assert.equal(g.state.chain.length,0);g.assertState();});
test('normal summon, tribute and card generation remain consistent',()=>{const g=fresh(),a=put(g,0,'monsters','battle-ox'),b=put(g,0,'monsters','kaibaman'),dragon=put(g,0,'hand','blue-eyes');act(g,{type:'summon',uid:dragon.uid,tributes:[a.uid,b.uid]});assert.equal(g.find(dragon.uid).zone,'monsters');assert.equal(g.state.normalUsed,true);assert.equal(g.find(a.uid).zone,'grave');});
test('Synchro requires exact level sum and the listed tuner',()=>{const g=fresh('junk'),j=put(g,0,'monsters','junk-synchron'),d=put(g,0,'monsters','doppelwarrior');const target=g.state.players[0].extra.find(c=>c.id==='junk-warrior');assert.equal(g.synchroValid(0,target,[j,d]),true);act(g,{type:'extra-summon',uid:target.uid,materials:[j.uid,d.uid]});assert.equal(g.find(target.uid).zone,'extraMonster');assert.equal(g.find(j.uid).zone,'grave');});
test('an Xyz summon tracks two materials and rank-up transfers all of them',()=>{const g=fresh('utopia'),a=put(g,0,'monsters','gagaga-magician'),b=put(g,0,'monsters','goblindbergh'),u=g.state.players[0].extra.find(c=>c.id==='utopia'),l=g.state.players[0].extra.find(c=>c.id==='utopia-lightning');act(g,{type:'extra-summon',uid:u.uid,materials:[a.uid,b.uid]});assert.equal(g.find(u.uid).card.overlays.length,2);act(g,{type:'extra-summon',uid:l.uid,materials:[u.uid]});assert.equal(g.find(l.uid).card.overlays.length,3);assert.equal(g.find(a.uid).zone,'overlays');g.assertState();});
test('pendulum cards enter the face-up Extra Deck and detaching them sends them to the GY',()=>{const g=fresh('qliphort'),p=put(g,0,'monsters','qli-carrier');g.move(p.uid,'grave',{kind:'tribute'});assert.equal(g.find(p.uid).zone,'extra');assert.equal(g.find(p.uid).card.faceUpExtra,true);const host=put(g,0,'monsters','utopia');g.remove(p.uid);host.overlays.push(p);g.detach(host.uid,[p.uid]);assert.equal(g.find(p.uid).zone,'grave');g.assertState();});
test('setting both scales then pendulum summoning uses the strict open interval',()=>{const g=fresh('qliphort'),a=put(g,0,'hand','qli-scout'),b=put(g,0,'hand','qli-monolith'),c=put(g,0,'hand','qli-carrier'),t=put(g,0,'hand','qli-towers');act(g,{type:'pendulum-scale',uid:a.uid,slot:4});act(g,{type:'pendulum-scale',uid:b.uid,slot:0});assert.ok(g.pendulumCandidates(0).some(m=>m.uid===c.uid));assert.ok(!g.pendulumCandidates(0).some(m=>m.uid===t.uid));act(g,{type:'pendulum-summon',uids:[c.uid]});assert.equal(g.level(g.find(c.uid).card),4);assert.equal(g.attackValue(g.find(c.uid).card),1800);assert.equal(g.pendulumCandidates(0).length,0);});
test('Exodia wins with five different hand components, never five copies of one',()=>{const g=fresh('exodia');for(const id of['exodia-head','exodia-left-arm','exodia-right-arm','exodia-left-leg','exodia-right-leg'])put(g,0,'hand',id);g.checkWin();assert.equal(g.state.winner,0);assert.equal(g.state.winKind,'exodia');});
test('save restore includes overlays, pendulum zones and current chain decisions',()=>{const g=fresh('utopia');const x=put(g,0,'monsters','utopia');const m=put(g,0,'hand','battle-ox');g.remove(m.uid);x.overlays.push(m);const p=put(g,0,'hand','pot-of-greed');const r=g.act({type:'activate',uid:p.uid,key:'pot-of-greed::cast'});assert.equal(r.ok,true);const restored=DuelEngine.restore(g.snapshot());assert.deepEqual(restored.snapshot(),g.snapshot());restored.assertState();});
