const test=require('node:test'),assert=require('node:assert/strict');
const {DuelEngine}=require('../src/advanced-engine.js');
const {CARDS,CARD_LIST,DECKS,isExtra}=global.DuelData,Decks=global.DuelDecks;
function fresh(deck='tearlaments'){const e=new DuelEngine({deck,opponentDeck:'blue',first:0,seed:103});e.state.turn=2;for(const p of e.state.players){p.deck.push(...p.hand);p.hand=[];}return e;}
function put(e,owner,zone,id,props={}){const f=e.refs(owner,['deck','extra']).find(f=>f.card.id===id),m=f?e.remove(f.card.uid).card:e.makeCard(id,owner);Object.assign(m,{faceUp:true,position:'attack',summonTurn:1,changedTurn:0},props);const p=e.state.players[owner];if(zone==='monsters'||zone==='spells')p[zone][props.slot??p[zone].indexOf(null)]=m;else if(zone==='extraMonster'||zone==='extraMonster2'){m.extraSlot=props.extraSlot??owner;p[zone]=m;}else if(zone==='fieldSpell')p[zone]=m;else p[zone].push(m);e.state.originalCardCount=e.physicalCards().filter(c=>CARDS[c.id].type!=='token').length;return m;}
function raw(e,a){const r=e.act(a);assert.equal(r.ok,true,JSON.stringify(a)+' / '+r.error);return r;}
function settle(e,prefer=null){let n=0;while(e.state.pending&&e.state.winner===null&&n++<220){const p=e.state.pending;let a=prefer?.(p,e);if(!a){if(p.kind==='window')a={type:'pass'};else if(p.kind==='trigger')a={type:'respond',uid:p.trigger.uid,key:p.trigger.key};else if(p.kind==='order')a={type:'choose',uids:p.candidates.map(c=>c.uid)};else a=e.chooseAI(p);}raw(e,a);}assert.ok(n<220,'effect decision sequence terminates');e.assertState();return e;}
function run(e,a,prefer){raw(e,a);return settle(e,prefer);}
const ctxSource=(owner,id='foolish-burial')=>({id,uid:'test-source',owner,effectType:'spell',generation:0});
test('expanded catalog preserves the 204 original cards and nine Link monsters',()=>{assert.equal(CARD_LIST.filter(c=>!c.notCollectible&&(!c.early||c.existing)).length,204);assert.equal(CARD_LIST.filter(c=>!c.notCollectible).length,7486);assert.equal(CARD_LIST.filter(c=>c.type==='link').length,9);assert.equal(Object.values(DECKS).filter(d=>d.preset).length,49);assert.equal(Decks.analyze(DECKS.tearlaments).valid,true);assert.equal(DECKS.tearlaments.extra.filter(id=>CARDS[id].type==='link').length,8);assert.equal(CARDS.perlereino.tearlaments,false);assert.equal(CARDS['tear-sulliek'].tearlaments,true);});
test('Link material weights are one OR the full Link rating, with minimum counts enforced',()=>{const e=fresh(),u=put(e,0,'monsters','knightmare-unicorn'),a=put(e,0,'monsters','tear-merrli'),b=put(e,0,'monsters','tear-scheiren'),ip=put(e,0,'monsters','ip-masquerena'),target=e.state.players[0].extra.find(c=>c.id==='accesscode-talker');assert.equal(e.linkValid(0,target,[u,a,b]),false);assert.equal(e.linkValid(0,target,[u,a]),true);assert.equal(e.linkValid(0,target,[ip,a,b]),true);assert.equal(e.linkValid(0,target,[u]),false);});
test('Link material name, attribute, token, effect and non-Link clauses are distinct',()=>{
  const e=fresh(),t1=put(e,0,'monsters','doppel-token'),t2=put(e,0,'monsters','doppel-token'),n=put(e,0,'monsters','blue-eyes'),m=put(e,0,'monsters','tear-merrli');
  const find=id=>e.state.players[0].extra.find(c=>c.id===id);
  assert.equal(e.linkValid(0,find('ip-masquerena'),[t1,t2]),true);assert.equal(e.linkValid(0,find('cross-sheep'),[t1,t2]),false);assert.equal(e.linkValid(0,find('dharc-charmer'),[n,m]),true);assert.equal(e.linkValid(0,find('eria-charmer'),[n,m]),false);assert.equal(e.linkValid(0,find('accesscode-talker'),[t1,t2,n,m]),false);assert.equal(e.linkValid(0,find('apollousa'),[t1,t2,n,m]),false);
});
test('the two Extra Monster Zones are shared and either empty side can be chosen',()=>{
  const e=fresh(),a=put(e,0,'monsters','tear-merrli'),b=put(e,0,'monsters','tear-scheiren'),ip=e.state.players[0].extra.find(c=>c.id==='ip-masquerena');
  run(e,{type:'extra-summon',uid:ip.uid,materials:[a.uid,b.uid],zone:'extra2'});assert.equal(ip.extraSlot,1);assert.equal(e.extraAt(1).owner,0);
  const rival=put(e,1,'extra','cross-sheep');assert.ok(!e.freeZones(1,rival).includes('extra'));assert.ok(e.freeZones(1,rival).includes('extra2'));
  const kit=e.state.players[0].extra.find(c=>c.id==='tear-kitkallos');assert.ok(!e.freeZones(0,kit).some(z=>typeof z==='string'));
});
test('arrow orientation follows the controller and opposing arrows also open main zones',()=>{const e=fresh();const sheep=put(e,0,'extraMonster','cross-sheep',{extraSlot:0});assert.deepEqual(e.linkedZones(0,sheep.uid),[0,2]);const eria=put(e,1,'extraMonster','eria-charmer',{extraSlot:1});assert.deepEqual(e.linkedZones(1,eria.uid),[0,2]);e.remove(eria.uid);e.state.players[1].grave.push(eria);const apo=put(e,1,'extraMonster','apollousa',{extraSlot:1,materialCount:3});assert.ok(e.linkedZones(0,apo.uid).includes(3));});
test('a Link material cannot supply the arrow for its own replacement summon',()=>{const e=fresh(),sheep=put(e,0,'extraMonster','cross-sheep',{extraSlot:0}),m=put(e,0,'monsters','tear-merrli',{slot:2}),u=e.state.players[0].extra.find(c=>c.id==='knightmare-unicorn');const zones=e.freeZones(0,u,{materials:[sheep.uid,m.uid]});assert.ok(zones.includes('extra'));assert.ok(!zones.includes(2));const old=e.snapshot();assert.equal(e.act({type:'extra-summon',uid:u.uid,materials:[sheep.uid,m.uid],zone:2}).ok,false);assert.deepEqual(e.snapshot(),old);});
test('co-link paths allow a genuine Extra Link into the second Extra Monster Zone',()=>{const e=fresh();put(e,0,'extraMonster','linkuriboh',{extraSlot:0});put(e,0,'monsters','knightmare-phoenix',{slot:1});const bridge=put(e,0,'monsters','knightmare-unicorn',{slot:2});put(e,0,'monsters','accesscode-talker',{slot:3});const crow=put(e,0,'monsters','dd-crow',{slot:4}),target=put(e,0,'extra','linkuriboh');assert.equal(e.canOccupyExtra(0,1,target),true);assert.equal(e.canOccupyExtra(0,1,target,[bridge.uid]),false);run(e,{type:'extra-summon',uid:target.uid,materials:[crow.uid],zone:'extra2'});assert.equal(e.extraMonsters(0).length,2);assert.equal(e.extraAt(1).card.uid,target.uid);});
test('Link has neither level nor rank, cannot defend, and revives to an ordinary main zone',()=>{const e=fresh(),ip=put(e,0,'grave','ip-masquerena',{properlySummoned:true}),reborn=put(e,0,'hand','monster-reborn');run(e,{type:'activate',uid:reborn.uid,key:'monster-reborn::cast',choices:{target:[ip.uid]}});assert.equal(e.find(ip.uid).zone,'monsters');assert.equal(e.level(ip),0);assert.equal(CARDS[ip.id].rank,undefined);assert.equal(CARDS[ip.id].def,null);e.state.turn++;assert.equal(e.act({type:'stance',uid:ip.uid}).ok,false);assert.ok(!e.actionsFor(ip.uid,0).some(a=>a.type==='stance'));});
test('Crystron Ametrix cannot turn Link monsters into defense position',()=>{const e=fresh(),ip=put(e,0,'monsters','ip-masquerena',{summonKind:'link'}),b=put(e,0,'monsters','blue-eyes',{summonKind:'special'}),ametrix=put(e,1,'extra','cry-ametrix');e.special(1,ametrix.uid,{via:'synchro'});e.pump();settle(e);assert.equal(e.find(ip.uid).card.position,'attack');assert.equal(e.find(b.uid).card.position,'defense');});
test('Link materials going to the GY do not activate Tearlaments fusion effects',()=>{const e=fresh(),a=put(e,0,'monsters','tear-merrli'),b=put(e,0,'monsters','tear-scheiren'),ip=e.state.players[0].extra.find(c=>c.id==='ip-masquerena');run(e,{type:'extra-summon',uid:ip.uid,materials:[a.uid,b.uid]});assert.deepEqual(e.monsters(0).map(c=>c.id),['ip-masquerena']);assert.equal(e.find(a.uid).zone,'grave');assert.equal(e.state.log.some(x=>x.key==='tear-merrli::fusion'||x.key==='tear-scheiren::fusion'),false);});
test('Knightmare discard is a cost and never activates the discarded Tear fusion',()=>{const e=fresh(),a=put(e,0,'monsters','battle-ox'),b=put(e,0,'monsters','blue-eyes'),s=put(e,0,'hand','tear-scheiren'),spell=put(e,1,'spells','mst',{faceUp:false,setTurn:2}),p=e.state.players[0].extra.find(c=>c.id==='knightmare-phoenix');run(e,{type:'extra-summon',uid:p.uid,materials:[a.uid,b.uid]});assert.equal(e.find(s.uid).zone,'grave');assert.equal(e.find(spell.uid).zone,'grave');assert.equal(e.monsters(0).some(c=>CARDS[c.id].type==='fusion'),false);});
test('Tear fusion requires its GY source and returns selected materials to the deck bottom',()=>{
  const e=fresh(),hero=put(e,0,'monsters','tear-havnis'),aqua=put(e,0,'monsters','supreme-sea-mare'),mer=put(e,0,'deck','tear-merrli'),foolish=put(e,0,'hand','foolish-burial'),zero=e.state.players[0].extra.find(c=>c.id==='tear-kitkallos');
  raw(e,{type:'activate',uid:foolish.uid,key:'foolish-burial::cast',choices:{target:[mer.uid]}});assert.equal(e.state.pending.kind,'trigger');raw(e,{type:'respond',uid:mer.uid,key:'tear-merrli::fusion'});assert.equal(e.state.pending.kind,'choice');raw(e,{type:'choose',uids:[zero.uid]});assert.equal(e.state.pending.kind,'materials');
  const before=e.snapshot();assert.equal(e.act({type:'choose',uids:[hero.uid,aqua.uid]}).ok,false);assert.deepEqual(e.snapshot(),before);
  raw(e,{type:'choose',uids:[mer.uid,aqua.uid],zone:2});assert.equal(e.find(zero.uid).zone,'monsters');assert.deepEqual(e.state.players[0].deck.slice(-2).map(c=>c.uid),[mer.uid,aqua.uid]);assert.equal(e.state.pending.kind,'trigger');raw(e,{type:'pass'});e.assertState();
});
test('D.D. Crow can banish a Tear fusion source before that chain link resolves',()=>{const e=fresh(),aqua=put(e,0,'monsters','supreme-sea-mare'),mer=put(e,0,'deck','tear-merrli'),spell=put(e,0,'hand','foolish-burial'),crow=put(e,1,'hand','dd-crow');raw(e,{type:'activate',uid:spell.uid,key:'foolish-burial::cast',choices:{target:[mer.uid]}});raw(e,{type:'respond',uid:mer.uid,key:'tear-merrli::fusion'});assert.equal(e.state.pending.kind,'window');raw(e,{type:'respond',uid:crow.uid,key:'dd-crow::banish',choices:{target:[mer.uid]}});settle(e);assert.equal(e.find(mer.uid).zone,'banished');assert.deepEqual(e.monsters(0).map(c=>c.uid),[aqua.uid]);});
test('rule cleanup, costs, battle and non-fusion summon materials are not card effects',()=>{const e=fresh();for(const kind of ['rule-resolved','rule-discard','cost-discard','cost-send','tribute','link-material','synchro-material','detach','battle'])assert.equal(e.effectMove({kind,source:ctxSource(0)}),false,kind);for(const kind of ['effect-send','effect-mill','destroy','fusion-material'])assert.equal(e.effectMove({kind}),true,kind);});
test('Sulliek sends its chosen monster by effect and can start a Tear fusion',()=>{const e=fresh(),mer=put(e,0,'monsters','tear-merrli'),aqua=put(e,0,'monsters','supreme-sea-mare'),trap=put(e,0,'spells','tear-sulliek',{faceUp:false,setTurn:1}),enemy=put(e,1,'monsters','battle-ox');run(e,{type:'activate',uid:trap.uid,key:'tear-sulliek::cast',choices:{mode:['mode:negate'],target:[enemy.uid]}},p=>p.kind==='choice'&&p.operation==='tear-send-selected'?{type:'choose',uids:[mer.uid]}:null);assert.equal(e.find(enemy.uid).card.effectNegated,true);assert.ok(e.monsters(0).some(c=>CARDS[c.id].type==='fusion'));assert.ok(e.wasUsed(0,trap,'negate','name'));});
test('I:P links during the opponent Main Phase and grants effect destruction protection',()=>{const e=fresh(),ip=put(e,0,'extraMonster','ip-masquerena',{extraSlot:0}),m=put(e,0,'monsters','tear-merrli'),cost=put(e,0,'hand','tear-scheiren'),enemy=put(e,1,'monsters','blue-eyes'),u=e.state.players[0].extra.find(c=>c.id==='knightmare-unicorn');e.state.active=1;e.state.frame={kind:'main-open',owner:1,windowOffered:false};e.pump();raw(e,{type:'respond',uid:ip.uid,key:'ip-masquerena::quick-link'});raw(e,{type:'choose',uids:[u.uid]});assert.equal(e.state.pending.purpose,'link-effect');run(e,{type:'choose',uids:[ip.uid,m.uid],zone:'extra'});assert.equal(e.find(u.uid).card.linkProtection,true);assert.equal(e.find(enemy.uid).zone,'deck');assert.equal(e.find(cost.uid).zone,'grave');assert.equal(e.destroy(u.uid,ctxSource(1,'raigeki')),false);assert.equal(e.state.active,1);});
test('Cross-Sheep revives a low-level monster after a Fusion appears in an arrow zone',()=>{const e=fresh();put(e,0,'extraMonster','cross-sheep',{extraSlot:0});const target=put(e,0,'grave','battle-ox'),fusion=put(e,0,'extra','ultimate-dragon');e.special(0,fusion.uid,{via:'fusion',zone:0});e.pump();settle(e);assert.equal(e.find(target.uid).zone,'monsters');assert.equal(e.state.players[0].monsters[0].uid,fusion.uid);});
test('a Charmer revives an opposing monster only into its arrow and preserves ownership',()=>{const e=fresh(),dharc=put(e,0,'extraMonster','dharc-charmer',{extraSlot:0}),target=put(e,1,'grave','knightmare-unicorn',{properlySummoned:true});raw(e,{type:'activate',uid:dharc.uid,key:'dharc-charmer::revive',choices:{target:[target.uid]}});assert.equal(e.state.pending.kind,'choice');assert.deepEqual(e.state.pending.candidates.map(c=>c.uid),['zone:0','zone:2']);run(e,{type:'choose',uids:['zone:2']});assert.equal(e.find(target.uid).owner,0);assert.equal(e.find(target.uid).index,2);e.destroy(target.uid,ctxSource(0,'raigeki'));assert.equal(e.find(target.uid).owner,1);assert.equal(e.find(target.uid).zone,'grave');});
test('Apollousa may negate once per chain, and can negate again in the next chain',()=>{const e=fresh(),apo=put(e,0,'monsters','apollousa',{materialCount:3}),thunder=put(e,1,'hand','thunder-dragon'),havnis=put(e,1,'hand','tear-havnis'),merrli=put(e,1,'hand','tear-merrli');e.state.active=1;raw(e,{type:'activate',uid:thunder.uid,key:'thunder-dragon::search'});raw(e,{type:'respond',uid:apo.uid,key:'apollousa::negate'});raw(e,{type:'respond',uid:havnis.uid,key:'tear-havnis::hand-special'});assert.ok(!e.state.pending||!e.state.pending.options?.some(o=>o.key==='apollousa::negate'));settle(e);assert.equal(e.attackValue(e.find(apo.uid).card),1600);raw(e,{type:'summon',uid:merrli.uid});raw(e,{type:'respond',uid:merrli.uid,key:'tear-merrli::mill'});assert.ok(e.state.pending.options.some(o=>o.key==='apollousa::negate'));raw(e,{type:'respond',uid:apo.uid,key:'apollousa::negate'});settle(e);assert.equal(e.attackValue(e.find(apo.uid).card),800);});
test('Rulkallos negates a Special Summon effect and then sends a Tear card by effect',()=>{const e=fresh(),rulk=put(e,0,'monsters','tear-rulkallos',{properlySummoned:true,summonKind:'fusion'}),scream=put(e,0,'hand','tear-scream'),target=put(e,1,'grave','blue-eyes'),reborn=put(e,1,'hand','monster-reborn');e.state.active=1;raw(e,{type:'activate',uid:reborn.uid,key:'monster-reborn::cast',choices:{target:[target.uid]}});assert.ok(e.state.pending.options.some(o=>o.key==='tear-rulkallos::negate'));raw(e,{type:'respond',uid:rulk.uid,key:'tear-rulkallos::negate'});settle(e,p=>p.kind==='choice'&&p.operation==='tear-send-selected'?{type:'choose',uids:[scream.uid]}:null);assert.equal(e.find(target.uid).zone,'grave');assert.equal(e.find(reborn.uid).zone,'grave');assert.equal(e.find(scream.uid).zone,'grave');assert.ok(e.state.players[0].hand.some(m=>CARDS[m.id].type==='trap'&&CARDS[m.id].tearlaments));});
test('Link arrow identity and a pending I:P material selection survive a save round-trip',()=>{const e=fresh(),ip=put(e,0,'extraMonster','ip-masquerena',{extraSlot:1}),m=put(e,0,'monsters','tear-merrli'),u=e.state.players[0].extra.find(c=>c.id==='knightmare-unicorn');e.state.active=1;e.state.frame={kind:'main-open',owner:1,windowOffered:false};e.pump();raw(e,{type:'respond',uid:ip.uid,key:'ip-masquerena::quick-link'});raw(e,{type:'choose',uids:[u.uid]});const g=DuelEngine.restore(e.snapshot());assert.deepEqual(g.snapshot(),e.snapshot());assert.equal(g.extraAt(1).card.uid,ip.uid);run(g,{type:'choose',uids:[ip.uid,m.uid]});assert.equal(CARDS[g.extraMonsters(0)[0].id].type,'link');});
test('V2 fixed extra zones migrate to distinct shared positions without touching old card identities',()=>{const e=fresh(),a=put(e,0,'extraMonster','utopia',{extraSlot:0}),b=put(e,1,'extraMonster','stardust-dragon',{extraSlot:1});const s=e.snapshot();s.state.version=2;for(const p of s.state.players){delete p.extraMonster.extraSlot;delete p.extraMonster2;}const restored=DuelEngine.restore(s);assert.equal(restored.state.version,3);assert.equal(restored.extraAt(0).card.uid,a.uid);assert.equal(restored.extraAt(1).card.uid,b.uid);});
test('Kitkallos sending itself and summoning Merrli produces separate five-card and three-card mills',()=>{
  const e=fresh(),kit=put(e,0,'extraMonster','tear-kitkallos',{extraSlot:0,properlySummoned:true,summonKind:'fusion'}),mer=put(e,0,'grave','tear-merrli');
  const top=['blue-eyes','battle-ox','alexandrite','luster-dragon','celtic-guardian','stone-soldier','summoned-skull','la-jinn'].map(id=>put(e,0,'deck',id)),ids=new Set(top.map(m=>m.uid));e.state.players[0].deck=[...top,...e.state.players[0].deck.filter(c=>!ids.has(c.uid))];
  const before=e.state.players[0].deck.length;run(e,{type:'activate',uid:kit.uid,key:'tear-kitkallos::exchange',choices:{target:[kit.uid]}});
  assert.equal(e.state.players[0].deck.length,before-8);assert.equal(e.find(kit.uid).zone,'grave');assert.equal(e.find(mer.uid).zone,'monsters');assert.deepEqual(e.state.log.filter(x=>x.kind==='mill').map(x=>x.count).sort(),[3,5]);
});
test('Abyss Dweller blocks later GY activations but does not negate an already activated Tear fusion',()=>{
  const e=fresh(),dweller=put(e,0,'monsters','abyss-dweller'),material=put(e,0,'monsters','battle-ox');e.attach(dweller.uid,material.uid);
  const scher=put(e,1,'hand','tear-scheiren'),aqua=put(e,1,'monsters','supreme-sea-mare'),kit=put(e,1,'extra','tear-kitkallos'),rulk=put(e,1,'extra','tear-rulkallos'),mer=put(e,1,'deck','tear-merrli'),foolish=put(e,1,'hand','foolish-burial');
  e.state.active=1;e.move(scher.uid,'grave',{kind:'effect-send',source:ctxSource(1),byOwner:1});e.pump();raw(e,{type:'respond',uid:scher.uid,key:'tear-scheiren::fusion'});raw(e,{type:'respond',uid:dweller.uid,key:'abyss-dweller::lock',choices:{cost:[material.uid]}});
  settle(e,p=>p.kind==='trigger'&&p.trigger.key==='tear-kitkallos::search-send'?{type:'pass'}:null);assert.equal(e.find(kit.uid).zone,'extraMonster');assert.equal(e.state.players[1].graveLockTurn,e.state.turn);
  run(e,{type:'activate',uid:foolish.uid,key:'foolish-burial::cast',choices:{target:[mer.uid]}});assert.equal(e.find(mer.uid).zone,'grave');assert.equal(e.find(rulk.uid).zone,'extra');assert.equal(e.state.pending,null);
});
test('Accesscode gains from the used Link material, cannot be answered, and tracks used cost attributes',()=>{
  const e=fresh(),unicorn=put(e,0,'monsters','knightmare-unicorn'),m=put(e,0,'monsters','hero-stratos'),dark=put(e,0,'grave','ip-masquerena'),fire=put(e,0,'grave','knightmare-phoenix'),enemy=put(e,1,'monsters','blue-eyes'),apo=put(e,1,'monsters','apollousa',{materialCount:4}),access=e.state.players[0].extra.find(c=>c.id==='accesscode-talker');
  run(e,{type:'extra-summon',uid:access.uid,materials:[unicorn.uid,m.uid]});assert.equal(e.attackValue(access),5300);assert.equal(apo.apollousaChain,undefined);
  run(e,{type:'activate',uid:access.uid,key:'accesscode-talker::destroy',choices:{cost:[unicorn.uid]}},p=>p.kind==='choice'&&p.operation==='destroy-selected'?{type:'choose',uids:[enemy.uid]}:null);
  const context=e.abilityContext(access.uid,'accesscode-talker::destroy','main',{owner:0}),group=e.fx.nextInput(e,context);assert.ok(!group.candidates.some(c=>c.uid===dark.uid||c.uid===access.uid));assert.ok(group.candidates.some(c=>c.uid===fire.uid));
  run(e,{type:'activate',uid:access.uid,key:'accesscode-talker::destroy',choices:{cost:[fire.uid]}});assert.equal(e.find(apo.uid).zone,'grave');assert.equal(e.find(access.uid).zone,'extraMonster');
});
test('a face-up Extra Deck Pendulum pair can use linked main zones while the Extra Zone is occupied',()=>{
  const e=fresh('qliphort');put(e,0,'extraMonster','cross-sheep',{extraSlot:0});put(e,0,'spells','qli-monolith',{slot:0});put(e,0,'spells','qli-scout',{slot:4});const a=put(e,0,'extra','qli-carrier',{faceUpExtra:true}),b=put(e,0,'extra','qli-disk',{faceUpExtra:true}),h=put(e,0,'hand','qli-helix');
  assert.equal(e.pendulumValid(0,[a.uid,b.uid,h.uid]),true);run(e,{type:'pendulum-summon',uids:[a.uid,b.uid,h.uid]});assert.deepEqual(e.state.players[0].monsters.slice(0,3).map(c=>c.id),['qli-carrier','qli-helix','qli-disk']);
});
test('Perlereino cares about the previous controller when a stolen Tear monster returns to its owner deck',()=>{
  const e=fresh(),field=put(e,0,'fieldSpell','perlereino'),stolen=put(e,0,'monsters','tear-merrli'),enemy=put(e,1,'monsters','blue-eyes');stolen.originalOwner=1;e.move(stolen.uid,'deck',{kind:'effect-return',source:ctxSource(0)});e.pump();assert.equal(e.state.pending.kind,'trigger');assert.equal(e.state.pending.trigger.key,'perlereino::destroy');assert.equal(e.state.pending.responder,0);run(e,{type:'respond',uid:field.uid,key:'perlereino::destroy',choices:{target:[enemy.uid]}});assert.equal(e.find(enemy.uid).zone,'grave');assert.equal(e.find(stolen.uid).owner,1);
});
test('Kaleido-Heart cannot be selected as a material by any Fusion profile',()=>{
  const e=fresh(),kaleido=put(e,0,'monsters','tear-kaleido-heart');assert.ok(!e.fusionPool(0).some(c=>c.uid===kaleido.uid));assert.ok(!e.fusionPool(0,{zones:['hand','monsters','extraMonster','grave'],noTokens:true}).some(c=>c.uid===kaleido.uid));
});
