const test=require('node:test'),assert=require('node:assert/strict');
const {DuelEngine}=require('../src/advanced-engine.js');
const D=globalThis.DuelData,E=globalThis.DuelEffects,{CARDS,CARD_LIST,DECKS}=D,LOCALES=require('../src/card-locales.js');
const id=name=>D.cardByName(name)?.id||name;
function fresh(){const e=new DuelEngine({deck:'early-ritual',opponentDeck:'early-fusion',seed:2002,first:0});e.state.turn=2;for(const p of e.state.players){p.deck.push(...p.hand);p.hand=[];}return e;}
function put(e,owner,zone,name,props={}){const cardId=id(name),f=e.refs(owner,['deck','extra']).find(f=>f.card.id===cardId),m=f?e.remove(f.card.uid).card:e.makeCard(cardId,owner);Object.assign(m,{faceUp:true,position:'attack',summonTurn:0,changedTurn:0,setTurn:0},props);const p=e.state.players[owner];if(['spells','monsters'].includes(zone))p[zone][props.slot??p[zone].indexOf(null)]=m;else if(zone==='fieldSpell')p.fieldSpell=m;else if(zone==='extraMonster'){m.extraSlot=owner;p.extraMonster=m;}else p[zone].push(m);e.state.originalCardCount=e.physicalCards().filter(c=>CARDS[c.id].type!=='token').length;return m;}
function act(e,a){const r=e.act(a);assert.equal(r.ok,true,JSON.stringify(a)+' : '+r.error);return r;}
function settle(e,choose){let n=0;while(e.state.pending&&e.state.winner===null&&n++<200){const p=e.state.pending,a=choose?.(p,e)||(p.kind==='window'?{type:'pass'}:p.kind==='trigger'?{type:'respond',uid:p.trigger.uid,key:p.trigger.key}:e.chooseAI(p));act(e,a);}assert.ok(n<200,'resolution terminates');e.assertState();}
function run(e,a,choose){act(e,a);settle(e,choose);}
function cast(e,m,choices={},pick){run(e,{type:'activate',uid:m.uid,key:m.id+'::cast',choices},pick);}
test('the 2002 snapshot is complete: 293 cards, every effect connected, trilingual text present',()=>{const cards=CARD_LIST.filter(c=>c.early&&c.releaseYear===2002);assert.equal(cards.length,293);assert.equal(cards.filter(c=>c.implementationStatus==='pending').length,0);for(const c of cards)for(const language of ['zh-CN','en','ja'])assert.ok(LOCALES[c.id]?.locales[language]?.name,c.id+' '+language);});
test('Union monsters equip, boost, protect their partner and can unequip',()=>{const e=fresh();const blade=put(e,0,'monsters','Dark Blade'),dragon=put(e,0,'monsters','Pitch-Dark Dragon');assert.equal(e.attackValue(blade),1800);run(e,{type:'activate',uid:dragon.uid,key:dragon.id+'::union-equip',choices:{target:[blade.uid]}});assert.equal(e.find(dragon.uid).zone,'spells');assert.equal(e.attackValue(blade),2200);assert.ok(!e.actionsFor(dragon.uid).some(a=>a.key===dragon.id+'::union-equip'),'once per turn');const enemy=put(e,1,'monsters','Blue-Eyes White Dragon');e.state.active=1;e.state.phase='battle';run(e,{type:'attack',uid:enemy.uid,target:blade.uid});assert.equal(e.find(blade.uid).zone,'monsters','partner survives');assert.equal(e.find(dragon.uid).zone,'grave','union took the destruction');
 const e2=fresh();const orc=put(e2,0,'monsters','Giant Orc'),goblin=put(e2,0,'monsters','Second Goblin');run(e2,{type:'activate',uid:goblin.uid,key:goblin.id+'::union-equip',choices:{target:[orc.uid]}});assert.equal(e2.find(goblin.uid).zone,'spells');run(e2,{type:'end'});run(e2,{type:'end'});assert.ok(e2.actionsFor(goblin.uid).some(a=>a.key===goblin.id+'::union-unequip'),'next turn allows unequip');act(e2,{type:'activate',uid:goblin.uid,key:goblin.id+'::union-unequip'});assert.equal(e2.find(goblin.uid).zone,'monsters');});
test('VWXYZ contact fusion banishes field components and cannot be revived from the Graveyard',()=>{const e=fresh();const x=put(e,0,'monsters','X-Head Cannon'),y=put(e,0,'monsters','Y-Dragon Head'),xy=put(e,0,'extra','XY-Dragon Cannon');act(e,{type:'activate',uid:x.uid,key:x.id+'::vwxyz'});assert.equal(e.state.pending.kind,'choice');act(e,{type:'choose',uids:[xy.uid]});assert.equal(e.state.pending.kind,'materials');act(e,{type:'choose',uids:[x.uid,y.uid]});assert.ok(['monsters','extraMonster'].includes(e.find(xy.uid).zone));assert.equal(e.find(x.uid).zone,'banished');assert.equal(e.find(y.uid).zone,'banished');e.move(xy.uid,'grave');assert.equal(e.canSpecial(0,xy,{via:'revive'}),false);});
test('Necrovalley blocks Graveyard moves and revives unless exempted',()=>{const e=fresh();put(e,0,'fieldSpell','Necrovalley');const assailant=put(e,0,'monsters',"Gravekeeper's Assailant"),vassal=put(e,0,'grave',"Gravekeeper's Vassal");assert.equal(e.attackValue(assailant),2000);const banished=put(e,0,'grave','Kuriboh');const release=e.move(banished.uid,'banished',{kind:'effect-banish'});assert.equal(release.to,'grave','Necrovalley stops the banish');assert.equal(e.canSpecial(0,vassal,{via:'revive'}),false);const rite=put(e,0,'spells','Rite of Spirit',{faceUp:false});cast(e,rite,{target:[vassal.uid]});assert.equal(e.find(vassal.uid).zone,'monsters','Rite ignores Necrovalley');});
test('Gravekeeper\'s Chief frees his controller\'s Graveyard from Necrovalley',()=>{const e=fresh();put(e,0,'fieldSpell','Necrovalley');put(e,0,'monsters',"Gravekeeper's Chief");const ox=put(e,0,'grave','Battle Ox');assert.equal(e.canSpecial(0,ox,{via:'revive'}),true);const foe=put(e,1,'grave','Battle Ox');assert.equal(e.canSpecial(1,foe,{via:'revive'}),false,'opponent still locked');});
test('Lava Golem summons onto the opponent\'s field by tributing their monsters and burns its current controller',()=>{const e=fresh();const a=put(e,1,'monsters','Battle Ox'),b=put(e,1,'monsters','Battle Ox');const golem=put(e,0,'hand','Lava Golem');act(e,{type:'activate',uid:golem.uid,key:golem.id+'::special'});assert.equal(e.state.pending.kind,'input');act(e,{type:'choose',uids:[a.uid,b.uid]});assert.equal(e.find(golem.uid).zone,'monsters');assert.equal(e.find(golem.uid).owner,1);assert.equal(e.state.players[0].normalSummonLockedTurn,e.state.turn);e.state.frame={kind:'standby',owner:0,stage:0,windowOffered:true};e.pump();settle(e);assert.deepEqual(e.state.players.map(p=>p.lp),[8000,8000]);e.state.active=1;e.state.frame={kind:'standby',owner:1,stage:0,windowOffered:true};e.pump();settle(e);assert.equal(e.state.players[0].lp,8000);assert.equal(e.state.players[1].lp,7000);});
test('Guardians refuse to be Summoned without their named Equip Card',()=>{const e=fresh();const foe=put(e,1,'monsters','Battle Ox'),host=put(e,0,'monsters','Battle Ox');const ceal=put(e,0,'hand','Guardian Ceal');assert.equal(e.canNormal(ceal,0),false);const bow=put(e,0,'hand','Shooting Star Bow - Ceal');cast(e,bow,{target:[host.uid]});assert.equal(e.find(bow.uid).zone,'spells','bow equipped');assert.equal(e.canNormal(ceal,0),true);run(e,{type:'summon',uid:ceal.uid});assert.equal(e.find(ceal.uid).zone,'monsters');assert.equal(e.attackValue(host),700,'bow subtracts 1000 ATK');assert.equal(e.canDirect(host,0),true,'bow grants direct attacks to its host');assert.equal(e.canDirect(ceal,0),false,'the Guardian itself has no bow');e.destroy(bow.uid);settle(e);assert.equal(e.canDirect(host,0),false);assert.ok(e.canAttack(ceal,0,foe.uid),'ordinary attacks stay legal');});
test('Dark Paladin negates a Spell by discarding and gains Dragon ATK',()=>{const e=fresh();const paladin=put(e,0,'monsters','Dark Paladin',{properlySummoned:true});assert.equal(e.attackValue(paladin),2900);put(e,1,'grave','Blue-Eyes White Dragon');put(e,0,'grave','Battle Ox');assert.equal(e.attackValue(paladin),3400,'one Dragon in the GY');const spark=put(e,1,'hand','Sparks'),cost=put(e,0,'hand','Battle Ox');e.state.active=1;e.state.phase='main1';act(e,{type:'activate',uid:spark.uid,key:spark.id+'::cast'});assert.equal(e.state.pending.kind,'window');run(e,{type:'respond',uid:paladin.uid,key:paladin.id+'::negate',choices:{cost:[cost.uid]}});assert.equal(e.find(spark.uid).zone,'grave');assert.equal(e.state.players[0].lp,8000);});
test('Spell Canceller forbids Spell activation and nullifies field Spells',()=>{const e=fresh();const canceller=put(e,0,'monsters','Spell Canceller');const spark=put(e,1,'hand','Sparks');e.state.active=1;e.state.phase='main1';assert.equal(e.act({type:'activate',uid:spark.uid,key:spark.id+'::cast'}).ok,false);put(e,1,'fieldSpell','Yami');const fiend=put(e,1,'monsters','Summoned Skull');assert.equal(e.attackValue(fiend),2500,'field aura suppressed');e.move(canceller.uid,'grave');assert.equal(e.attackValue(fiend),2700,'aura returns after Spell Canceller leaves');});
test('King Tiger Wanghu destroys weak summons but not Sets or Flip Summons',()=>{const e=fresh();put(e,1,'monsters','King Tiger Wanghu');const weak=put(e,0,'hand','Kuriboh');run(e,{type:'summon',uid:weak.uid});settle(e);assert.equal(e.find(weak.uid).zone,'grave');run(e,{type:'end'});run(e,{type:'end'});const set=put(e,0,'hand','Man-Eater Bug');run(e,{type:'summon',uid:set.uid,mode:'defense'});settle(e);assert.equal(e.find(set.uid).zone,'monsters','Set monsters survive');run(e,{type:'end'});run(e,{type:'end'});run(e,{type:'stance',uid:set.uid});settle(e);assert.equal(e.find(set.uid).zone,'monsters','Flip Summons are not destroyed');});
test('Maju Garzett copies the combined original ATK of its Tributes',()=>{const e=fresh();const a=put(e,0,'monsters','Summoned Skull'),b=put(e,0,'monsters','Summoned Skull');const garzett=put(e,0,'hand','Maju Garzett');act(e,{type:'summon',uid:garzett.uid});assert.equal(e.state.pending.purpose,'tribute');act(e,{type:'choose',uids:[a.uid,b.uid]});assert.equal(e.find(garzett.uid).zone,'monsters');assert.equal(e.attackValue(garzett),5000);});
test('Kaiser Colosseum caps the opponent\'s monster count',()=>{const e=fresh();put(e,0,'spells','Kaiser Colosseum');put(e,0,'monsters','Battle Ox');put(e,1,'monsters','Kuriboh');const second=put(e,1,'hand','Kuriboh');e.state.active=1;e.state.phase='main1';assert.equal(e.canNormal(second,1),false);e.move(e.monsters(0)[0].uid,'grave');assert.equal(e.canNormal(second,1),true,'cap follows the controller count');});
test('2002 Toons direct attack only through Toon World',()=>{const e=fresh();const elf=put(e,0,'monsters','Toon Gemini Elf');assert.equal(e.canDirect(elf,0),false);const world=put(e,0,'spells','Toon World');assert.equal(e.canDirect(elf,0),true);const foeToon=put(e,1,'monsters','Toon Cannon Soldier');assert.equal(e.canDirect(elf,0),false,'opponent Toon blocks direct attacks');e.destroy(foeToon.uid);e.destroy(world.uid);settle(e);assert.equal(e.find(elf.uid).zone,'grave','Toon World destruction takes the Toons with it');});
test('Amazoness Swords Woman redirects her battle damage to the opponent',()=>{const e=fresh();const swords=put(e,0,'monsters','Amazoness Swords Woman');const blue=put(e,1,'monsters','Blue-Eyes White Dragon');e.state.active=1;e.state.phase='battle';run(e,{type:'attack',uid:blue.uid,target:swords.uid});assert.equal(e.state.players[0].lp,8000);assert.equal(e.state.players[1].lp,6500);});
test('Contract with Exodia summons a protected Exodia Necross',()=>{const e=fresh();for(const name of ['Exodia the Forbidden One','Right Arm of the Forbidden One','Left Arm of the Forbidden One','Right Leg of the Forbidden One','Left Leg of the Forbidden One'])put(e,0,'grave',name);const necross=put(e,0,'hand','Exodia Necross'),contract=put(e,0,'hand','Contract with Exodia');cast(e,contract,{target:[necross.uid]});assert.equal(e.find(necross.uid).zone,'monsters');assert.equal(e.destroy(necross.uid,{id:id('Raigeki'),owner:1,effectType:'spell'}),false,'immune to Spell destruction');assert.equal(e.destroy(necross.uid,{id:id('Dark Hole'),owner:1,effectType:'spell'},true),false,'immune to battle');put(e,0,'hand','Right Arm of the Forbidden One');e.move(e.state.players[0].grave.filter(c=>c.id===id('Right Arm of the Forbidden One'))[0].uid,'banished',{ignoreNecrovalley:true,kind:'effect-banish'});e.state.frame={kind:'standby',owner:0,stage:0,windowOffered:true};e.pump();settle(e);assert.equal(e.find(necross.uid).zone,'grave','missing piece destroys Necross');});
test('Book of Moon and Book of Taiyou handle face-down positions without triggering FLIP effects',()=>{const e=fresh();const bug=put(e,0,'monsters','Man-Eater Bug');put(e,1,'monsters','Blue-Eyes White Dragon');const moon=put(e,0,'hand','Book of Moon');cast(e,moon,{target:[bug.uid]});assert.equal(e.find(bug.uid).zone,'monsters');assert.equal(bug.faceUp,false);assert.equal(bug.position,'defense');const taiyou=put(e,0,'hand','Book of Taiyou');cast(e,taiyou,{target:[bug.uid]});assert.equal(bug.faceUp,true);assert.equal(bug.position,'attack');assert.ok(!e.state.players[0].grave.some(c=>c.id===id('Blue-Eyes White Dragon')),'the flip did not destroy anything');});
test('cost selections actually leave their zones (tribute and discard costs)',()=>{
  // Gravekeeper's Cannonholder: the tributed monster must reach the Graveyard, not stay on the field.
  const e=fresh();
  const cannon=put(e,0,'monsters',"Gravekeeper's Cannonholder"),vassal=put(e,0,'monsters',"Gravekeeper's Vassal");
  run(e,{type:'activate',uid:cannon.uid,key:cannon.id+'::burn',choices:{cost:[vassal.uid]}});
  assert.equal(e.find(vassal.uid)?.zone,'grave','the tribute reaches the Graveyard');
  assert.ok(e.state.players[0].grave.some(m=>m.uid===vassal.uid),'it lands in its owner\'s Graveyard');
  assert.equal(e.state.players[1].lp,7300,'700 damage is dealt');
  assert.equal(e.find(cannon.uid)?.zone,'monsters','Cannonholder cannot tribute itself');
  // Toon Cannon Soldier and Mass Driver share the same tribute-cost pattern.
  const e2=fresh();
  const toon=put(e2,0,'monsters','Toon Cannon Soldier'),ox=put(e2,0,'monsters','Battle Ox');
  run(e2,{type:'activate',uid:toon.uid,key:toon.id+'::burn',choices:{cost:[ox.uid]}});
  assert.equal(e2.find(ox.uid)?.zone,'grave','Toon Cannon Soldier tribute reaches the Graveyard');
  assert.equal(e2.state.players[1].lp,7500);
  const e3=fresh();
  const driver=put(e3,0,'spells','Mass Driver'),ox2=put(e3,0,'monsters','Battle Ox');
  run(e3,{type:'activate',uid:driver.uid,key:driver.id+'::burn',choices:{cost:[ox2.uid]}});
  assert.equal(e3.find(ox2.uid)?.zone,'grave','Mass Driver tribute reaches the Graveyard');
  assert.equal(e3.state.players[1].lp,7600);
  // A discard cost (Raigeki Break) must move the discarded card to the Graveyard.
  const e4=fresh();
  const trap=put(e4,0,'spells','Raigeki Break',{faceUp:false,setTurn:1});
  const handCard=put(e4,0,'hand','Red Medicine'),foe=put(e4,1,'monsters','Battle Ox');
  run(e4,{type:'activate',uid:trap.uid,key:trap.id+'::cast',choices:{cost:[handCard.uid],target:[foe.uid]}});
  assert.equal(e4.find(handCard.uid)?.zone,'grave','the discarded cost card reaches the Graveyard');
  assert.equal(e4.find(foe.uid)?.zone,'grave','the destroyed target leaves the field');
});
test('the Gravekeeper 2002 preset duels legally against the original presets',()=>{for(const opponent of ['early-ritual','early-fusion']){const e=new DuelEngine({deck:'gravekeeper-2002',opponentDeck:opponent,seed:77,first:0});let steps=0;while(e.state.winner===null&&steps++<1500){const a=e.aiNext();if(!a)break;const r=e.act(a);if(!r.ok)throw new Error(opponent+' : '+r.error);}assert.ok(e.state.winner!==null||steps>=1500);}});
