const test=require('node:test'),assert=require('node:assert/strict');
const {D,put,clear,exercise}=require('./yearly-sweep-helpers.cjs');
const cards=D.CARD_LIST.filter(c=>c.early&&c.releaseYear===2004);
const elements=e=>{clear(e,0,'monsters');for(const n of ['Harpie Lady','Mother Grizzly','UFO Turtle','Battle Ox'])put(e,0,'monsters',n);};
const setup={
 'Machine Duplication':e=>{put(e,0,'monsters','cyber-core');put(e,0,'deck','Cyber Dragon');put(e,0,'deck','Cyber Dragon');},
 'The Second Sarcophagus':e=>{put(e,0,'spells','The First Sarcophagus');put(e,0,'deck','The Third Sarcophagus');},
 'The Third Sarcophagus':e=>{put(e,0,'spells','The First Sarcophagus');put(e,0,'deck','The Second Sarcophagus');},
 'Special Hurricane':e=>{e.monsters(1)[0].summonKind='effect';},
 'Soul Reversal':e=>put(e,0,'grave','Man-Eater Bug'),
 'Cross Counter':e=>{clear(e,0,'monsters');put(e,0,'monsters','Blue-Eyes Ultimate Dragon',{position:'defense'});},
 'Dark Magic Attack':e=>put(e,0,'monsters','Dark Magician'),
 'Sword of the Soul-Eater':e=>put(e,0,'monsters','Mystical Shine Ball'),
 'Thousand Energy':e=>put(e,0,'monsters','Mystical Shine Ball'),
 'Triangle Power':e=>put(e,0,'monsters','Mokey Mokey'),
 'Delta Attacker':e=>{clear(e,0,'monsters');for(let i=0;i<3;i++)put(e,0,'monsters','Battle Ox');},
 'The Law of the Normal':e=>{clear(e,0,'monsters');for(let i=0;i<5;i++)put(e,0,'monsters','Mystical Shine Ball');},
 'Order to Charge':e=>put(e,0,'monsters','Mystical Shine Ball'),
 'Tricky Spell 4':e=>put(e,0,'monsters','The Tricky'),
 'Level Up!':e=>{put(e,0,'monsters','Armed Dragon LV3');put(e,0,'deck','Armed Dragon LV5');},
 'Fusion Weapon':e=>put(e,0,'monsters','Elemental HERO Flame Wingman'),
 'Ritual Weapon':e=>put(e,0,'monsters','Relinquished'),
 'Big Wave Small Wave':e=>{put(e,0,'monsters','Mother Grizzly');put(e,0,'hand','Mother Grizzly');},
 'Inferno Fire Blast':e=>put(e,0,'monsters','Red-Eyes Black Dragon'),
 'Mind Wipe':e=>{for(const c of [...e.state.players[1].hand].slice(0,3))e.move(c.uid,'grave',{kind:'rule-fixture'});},
 'The Graveyard in the Fourth Dimension':e=>{put(e,0,'grave','Armed Dragon LV3');put(e,0,'grave','Armed Dragon LV5');},
 'Malice Dispersion':e=>put(e,1,'spells','Gravity Bind'),
 'Inferno Tempest':e=>clear(e,0,'monsters'),
 'Fulfillment of the Contract':e=>put(e,0,'grave','Black Luster Soldier',{properlySummoned:true}),
 'Re-Fusion':e=>put(e,0,'grave','Master of Oz',{properlySummoned:true}),
 'Release Restraint':e=>{put(e,0,'monsters','Gearfried the Iron Knight');put(e,0,'deck','Gearfried the Swordmaster');},
 'Overpowering Eye':e=>put(e,0,'monsters','Vampire Lady'),
 'Soul Rope':e=>put(e,1,'hand','Raigeki'),
 'Order to Smash':e=>put(e,0,'monsters','Mystical Shine Ball'),
 'Heavy Slump':e=>{for(let i=0;i<4;i++)put(e,1,'hand','Sparks');},
 'Ninjitsu Art of Decoy':e=>put(e,0,'monsters','Strike Ninja'),
 'Spell Purification':e=>put(e,1,'spells','Soul Absorption'),
 'Fuh-Rin-Ka-Zan':elements,
 'Rare Metalmorph':e=>put(e,0,'monsters','Gadget Soldier'),
 'Return from the Different Dimension':e=>put(e,0,'banished','Blue-Eyes White Dragon'),
 'Xing Zhen Hu':e=>put(e,1,'spells','Mystical Space Typhoon',{faceUp:false}),
 'Penalty Game!':e=>e.move(e.state.players[1].hand[0].uid,'grave',{kind:'rule-fixture'}),
 'Deck Devastation Virus':e=>put(e,0,'monsters','Dark Magician'),
 'Beast Soul Swap':e=>put(e,0,'monsters','Berserk Gorilla'),
 'Elemental Burst':elements,
 'Vampire Genesis':e=>put(e,0,'monsters','Vampire Lord'),
 'Red-Eyes Darkness Dragon':e=>put(e,0,'monsters','Red-Eyes Black Dragon'),
 'Blue-Eyes Shining Dragon':e=>put(e,0,'monsters','Blue-Eyes Ultimate Dragon'),
 'Sorcerer of Dark Magic':e=>{put(e,0,'monsters','Dark Magician');put(e,0,'monsters','Dark Magician');},
};
test('2004 source identities and executable coverage are complete',()=>{assert.equal(cards.length,284);assert.equal(cards.filter(c=>c.implementationStatus==='pending').length,0);assert.equal(new Set(cards.map(c=>c.providerId)).size,284);});
for(const card of cards)test('2004 sweep · '+card.officialName,()=>exercise(card,setup));
