const test=require('node:test'),assert=require('node:assert/strict');
const {D,put,clear,exercise}=require('./yearly-sweep-helpers.cjs');
const cards=D.CARD_LIST.filter(c=>c.early&&c.releaseYear===2005);
const setup={
 'Miracle Fusion':e=>{put(e,0,'grave','Elemental HERO Avian');put(e,0,'grave','Elemental HERO Burstinatrix');put(e,0,'extra','Elemental HERO Flame Wingman');},
 'Power Bond':e=>{put(e,0,'hand','Cyber Dragon');put(e,0,'hand','Cyber Dragon');put(e,0,'extra','Cyber Twin Dragon');},
 'Hero Spirit':e=>{clear(e,0,'monsters');put(e,0,'monsters','Elemental HERO Avian');},
 'The Wicked Dreadroot':e=>put(e,0,'monsters','Battle Ox'),
 'Ocean Dragon Lord - Neo-Daedalus':e=>put(e,0,'monsters','Levia-Dragon - Daedalus'),
 'Master Monk':e=>put(e,0,'monsters','Monk Fighter'),
 'Megarock Dragon':e=>put(e,0,'grave','Giant Soldier of Stone'),
 'Dark Eradicator Warlock':e=>put(e,0,'monsters','Dark Magician'),
 'Armed Dragon LV10':e=>put(e,0,'monsters','Armed Dragon LV7'),
 'Exxod, Master of The Guard':e=>put(e,0,'monsters','Guardian Sphinx'),
 'Doom Dozer':e=>{put(e,0,'grave','Man-Eater Bug');put(e,0,'grave','Pinch Hopper');},
 'Elemental HERO Neo Bubbleman':e=>{put(e,0,'monsters','Elemental HERO Bubbleman');put(e,0,'hand','Metamorphosis');},
 'Battery Charger':e=>put(e,0,'grave','Batteryman AA'),
 'Legendary Black Belt':e=>put(e,0,'monsters','Monk Fighter'),
 'Kaminote Blow':e=>put(e,0,'monsters','Monk Fighter'),
 'Fusion Recovery':e=>{put(e,0,'grave','Polymerization');put(e,0,'grave','Elemental HERO Avian',{earlySent:{kind:'fusion-material'}});},
 'Transcendent Wings':e=>{put(e,0,'monsters','Winged Kuriboh');put(e,0,'deck','Winged Kuriboh LV10');},
 'Des Croaking':e=>{clear(e,0,'monsters');for(let i=0;i<3;i++)put(e,0,'monsters','Des Frog');},
 'Bubble Shuffle':e=>{put(e,0,'monsters','Elemental HERO Bubbleman');put(e,0,'hand','Elemental HERO Bladedge');},
 "Dragon's Mirror":e=>{put(e,0,'grave','Blue-Eyes White Dragon');put(e,0,'grave','Blue-Eyes White Dragon');put(e,0,'extra','Blue-Eyes Ultimate Dragon');},
 'Spark Blaster':e=>put(e,0,'monsters','Elemental HERO Sparkman'),
 'Divine Sword - Phoenix Blade':e=>put(e,0,'monsters','Elemental HERO Sparkman'),
 'Magicians Unite':e=>{clear(e,0,'monsters');put(e,0,'monsters','Dark Magician');put(e,0,'monsters','Royal Magical Library');},
 'Feather Shot':e=>put(e,0,'monsters','Elemental HERO Avian'),
 'Bonding - H2O':e=>{clear(e,0,'monsters');put(e,0,'monsters','Hydrogeddon');put(e,0,'monsters','Hydrogeddon');put(e,0,'monsters','Oxygeddon');put(e,0,'deck','Water Dragon');},
 'Level Modulation':e=>put(e,0,'grave','Armed Dragon LV5',{properlySummoned:true}),
 'Armed Changer':e=>put(e,0,'hand','Sword of Deep-Seated'),
 'Gateway to Dark World':e=>put(e,0,'grave','Broww, Huntsman of Dark World'),
 'Ojamuscle':e=>{put(e,0,'monsters','Ojama King');put(e,1,'monsters','Ojama Green');},
 'Burst Return':e=>put(e,0,'monsters','Elemental HERO Burstinatrix'),
 'Bubble Blaster':e=>put(e,0,'monsters','Elemental HERO Bubbleman'),
 'Bubble Illusion':e=>put(e,0,'monsters','Elemental HERO Bubbleman'),
 'Cyclone Boomerang':e=>put(e,0,'monsters','Elemental HERO Wildheart'),
 'Ancient Gear Factory':e=>{put(e,0,'hand','Ancient Gear Golem');put(e,0,'grave','Ancient Gear Golem');put(e,0,'grave','Ancient Gear Golem');},
 'Symbol of Heritage':e=>{put(e,0,'grave','Blue-Eyes White Dragon');put(e,0,'grave','Blue-Eyes White Dragon');},
 'Photon Generator Unit':e=>{put(e,0,'monsters','Cyber Dragon');put(e,0,'monsters','Cyber Dragon');put(e,0,'deck','Cyber Laser Dragon');},
 'Ancient Gear Drill':e=>put(e,0,'monsters','Ancient Gear Soldier'),
 'Hero Heart':e=>put(e,0,'monsters','Elemental HERO Avian'),
 'Trial of the Princesses':e=>put(e,0,'monsters','White Magician Pikeru'),
 'Magnet Circle LV2':e=>put(e,0,'hand','Ancient Gear'),
 'The Flute of Summoning Kuriboh':e=>put(e,0,'deck','Winged Kuriboh'),
 'Rock Bombardment':e=>put(e,0,'deck','Giant Soldier of Stone'),
 'Lone Wolf':e=>{clear(e,0,'monsters');put(e,0,'monsters','Monk Fighter');},
 'Minefield Eruption':e=>put(e,0,'monsters','Mine Golem'),
 'Trap of Darkness':e=>{e.state.players[0].lp=2500;put(e,0,'grave','Jar of Greed');},
 'A Rival Appears!':e=>put(e,0,'hand','Blue-Eyes White Dragon'),
 'Spiritual Water Art - Aoi':e=>put(e,0,'monsters','Mother Grizzly'),
 'Spiritual Fire Art - Kurenai':e=>put(e,0,'monsters','UFO Turtle'),
 'Spiritual Wind Art - Miyabi':e=>put(e,0,'monsters','Harpie Lady'),
 'Magical Explosion':e=>{for(const m of [...e.state.players[0].hand])e.move(m.uid,'grave',{kind:'rule-fixture'});},
 'Fire Darts':e=>{for(const m of [...e.state.players[0].hand])e.move(m.uid,'grave',{kind:'rule-fixture'});},
 "Magician's Circle":e=>{clear(e,1,'monsters');put(e,1,'monsters','Dark Magician');put(e,0,'deck','Mystic Tomato');},
 'The Forces of Darkness':e=>{put(e,0,'grave','Broww, Huntsman of Dark World');put(e,0,'grave','Beiige, Vanguard of Dark World');},
 'Hero Barrier':e=>put(e,0,'monsters','Elemental HERO Clayman'),
 'The League of Uniform Nomenclature':e=>{put(e,0,'monsters','Mystical Shine Ball');put(e,0,'deck','Mystical Shine Ball');put(e,0,'deck','Mystical Shine Ball');},
 'Feather Wind':e=>put(e,0,'monsters','Elemental HERO Avian'),
 'Roll Out!':e=>{put(e,0,'grave','W-Wing Catapult');put(e,0,'monsters','V-Tiger Jet');},
 'Hero Ring':e=>put(e,0,'monsters','Elemental HERO Clayman'),
 'Clay Charge':e=>{clear(e,0,'monsters');put(e,0,'monsters','Elemental HERO Clayman');},
 'Success Probability 0%':e=>{put(e,1,'extra','Master of Oz');put(e,1,'extra','Sanwitch');},
 'Next to be Lost':e=>put(e,0,'deck','Blue-Eyes White Dragon'),
 'Generation Shift':e=>put(e,0,'deck','Blue-Eyes White Dragon'),
 'Attack Reflector Unit':e=>{put(e,0,'monsters','Cyber Dragon');put(e,0,'deck','Cyber Barrier Dragon');},
 'Super Junior Confrontation':e=>{e.monsters(0)[0].position='defense';},
 'Treasure Map':e=>put(e,1,'hand','Giant Trunade'),
};
test('2005 source identities and executable coverage are complete',()=>{assert.equal(cards.length,298);assert.equal(cards.filter(c=>c.implementationStatus==='pending').length,0);assert.equal(new Set(cards.map(c=>c.providerId)).size,298);});
for(const card of cards)test('2005 sweep · '+card.officialName,()=>exercise(card,setup));
