const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{createHash}=require('node:crypto');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..'),out=path.join(root,'output/v4-browser',new Date().toISOString().replace(/[:.]/g,'-'));
const report={ok:false,checks:[],screenshots:[],errors:[],requests:[],archive:out};let browser;
async function menu(page,action){if(await page.locator('#modal').evaluate(el=>el.open))await page.locator('#modal [data-action="close-modal"]').first().click();await page.locator('.site-header .brand').click();await page.locator('#home-screen [data-action="'+action+'"]').first().click();}
async function check(name,fn){await fn();report.checks.push(name);console.log('OK',name);}
(async()=>{
 await fs.mkdir(out,{recursive:true});let executablePath=process.env.DUEL_BROWSER;const edge='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe';if(!executablePath)try{await fs.access(edge);executablePath=edge;}catch{}
 browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{}),args:['--no-first-run','--disable-background-networking','--mute-audio']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
 await context.route(/https?:\/\//,r=>r.abort());await context.addInitScript(()=>{localStorage.setItem('duel-sanctuary-welcomed-v3','true');localStorage.setItem('duel-sanctuary-online-art-v2','false');localStorage.setItem('duel-sanctuary-prefs-v1',JSON.stringify({sound:false,reducedMotion:true,speed:'fast'}));});
 const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.stack));page.on('request',r=>{if(/^https?:/.test(r.url()))report.requests.push(r.url());});
 async function shot(name){const file=path.join(out,name+'.png');await page.screenshot({path:file,fullPage:true,animations:'disabled'});report.screenshots.push(file);}
 async function load(file){await page.goto(pathToFileURL(path.join(root,file)).href);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');}
 await check('art-free single HTML starts offline with all 5754 cards and thirty-eight decks',async()=>{await load('output/no-art/index.html');const state=await page.evaluate(()=>({cards:DuelData.CARD_LIST.filter(c=>!c.notCollectible).length,decks:DuelDecks.list().length,art:DuelArt.status().cached,overflow:document.documentElement.scrollWidth>innerWidth}));assert.deepEqual(state,{cards:5754,decks:38,art:0,overflow:false});await shot('01-offline-no-art');});
 await check('year filters, cumulative filters, Ritual category and archive pagination',async()=>{await menu(page,'library');assert.equal(await page.locator('#library-grid .library-card').count(),24);await page.selectOption('#library-year','1999');assert.match(await page.locator('#library-count').textContent(),/^623 /);await page.click('[data-action="library-page"][data-delta="1"]');assert.equal(await page.locator('#library-page-jump').inputValue(),'2');assert.equal(await page.locator('#library-page-jump').getAttribute('max'),'26');await page.selectOption('#library-year','through-2000');assert.match(await page.locator('#library-count').textContent(),/^960 /);await page.selectOption('#library-year','through-2001');await page.click('[data-action="library-filter"][data-filter="ritual"]');assert.equal(await page.locator('#library-grid .library-card').count(),16);await shot('02-ritual-archive');await page.click('#library-grid .library-card');assert.match(await page.locator('#modal .card-coverage').textContent(),/仪式怪兽编入主卡组/);await page.click('#modal [data-action="close-modal"]');});
 await check('workshop can copy, edit, export, import, save and play a Ritual deck',async()=>{await menu(page,'workshop');await page.selectOption('#ws-source','early-ritual');await page.selectOption('#ws-year','2000');await page.click('[data-action="ws-filter"][data-filter="ritual"]');await page.fill('#ws-search','Relinquished');assert.equal(await page.locator('#ws-card-grid .ws-card').count(),1);await page.fill('#ws-name','仪式 · 离线验证');assert.equal(await page.locator('#ws-save').isEnabled(),true);await page.click('#ws-save');const downloadEvent=page.waitForEvent('download');await page.click('[data-action="ws-export"]');const download=await downloadEvent,raw=await fs.readFile(await download.path());await page.click('[data-action="ws-new"]');assert.equal(await page.locator('#ws-save').isEnabled(),false);await page.setInputFiles('#ws-import-file',{name:'ritual.json',mimeType:'application/json',buffer:raw});await page.waitForFunction(()=>duelApp.workshopDraft.cards.length===40);await shot('03-yearly-workshop');await page.click('#ws-play');await page.click('[data-action="begin-game"]');assert.equal(await page.evaluate(()=>duelApp.engine.deckInfo(0).name),'仪式 · 离线验证');});
 async function stage(entries){return page.evaluate(entries=>{const e=new DuelEngine({deck:'early-ritual',opponentDeck:'early-fusion',first:0,seed:44});e.state.turn=2;for(const p of e.state.players){p.deck.push(...p.hand);p.hand=[];}const ids={};for(const [owner,zone,name,props={}] of entries){const id=DuelData.cardByName(name)?.id||name,f=e.refs(owner,['deck','extra']).find(f=>f.card.id===id),m=f?e.remove(f.card.uid).card:e.makeCard(id,owner);Object.assign(m,{faceUp:true,position:'attack',summonTurn:0,changedTurn:0,setTurn:0},props);if(['monsters','spells'].includes(zone))e.state.players[owner][zone][props.slot??e.state.players[owner][zone].indexOf(null)]=m;else e.state.players[owner][zone].push(m);ids[name]=m.uid;}e.state.originalCardCount=e.physicalCards().filter(m=>DuelData.CARDS[m.id].type!=='token').length;duelApp.restore(e.snapshot());return ids;},entries);}
 async function command(uid,text){await page.locator('[data-action="select-card"][data-card-uid="'+uid+'"]').first().click();await page.locator('#card-popover button').filter({hasText:text}).first().click();}
 async function pick(uid){await page.locator('[data-action="pending-pick"][data-uid="'+uid+'"]').click();}
 await check('Ritual summon uses actual UI choices, rejects surplus tribute, and saves pending decisions',async()=>{const ids=await stage([[0,'hand','Black Luster Soldier'],[0,'hand','Black Luster Ritual'],[0,'hand','Blue-Eyes White Dragon'],[0,'hand','Kuriboh']]);await command(ids['Black Luster Ritual'],'仪式召唤');await pick(ids['Black Luster Soldier']);await page.click('#pending-confirm');await pick(ids['Blue-Eyes White Dragon']);assert.equal(await page.locator('#pending-confirm').isEnabled(),true);await pick(ids.Kuriboh);assert.equal(await page.locator('#pending-confirm').isEnabled(),false);await pick(ids.Kuriboh);await shot('04-ritual-materials');await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');assert.equal(await page.evaluate(()=>duelApp.engine.state.pending.purpose),'ritual');await page.click('#home-continue');await pick(ids['Blue-Eyes White Dragon']);await page.click('[data-action="summon-position"][data-position="defense"]');await page.click('#pending-confirm');await page.waitForFunction(uid=>duelApp.engine.find(uid)?.zone==='monsters',ids['Black Luster Soldier']);assert.equal(await page.evaluate(uid=>duelApp.engine.find(uid).card.position,ids['Black Luster Soldier']),'defense');await shot('05-ritual-summoned');});
 await check('a large card-name declaration is searchable without rendering 5754 card images',async()=>{const ids=await stage([[0,'hand','Prohibition']]);await command(ids.Prohibition,await page.evaluate(()=>DuelI18n.effectLabel(DuelEffects.get(DuelData.cardByName('Prohibition').id+'::cast'))));assert.equal(await page.locator('#pending-search').count(),1);assert.equal(await page.locator('#modal .selection-grid .playing-card').count(),0);await page.fill('#pending-search','青眼白龙');assert.equal(await page.locator('#modal .selection-card:visible').count(),2);await page.locator('#modal .selection-card[data-uid="blue-eyes"]:visible').click();await page.click('#pending-confirm');});
 await check('a 390px mobile viewport keeps the board and paged workshop usable',async()=>{await page.setViewportSize({width:390,height:844});await shot('06-mobile-field');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await menu(page,'workshop');await page.click('#ws-filter-toggle');await page.selectOption('#ws-year','2001');await page.click('.ws-filter-done');await shot('07-mobile-workshop');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.click('#modal [data-action="close-modal"]');await page.setViewportSize({width:1440,height:1000});});
 await check('robot vs robot spectator mode reveals both hands and Set cards, decides turn order by rock-paper-scissors and supports pause / step',async()=>{await menu(page,'new-game');await page.click('[data-action="choose-mode"][data-value="spectate"]');assert.equal(await page.locator('[data-action="choose-first"]').count(),0);assert.match(await page.locator('.setup-order-note').textContent(),/猜拳/);await page.click('[data-action="choose-deck"][data-deck="gravekeeper-2002"]');await page.selectOption('#opponent-deck','early-fusion');await page.click('[data-action="begin-game"]');await page.waitForSelector('#cinematic.cinematic-rps.visible');assert.match(await page.locator('#cinematic').textContent(),/ROBOT A.*VS.*ROBOT B/s);await shot('09-rps');await page.waitForFunction(()=>duelApp.engine.state.mode==='spectate'&&duelApp.spectate.active);await page.evaluate(()=>duelApp.spectateToggle());assert.equal(await page.evaluate(()=>duelApp.spectate.paused),true);
  const revealed=await page.evaluate(()=>{const s=duelApp.engine.state;return {handB:s.players[1].hand.length,publicB:document.querySelectorAll('#opponent-bar .public-hand-card').length,backs:document.querySelectorAll('#opponent-bar .enemy-card').length,handA:s.players[0].hand.length,slotsA:document.querySelectorAll('#hand-cards .hand-slot').length,dots:document.querySelectorAll('#hand-cards .playable-dot').length,title:document.querySelector('#hand-title').textContent};});
  assert.equal(revealed.publicB,revealed.handB);assert.equal(revealed.backs,0);assert.equal(revealed.slotsA,revealed.handA);assert.equal(revealed.dots,0);assert.equal(revealed.title,'机器人 A 的手牌');
  const before=await page.evaluate(()=>duelApp.engine.state.log.length);await page.waitForTimeout(900);assert.equal(await page.evaluate(()=>duelApp.engine.state.log.length),before,'paused spectate does not advance');
  await page.evaluate(()=>{let n=0;while(n++<60&&!document.querySelector('#duel-board .set-badge')&&duelApp.engine.state.winner===null)duelApp.spectateStep();});assert.ok(await page.evaluate(()=>duelApp.engine.state.log.length)>before,'step advances the duel');
  const set=await page.evaluate(()=>{const b=document.querySelector('#duel-board .set-badge');const z=b?.closest('.zone');return {badge:!!b,backs:document.querySelectorAll('#duel-board .card-back').length,aria:z?.getAttribute('aria-label')||''};});assert.equal(set.badge,true,'a Set card is revealed');assert.equal(set.backs,0);assert.match(set.aria,/^机器人 [AB] 的/);await shot('10-spectate-revealed');
  await page.keyboard.press('e');await page.keyboard.press('1');assert.equal(await page.locator('#card-popover').isHidden(),true);assert.match(await page.locator('#turn-panel').textContent(),/ROBOT [AB]/);
  await page.evaluate(()=>duelApp.setLanguage('en'));assert.match(await page.locator('#turn-panel').textContent(),/Robot [AB] turn/);assert.equal(await page.locator('#hand-title').textContent(),'Robot A hand');await page.evaluate(()=>duelApp.setLanguage('zh-CN'));
  await menu(page,'new-game');await page.click('[data-action="choose-mode"][data-value="duel"]');await page.click('[data-action="begin-game"]');await page.waitForFunction(()=>duelApp.engine.state.mode!=='spectate');assert.equal(await page.evaluate(()=>document.querySelectorAll('#opponent-bar .enemy-card').length>0||duelApp.engine.state.players[1].hand.length===0),true,'normal duel hides the opponent hand again');});
 await check('production single HTML uses embedded local art and performs zero HTTP requests',async()=>{await load('index.html');report.buildSha256=createHash('sha256').update(await fs.readFile(path.join(root,'index.html'))).digest('hex');const status=await page.evaluate(()=>DuelArt.status());report.embeddedArt=status.cached;assert.equal(status.mode,'hybrid');await menu(page,'library');await page.selectOption('#library-year','1999');await page.click('[data-action="library-filter"][data-filter="monster"]');await page.waitForFunction(()=>[...document.querySelectorAll('#library-grid img[src]')].some(img=>img.complete&&img.naturalWidth>0));await shot('08-local-original-art');assert.equal(report.requests.length,0);assert.equal(await page.locator('img[src="undefined"]').count(),0);});
 assert.deepEqual(report.errors,[]);report.ok=true;
})().catch(e=>{report.errors.push(e.stack);console.error(e.stack);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await fs.mkdir(out,{recursive:true});await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));await fs.writeFile(path.join(root,'output/v4-browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));});
