const test=require('node:test'),assert=require('node:assert/strict');
const {DuelEngine}=require('../src/advanced-engine.js');
const D=global.DuelData,E=global.DuelEffects,{CARDS,CARD_LIST,DECKS}=D;
const id=name=>D.cardByName(name)?.id||name;
function fresh(){const e=new DuelEngine({deck:'early-ritual',opponentDeck:'early-fusion',seed:1202,first:0});e.state.turn=2;for(const p of e.state.players){p.deck.push(...p.hand);p.hand=[];}return e;}
function put(e,owner,zone,name,props={}){const cardId=id(name),f=e.refs(owner,['deck','extra']).find(f=>f.card.id===cardId),m=f?e.remove(f.card.uid).card:e.makeCard(cardId,owner);Object.assign(m,{faceUp:true,position:'attack',summonTurn:0,changedTurn:0,setTurn:0},props);const p=e.state.players[owner];if(['spells','monsters'].includes(zone))p[zone][props.slot??p[zone].indexOf(null)]=m;else if(zone==='fieldSpell')p.fieldSpell=m;else if(zone==='extraMonster'){m.extraSlot=owner;p.extraMonster=m;}else p[zone].push(m);e.state.originalCardCount=e.physicalCards().filter(c=>CARDS[c.id].type!=='token').length;return m;}
function act(e,a){const r=e.act(a);assert.equal(r.ok,true,JSON.stringify(a)+' : '+r.error);return r;}
function settle(e,choose){let n=0;while(e.state.pending&&e.state.winner===null&&n++<200){const p=e.state.pending,a=choose?.(p,e)||(p.kind==='window'?{type:'pass'}:p.kind==='trigger'?{type:'respond',uid:p.trigger.uid,key:p.trigger.key}:e.chooseAI(p));act(e,a);}assert.ok(n<200,'resolution terminates');e.assertState();}
function run(e,a,choose){act(e,a);settle(e,choose);}
function cast(e,m,choices={},pick){run(e,{type:'activate',uid:m.uid,key:m.id+'::cast',choices},pick);}
test('all fourteen local snapshots are imported once, with stable identities and separate effect coverage',()=>{const early=CARD_LIST.filter(c=>c.early);assert.equal(early.length,5664);assert.equal(new Set(early.map(c=>c.providerId)).size,5664);assert.deepEqual([1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012].map(y=>early.filter(c=>c.releaseYear===y).length),[623,337,242,293,237,284,298,312,408,537,520,573,518,482]);assert.equal(CARD_LIST.filter(c=>!c.notCollectible).length,5754);assert.equal(early.filter(c=>c.existing).length,114);assert.equal(early.filter(c=>c.implementationStatus==='pending').length,0);assert.ok(early.every(c=>c.originalDescription&&c.dateVerification==='provider_candidate'));});
test('thirty-eight presets remain valid and Rituals belong to the Main Deck',()=>{for(const deck of Object.values(DECKS).filter(d=>d.preset))assert.equal(global.DuelDecks.analyze(deck).valid,true,deck.id);assert.equal(Object.values(DECKS).filter(d=>d.preset).length,38);for(const m of CARD_LIST.filter(c=>c.type==='ritual')){assert.ok(D.isMonster(m));assert.ok(!D.isExtra(m));}});
test('all twenty-seven named Ritual pairs actually summon with their own spells',()=>{const spells=CARD_LIST.filter(c=>c.ritualTarget);assert.equal(spells.length,27);for(const def of spells){const e=fresh(),spell=put(e,0,'hand',def.id),target=put(e,0,'hand',def.ritualTarget),material=put(e,0,'hand',def.ritualExact?'Summoned Skull':'Blue-Eyes White Dragon');cast(e,spell,{},p=>p.purpose==='ritual'?{type:'choose',uids:[material.uid],position:'defense'}:p.kind==='trigger'&&p.trigger.sourceId===id('Dawn of the Herald')?{type:'pass'}:null);assert.equal(e.find(target.uid).zone,'monsters',def.officialName);assert.equal(target.summonKind,'ritual');assert.equal(target.position,'defense');assert.equal(target.properlySummoned,true);assert.equal(e.find(material.uid).zone,'grave');}});
test('Ritual cards cannot be Normal Summoned or improperly revived',()=>{const e=fresh(),r=put(e,0,'hand','Black Luster Soldier');assert.equal(e.canNormal(r),false);assert.equal(e.canSpecial(0,r,{via:'effect'}),false);e.move(r.uid,'grave');assert.equal(e.canSpecial(0,r,{via:'revive'}),false);r.properlySummoned=true;assert.equal(e.canSpecial(0,r,{via:'revive'}),true);e.move(r.uid,'hand');assert.equal(r.properlySummoned,false);});
test('Ritual validation rejects over-tributing and levelless Xyz/Link materials',()=>{const e=fresh(),r=put(e,0,'hand','Black Luster Soldier'),lv8=put(e,0,'hand','Blue-Eyes White Dragon'),lv1=put(e,0,'hand','Kuriboh'),link=put(e,0,'monsters','linkuriboh'),xyz=put(e,0,'monsters','abyss-dweller'),spell=id('Black Luster Ritual');assert.equal(e.ritualValid(0,r,[lv8],spell),true);assert.equal(e.ritualValid(0,r,[lv8,lv1],spell),false);assert.equal(e.ritualValid(0,r,[link,xyz],spell),false);assert.equal(e.ritualValid(0,r,[lv8],id('Black Magic Ritual')),false);});
test('Rituals permit necessary over-level sums and free a main zone by tributing it',()=>{const e=fresh(),r=put(e,0,'hand','Black Luster Soldier'),a=put(e,0,'monsters','Summoned Skull'),b=put(e,0,'hand','Summoned Skull');for(let i=1;i<5;i++)put(e,0,'monsters','Battle Ox');const s=id('Black Luster Ritual');assert.ok(e.ritualValid(0,r,[a,b],s));const hand8=put(e,0,'hand','Blue-Eyes White Dragon');assert.equal(e.ritualValid(0,r,[hand8],s),false);});
test('Mask of Restrict disables Ritual tributing from both the hand and field',()=>{const e=fresh(),r=put(e,0,'hand','Black Luster Soldier');put(e,0,'hand','Blue-Eyes White Dragon');put(e,1,'spells','Mask of Restrict');assert.equal(e.ritualCombos(0,r,id('Black Luster Ritual')).length,0);});
test('Ritual selection survives a JSON save and resumes with identical outcome',()=>{const e=fresh(),r=put(e,0,'hand','Black Luster Soldier'),s=put(e,0,'hand','Black Luster Ritual'),mat=put(e,0,'hand','Blue-Eyes White Dragon');act(e,{type:'activate',uid:s.uid,key:s.id+'::cast'});assert.equal(e.state.pending.kind,'choice');act(e,{type:'choose',uids:[r.uid]});assert.equal(e.state.pending.purpose,'ritual');const saved=e.snapshot(),copy=DuelEngine.restore(JSON.parse(JSON.stringify(saved)));assert.deepEqual(copy.snapshot(),saved);run(e,{type:'choose',uids:[mat.uid],position:'attack'});run(copy,{type:'choose',uids:[mat.uid],position:'attack'});assert.deepEqual(copy.snapshot(),e.snapshot());});
test('negating a Ritual spell consumes neither the monster nor its tribute',()=>{const e=fresh(),r=put(e,0,'hand','Black Luster Soldier'),s=put(e,0,'hand','Black Luster Ritual'),mat=put(e,0,'hand','Blue-Eyes White Dragon'),jammer=put(e,1,'spells','Magic Jammer',{faceUp:false}),cost=put(e,1,'hand','Battle Ox');act(e,{type:'activate',uid:s.uid,key:s.id+'::cast'});assert.equal(e.state.pending.kind,'window');run(e,{type:'respond',uid:jammer.uid,key:jammer.id+'::cast',choices:{cost:[cost.uid]}});assert.equal(e.find(r.uid).zone,'hand');assert.equal(e.find(mat.uid).zone,'hand');assert.equal(e.find(s.uid).zone,'grave');});
test('a negated Normal Summon does not trigger Senju and still spends the normal summon',()=>{const e=fresh(),m=put(e,0,'hand','Senju of the Thousand Hands'),judgment=put(e,1,'spells','Solemn Judgment',{faceUp:false});act(e,{type:'summon',uid:m.uid});assert.equal(e.state.pending.context.kind,'summon-attempt');run(e,{type:'respond',uid:judgment.uid,key:judgment.id+'::cast'});assert.equal(e.find(m.uid).zone,'grave');assert.equal(e.state.players[1].lp,4000);assert.equal(e.state.normalUsed,true);assert.ok(!e.state.log.some(l=>l.key===m.id+'::search'));});
test('Normal Summon and Ritual search use distinct monster and spell pools',()=>{for(const [name,kind] of [['Senju of the Thousand Hands','ritual'],['Sonic Bird','spell']]){const e=fresh(),m=put(e,0,'hand',name);run(e,{type:'summon',uid:m.uid});assert.ok(e.state.players[0].hand.some(m=>CARDS[m.id].type===kind&&(kind!=='spell'||CARDS[m.id].spellKind==='ritual')));}});
test('a FLIP monster destroyed in battle resolves after damage',()=>{const e=fresh();e.state.phase='battle';const bug=put(e,1,'monsters','Man-Eater Bug',{faceUp:false,position:'defense'}),att=put(e,0,'monsters','Blue-Eyes White Dragon');run(e,{type:'attack',uid:att.uid,target:bug.uid});assert.equal(e.find(bug.uid).zone,'grave');assert.equal(e.find(att.uid).zone,'grave');});
test('Sangan tributed for a Ritual searches without losing physical cards',()=>{const e=fresh(),r=put(e,0,'hand','Relinquished'),s=put(e,0,'hand','Black Illusion Ritual'),mat=put(e,0,'monsters','Sangan');cast(e,s,{},p=>p.purpose==='ritual'?{type:'choose',uids:[mat.uid]}:null);assert.equal(e.find(r.uid).zone,'monsters');assert.ok(e.state.players[0].hand.length>=1);assert.ok(e.state.players[0].nameLocks.length);});
test('Relinquished equips a monster without fabricating a Graveyard event',()=>{const e=fresh(),r=put(e,0,'monsters','Relinquished',{properlySummoned:true}),s=put(e,1,'monsters','Sangan');run(e,{type:'activate',uid:r.uid,key:r.id+'::absorb',choices:{target:[s.uid]}});assert.equal(e.find(s.uid).zone,'spells');assert.equal(e.attackValue(r),1000);assert.equal(e.defenseValue(r),600);assert.ok(!e.state.log.some(l=>l.key===s.id+'::search'));assert.equal(s.originalOwner,1);});
test('Relinquished substitutes its equip for battle destruction and reflects damage',()=>{const e=fresh(),r=put(e,0,'monsters','Relinquished'),victim=put(e,1,'monsters','Battle Ox');run(e,{type:'activate',uid:r.uid,key:r.id+'::absorb',choices:{target:[victim.uid]}});const attacker=put(e,1,'monsters','Blue-Eyes White Dragon');e.state.active=1;e.state.phase='battle';run(e,{type:'attack',uid:attacker.uid,target:r.uid});assert.equal(e.find(r.uid).zone,'monsters');assert.equal(e.find(victim.uid).zone,'grave');assert.equal(e.state.players[0].lp,6700);assert.equal(e.state.players[1].lp,6700);assert.equal(e.attackValue(r),0);});
test('equip bonuses disappear immediately when the equip leaves',()=>{const e=fresh(),m=put(e,0,'monsters','Battle Ox'),s=put(e,0,'hand','United We Stand');cast(e,s,{target:[m.uid]});assert.equal(e.attackValue(m),2500);put(e,0,'monsters','Kuriboh');assert.equal(e.attackValue(m),3300);e.destroy(s.uid);assert.equal(e.attackValue(m),1700);});
test('field auras use race and A Legendary Ocean reduces WATER levels',()=>{const e=fresh(),m=put(e,0,'monsters','Mother Grizzly');put(e,0,'fieldSpell','A Legendary Ocean');assert.equal(e.attackValue(m),1600);assert.equal(e.level(m),3);assert.ok(e.hasEarly('Umi'));});
test('Change of Heart returns a stolen monster at End Phase without changing ownership',()=>{const e=fresh(),m=put(e,1,'monsters','Blue-Eyes White Dragon'),s=put(e,0,'hand','Change of Heart');cast(e,s,{target:[m.uid]});assert.equal(e.find(m.uid).owner,0);assert.equal(m.originalOwner,1);run(e,{type:'end'});assert.equal(e.find(m.uid).owner,1);});
test('Call of the Haunted remains linked when removed after revival',()=>{const e=fresh(),m=put(e,0,'grave','Battle Ox'),s=put(e,0,'spells','Call of the Haunted',{faceUp:false});cast(e,s,{target:[m.uid]});assert.equal(e.find(m.uid).zone,'monsters');e.move(s.uid,'hand',{kind:'effect-return'});e.pump();settle(e);assert.equal(e.find(m.uid).zone,'grave');});
test('one Fusion substitute works, two substitutes do not',()=>{const e=fresh(),f=put(e,0,'extra','Blue-Eyes Ultimate Dragon'),a=put(e,0,'hand','Blue-Eyes White Dragon'),b=put(e,0,'hand','Blue-Eyes White Dragon'),sub=put(e,0,'hand','Mystical Sheep #1'),sub2=put(e,0,'hand','Versago the Destroyer');assert.equal(e.fusionValid(0,f,[a,b,sub]),true);assert.equal(e.fusionValid(0,f,[a,sub,sub2]),false);assert.ok(e.fusionCombos(0,f).some(set=>set.includes(sub.uid)));});
test('DNA Surgery changes current race, including equipment validity filters',()=>{const e=fresh(),m=put(e,0,'monsters','Blue-Eyes White Dragon'),s=put(e,0,'spells','DNA Surgery',{faceUp:false});cast(e,s,{race:['race:战士族']});assert.equal(e.race(m),'战士族');e.destroy(s.uid);assert.equal(e.race(m),'龙族');});
test('Gravity Bind checks levels, leaving Xyz and Link attacks available',()=>{const e=fresh();put(e,1,'spells','Gravity Bind');const dragon=put(e,0,'monsters','Blue-Eyes White Dragon'),xyz=put(e,0,'monsters','abyss-dweller');e.state.phase='battle';assert.equal(e.canAttack(dragon,0,null),false);assert.equal(e.canAttack(xyz,0,null),true);});
test('Ground Collapse blocks Normal and Special placement, not only the counter',()=>{const e=fresh(),s=put(e,0,'hand','Ground Collapse');cast(e,s,{zones:['zone:0:0','zone:1:0']});const m=put(e,0,'hand','Battle Ox');run(e,{type:'summon',uid:m.uid});assert.equal(e.find(m.uid).index,1);assert.ok(!e.freeZones(0,put(e,0,'hand','Kuriboh')).includes(0));});
test('cards with always-treated-as names share the three-copy deck limit',()=>{const spec={...DECKS['early-ritual'],cards:[...DECKS['early-ritual'].cards]};spec.cards.splice(0,4,id('Harpie Lady'),id('Harpie Lady'),id('Harpie Lady'),id('Cyber Harpie Lady'));assert.ok(global.DuelDecks.analyze(spec).errors.some(x=>x.includes('同名')));});
test('Scapegoat tokens cannot be tributed for Tribute Summons but can pay effect costs',()=>{const e=fresh(),s=put(e,0,'hand','Scapegoat');cast(e,s);assert.equal(e.monsters(0).length,4);const token=e.monsters(0)[0];assert.equal(e.canTribute(token,0,'normal'),false);assert.equal(e.canTribute(token,0,'effect'),true);assert.equal(e.canSpecial(0,put(e,0,'hand','Battle Ox')),false);});
test('Cross-Sheep also resolves its Ritual draw two discard two effect',()=>{const e=fresh(),sheep=put(e,0,'extraMonster','cross-sheep'),r=put(e,0,'hand','Relinquished'),s=put(e,0,'hand','Black Illusion Ritual'),mat=put(e,0,'hand','Kuriboh');const deckBefore=e.state.players[0].deck.length;cast(e,s,{},p=>p.purpose==='ritual'?{type:'choose',uids:[mat.uid],zone:0}:null);assert.equal(e.find(r.uid).index,0);assert.equal(e.state.players[0].deck.length,deckBefore-2);assert.equal(e.state.players[0].hand.length,0);});
test('Destiny Board places I N A L in order and wins',()=>{const e=fresh(),board=put(e,0,'spells','Destiny Board');for(const name of ['Spirit Message "I"','Spirit Message "N"','Spirit Message "A"','Spirit Message "L"'])put(e,0,'deck',name);for(let i=0;i<4;i++){e.state.active=1;e.state.turn=3+i*2;e.state.frame={kind:'end',owner:1,stage:0,windowOffered:true};e.pump();settle(e);}assert.equal(e.state.winner,0);assert.ok(e.state.resultReason.includes('通灵盘'));});
test('Cyber Jar removes field monsters and processes five revealed cards for each player',()=>{const e=fresh(),jar=put(e,0,'monsters','Cyber Jar',{faceUp:false,position:'defense'});run(e,{type:'stance',uid:jar.uid});assert.equal(e.find(jar.uid).zone,'grave');assert.ok(e.monsters(0).length+e.state.players[0].hand.length>=5);assert.ok(e.monsters(1).length+e.state.players[1].hand.length>=5);});
test('invalid actions still roll back all added early-era state',()=>{const e=fresh(),m=put(e,0,'hand','Black Luster Soldier'),snapshot=e.snapshot();assert.equal(e.act({type:'summon',uid:m.uid}).ok,false);assert.deepEqual(e.snapshot(),snapshot);});
test('Ritual spell fixed level requirement survives A Legendary Ocean level reduction',()=>{const e=fresh(),r=put(e,0,'hand','Crab Turtle'),mat=put(e,0,'hand','Gaia the Fierce Knight');put(e,0,'fieldSpell','A Legendary Ocean');assert.equal(e.level(r),7);assert.equal(e.ritualRequirement(id('Turtle Oath'),r),8);assert.equal(e.ritualValid(0,r,[mat],id('Turtle Oath')),false);});
test('A Legendary Ocean affects ordinary Tribute Summon requirements in the hand',()=>{const e=fresh(),m=put(e,0,'hand','Amphibian Beast');put(e,0,'fieldSpell','A Legendary Ocean');assert.equal(e.level(m),5);assert.equal(e.tributeCount(m),1);const lv5=put(e,0,'hand','The Legendary Fisherman');assert.equal(e.level(lv5),4);assert.equal(e.tributeCount(lv5),0);});
test('Sangan whose Summon was negated never counts as having reached the field',()=>{const e=fresh(),m=put(e,0,'hand','Sangan'),judgment=put(e,1,'spells','Solemn Judgment',{faceUp:false});act(e,{type:'summon',uid:m.uid});run(e,{type:'respond',uid:judgment.uid,key:judgment.id+'::cast'});assert.equal(e.find(m.uid).zone,'grave');assert.equal(e.state.players[0].hand.length,0);assert.ok(!e.state.log.some(l=>l.key===m.id+'::search'));});
test('set continuous traps cannot use their face-up effects before card activation',()=>{const e=fresh(),s=put(e,0,'spells','Ultimate Offering',{faceUp:false});put(e,0,'hand','Battle Ox');assert.ok(!e.actionsFor(s.uid).some(a=>a.key===s.id+'::normal'));});
test('Ultimate Offering supplies an additional summon without restoring the normal allowance',()=>{const e=fresh(),s=put(e,0,'spells','Ultimate Offering'),m=put(e,0,'hand','Battle Ox');e.state.normalUsed=true;run(e,{type:'activate',uid:s.uid,key:s.id+'::normal'});assert.equal(e.find(m.uid).zone,'monsters');assert.equal(e.state.normalUsed,true);assert.equal(e.state.players[0].lp,7500);});
test('Confiscation reveals its selectable hand targets rather than hidden card backs',()=>{const e=fresh(),s=put(e,0,'hand','Confiscation'),target=put(e,1,'hand','Blue-Eyes White Dragon',{faceUp:false});act(e,{type:'activate',uid:s.uid,key:s.id+'::cast'});assert.equal(e.state.pending.kind,'choice');const o=e.state.pending.candidates.find(c=>c.uid===target.uid);assert.equal(o.cardId,target.id);assert.equal(o.hidden,undefined);run(e,{type:'choose',uids:[target.uid]});assert.equal(e.find(target.uid).zone,'grave');});
test('Embodiment of Apophis is a real temporary monster with level and statistics',()=>{const e=fresh(),trap=put(e,0,'spells','Embodiment of Apophis',{faceUp:false});cast(e,trap);assert.equal(e.find(trap.uid).zone,'monsters');assert.equal(e.level(trap),4);assert.equal(e.attackValue(trap),1600);assert.equal(e.defenseValue(trap),1800);assert.equal(e.race(trap),'爬虫类族');e.move(trap.uid,'grave');assert.equal(trap.asMonster,undefined);});
test('Makyura grants exactly one Trap activation from the hand',()=>{const e=fresh(),m=put(e,0,'monsters','Makyura the Destructor'),jar=put(e,0,'hand','Jar of Greed'),second=put(e,0,'hand','Jar of Greed');e.move(m.uid,'grave',{kind:'effect-send',byOwner:0});e.pump();settle(e);assert.ok(e.actionsFor(jar.uid).some(a=>a.key===jar.id+'::cast'));cast(e,jar);assert.ok(!e.actionsFor(second.uid).some(a=>a.key===second.id+'::cast'));});
test('Freed replaces the normal draw with a Warrior search',()=>{const e=fresh();put(e,0,'monsters','Freed the Matchless General');put(e,0,'deck','Celtic Guardian');run(e,{type:'end'});run(e,{type:'end'});assert.equal(e.state.active,0);assert.ok(e.state.log.some(l=>l.kind==='search'));assert.equal(e.state.players[0].hand.length,1);assert.equal(CARDS[e.state.players[0].hand[0].id].race,'战士族');});
test('continuous hand reveal rules expose only the intended hand',()=>{const e=fresh();assert.equal(e.handRevealed(1,0),false);const eye=put(e,0,'spells','The Eye of Truth');assert.equal(e.handRevealed(1,0),true);assert.equal(e.handRevealed(0,1),false);e.destroy(eye.uid);put(e,1,'monsters','Ceremonial Bell');assert.equal(e.handRevealed(0,1),true);assert.equal(e.handRevealed(1,0),true);});
test('a properly absorbed Sangan later sent from the equip zone still searches',()=>{const e=fresh(),r=put(e,0,'monsters','Relinquished'),s=put(e,1,'monsters','Sangan');run(e,{type:'activate',uid:r.uid,key:r.id+'::absorb',choices:{target:[s.uid]}});e.destroy(s.uid,{id:r.id,owner:0});e.pump();settle(e);assert.ok(e.state.players[1].hand.length>=1);});
test('7 Completed cannot start a mode choice without any legal Machine target',()=>{const e=fresh(),equip=put(e,0,'hand','7 Completed');put(e,0,'monsters','Battle Ox');assert.ok(!e.actionsFor(equip.uid).some(a=>a.key===equip.id+'::cast'));const machine=put(e,0,'monsters','Patrol Robo'),before=e.attackValue(machine);cast(e,equip,{stat:['stat:ATK'],target:[machine.uid]});assert.equal(e.attackValue(machine),before+700);});
test('Chosen One requires its two other hand cards before offering activation',()=>{const e=fresh(),spell=put(e,0,'hand','Chosen One');put(e,0,'hand','Battle Ox');assert.ok(!e.actionsFor(spell.uid).some(a=>a.key===spell.id+'::cast'));put(e,0,'hand','Sparks');put(e,0,'hand','Red Medicine');assert.ok(e.actionsFor(spell.uid).some(a=>a.key===spell.id+'::cast'));});
test('Chain Energy charges a hand activation or summon once, not twice',()=>{const e=fresh();put(e,1,'spells','Chain Energy');e.state.players[0].lp=750;const spark=put(e,0,'hand','Sparks');cast(e,spark);assert.equal(e.state.players[0].lp,250);assert.equal(e.state.players[1].lp,7800);e.state.players[0].lp=750;const m=put(e,0,'hand','Blue-Eyes White Dragon');e.special(0,m.uid,{via:'effect'});assert.equal(e.state.players[0].lp,250);assert.equal(e.find(m.uid).zone,'monsters');});
test('Ameba resolves under its new controller and only once while remaining face-up',()=>{const e=fresh(),m=put(e,0,'monsters','Ameba');e.takeControl(m.uid,1);e.pump();settle(e);assert.equal(e.state.players[1].lp,6000);e.takeControl(m.uid,0);e.pump();settle(e);assert.equal(e.state.players[0].lp,8000);assert.equal(e.state.players[1].lp,6000);});
test('Sanga uses its zero-ATK effect only once per face-up stay and only for that calculation',()=>{const e=fresh(),sanga=put(e,0,'monsters','Sanga of the Thunder'),blue=put(e,1,'monsters','Blue-Eyes White Dragon');e.state.active=1;e.state.phase='battle';run(e,{type:'attack',uid:blue.uid,target:sanga.uid},p=>p.kind==='window'&&p.options.some(o=>o.key===sanga.id+'::zero')?{type:'respond',uid:sanga.uid,key:sanga.id+'::zero'}:null);assert.equal(sanga.zeroUsed,true);assert.equal(e.attackValue(blue),3000);e.state.turn+=2;const next=put(e,1,'monsters','Blue-Eyes White Dragon');e.state.frame={kind:'attack',owner:1,attack:{uid:next.uid,target:sanga.uid,owner:1,stage:'calc',serial:42}};assert.ok(!e.responseOptions(0).some(o=>o.key===sanga.id+'::zero'));});
test('a normal Trap Monster is a Ritual/Link material but not an Effect Monster material',()=>{const e=fresh(),trap=put(e,0,'spells','Embodiment of Apophis',{faceUp:false});cast(e,trap);const ox=put(e,0,'hand','Battle Ox'),r=put(e,0,'hand','Black Luster Soldier'),spell=put(e,0,'hand','Black Luster Ritual'),unicorn=put(e,0,'monsters','knightmare-unicorn'),access=put(e,0,'extra','accesscode-talker'),phoenix=put(e,0,'extra','knightmare-phoenix');assert.equal(e.linkValid(0,access,[trap,unicorn]),false);assert.equal(e.linkValid(0,phoenix,[trap,unicorn]),true);assert.equal(e.ritualValid(0,r,[trap,ox],spell.id),true);cast(e,spell,{},p=>p.purpose==='ritual'?{type:'choose',uids:[trap.uid,ox.uid]}:null);assert.equal(e.find(r.uid).zone,'monsters');assert.equal(e.find(trap.uid).zone,'grave');assert.equal(trap.asMonster,undefined);});
test('Magical Hats does not invent levels, types or attributes for its temporary monsters',()=>{const e=fresh(),trap=put(e,0,'spells','Magical Hats',{faceUp:false}),ox=put(e,0,'monsters','Battle Ox'),a=put(e,0,'deck','Sparks'),b=put(e,0,'deck','Red Medicine'),enemy=put(e,1,'monsters','Blue-Eyes White Dragon'),r=put(e,0,'hand','Relinquished');e.state.active=1;e.state.phase='battle';act(e,{type:'attack',uid:enemy.uid,target:ox.uid});act(e,{type:'respond',uid:trap.uid,key:trap.id+'::cast',choices:{target:[ox.uid],hats:[a.uid,b.uid]}});assert.equal(e.find(a.uid).zone,'monsters');assert.equal(e.find(b.uid).zone,'monsters');assert.equal(e.level(a),0);assert.equal(e.race(a),'无种族');assert.equal(e.attribute(a),'无');assert.ok(!e.ritualPool(0,r).some(m=>m.uid===a.uid||m.uid===b.uid));});
test('a control exchange never loses Extra Zone monsters when both main fields are full',()=>{const e=fresh();for(const owner of [0,1])for(let i=0;i<5;i++)put(e,owner,'monsters','Battle Ox');const a=put(e,0,'extraMonster','cross-sheep'),b=put(e,1,'extraMonster','ip-masquerena'),spell=put(e,0,'hand','Creature Swap');cast(e,spell,{},p=>p.operation==='early-swap-first'?{type:'choose',uids:[a.uid]}:p.operation==='early-swap-second'?{type:'choose',uids:[b.uid]}:null);assert.equal(e.find(a.uid).owner,0);assert.equal(e.find(b.uid).owner,1);e.assertState();});
