const {chromium}=require('playwright'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url'),{createHash}=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.join(root,'output/years-browser'),report={checks:[],errors:[],yearCounts:{}};
async function menu(page,action){if(await page.locator('#modal').evaluate(el=>el.open))await page.locator('#modal [data-action="close-modal"]').first().click();await page.locator('.site-header .brand').click();await page.locator('#home-screen [data-action="'+action+'"]').first().click();}
(async()=>{await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.DUEL_BROWSER||'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',args:['--mute-audio']});const context=await browser.newContext({viewport:{width:1440,height:900}});await context.route(/https?:\/\//,r=>r.abort());await context.addInitScript(()=>{localStorage.setItem('duel-sanctuary-prefs-v1',JSON.stringify({sound:false,music:false,reducedMotion:true}));localStorage.setItem('duel-sanctuary-online-art-v2','false');});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
 const check=async(name,fn)=>{await fn();report.checks.push(name);console.log('OK',name);};
 try{await page.goto(pathToFileURL(path.join(root,'index.html')).href);await page.waitForFunction(()=>window.duelApp&&window.DuelData);
  await check('all 7486 cards, 49 decks and seventeen years load offline',async()=>{const result=await page.evaluate(()=>({cards:DuelData.CARD_LIST.filter(c=>!c.notCollectible).length,decks:DuelDecks.list().length,years:DuelData.earlyYears,pending:DuelData.CARD_LIST.filter(c=>c.implementationStatus==='pending').length}));assert.deepEqual(result,{cards:7486,decks:49,years:[1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015],pending:0});});
  await check('single-year and cumulative archive filters use the imported counts in all three languages',async()=>{await menu(page,'library');for(const language of ['zh-CN','en','ja']){await page.evaluate(l=>duelApp.setLanguage(l),language);for(const [year,count,total] of [[2003,237,1732],[2004,284,2016],[2005,298,2314]]){await page.selectOption('#library-year',String(year));assert.match(await page.locator('#library-count').textContent(),new RegExp('^'+count+' '));const ids=await page.locator('#library-grid .library-card').evaluateAll(els=>els.map(el=>el.dataset.cardId));assert.ok(ids.length>0);assert.equal(await page.evaluate(({ids,year})=>ids.every(id=>DuelData.CARDS[id].releaseYear===year),{ids,year}),true);await page.selectOption('#library-year','through-'+year);assert.match(await page.locator('#library-count').textContent(),new RegExp('^'+total+' '));report.yearCounts[year]=count;}}await page.selectOption('#library-year','2005');await page.screenshot({path:path.join(out,'01-year-2005-japanese.png'),animations:'disabled'});});
  await check('new presets can be selected and a Dark World spectator duel uses its real construction',async()=>{await page.evaluate(()=>duelApp.setLanguage('zh-CN'));await menu(page,'new-game');for(const id of ['chaos-2003','level-2004','darkworld-2005']){assert.equal(await page.locator('[data-action="choose-deck"][data-deck="'+id+'"]').count(),1);await page.click('[data-action="choose-deck"][data-deck="'+id+'"]');}await page.click('[data-action="choose-mode"][data-value="spectate"]');await page.selectOption('#opponent-deck','level-2004');await page.click('[data-action="begin-game"]');await page.waitForFunction(()=>duelApp.engine.state.players[0].deckId==='darkworld-2005'&&duelApp.spectate.active);await page.evaluate(()=>{if(!duelApp.spectate.paused)duelApp.spectateToggle();duelApp.skipChain();});const result=await page.evaluate(()=>({mine:duelApp.engine.deckInfo(0).cards,expected:DuelData.DECKS['darkworld-2005'].cards,other:duelApp.engine.state.players[1].deckId,mode:duelApp.engine.state.mode}));assert.deepEqual(result.mine,result.expected);assert.equal(result.other,'level-2004');assert.equal(result.mode,'spectate');await page.screenshot({path:path.join(out,'02-darkworld-spectate.png'),animations:'disabled'});});
  await check('the enlarged archive stays usable on a 390px screen and preserves the selected language',async()=>{await page.setViewportSize({width:390,height:844});await menu(page,'library');await page.selectOption('#library-year','2004');await page.evaluate(()=>duelApp.setLanguage('en'));assert.match(await page.locator('#library-count').textContent(),/^284 /);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(out,'03-mobile-year-2004.png'),animations:'disabled'});await page.reload();await page.waitForFunction(()=>window.duelApp);assert.equal(await page.evaluate(()=>DuelI18n.language),'en');});
  assert.deepEqual(report.errors,[]);report.buildSha256=createHash('sha256').update(await fs.readFile(path.join(root,'index.html'))).digest('hex');
 }catch(error){report.failure=error.stack;console.error(error);await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});process.exitCode=1;}finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();}
})();
