import {spawnSync} from 'node:child_process';
import {writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),run=join(root,'output/v4-checks',new Date().toISOString().replace(/[:.]/g,'-'));
await mkdir(run,{recursive:true});
const files=['tests/engine.test.cjs','tests/v2-core.test.cjs','tests/v2-regression.test.cjs','tests/v3-rules.test.cjs','tests/v4-rules.test.cjs','tests/v4-2002.test.cjs','tests/v4-2002-sweep.test.cjs','tests/yearly-collector.test.mjs','tests/game-art.test.mjs','tests/collection-progress.test.mjs','tests/i18n.test.cjs','tests/experience.test.cjs','tests/tournament.test.cjs','tests/ai-marginal.test.cjs'];
const result=spawnSync(process.execPath,['--test','--test-reporter=tap',...files],{cwd:root,encoding:'utf8',maxBuffer:20_000_000});
const log=(result.stdout||'')+(result.stderr||'');await writeFile(join(run,'results.tap'),log);process.stdout.write(log);
const number=key=>Number(log.match(new RegExp('^# '+key+' (\\d+)$','m'))?.[1]||0),report={at:new Date().toISOString(),node:process.version,ok:result.status===0,tests:number('tests'),pass:number('pass'),fail:number('fail'),files,archive:run,network:'no real requests; asset tests use synthetic fixtures'};
await writeFile(join(run,'report.json'),JSON.stringify(report,null,2));await writeFile(join(root,'output/v4-checks-report.json'),JSON.stringify(report,null,2));process.exitCode=result.status||0;
