import {spawnSync} from 'node:child_process';
import {writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),run=join(root,'output/v4-checks',new Date().toISOString().replace(/[:.]/g,'-'));
await mkdir(run,{recursive:true});
const files=['tests/engine.test.cjs','tests/v2-core.test.cjs','tests/v2-regression.test.cjs','tests/v3-rules.test.cjs','tests/v4-rules.test.cjs','tests/v4-2002.test.cjs','tests/v4-2002-sweep.test.cjs','tests/yearly-collector.test.mjs','tests/game-art.test.mjs','tests/collection-progress.test.mjs','tests/i18n.test.cjs','tests/experience.test.cjs','tests/tournament.test.cjs','tests/ai-marginal.test.cjs','tests/v4-2003.test.cjs','tests/v4-2003-sweep.test.cjs','tests/v4-2004.test.cjs','tests/v4-2004-sweep.test.cjs','tests/v4-2005.test.cjs','tests/v4-2005-sweep.test.cjs'];
files.push('tests/ai-tactics.test.cjs','tests/duel-outcome.test.cjs','tests/journal.test.cjs');
files.push('tests/gx-rules.test.cjs','tests/gx-sweep.test.cjs','tests/card-materials.test.mjs','tests/chronicle-rules.test.cjs','tests/chronicle-2013.test.cjs','tests/chronicle-2014.test.cjs',...['traps','spells','monsters','xyz','archetypes','knights','monarch','samurai','pendulum'].map(b=>'tests/chronicle-2014-'+b+'.test.cjs'),'tests/chronicle-sweep.test.cjs');
files.push('tests/controller-costs.test.cjs');
files.push('tests/lingering.test.cjs','tests/simulation-fixes.test.cjs');
files.push('tests/ai-planner.test.cjs');
files.push('tests/pvp.test.mjs','tests/pvp-network.test.mjs');
files.push('tests/ai-provider.test.cjs','tests/card-resolver.test.cjs','tests/deck-parse.test.cjs','tests/ai-proxy.test.mjs');
files.push('tests/deck-research.test.cjs','tests/deck-search.test.mjs');
files.push('tests/audio-lifecycle.test.cjs');
files.push('tests/rule-modes.test.cjs','tests/archetype-membership.test.cjs','tests/archetype-registry.test.cjs','tests/archetype-interactions.test.cjs');
files.push(...['pendulum','engines','themes','expansion','final'].map(n=>'tests/chronicle-2015-'+n+'.test.cjs'));
files.push(...['core','engines','support','abc','fusion','themes','kozmo'].map(n=>'tests/chronicle-2016-'+n+'.test.cjs'));
files.push('tests/optimization-project.test.cjs','tests/workshop-drag.test.cjs','tests/side-matches.test.cjs','tests/pvp-matches.test.mjs');
files.push('tests/card-link.test.mjs','tests/link-materials.test.cjs');
files.push('tests/chronicle-2017.test.cjs','tests/chronicle-2017-interactions.test.cjs','tests/chronicle-2017-expansion.test.cjs');
files.push('tests/chronicle-2018.test.cjs','tests/chronicle-2018-interactions.test.cjs');
files.push('tests/chronicle-2019.test.cjs','tests/chronicle-2019-interactions.test.cjs');
const concurrency=process.env.DUEL_TEST_CONCURRENCY;
if(concurrency&&!/^[1-9]\d*$/.test(concurrency))throw new Error('DUEL_TEST_CONCURRENCY must be a positive integer');
const result=spawnSync(process.execPath,['--test','--test-reporter=tap',...(concurrency?['--test-concurrency='+concurrency]:[]),...files],{cwd:root,encoding:'utf8',maxBuffer:20_000_000});
const log=(result.stdout||'')+(result.stderr||'');await writeFile(join(run,'results.tap'),log);process.stdout.write(log);
const number=key=>Number(log.match(new RegExp('^# '+key+' (\\d+)$','m'))?.[1]||0),report={at:new Date().toISOString(),node:process.version,ok:result.status===0,tests:number('tests'),pass:number('pass'),fail:number('fail'),files,archive:run,network:'local HTTP/WebSocket for PVP; asset tests use synthetic fixtures'};
await writeFile(join(run,'report.json'),JSON.stringify(report,null,2));await writeFile(join(root,'output/v4-checks-report.json'),JSON.stringify(report,null,2));process.exitCode=result.status||0;
