/* Shared 2009–2012 mechanics. State is JSON; temporary rule-evaluation guards
 * and cost context are deliberately not persisted. */
(function(root){
 'use strict';const X=root.DuelChronicle,{D,E,H,C,I,is,allM,allS,allF,monster,hand,deck,grave,first,args,src,active,field,has,extend,g,target,moved,choose,revive,search,card,def,series,lock,locked,effect,watch,mark}=X,{CARDS}=D,P=root.ModernDuelEngine.prototype,U=root.DuelModernUtils;
 const named=(m,n)=>!!m&&def(m)?.officialName===n,rawIds=new Map();
 function raw(e,n,owner=null){let id=rawIds.get(n);if(id===undefined){id=C(n)?.id||null;rawIds.set(n,id);}if(!id)return [];const out=[];for(const p of owner===null?[0,1]:[owner]){const s=e.state.players[p];if(!s)continue;for(const [zone,list] of [['monsters',s.monsters],['spells',s.spells],['extraMonster',[s.extraMonster,s.extraMonster2]],['fieldSpell',[s.fieldSpell]]])for(const m of list||[])if(m&&m.id===id&&m.faceUp&&!m.pendingActivation&&!m.effectNegated&&!m.spellNegated)out.push({owner:p,zone,card:m});}return out;}
 const rawHas=(e,n,p=null)=>raw(e,n,p).some(f=>!(f.card.eraNegatedUntil>=e.state.turn)),fmonster=z=>z==='monsters'||z==='extraMonster',normal=(e,m)=>e.isNormalMonster(m);
 // Preserve source identity for detach costs, including WATER/Atlantean costs.
 const payCost=E.payCost;E.payCost=function(e,c){const previous=e._eraCostSource;e._eraCostSource=c.source;try{return payCost(e,c);}finally{e._eraCostSource=previous;}};
 P.detach=function(uid,uids){const f=this.find(uid);U.req(f&&fmonster(f.zone),'超量怪兽不在场上。');U.req(new Set(uids).size===uids.length&&uids.every(uid=>f.card.overlays.some(m=>m.uid===uid)),'请选择此怪兽持有的超量素材。');const source=this._eraCostSource||this.state.resolvingLink?.source;for(const uid of uids)this.move(uid,'grave',{kind:'detach',reason:'移除超量素材',source,asCost:!!this._eraCostSource,byOwner:source?.owner??f.owner});};
 // Flexible Synchro materials do not mutate the card's actual displayed Level.
 C('Vanadis of the Nordic Ascendant').nordicSubstitute=true;
 P.synchroMaterialTuner=function(m,extra,list){if(!this.isTuner(m))return false;if(!is(m,'Phantom King Hydride'))return true;const fixed=list.filter(q=>this.isTuner(q)&&!is(q,'Phantom King Hydride')),need=Math.max(0,(def(extra).synchro?.minTuners||1)-fixed.length);return list.filter(q=>is(q,'Phantom King Hydride')).slice(0,need).includes(m);};
 P.synchroMaterialLevel=function(m,extra,list){if(is(m,'Road Synchron')&&!is(extra,'Road Warrior'))return Math.max(1,this.level(m)-2);if(list.some(q=>is(q,'Mono Synchron'))&&!is(m,'Mono Synchron'))return 1;return this.level(m);};
 P.xyzMaterialLevel=function(m,extra){return is(m,'Star Drawing')&&def(extra).rank===5?5:this.level(m);};
 const handRules=[['T.G. Cyber Magician',m=>series(m,'T.G.'),m=>series(m,'T.G.'),1,5],['Malefic Parallel Gear',m=>series(m,'Malefic'),()=>true,1,1],['Mara of the Nordic Alfar',m=>series(m,'Nordic'),()=>true,2,2],['Eccentric Boy',monster,()=>true,1,1]];
 extend('synchroValid',function(prior,p,extra,list,o={}){
  if(!extra||!list.every(Boolean))return false;
  const handMats=list.filter(m=>this.find(m.uid)?.zone==='hand'),opponents=list.filter(m=>this.find(m.uid)?.owner!==p);
  if(handMats.length&&!o.virtual&&!handRules.some(([name,pred,accept,min,max])=>list.some(m=>is(m,name)&&fmonster(this.find(m.uid)?.zone)&&this.find(m.uid)?.owner===p)&&accept(extra)&&handMats.length>=min&&handMats.length<=max&&handMats.every(m=>this.find(m.uid)?.owner===p&&pred(m))))return false;
  if(opponents.some(m=>m.eraSynchroOwner!==p||m.eraSynchroTurn!==this.state.turn))return false;
  if(list.some(m=>m.eraNoSynchro||m.eraNoSynchroTurn===this.state.turn||m.eraSynchroRace&&m.eraSynchroRace!==this.race(extra)))return false;
  const restricted=[['Scrap Chimera','Scrap'],['Scrap Soldier','Scrap'],['XX-Saber Boggart Knight','X-Saber'],['Blackwing - Breeze the Zephyr','Blackwing']];
  if(restricted.some(([n,f])=>list.some(m=>is(m,n))&&!series(extra,f)))return false;
  if(list.some(m=>is(m,'Scrap Chimera')||is(m,'Scrap Mind Reader'))&&!list.every(m=>series(m,'Scrap')))return false;
  if(list.some(m=>is(m,'Vanadis of the Nordic Ascendant'))&&!list.filter(m=>!is(m,'Vanadis of the Nordic Ascendant')).every(m=>series(m,'Nordic')))return false;
  if(list.some(m=>is(m,'Blackwing - Kochi the Daybreak')&&!m.normalSummoned))return false;
  if(list.some(m=>is(m,'Trust Guardian'))&&this.level(extra)<7||list.some(m=>is(m,'Chain Dog'))&&this.race(extra)!=='兽族'||list.some(m=>is(m,'Fishborg Launcher'))&&!this.hasAttribute(extra,'水')||list.some(m=>is(m,'Brotherhood of the Fire Fist - Spirit'))&&this.race(extra)!=='兽战士族')return false;
  if(list.some(m=>is(m,'Mono Synchron'))&&!list.filter(m=>!is(m,'Mono Synchron')).every(m=>this.level(m)<=4&&['战士族','机械族'].includes(this.race(m))))return false;
  return prior.call(this,p,extra,list,{...o,...(handMats.length||opponents.length?{virtual:true}:{})});
 });
 extend('synchroCombos',function(prior,p,extra,required=null){const original=prior.call(this,p,extra,required),extraPool=this.monsters(1-p).filter(m=>m.eraSynchroOwner===p&&m.eraSynchroTurn===this.state.turn);let handPool=[];
  for(const [n,pred,accept] of handRules)if(accept(extra)&&this.monsters(p).some(m=>m.faceUp&&is(m,n)))handPool.push(...hand(this,p,pred));
  if(!handPool.length&&!extraPool.length)return original;const pool=[...this.monsters(p).filter(m=>m.faceUp),...new Map([...handPool,...extraPool].map(m=>[m.uid,m])).values()],out=[...original],seen=new Set(out.map(a=>a.slice().sort().join('|')));let visited=0;
  const walk=(at,set)=>{if(++visited>5000||out.length>=100)return;if(set.length>=2&&(!required||set.some(m=>m.uid===required))&&this.synchroValid(p,extra,set)){const u=set.map(m=>m.uid),k=u.slice().sort().join('|');if(!seen.has(k)){seen.add(k);out.push(u);}}if(set.length>=7)return;for(let i=at;i<pool.length;i++)walk(i+1,[...set,pool[i]]);};walk(0,[]);return out;
 });
 extend('xyzValid',function(prior,p,extra,list,rankUp=false){return prior.call(this,p,extra,list,rankUp)&&list.every(m=>(!is(m,'Constellar Siat')||series(extra,'Constellar'))&&(!is(m,'Heroic Challenger - Double Lance')||this.race(extra)==='战士族')&&(!is(m,'Garbage Lord')||this.hasAttribute(extra,'暗'))&&(!m.eraXyzAttribute||this.hasAttribute(extra,m.eraXyzAttribute)));});
 extend('performXyz',function(prior,p,uid,uids,o={}){const ids=uids.map(u=>card(this,u)?.id);const r=prior.call(this,p,uid,uids,o);if(r){if(o.rankUp)r.eraRankUpTurn=this.state.turn;if(ids.includes(I('Heroic Challenger - Extra Sword')))this.modify(uid,'atk','add',1000,null);if(ids.includes(I('Star Drawing')))this.draw(p,1);}return r;});
 extend('performSynchro',function(prior,p,uid,uids,o={}){const ids=uids.map(u=>card(this,u)?.id);const r=prior.call(this,p,uid,uids,o),m=card(this,uid);if(m){m.eraSynchroMaterials=ids;if(ids.includes(I('Needle Soldier')))m.eraPiercing=true;if(ids.includes(I('Torapart')))m.eraTorapart=true;if(ids.includes(I('Trust Guardian')))m.eraTrustGuardian=true;}return r;});
 // Gishki's whole tribute and LP rituals share the normal ritual UI validation.
 extend('ritualAccepts',function(prior,id,m){return !!m&&def(m).type==='ritual'&&CARDS[id]?.ritualSeries&&series(m,CARDS[id].ritualSeries)||prior.call(this,id,m);});
 extend('ritualPool',function(prior,p,m,id){if(is({id},'Gishki Photomirror'))return [];if(is({id},'Forbidden Arts of the Gishki'))return allM(this).filter(q=>q.faceUp&&this.level(q)>0&&this.canTribute(q,this.find(q.uid).owner));const list=prior.call(this,p,m,id);return CARDS[id]?.ritualAny?list.filter(q=>this.find(q.uid)?.zone==='deck'):list;});
 P.ritualWeight=function(m,target,id){return def(m).eraRitualWhole&&this.hasAttribute(target,'水')?this.ritualRequirement(id,target):this.level(m);};
 P.ritualValid=function(p,m,list,id){if(!m||this.find(m.uid)?.zone!=='hand'||this.find(m.uid)?.owner!==p||!this.ritualAccepts(id,m)||!this.canSpecial(p,m,{via:'ritual'}))return false;if(is({id},'Gishki Photomirror'))return !list.length&&this.state.players[p].lp>this.level(m)*500&&this.freeZones(p,m).length>0;const pool=new Set(this.ritualPool(p,m,id).map(q=>q.uid)),need=this.ritualRequirement(id,m),weights=list.map(q=>q&&this.ritualWeight(q,m,id)),sum=weights.reduce((a,b)=>a+b,0);return list.length>0&&new Set(list.map(q=>q?.uid)).size===list.length&&list.every(q=>q&&pool.has(q.uid))&&(CARDS[id].ritualExact?sum===need:sum>=need)&&weights.every(n=>sum-n<need)&&this.freeZones(p,m,{materials:list.map(q=>q.uid)}).length>0;};
 P.ritualCombos=function(p,m,id){if(!m||!this.ritualAccepts(id,m)||!this.canSpecial(p,m,{via:'ritual'}))return [];if(is({id},'Gishki Photomirror'))return this.ritualValid(p,m,[],id)?[[]]:[];const pool=this.ritualPool(p,m,id),need=this.ritualRequirement(id,m),out=[];const walk=(at,list,total)=>{if(out.length>=200)return;if(total>=need){if(this.ritualValid(p,m,list,id))out.push(list.map(q=>q.uid));return;}for(let i=at;i<pool.length;i++)walk(i+1,[...list,pool[i]],total+this.ritualWeight(pool[i],m,id));};walk(0,[],0);return out;};
 P.performRitual=function(p,uid,uids,id,source,zone=null,position='attack'){const m=card(this,uid),list=uids.map(u=>card(this,u));U.req(this.ritualValid(p,m,list,id),'仪式素材或生命值不符合要求。');const snapshots=list.map(q=>this.describe(q));if(is({id},'Gishki Photomirror'))this.payLP(p,this.level(m)*500);else for(const q of list){const djinn=def(q).eraDjinn&&this.find(q.uid)?.zone==='grave';this.move(q.uid,djinn?'banished':'grave',{kind:CARDS[id].ritualAny?'effect-ritual-material':'effect-ritual-tribute',source,byOwner:p});}if(CARDS[id].ritualAny)this.shuffle(this.state.players[p].deck);const result=this.special(p,uid,{via:'ritual',position,materials:snapshots,...(zone!==null?{zone}:{})});if(result){result.eraDjinnMaterials=snapshots.filter(q=>CARDS[q.id].eraDjinn).map(q=>q.id);result.eraRitualSpell=id;result.eraRitualMaterials=uids;if(is({id},'Forbidden Arts of the Gishki')){this.modify(uid,'atk','mul',.5,null,source);this.state.players[p].skipBattleTurn=this.state.turn;}this.emit({type:'era-ritual',owner:p,uid,id:m.id,spellId:id,source,materials:snapshots});}return result;};
 extend('runTask',function(prior,t){if(t.op==='ritual-materials'&&is({id:t.spellId},'Gishki Photomirror')){const m=card(this,t.uid);if(m&&this.ritualValid(t.owner,m,[],t.spellId))return this.performRitual(t.owner,t.uid,[],t.spellId,t.source);return;}return prior.call(this,t);});
 effect('Gishki Aquamirror',(e,c)=>grave(e,c.owner,m=>series(m,'Gishki')&&def(m).type==='ritual'),(e,c)=>moved(e,c,args(c),'hand','effect-return'),{zones:['grave'],oncePerTurn:false,cost:(e,c)=>{moved(e,c,[c.uid],'deck','cost-return');e.shuffle(e.state.players[c.owner].deck);},role:'search'});
 E.trigger(I('Dawn of the Herald'),'era-recover',{label:C('Dawn of the Herald').name,zones:['grave','spells'],inputs:(e,c)=>[g(e,c,'target','选择仪式解放的怪兽',grave(e,c.owner,m=>c.event.materials.some(q=>q.uid===m.uid)),1,1,'search')],cost:(e,c)=>moved(e,c,[c.uid],'banished','cost-banish'),resolve:(e,c)=>moved(e,c,args(c),'hand','effect-return')});E.on('era-ritual',(e,v)=>{if(v.spellId===I('Dawn of the Herald')){const m=card(e,v.source?.uid);if(m)e.addTrigger(m.uid,m.id+'::era-recover',v,{owner:v.owner});}});
 // Field-bound once uses reset when a card is turned face-down; generation is
 // part of both effect identities and target validation.
 extend('setPosition',function(prior,uid,pos,s,down=false){const m=card(this,uid),was=m?.faceUp;const r=prior.call(this,uid,pos,s,down);if(r&&down&&was&&m){m.generation=(m.generation||0)+1;for(const key of Object.keys(m))if(key.startsWith('era')&&!['eraDjinnMaterials'].includes(key))delete m[key];}return r;});
 extend('move',function(prior,uid,to,o={}){const f=this.find(uid),m=f?.card,was=f&&field(f.zone),keep=['eraEclipse'];const r=prior.call(this,uid,to,o);if(r&&was&&r.to!==r.from&&m){for(const k of Object.keys(m))if(k.startsWith('era')&&!keep.includes(k))delete m[k];}return r;});
 // Original effects can safely survive their source leaving the field. Only
 // effects that actually require a surviving source decline that operation.
 const oldAttach=P.attach;P.attach=function(host,uid,s){const r=oldAttach.call(this,host,uid,s);if(r)this.emit({type:'era-attach',owner:this.find(host).owner,uid:host,materialUid:uid});return r;};
 const equipMonster=P.equipMonster;P.equipMonster=function(uid,host,p,s){const r=equipMonster.call(this,uid,host,p,s);if(r)this.emit({type:'era-equipped',owner:p,uid:host,equipUid:uid,equipId:card(this,uid)?.id});return r;};
 E.on('summon',(e,v)=>{const p=e.state.players[v.owner];if(v.kind==='normal'){(p.eraNormalNames||=[]).push(v.id);}if(v.kind==='xyz')p.eraXyzTurn=e.state.turn;if(v.kind==='normal'&&v.materials?.some(m=>is(m,'Hardened Armed Dragon'))&&CARDS[v.id].level>=7){const m=card(e,v.uid);if(m)m.eraPermanentEffectProtect=true;}});
 E.on('phase',(e,v)=>{if(v.phase==='battle'&&locked(e,v.owner,'fishborgArcher'))for(const m of e.monsters(v.owner).filter(m=>!e.hasAttribute(m,'水')))e.destroy(m.uid,{owner:v.owner,effectType:'monster',id:I('Fishborg Archer')});});
 extend('endTurn',function(prior,...a){const before=this.state.turn,r=prior.call(this,...a);if(this.state.turn!==before)for(const p of this.state.players){p.eraNormalNames=[];p.eraBlackwingDestroyed=0;p.eraDamageCount=0;}return r;});
 E.on('move',(e,v)=>{if(v.kind==='battle'&&v.to==='grave'&&v.previous?.eraMiniGuts?.turn===e.state.turn)e.damage(1-v.previous.eraMiniGuts.owner,Math.max(0,CARDS[v.id].atk),'效果');if(['battle','destroy'].includes(v.kind)&&v.to==='grave'){if(series({id:v.id},'Blackwing'))e.state.players[v.owner].eraBlackwingDestroyed=(e.state.players[v.owner].eraBlackwingDestroyed||0)+1;if(CARDS[v.id].type==='synchro'&&v.byOwner!==undefined&&v.byOwner!==v.owner)e.state.players[v.byOwner].eraDestroyedSynchro=e.state.turn;}});
 // Exported only for deterministic tests and the companion continuous rules.
 Object.assign(X,{raw,rawHas,fmonster});
 if(typeof module!=='undefined'){require('./chronicle-continuous.js');require('./chronicle-costs.js');require('./chronicle-copies.js');}
})(globalThis);
