(function(root){
 'use strict';
 const D=root.DuelData,{CARDS,isMonster}=D,P=root.ModernDuelEngine.prototype,U=root.DuelModernUtils,{req,cp,fieldMonster}=U;
 if(P.earlyRulesLoaded)return;P.earlyRulesLoaded=true;
 const old={};
 function wrap(name,fn){old[name]=P[name];P[name]=fn;}
 const names=(e,name)=>[0,1].flatMap(p=>e.field(p)).filter(m=>(CARDS[m.id].officialName===name||CARDS[m.id].nameAlias===name)&&m.faceUp&&!m.summonPending&&(fieldMonster(e.find(m.uid)?.zone)?!e.negated(m):e.activeSpell(m)));
 P.hasEarly=function(name,owner=null){return names(this,name).some(c=>owner===null||this.find(c.uid).owner===owner);};
 P.race=function(card){if(card.raceOverride)return card.raceOverride;const dna=names(this,'DNA Surgery').at(-1);if(dna&&card.faceUp&&fieldMonster(this.find(card.uid)?.zone))return dna.declaredRace||CARDS[card.id].race;const equip=this.activeEquip(card).find(c=>c.raceChange);return equip?.raceChange||CARDS[card.id].race;};
 P.canTribute=function(card,owner=this.state.active,kind='effect'){return !!card&&!CARDS[card.id].cannotTribute&&!(kind==='normal'&&CARDS[card.id].cannotTributeSummon)&&!this.hasEarly('Mask of Restrict')&&(this.find(card.uid)?.owner===owner||card.soulExchangeOwner===owner&&card.soulExchangeTurn===this.state.turn);};
 P.ritualPool=function(owner,target){return this.refs(owner,['hand','monsters','extraMonster']).filter(f=>f.card.uid!==target.uid&&(isMonster(CARDS[f.card.id])||fieldMonster(f.zone)&&f.card.asMonster)&&this.level(f.card)>0&&this.canTribute(f.card,owner,'ritual')).map(f=>f.card);};
 P.ritualRequirement=function(spellId,target){return CARDS[spellId]?.ritualLevel||CARDS[target.id].level;};
 P.ritualValid=function(owner,target,materials,spellId){
  if(!target||this.find(target.uid)?.zone!=='hand'||this.find(target.uid)?.owner!==owner||CARDS[target.id].type!=='ritual'||CARDS[spellId]?.ritualTarget!==target.id||!this.canSpecial(owner,target,{via:'ritual'}))return false;
  const pool=new Set(this.ritualPool(owner,target).map(c=>c.uid)),need=this.ritualRequirement(spellId,target),levels=materials.map(c=>c&&this.level(c)),sum=levels.reduce((a,b)=>a+b,0);
  return materials.length>0&&new Set(materials.map(c=>c?.uid)).size===materials.length&&materials.every(c=>c&&pool.has(c.uid))&&sum>=need&&levels.every(n=>sum-n<need)&&this.freeZones(owner,target,{materials:materials.map(c=>c.uid)}).length>0;
 };
 P.ritualCombos=function(owner,target,spellId){
  if(!target||CARDS[spellId]?.ritualTarget!==target.id||!this.canSpecial(owner,target,{via:'ritual'}))return [];
  const pool=this.ritualPool(owner,target),need=this.ritualRequirement(spellId,target),out=[];
  // Stop a branch once it meets the level requirement: adding more would be unnecessary.
  function walk(at,chosen,total,e){if(out.length>=200)return;if(total>=need){if(e.ritualValid(owner,target,chosen,spellId))out.push(chosen.map(c=>c.uid));return;}for(let i=at;i<pool.length;i++)walk(i+1,[...chosen,pool[i]],total+e.level(pool[i]),e);}
  walk(0,[],0,this);return out;
 };
 P.ritualOptions=function(owner,spellId){return this.state.players[owner].hand.filter(c=>c.id===CARDS[spellId]?.ritualTarget&&this.ritualCombos(owner,c,spellId).length);};
 P.performRitual=function(owner,uid,uids,spellId,source,zone=null,position='attack'){
  const target=this.find(uid)?.card,materials=uids.map(x=>this.find(x)?.card);req(this.ritualValid(owner,target,materials,spellId),'仪式素材需要满足等级，不能额外解放多余素材，并须留下可用的主怪兽区。');
  const snapshots=materials.map(c=>this.describe(c));for(const card of materials)this.move(card.uid,'grave',{kind:'effect-ritual-tribute',source,byOwner:owner});
  return this.special(owner,uid,{via:'ritual',position,materials:snapshots,...(zone!==null?{zone}:{})});
 };
 wrap('validatePick',function(p,uids){const r=old.validatePick.call(this,p,uids);if(!r.valid)return r;if(p.purpose==='ritual'&&!this.ritualValid(p.owner,this.find(p.uid)?.card,uids.map(uid=>this.find(uid)?.card),p.spellId))return {valid:false,message:'等级不足、包含多余解放，或没有可用主怪兽区。'};return r;});
 wrap('choose',function(a){const p=this.state.pending;if(p?.kind==='materials'&&p.purpose==='ritual'){const r=this.validatePick(p,a.uids||[]);req(r.valid,r.message);this.state.pending=null;return this.performRitual(p.owner,p.uid,a.uids,p.spellId,p.source,a.zone??null,a.position||'attack');}return old.choose.call(this,a);});
 wrap('runTask',function(t){if(t.op==='ritual-materials'){const m=this.find(t.uid)?.card,sets=this.ritualCombos(t.owner,m,t.spellId);if(!sets.length){this.log('effect','仪式召唤未能进行：手牌、素材或区域已改变',t.owner);return;}this.state.pending={kind:'materials',purpose:'ritual',owner:t.owner,responder:t.owner,uid:m.uid,spellId:t.spellId,source:t.source,title:'仪式解放 · '+CARDS[m.id].name+' / '+this.level(m)+' 星',min:1,max:this.ritualPool(t.owner,m).length,candidates:this.ritualPool(t.owner,m).map(c=>this.option(c,{viewer:t.owner})),cancelable:false};return;}return old.runTask.call(this,t);});
 wrap('chooseAI',function(p){if(p.kind==='materials'&&p.purpose==='ritual'){const sets=this.ritualCombos(p.owner,this.find(p.uid)?.card,p.spellId).sort((a,b)=>a.reduce((n,uid)=>n+this.cardUtility(this.find(uid).card,p.owner),0)-b.reduce((n,uid)=>n+this.cardUtility(this.find(uid).card,p.owner),0));req(sets.length,'仪式召唤没有合法素材。');return {type:'choose',uids:sets[0]};}return old.chooseAI.call(this,p);});
 wrap('materialMatches',function(card,spec,owner){if(spec.officialName&&CARDS[card.id].officialName!==spec.officialName)return false;return old.materialMatches.call(this,card,spec,owner);});
 P.flipFaceUp=function(uid,{suppress=false,position=null,source=null}={}){const f=this.find(uid);if(!f||!fieldMonster(f.zone)||f.card.faceUp||this.unaffected(f.card,source))return false;f.card.faceUp=true;if(position)f.card.position=position;this.log('reveal','翻开「'+CARDS[f.card.id].name+'」',f.owner,{uid,cardId:f.card.id});if(!suppress)this.emit({type:'flip',uid,id:f.card.id,owner:f.owner,previous:this.describe(f.card)});return true;};
 P.setPosition=function(uid,position,source=null,faceDown=false){const f=this.find(uid);if(!f||!fieldMonster(f.zone)||CARDS[f.card.id].type==='link'||this.unaffected(f.card,source)||faceDown&&(CARDS[f.card.id].type==='token'||this.hasEarly('Light of Intervention')))return false;const from=f.card.position;f.card.position=position;if(faceDown){f.card.faceUp=false;this.cleanupEquips(uid);}else if(!f.card.faceUp)this.flipFaceUp(uid,{source});this.emit({type:'position',uid,id:f.card.id,owner:f.owner,from,to:position});return true;};
 P.putOnDeck=function(uid,where='top',source=null){const f=this.find(uid);if(!f)return;const owner=f.card.originalOwner;this.move(uid,'deck',{kind:'effect-return',source,byOwner:source?.owner});const now=this.find(uid);if(now?.zone==='deck'&&where==='top'){const m=this.remove(uid).card;this.state.players[owner].deck.unshift(m);}};
 P.revealCards=function(owner,cards,title='公开确认卡片'){for(const c of cards)this.log('reveal',title+' · '+CARDS[c.id].name,owner,{uid:c.uid,cardId:c.id});if(cards.length)this.queueChoice(owner,title,cards.map(c=>this.option(c,{viewer:this.find(c.uid)?.owner,reveal:true})),0,0,'early-confirm',{});};
 P.takeControl=function(uid,owner,{until=null,source=null,exchange=false}={}){const f=this.find(uid);if(!f||!fieldMonster(f.zone)||f.owner===owner||this.unaffected(f.card,source))return false;const slot=this.state.players[owner].monsters.indexOf(null);if(slot<0)return false;const before=f.owner,card=this.remove(uid).card;delete card.extraSlot;this.state.players[owner].monsters[slot]=card;if(until!==null)card.controlReturn={owner:before,turn:until};this.log('control',this.name(owner)+'取得「'+CARDS[card.id].name+'」的控制权',owner,{uid,cardId:card.id});this.emit({type:'control',uid,id:card.id,owner,from:before,source});return true;};
 P.equipMonster=function(uid,targetUid,owner,source=null){const f=this.find(uid),target=this.find(targetUid),slot=this.state.players[owner].spells.indexOf(null);if(!f||!target||!fieldMonster(target.zone)||slot<0||this.unaffected(f.card,source))return false;const previous=this.describe(f.card),stats={atk:f.card.faceUp?this.attackValue(f.card):0,def:f.card.faceUp?this.defenseValue(f.card):0};for(const m of [...(f.card.overlays||[])])this.move(m.uid,'grave',{kind:'rule-material'});this.cleanupEquips(uid);const card=this.remove(uid).card;card.generation++;card.mods=[];card.monsterEquip=true;card.faceUp=true;card.equipTarget=targetUid;card.equipStats=stats;this.state.players[owner].spells[slot]=card;this.log('equip','「'+CARDS[card.id].name+'」成为「'+CARDS[target.card.id].name+'」的装备',owner,{uid,cardId:card.id});this.emit({type:'move',uid,id:card.id,owner:f.owner,from:f.zone,to:'spells',kind:'effect-equip',source,byOwner:owner,byEffect:true,previous});this.emit({type:'equip',uid,id:card.id,owner,target:targetUid});return true;};
 wrap('describe',function(card,found){return {...old.describe.call(this,card,found),equipTarget:card.equipTarget,monsterEquip:!!card.monsterEquip,equipStats:card.equipStats,controlReturn:card.controlReturn,earlyFlags:card.earlyFlags};});
 wrap('originalDefense',function(card){const fn=this.fx?.passives?.[card.id]?.originalDefense;return this._advancedReady&&!this.negated(card)&&fn?fn(this,card):old.originalDefense.call(this,card);});
 wrap('beginNextTurn',function(){old.beginNextTurn.call(this);if(this.state.winner===null){this.state.frame={kind:'standby',owner:this.state.active,stage:0,windowOffered:false};}});
 wrap('settleFrame',function(){const f=this.state.frame;
  if(f?.kind==='summon-attempt'){
   if(!f.windowOffered){f.windowOffered=true;this.openWindow(1-f.owner,0);return true;}
   if(this.state.pending||this.state.chain.length||this.state.chainResolving)return false;
   this.state.frame=f.resumeFrame||{kind:'summon',owner:f.owner,uid:f.uid,summonKind:f.summonKind,windowOffered:false};
   for(const v of [f.summonEvent,...(f.summonGroup||[])]){const m=this.find(v.uid)?.card;if(m){delete m.summonPending;if(!f.summonNegated&&fieldMonster(this.find(m.uid)?.zone)){this.state.acceptingSummon=true;try{this.emit({...v,group:f.summonGroup||[]});if(f.flipEvent)this.emit(f.flipEvent);}finally{this.state.acceptingSummon=false;}}}}return true;
  }
  if(f?.kind==='standby'&&f.stage===0){f.stage=1;const p=this.state.players[f.owner];if(p.skipStandby>0)p.skipStandby--;else this.emit({type:'standby',owner:f.owner});return true;}
  if(f?.kind==='standby'&&f.stage===1&&!this.state.pending){f.stage=2;this.state.frame={kind:'main-open',owner:f.owner,windowOffered:false};return true;}return old.settleFrame.call(this);
 });
 wrap('changePhase',function(phase){if(this.state.phase==='battle'&&phase!=='battle')this.emit({type:'battle-end',owner:this.state.active});return old.changePhase.call(this,phase);});
 wrap('endTurn',function(){if(this.state.phase==='battle')this.emit({type:'battle-end',owner:this.state.active});return old.endTurn.call(this);});
 wrap('damage',function(owner,amount,source='战斗'){const a=this.state.frame?.attack,participants=a?[a.uid,a.target].map(uid=>this.find(uid)).filter(Boolean):[];let reflect=false;if(this._advancedReady&&source==='战斗'){
  if(this.hasEarly('Tornado Wall',owner)&&this.hasEarly('Umi'))amount=0;
  for(const f of participants){const r=CARDS[f.card.id].earlyRules||{};if(f.owner===owner&&r.ownBattleNoDamage&&this.state.active===owner&&!this.negated(f.card))amount=0;if(f.owner!==owner&&r.halfBattleDamage&&!this.negated(f.card))amount=Math.floor(amount/2);if(f.owner===owner&&r.reflectBattle&&!this.negated(f.card)&&(this.activeEquip(f.card).some(m=>m.monsterEquip)||a?.relinquishedWasEquipped))reflect=true;}
 }const before=this.state.players[owner].lp;old.damage.call(this,owner,amount,source);const actual=before-this.state.players[owner].lp;if(this._advancedReady&&actual>0){this.emit({type:'damage',owner,amount:actual,source,battle:source==='战斗',attack:a?cp(a):null});if(reflect&&this.state.winner===null)this.damage(1-owner,actual,'效果');}});
 wrap('heal',function(owner,amount){if(this._advancedReady&&this.hasEarly('Bad Reaction to Simochi',1-owner)){this.damage(owner,amount,'效果');return;}old.heal.call(this,owner,amount);if(this._advancedReady&&amount>0)this.emit({type:'heal',owner,amount});});
 P.rawEarly=function(name){const id=D.cardByName(name)?.id;return id?[0,1].flatMap(p=>this.refs(p,['monsters','extraMonster','spells','fieldSpell'])).filter(f=>f.card.id===id&&f.card.faceUp&&!f.card.pendingActivation&&!f.card.effectNegated&&!f.card.spellNegated):[];};
 P.trapsSuppressed=function(){return this.rawEarly('Royal Decree').length>0||this.rawEarly('Jinzo').length>0&&!this.rawEarly('Skill Drain').length;};
 wrap('activeSpell',function(card){if(!old.activeSpell.call(this,card)||card.spellNegatedUntil>=this.state.turn)return false;if(!this._advancedReady)return true;const c=CARDS[card.id];if(c.type==='trap'&&this.trapsSuppressed()&&c.officialName!=='Royal Decree')return false;if((c.type==='spell'||card.monsterEquip)&&!this.trapsSuppressed()&&this.rawEarly('Imperial Order').length)return false;if(card.equipTarget&&!this.trapsSuppressed()&&this.rawEarly("The Emperor's Holiday").length)return false;return true;});
 P.earlyCanUse=function(c,a){const d=CARDS[c.sourceId],f=this.find(c.uid);if(d.implementationStatus==='pending'||d.unplayableFromHand&&a.cardActivation)return false;if(this.isProhibited(c.sourceId,c.uid))return false;
  if(d.flip&&(this.hasEarly('Royal Command')||this.hasEarly('Fiend Skull Dragon')))return false;
  if(d.type==='trap'&&this.hasEarly('Jinzo')&&(a.cardActivation||f?.zone==='spells'))return false;
  if(a.cardActivation&&d.type==='spell'&&this.hasEarly('Anti-Spell Fragrance')&&(f?.zone==='hand'||f?.card.setTurn>=this.state.turn-1))return false;
  if(a.cardActivation&&['spell','trap'].includes(d.type)&&this.state.coldWaveUntil>=this.state.turn)return false;
  if(d.officialName==='Monster Reborn'&&this.hasEarly('Call of Darkness'))return false;
  if(f&&fieldMonster(f.zone)&&f.card.earlyBattleNegated)return false;
  return true;
 };
 P.isProhibited=function(id,uid){return [0,1].some(p=>this.spells(p).some(m=>this.activeSpell(m)&&m.prohibitedId===id&&!(m.prohibitionExempt||[]).includes(uid)));};
 P.canTarget=function(card,source){return !(card.faceUp&&this.race(card)==='龙族'&&this.hasEarly('Lord of D.')&&!this.unaffected(card,source));};
 P.earlyNegatesLink=function(link,probe=false){const f=this.find(link.uid),a=this.fx.get(link.key),type=link.source.effectType;if(a.cannotNegate)return false;
  if(type==='trap'&&f&&['spells','fieldSpell'].includes(f.zone)&&this.trapsSuppressed())return true;
  if(type==='spell'&&f&&['spells','fieldSpell'].includes(f.zone)&&this.rawEarly('Imperial Order').length&&!this.trapsSuppressed())return true;
  if(CARDS[link.sourceId].flip&&(this.hasEarly('Royal Command')||this.hasEarly('Fiend Skull Dragon')))return true;
  const targets=Object.values(link.targetMeta||{}).flatMap(x=>Object.keys(x)).map(uid=>this.find(uid)).filter(f=>f&&fieldMonster(f.zone)&&f.card.faceUp&&!this.negated(f.card));
  for(const t of targets){const d=CARDS[t.card.id],r=d.earlyRules||{};if(type==='spell'&&(r.negateTargetSpell||d.officialName==='Freed the Matchless General'||this.race(t.card)==='战士族'&&this.hasEarly('Frontier Wiseman',t.owner))||type==='trap'&&r.negateTargetTrap){if(f&&!probe)this.destroy(f.card.uid,{id:t.card.id,uid:t.card.uid,owner:t.owner,effectType:'monster'});return true;}}
  return false;
 };
 P.zoneBlocked=function(owner,index){return [0,1].some(p=>this.spells(p).some(m=>this.activeSpell(m)&&(m.blockedZones||[]).some(([o,i])=>o===owner&&i===index)))||(this.state.players[owner].reservedZones||[]).some(r=>r.index===index&&r.until>=this.state.turn);};
 wrap('freeMain',function(owner){return this.state.players[owner].monsters.filter((c,i)=>!c&&!this.zoneBlocked(owner,i)).length;});
 wrap('freeZones',function(owner,card,options={}){return old.freeZones.call(this,owner,card,options).filter(z=>typeof z!=='number'||!this.zoneBlocked(owner,z));});
 wrap('canNormal',function(card,owner=this.state.active){if(!old.canNormal.call(this,card,owner)||this.isProhibited(card.id,card.uid))return false;const r=CARDS[card.id].earlyRules||{};if(r.requiresNoMonstersToNormal&&this.monsters(owner).length)return false;const fee=this.rawEarly('Chain Energy').filter(f=>this.activeSpell(f.card)).length*500;return this.state.players[owner].lp>fee;});
 wrap('tributeCount',function(card){if(CARDS[card.id].earlyRules?.lastHandNoTribute&&this.find(card.uid)?.zone==='hand'&&this.state.players[this.find(card.uid).owner].hand.length===1)return 0;return old.tributeCount.call(this,card);});
 wrap('tributeSets',function(card,noTribute=false,owner=this.state.active){return old.tributeSets.call(this,card,noTribute,owner).filter(set=>set.every(uid=>this.canTribute(this.find(uid)?.card,owner,'normal')));});
 P.summonsLocked=function(owner,setting=false){return !setting&&(this.hasEarly('The Last Warrior from Another Planet')||this.hasEarly('Jam Breeding Machine',owner)||this.state.players[owner].normalSummonLockedTurn===this.state.turn);};
 wrap('normalSummon',function(a){const owner=this.state.active;req(!this.summonsLocked(owner,a.mode==='defense'),'场上的效果禁止召唤怪兽。');old.normalSummon.call(this,a);const m=this.find(a.uid)?.card;if(m&&fieldMonster(this.find(a.uid).zone)){if(a.mode==='defense'&&this.hasEarly('Light of Intervention')){m.faceUp=true;this.emit({type:'summon',owner,uid:m.uid,id:m.id,kind:'normal',from:'hand',materials:[]});}const fees=this.rawEarly('Chain Energy').filter(f=>this.activeSpell(f.card)).length*500;if(fees)this.payLP(owner,fees);}});
 wrap('canSpecial',function(owner,card,options={}){if(!old.canSpecial.call(this,owner,card,options))return false;const r=CARDS[card.id].earlyRules||{},f=this.find(card.uid);if(this.hasEarly('The Last Warrior from Another Planet')||this.hasEarly('Jowgen the Spiritualist')||this.hasEarly('Jam Breeding Machine',owner)&&CARDS[card.id].officialName!=='Slime Token')return false;if(r.noGraveSpecial&&f?.zone==='grave')return false;if(this.isProhibited(card.id,card.uid))return false;const fees=f?.zone==='hand'&&!options.chainEnergyPaid?this.rawEarly('Chain Energy').filter(f=>this.activeSpell(f.card)).length*500:0;return this.state.players[owner].lp>fees;});
 wrap('special',function(owner,uid,options={}){const f=this.find(uid),fees=f?.zone==='hand'?this.rawEarly('Chain Energy').filter(f=>this.activeSpell(f.card)).length*500:0;if(fees){if(!this.canSpecial(owner,f.card,options))return null;this.payLP(owner,fees);}return old.special.call(this,owner,uid,{...options,chainEnergyPaid:!!fees||options.chainEnergyPaid});});
 wrap('setCard',function(a){req(this.state.coldWaveUntil<this.state.turn||!this.state.coldWaveUntil,'寒波期间不能盖放魔法陷阱。');old.setCard.call(this,a);const fees=this.rawEarly('Chain Energy').filter(f=>this.activeSpell(f.card)).length*500;if(fees)this.payLP(this.state.active,fees);});
 wrap('commitPrepared',function(c){return old.commitPrepared.call(this,c);});
 wrap('attribute',function(card){const equip=this.activeEquip(card).find(m=>m.attributeChange);return equip?.attributeChange||old.attribute.call(this,card);});
 wrap('level',function(card){let n=old.level.call(this,card);const f=this.find(card.uid);if(this._advancedReady&&n>0&&f&&(fieldMonster(f.zone)&&card.faceUp||f.zone==='hand')&&this.attribute(card)==='水'&&this.hasEarly('A Legendary Ocean'))n=Math.max(1,n-this.rawEarly('A Legendary Ocean').length);return n;});
 const originalAtk=P.originalAttack,originalDef=P.originalDefense;
 P.originalAttack=function(card){if(card.hourglassUntil&&!this.negated(card))return (CARDS[card.id].atk||0)*(this.state.turn<=card.hourglassUntil?.5:2);if(card.swappedOriginalUntil>=this.state.turn)return CARDS[card.id].def||0;return originalAtk.call(this,card);};
 P.originalDefense=function(card){if(card.hourglassUntil&&!this.negated(card))return (CARDS[card.id].def||0)*(this.state.turn<=card.hourglassUntil?.5:2);if(card.swappedOriginalUntil>=this.state.turn)return CARDS[card.id].atk||0;return originalDef.call(this,card);};
 wrap('stat',function(card,stat,battle=null){let value=old.stat.call(this,card,stat,battle);if(!card||!this._advancedReady)return value;const f=this.find(card.uid);if(f&&fieldMonster(f.zone)&&card.faceUp&&battle){for(const s of this.passiveSources()){const fn=this.fx.passives[s.card.id]?.battleStat;if(fn)value+=fn(this,s,card,stat,battle)||0;}if(card.earlyBattleBoost?.serial===battle.serial)value+=card.earlyBattleBoost[stat]||0;}
  if(stat==='atk'&&card.mirrorWallSources?.some(uid=>{const s=this.find(uid);return s&&this.activeSpell(s.card);}))value=Math.floor(value/2);
  return Math.max(0,Math.floor(value));
 });
 P.canDirect=function(card,owner=this.state.active){const r=CARDS[card.id].earlyRules||{};if(this.negated(card))return card.directAttackTurn===this.state.turn;if(r.direct)return true;if(r.toon)return !this.monsters(1-owner).some(m=>m.faceUp&&CARDS[m.id].toon);if(r.conditionalDirect)return this.monsters(1-owner).filter(m=>m.faceUp).every(m=>['地','水','炎'].includes(this.attribute(m)));return card.directAttackTurn===this.state.turn||this.monsters(1-owner).every(m=>m.faceUp&&CARDS[m.id].earlyRules?.umiNoAttackTarget&&this.hasEarly('Umi'));};
 wrap('attackAllowance',function(card){const r=CARDS[card.id].earlyRules||{};return this.negated(card)?old.attackAllowance.call(this,card):Math.max(old.attackAllowance.call(this,card),r.attackAll?Math.max(1,this.monsters(1-this.find(card.uid).owner).length):r.attacks||1);});
 wrap('attackBlocked',function(owner){return old.attackBlocked.call(this,owner)||this.hasEarly("Nightmare's Steelcage");});
 wrap('canAttack',function(card,owner=this.state.active,target=null){const r=CARDS[card.id].earlyRules||{},oldPosition=card.position;if(r.defenseAttack&&!this.negated(card)&&card.faceUp)card.position='attack';let valid;try{valid=old.canAttack.call(this,card,owner,target);}finally{card.position=oldPosition;}if(!valid)return false;const off=this.negated(card),t=target?this.find(target)?.card:null,others=this.monsters(1-owner).filter(m=>m.faceUp&&!this.negated(m));
  if(card.attackLockedUntil>=this.state.turn||!off&&r.noDirect&&!target||!off&&r.summonSickness&&card.summonTurn===this.state.turn)return false;
  if(!off&&r.requiresOtherDragon&&!this.monsters(owner).some(m=>m.uid!==card.uid&&m.faceUp&&this.race(m)==='龙族'))return false;
  if(!off&&r.attackAll&&(card.earlyAttackedTargets||[]).includes(target||'direct'))return false;
  if(this.hasEarly('Gravity Bind')&&this.level(card)>=4||this.hasEarly('Messenger of Peace')&&this.attackValue(card)>=1500||this.hasEarly('Insect Barrier',1-owner)&&this.race(card)==='昆虫族')return false;
  if(this.hasEarly('Vengeful Bog Spirit')&&card.summonTurn===this.state.turn)return false;
  if(this.hasEarly('The Dark Door')&&this.monsters(owner).some(m=>m.uid!==card.uid&&m.attacksMade>0))return false;
  if(allBound(this,card))return false;
  if(this.activeEquip(card).some(m=>CARDS[m.id].equipRules?.noAttack)||[0,1].some(p=>this.field(p).some(m=>m.faceUp&&m.attackLockTarget===card.uid&&this.hasActiveCard(m))))return false;
  if(this.spells(1-owner).some(m=>this.activeSpell(m)&&m.declaredRace===this.race(card)&&CARDS[m.id].officialName==='Array of Revealing Light')&&card.summonTurn===this.state.turn)return false;
  if(t){const tr=CARDS[t.id].earlyRules||{};if(t.faceUp&&!this.negated(t)){if(tr.umiNoAttackTarget&&this.hasEarly('Umi'))return false;if(tr.untargetableWithOthers&&this.monsters(1-owner).length>1)return false;}if(this.race(t)==='战士族'&&others.some(m=>CARDS[m.id].earlyRules?.protectWarriors&&m.uid!==t.uid))return false;if(!off&&r.toon&&others.some(m=>CARDS[m.id].toon)&&!CARDS[t.id].toon)return false;const magnets=others.filter(m=>this.activeEquip(m).some(eq=>CARDS[eq.id].equipRules?.magnet));if(magnets.length&&!magnets.includes(t))return false;if(!t.faceUp&&this.state.feintPlanTurn===this.state.turn)return false;}
  const fees=this.attackCost(card,owner);if(this.state.players[owner].lp<=fees)return false;if(this.hasEarly("Gravekeeper's Servant",1-owner)&&(!this.state.players[owner].deck.length||this.hasEarly('Banisher of the Light')))return false;
  return true;
 });
 function allBound(e,card){return e.hasEarly('Thousand-Eyes Restrict')&&!e.monsters(0).concat(e.monsters(1)).filter(m=>m.faceUp&&!e.negated(m)&&CARDS[m.id].earlyRules?.bindOtherMonsters).every(m=>m.uid===card.uid);}
 P.hasActiveCard=function(card){const f=this.find(card.uid);return card.faceUp&&(fieldMonster(f?.zone)?!this.negated(card):this.activeSpell(card));};
 P.attackCost=function(card,owner){return this.rawEarly('Toll').filter(f=>this.activeSpell(f.card)).length*500+(!this.negated(card)?CARDS[card.id].earlyRules?.attackLP||0:0);};
 wrap('declareAttack',function(a){const f=this.find(a.uid),target=typeof a.target==='string'?a.target:a.target?.uid||null;if(f&&this.canDirect(f.card,f.owner)&&!target)f.card.directAttackTurn=this.state.turn;req(f&&this.canAttack(f.card,f.owner,target),'这个攻击不满足持续效果或代价条件。');const fee=this.attackCost(f.card,f.owner);if(fee)this.payLP(f.owner,fee);const n=this.rawEarly("Gravekeeper's Servant").filter(x=>x.owner!==f.owner&&this.activeSpell(x.card)).length;for(let i=0;i<n;i++){const top=this.state.players[f.owner].deck[0];req(top,'卡组没有足够卡片支付攻击代价。');this.move(top.uid,'grave',{kind:'cost-send',byOwner:f.owner});}if(CARDS[f.card.id].earlyRules?.defenseAttack&&!this.negated(f.card)){f.card.attackingFromDefense=true;f.card.position='attack';}old.declareAttack.call(this,a);(f.card.earlyAttackedTargets||=[]).push(target||'direct');});
 wrap('finishBattle',function(a){const f=this.find(a.uid),d=this.find(a.target);if([f,d].some(x=>x&&CARDS[x.card.id].earlyRules?.reflectBattle&&this.activeEquip(x.card).some(m=>m.monsterEquip)))a.relinquishedWasEquipped=true;const victimSide=d?.owner;const atk=f?this.attackValue(f.card,a):0,def=d?this.defenseValue(d.card,a):0,defending=d?.card.position==='defense';const pierce=f&&!this.negated(f.card)&&(CARDS[f.card.id].earlyRules?.piercing||this.activeEquip(f.card).some(m=>CARDS[m.id].equipRules?.piercing)||this.hasEarly("Dragon's Rage",f.owner)&&this.race(f.card)==='龙族');old.finishBattle.call(this,a);if(pierce&&defending&&atk>def&&this.state.winner===null)this.damage(victimSide,atk-def,'战斗');if(f?.card.attackingFromDefense&&fieldMonster(this.find(f.card.uid)?.zone)){f.card.position='defense';delete f.card.attackingFromDefense;}});
 wrap('actionsFor',function(uid,owner=this.state.active){const actions=old.actionsFor.call(this,uid,owner),f=this.find(uid);if(!f)return actions;const result=actions.filter(a=>!(a.type==='summon'&&this.summonsLocked(owner,a.mode==='defense'))&&!(a.type==='stance'&&this.positionLocked(f.card)));if(this.state.phase==='battle'&&fieldMonster(f.zone)&&this.canDirect(f.card,owner)&&this.canAttack(f.card,owner,null)&&!result.some(a=>a.type==='attack'))result.push({type:'attack',uid,label:'选择攻击目标 / 直接攻击',icon:'swords'});return result;});
 P.positionLocked=function(card){const f=this.find(card.uid);return card.positionLockedUntil>=this.state.turn||this.state.players[f?.owner??0].positionLockedTurn===this.state.turn||allBound(this,card)||this.hasEarly('Dragon Capture Jar')&&card.faceUp&&this.race(card)==='龙族'||[0,1].some(p=>this.field(p).some(m=>m.attackLockTarget===card.uid&&this.hasActiveCard(m)));};
 wrap('changeStance',function(a){const f=this.find(a.uid);req(f&&!this.positionLocked(f.card),'持续效果禁止这只怪兽变更表示。');return old.changeStance.call(this,a);});
 wrap('unaffected',function(card,source){if(old.unaffected.call(this,card,source))return true;return !!source&&card.faceUp&&!this.negated(card)&&CARDS[card.id].earlyRules?.umiSpellImmunity&&['spell','pendulum-spell'].includes(source.effectType||CARDS[source.id]?.type)&&this.hasEarly('Umi');});
 wrap('destroy',function(uid,source=null,battle=false,extra={}){const f=this.find(uid);if(!f)return false;if(!battle&&f.card.reflectCounters>0){f.card.reflectCounters--;return false;}if(!battle&&CARDS[f.card.id].equipIndestructible&&f.card.equipTarget&&this.activeSpell(f.card))return false;return old.destroy.call(this,uid,source,battle,extra);});
 wrap('move',function(uid,destination,options={}){const f=this.find(uid);if(!f)return old.move.call(this,uid,destination,options);const restore=f.card.controlOwner!==undefined&&f.card.equipTarget?{owner:f.card.controlOwner,uid:f.card.equipTarget}:null;let dest=destination;
  if(dest==='grave'&&!options.ignoreReplacement&&this._advancedReady&&this.hasEarly('Banisher of the Light'))dest='banished';
  if(dest==='banished'&&f.zone==='grave'&&this._advancedReady&&this.hasEarly('Kycoo the Ghost Destroyer',1-(options.byOwner??this.state.active))){if((options.kind||'').startsWith('cost'))throw new root.DuelRuleError('空相卡片的效果禁止从墓地除外作为代价。');return {card:f.card,from:f.zone,to:f.zone,owner:f.owner,destroyed:false};}
  const result=old.move.call(this,uid,dest,options);if(restore&&fieldMonster(this.find(restore.uid)?.zone)&&this.find(restore.uid).owner!==restore.owner){if(!this.takeControl(restore.uid,restore.owner))this.move(restore.uid,'grave',{kind:'rule-control-return'});}return result;
 });
 wrap('emit',function(v){
  if(v.type==='flip'&&this.state.frame?.kind==='summon-attempt'&&this.state.frame.uid===v.uid){const m=this.find(v.uid)?.card;if(m){delete m.summonPending;v.previous.wasNegated=this.negated(m);m.summonPending=true;}this.state.frame.flipEvent=cp(v);return;}
  if(this._advancedReady&&v.type==='summon'&&!this.state.acceptingSummon&&!this.state.resolvingLink&&!this.state.chainResolving&&(['normal','flip','synchro','xyz','link','pendulum','toon'].includes(v.kind)||v.kind.startsWith('early-special:'))){
   const m=this.find(v.uid)?.card;if(m){m.summonPending=true;if(this.state.frame?.kind==='summon-attempt'&&v.kind==='pendulum')(this.state.frame.summonGroup||=[]).push(cp(v));else this.state.frame={kind:'summon-attempt',owner:v.owner,uid:v.uid,summonKind:v.kind,summonEvent:cp(v),resumeFrame:this.state.frame?cp(this.state.frame):null,windowOffered:false};return;}
  }
  if(this._advancedReady&&['summon','damage','move','added'].includes(v.type)){this.state.earlyEvent=cp(v);if(v.type==='summon')this.state.earlyWindowSummon=cp(v);if(['summon','damage'].includes(v.type))this.state.earlyNeedsWindow=!!this.state.chainResolving;}
  return old.emit.call(this,v);
 });
 P.negateSummon=function(source){const f=this.state.frame;if(f?.kind!=='summon-attempt'||f.summonNegated)return false;f.summonNegated=true;for(const v of [f.summonEvent,...(f.summonGroup||[])]){const card=this.find(v.uid)?.card;if(card){card.properlySummoned=false;delete card.summonPending;this.move(card.uid,'grave',{kind:'rule-negated-summon',source,byOwner:source.owner,negatedSummon:true,negatedActivation:true,from:'summon-pending'});}}this.log('negate','这次召唤被无效',source.owner);return true;};
 wrap('windowContext',function(){return {...old.windowContext.call(this),earlyEvent:this.state.earlyEvent?cp(this.state.earlyEvent):null,earlySummon:this.state.earlyWindowSummon?cp(this.state.earlyWindowSummon):null};});
 wrap('act',function(a){const previous=this.snapshot();if(!this.state.pending){this.state.earlyWindowSummon=null;this.state.earlyEvent=null;}try{const result=old.act.call(this,a);if(!result.ok){this.state=previous.state;this.randomState=previous.randomState;}return result;}catch(error){this.state=previous.state;this.randomState=previous.randomState;throw error;}});
 wrap('draw',function(owner,n=1,silent=false){if(this._advancedReady&&this.state.inDrawPhase&&this.state.players[owner].discardBeforeDraw){this.state.players[owner].discardBeforeDraw=false;for(const m of [...this.state.players[owner].hand])this.move(m.uid,'grave',{kind:'effect-discard',byOwner:1-owner});}return old.draw.call(this,owner,n,silent);});
 P.fusionSubstituteValid=function(extra,materials,specs){if(CARDS[extra.id].fusionExact)return false;const walk=(i,used,sub)=>{if(i===specs.length)return true;for(let j=0;j<materials.length;j++)if(!used.includes(j)){const m=materials[j],exact=this.materialMatches(m,specs[i]);if(exact&&walk(i+1,[...used,j],sub))return true;if(!sub&&!exact&&(specs[i].id||specs[i].officialName)&&CARDS[m.id].fusionSubstitute&&!this.negated(m)&&walk(i+1,[...used,j],true))return true;}return false;};return walk(0,[],false);};
 if(typeof module!=='undefined')module.exports=P;
})(globalThis);
