(function(root){
 'use strict';const X=root.DuelChronicle,{D,E,H,C,I,is,A,Q,passive,mark,allM,allS,allF,monster,ownM,foeM,hand,deck,grave,first,args,self,src,active,field,has,extend,g,choose,target,moved,destroy,pay,once,onEntry,onFlip,onEnd,onStandby,onDamage,onBattleWin,revive,search,specialChoice,series,guard,defer,card,def,arch,names,gy,fromField,destroyed,discarded,noHand,effect,cast,watch,entrySearch,entryReturn,sent,sentRecruit,sentSearch,specialSelf,summonCost,aura,ownAura,protect,quickNegate,lock,locked,negateMonster,blackwing,koaki,morph,naturia,infernity,saber,ice,watt,scrap,karakuri,laval,gusto,gem,gishki,vylon,nordic,battleGY,windup,inzektor,photon,evoltile,evolsaur,ninja,constellar,lswarm,aqua,faceOnce}=X,{CARDS}=D;
 const hieratic=arch('Hieratic'),madolche=arch('Madolche'),spellbook=m=>series(m,'Spellbook')&&def(m)?.type==='spell',prophecy=arch('Prophecy'),chronomaly=arch('Chronomaly'),heroic=arch('Heroic'),gear=arch('Geargia'),mermail=arch('Mermail'),atlantean=arch('Atlantean'),heraldic=arch('Heraldic Beast'),firefist=arch('Fire Fist'),formation=arch('Fire Formation'),hazy=arch('Hazy Flame'),fireking=arch('Fire King');
 const millChoice=(e,c,pred,n=1)=>choose(e,c,'选择卡组卡片送墓',deck(e,c.owner,pred),n,n,'early-move',{to:'grave',kind:'effect-send',shuffle:true,role:'send-deck'}),handSpecialEffect=(name,n,pred,after)=>effect(name,null,(e,c)=>{const m=revive(e,c,c.uid);if(m)after?.(e,c,m);},{zones:['hand'],oncePerTurn:false,inputs:(e,c)=>[g(e,c,'cost','选择其他手牌丢弃',hand(e,c.owner,m=>m.uid!==c.uid&&pred(e,m)),n,n,'cost')],cost:(e,c)=>H.discard(e,c,args(c,'cost')),summons:true});
 // WATER discards are costs. Atlanteans and Gunde listen to the actual move,
 // retaining the activating monster's identity and attribute in the event.
 handSpecialEffect('Mermail Abyssmegalo',2,(e,m)=>e.hasAttribute(m,'水'),(e,c)=>search(e,c,deck(e,c.owner,m=>!monster(m)&&series(m,'Abyss-'))));effect('Mermail Abyssmegalo',null,(e,c)=>{if(self(e,c))self(e,c).bonusAttacks=1;},{mode:'era-second',inputs:(e,c)=>[g(e,c,'cost','选择其他攻击表示水属性解放',ownM(e,c).filter(m=>m.uid!==c.uid&&m.position==='attack'&&e.hasAttribute(m,'水')),1,1,'cost')],cost:(e,c)=>X.tribute(e,c,args(c,'cost'))});
 handSpecialEffect('Mermail Abyssleed',3,(e,m)=>e.hasAttribute(m,'水'),(e,c)=>search(e,c,grave(e,c.owner,m=>!monster(m)&&series(m,'Abyss-'))));effect('Mermail Abyssleed',null,(e,c)=>X.randomDiscard(e,1-c.owner,1,c.source),{mode:'era-hand',once:H.once('abyssleed'),inputs:(e,c)=>[g(e,c,'cost','选择其他攻击表示水精鳞解放',ownM(e,c).filter(m=>m.uid!==c.uid&&m.position==='attack'&&mermail(m)),1,1,'cost')],cost:(e,c)=>X.tribute(e,c,args(c,'cost'))});
 for(const n of ['Mermail Abysspike','Mermail Abyssturge'])onEntry(n,'era-search',{once:H.once('mermail-search'),inputs:(e,c)=>[g(e,c,'cost','选择水属性手牌丢弃',hand(e,c.owner,m=>e.hasAttribute(m,'水')),1,1,'cost')],cost:(e,c)=>H.discard(e,c,args(c,'cost')),resolve:(e,c)=>n==='Mermail Abysspike'?search(e,c,deck(e,c.owner,m=>e.hasAttribute(m,'水')&&e.level(m)===3)):search(e,c,grave(e,c.owner,m=>e.hasAttribute(m,'水')&&e.level(m)<=3))},['normal','special']);
 sentRecruit('Mermail Abysslinde',(e,m)=>mermail(m)&&m.id!==I('Mermail Abysslinde'),destroyed,{once:H.once('linde')});sent('Mermail Abyssgunde',(e,c)=>revive(e,c,first(c)),discarded,{once:H.once('gunde'),inputs:target('选择水精鳞复活',(e,c)=>grave(e,c.owner,m=>mermail(m)&&m.id!==c.sourceId),'special')});sent('Mermail Abysshilde',(e,c)=>specialChoice(e,c,hand(e,c.owner,m=>mermail(m)&&m.id!==c.sourceId)),(e,v)=>v.to==='grave',{once:H.once('hilde')});aura('Mermail Abysslung',(e,m,s)=>e.find(m.uid)?.owner===s.owner&&e.hasAttribute(m,'水'),300);
 onBattleWin('Mermail Abyssnose',{once:H.once('nose'),inputs:(e,c)=>[g(e,c,'cost','选择水属性手牌丢弃',hand(e,c.owner,m=>e.hasAttribute(m,'水')),1,1,'cost')],cost:(e,c)=>H.discard(e,c,args(c,'cost')),resolve:(e,c)=>specialChoice(e,c,deck(e,c.owner,mermail),{position:'defense',shuffle:true})});watch('Mermail Abyssdine','era-special','added',(e,v,f)=>v.owner===f.owner&&!v.normalDraw&&v.uids.includes(f.card.uid)&&e.monsters(f.owner).some(mermail),{once:H.once('dine'),resolve:(e,c)=>revive(e,c,c.uid)},{zones:['hand']});onEntry('Mermail Abyssdine','era-revive',{once:H.once('dine'),inputs:target('选择低等级水精鳞',(e,c)=>grave(e,c.owner,m=>mermail(m)&&e.level(m)<=3),'special'),resolve:(e,c)=>revive(e,c,first(c))},['special']);
 const waterCost=(e,v)=>v.to==='grave'&&(/^cost-/.test(v.kind||'')||v.kind==='detach'&&v.asCost)&&v.source?.effectType==='monster'&&CARDS[v.source.id]?.attribute==='水';
 sent('Atlantean Marksman',(e,c)=>destroy(e,c,args(c)),waterCost,{inputs:target('选择破坏的对方盖卡',(e,c)=>e.field(1-c.owner).filter(m=>!m.faceUp)),mandatory:true});onDamage('Atlantean Marksman',{resolve:(e,c)=>specialChoice(e,c,deck(e,c.owner,m=>atlantean(m)&&e.race(m)==='海龙族'&&e.level(m)<=4&&m.id!==c.sourceId),{shuffle:true})});sent('Atlantean Heavy Infantry',(e,c)=>destroy(e,c,args(c)),waterCost,{inputs:target('选择破坏的对方表侧卡',(e,c)=>e.field(1-c.owner).filter(m=>m.faceUp)),mandatory:true});effect('Atlantean Heavy Infantry',null,(e,c)=>{e.state.normalUsed=false;lock(e,c.owner,'normalRace','海龙族');lock(e,c.owner,'maxNormalLevel',4);},{condition:e=>e.state.normalUsed});sentSearch('Atlantean Dragoons',(e,m)=>e.race(m)==='海龙族'&&m.id!==I('Atlantean Dragoons'),waterCost,{mandatory:true});
 summonCost('Poseidra, the Atlantean Dragon',(e,c)=>ownM(e,c).filter(m=>e.hasAttribute(m,'水')&&e.level(m)<=3),3,{zones:['hand','grave']});onEntry('Poseidra, the Atlantean Dragon','era-bounce',{resolve:(e,c)=>{const list=allS(e),n=list.length;moved(e,c,list.map(m=>m.uid),'hand','effect-return');if(n>=3)for(const m of foeM(e,c))e.modify(m.uid,'atk','add',-n*300,null,c.source);}},['year-special:'+I('Poseidra, the Atlantean Dragon')]);
 const hieraticRecruit=(e,c,onlyHieratic=false)=>choose(e,c,'选择通常龙族登场',H.cards(e,c.owner,['hand','deck','grave'],m=>e.race(m)==='龙族'&&e.isNormalMonster(m)&&(!onlyHieratic||hieratic(m))),1,1,'era-hieratic',{zero:!onlyHieratic,role:'special'});E.op('era-hieratic',(e,t)=>{const m=revive(e,{owner:t.owner,source:t.context.source},t.picks[0]);if(m&&t.context.zero)for(const k of ['atk','def'])e.modify(m.uid,k,'set',0,null,t.context.source);e.shuffle(e.state.players[t.owner].deck);});
 for(const n of ['Hieratic Dragon of Su','Hieratic Dragon of Eset','Hieratic Dragon of Nebthet','Hieratic Dragon of Tefnuit','Hieratic Dragon of Gebeb'])sent(n,(e,c)=>hieraticRecruit(e,c,n==='Hieratic Dragon of Gebeb'),(e,v)=>/tribute/.test(v.kind),{mandatory:true});
 for(const [n,pool] of [['Hieratic Dragon of Su',(e,c)=>e.spells(1-c.owner)],['Hieratic Dragon of Nebthet',foeM]]){summonCost(n,(e,c)=>ownM(e,c).filter(hieratic));effect(n,pool,(e,c)=>destroy(e,c,args(c)),{inputs:(e,c)=>[g(e,c,'cost','选择其他手牌或场上圣刻解放',H.cards(e,c.owner,['hand','monsters','extraMonster'],m=>hieratic(m)&&m.uid!==c.uid),1,1,'cost'),g(e,c,'target','选择破坏对象',pool(e,c))],cost:(e,c)=>moved(e,c,args(c,'cost'),'grave','cost-tribute')});}
 C('Hieratic Dragon of Eset').tributeCount=0;onEntry('Hieratic Dragon of Eset','era-reduced',{resolve:(e,c)=>{if(!c.event.materials.length)e.modify(c.uid,'atk','set',1000,null,c.source);}},['normal']);effect('Hieratic Dragon of Eset',e=>allM(e).filter(m=>m.faceUp&&e.race(m)==='龙族'&&e.isNormalMonster(m)),(e,c)=>{const m=card(e,first(c));if(m)for(const q of allM(e).filter(q=>q.faceUp&&hieratic(q)))q.levelOverride={value:e.level(m),until:e.state.turn};},{role:'own-boost'});
 specialSelf('Hieratic Dragon of Tefnuit',(e,c)=>!ownM(e,c).length&&foeM(e,c).length>0);onEntry('Hieratic Dragon of Tefnuit','era-noattack',{resolve:(e,c)=>{if(self(e,c))self(e,c).eraNoAttackUntil=e.state.turn;}},['year-special:'+I('Hieratic Dragon of Tefnuit')]);onBattleWin('Hieratic Dragon of Gebeb',{resolve:(e,c)=>hieraticRecruit(e,c)});watch('Hieratic Dragon of Nuit','era-target','era-activation',(e,v,f)=>e.state.chain.some(l=>l.uid===v.uid&&Object.values(l.targetMeta||{}).some(g=>g[f.card.uid])),{once:once(),resolve:(e,c)=>hieraticRecruit(e,c)},{mandatory:true});
 specialSelf('Hieratic Dragon of Asar',()=>true);const asar=E.get(I('Hieratic Dragon of Asar')+'::gx-special');asar.inputs=(e,c)=>[g(e,c,'light','选择光属性龙族除外',grave(e,c.owner,m=>e.race(m)==='龙族'&&e.hasAttribute(m,'光')),1,1,'cost'),g(e,c,'normal','选择通常龙族除外',grave(e,c.owner,m=>e.race(m)==='龙族'&&e.isNormalMonster(m)&&!args(c,'light').includes(m.uid)),1,1,'cost')];asar.cost=(e,c)=>moved(e,c,[...args(c,'light'),...args(c,'normal')],'banished','cost-banish');protect('Hieratic Dragon of Asar',(e,m)=>{const p=e.find(m.uid).owner,q=e.monsters(p).find(q=>q.uid!==m.uid&&q.faceUp&&hieratic(q));if(!q)return false;X.tribute(e,{owner:p,source:src(e,m)},[q.uid]);return true;});summonCost('Hieratic Dragon of Sutekh',(e,c)=>grave(e,c.owner,m=>e.race(m)==='龙族'&&e.isNormalMonster(m)),3,{only:true,banish:true});effect('Hieratic Dragon of Sutekh',allF,(e,c)=>destroy(e,c,args(c)),{banish:(e,c)=>grave(e,c.owner,m=>e.race(m)==='龙族')});
 for(const n of ['Inzektor Ladybug','Inzektor Earwig','Inzektor Firefly','Inzektor Hopper'])effect(n,(e,c)=>H.cards(e,c.owner,['hand','grave'],m=>inzektor(m)&&monster(m)),(e,c)=>e.equipMonster(first(c),c.uid,c.owner,c.source),{mode:'era-equip',role:'own-boost'});for(const n of ['Inzektor Ladybug','Inzektor Earwig','Inzektor Firefly'])aura(n,(e,m,s)=>s.card.equipTarget===m.uid,(e,m,s,k)=>def(s.card)[k]||0,['atk','def']);
 effect('Inzektor Ladybug',(e,c)=>ownM(e,c).filter(m=>m.faceUp),(e,c)=>{const m=card(e,first(c));if(m)m.levelOverride={value:e.level(m)+2};},{zones:['spells'],cost:(e,c)=>H.sendCost(e,c,[c.uid]),oncePerTurn:false,role:'own-boost'});sent('Inzektor Earwig',(e,c)=>{const uid=c.event.previous.equipTarget;if(card(e,uid))e.modify(uid,'atk','add',1000,e.state.turn,c.source);},(e,v)=>v.from==='spells'&&v.to==='grave'&&!!v.previous.equipTarget);
 effect('Inzektor Giga-Cricket',(e,c)=>ownM(e,c).filter(m=>m.faceUp&&inzektor(m)),(e,c)=>e.equipMonster(c.uid,first(c),c.owner,c.source),{zones:['grave'],once:H.once('cricket'),banish:(e,c)=>grave(e,c.owner,m=>e.race(m)==='昆虫族'&&m.uid!==c.uid),role:'own-boost'});aura('Inzektor Giga-Cricket',(e,m,s)=>s.card.equipTarget===m.uid,(e,m)=>2000-e.originalAttack(m));passive('Inzektor Giga-Cricket',{piercing:(e,s,m)=>s.card.equipTarget===m.uid});effect('Inzektor Hopper',null,(e,c)=>{const m=card(e,c.eraHost);if(m){m.directUntil=e.state.turn;e.state.players[c.owner].attackOnly={uid:m.uid,turn:e.state.turn};}},{zones:['spells'],cost:(e,c)=>{c.eraHost=card(e,c.uid).equipTarget;H.sendCost(e,c,[c.uid]);},oncePerTurn:false});
 // Madolche returns resolve from the GY and can be interrupted there.
 for(const n of ['Madolche Magileine','Madolche Mewfeuille','Madolche Butlerusk','Madolche Baaple','Madolche Puddingcess','Madolche Chouxvalier','Madolche Marmalmaide','Madolche Messengelato','Madolche Cruffssant'])sent(n,(e,c)=>{if(e.find(c.uid)?.zone==='grave'){moved(e,c,[c.uid],'deck','effect-return');e.shuffle(e.state.players[c.owner].deck);}},(e,v)=>destroyed(e,v)&&v.byOwner!==v.owner,{mandatory:true});
 entrySearch('Madolche Magileine',(e,m)=>madolche(m),['normal','flip']);onEntry('Madolche Mewfeuille','era-special',{resolve:(e,c)=>specialChoice(e,c,hand(e,c.owner,madolche))},['normal']);entrySearch('Madolche Butlerusk',(e,m)=>def(m).spellKind==='field',['normal'],{condition:(e,c)=>ownM(e,c).some(m=>m.uid!==c.uid&&m.faceUp&&madolche(m))});onFlip('Madolche Marmalmaide',{resolve:(e,c)=>search(e,c,grave(e,c.owner,m=>madolche(m)&&!monster(m)))});entrySearch('Madolche Messengelato',(e,m)=>madolche(m)&&!monster(m),['special'],{condition:(e,c)=>ownM(e,c).some(m=>m.faceUp&&madolche(m)&&e.race(m)==='兽族')});
 effect('Madolche Baaple',null,(e,c)=>{for(const uid of [...args(c,'own'),...args(c)]){const m=card(e,uid);if(m){e.setPosition(uid,'defense',c.source);m.positionLockedUntil=e.state.turn+1;}}},{inputs:(e,c)=>[g(e,c,'own','选择自己攻击表示甜点',ownM(e,c).filter(m=>madolche(m)&&m.position==='attack'),1,1,'own-boost'),g(e,c,'target','选择对方攻击表示怪兽',foeM(e,c).filter(m=>m.faceUp&&m.position==='attack'))]});ownAura('Madolche Puddingcess',(e,m,s)=>!grave(e,s.owner,monster).length?800:0,['atk','def']);watch('Madolche Puddingcess','era-destroy','damage-end',(e,v,f)=>[v.attack.uid,v.attack.target].includes(f.card.uid),{inputs:target('选择对方卡片',(e,c)=>e.field(1-c.owner)),resolve:(e,c)=>destroy(e,c,args(c))});effect('Madolche Cruffssant',(e,c)=>e.field(c.owner).filter(m=>m.faceUp&&madolche(m)&&m.uid!==c.uid),(e,c)=>{moved(e,c,args(c),'hand','effect-return');const m=self(e,c);if(m){m.levelOverride={value:e.level(m)+1};e.modify(m.uid,'atk','add',300,null,c.source);}},{role:'own-boost'});
 E.on('era-activation',(e,v)=>{if(spellbook({id:v.id}))lock(e,v.owner,'spellbookActivated');});entrySearch('Spellbook Magician of Prophecy',(e,m)=>spellbook(m),['normal','flip']);effect('Strength of Prophecy',e=>allM(e).filter(m=>m.faceUp&&e.race(m)==='魔法师族'),(e,c)=>{const m=card(e,first(c));if(m){m.levelOverride={value:e.level(m)+1};e.modify(m.uid,'atk','add',500,null,c.source);}},{inputs:(e,c)=>[g(e,c,'cost','选择魔导书返回卡组',grave(e,c.owner,spellbook),1,1,'cost'),g(e,c,'target','选择魔法师族',allM(e).filter(m=>m.faceUp&&e.race(m)==='魔法师族'),1,1,'own-boost')],cost:(e,c)=>{moved(e,c,args(c,'cost'),'deck','cost-return');e.shuffle(e.state.players[c.owner].deck);}});
 effect('Amores of Prophecy',null,(e,c)=>{e.revealCards(1-c.owner,[hand(e,c.owner,spellbook)[0]],'展示魔导书');specialChoice(e,c,hand(e,c.owner,m=>e.race(m)==='魔法师族'&&e.level(m)<=4));},{condition:(e,c)=>hand(e,c.owner,spellbook).length>0,summons:true});effect('Charioteer of Prophecy',(e,c)=>grave(e,c.owner,m=>e.race(m)==='魔法师族'),(e,c)=>moved(e,c,args(c),'hand','effect-return'),{inputs:(e,c)=>[g(e,c,'cost','选择魔导书丢弃',hand(e,c.owner,spellbook),1,1,'cost'),g(e,c,'target','选择回收的魔法师',grave(e,c.owner,m=>e.race(m)==='魔法师族'),1,1,'search')],cost:(e,c)=>H.discard(e,c,args(c,'cost'))});
 specialSelf('High Priestess of Prophecy',(e,c)=>hand(e,c.owner,spellbook).length>=3);E.get(I('High Priestess of Prophecy')+'::gx-special').cost=(e,c)=>e.revealCards(1-c.owner,hand(e,c.owner,spellbook).slice(0,3),'展示三张魔导书');effect('High Priestess of Prophecy',allF,(e,c)=>destroy(e,c,args(c)),{banish:(e,c)=>H.cards(e,c.owner,['hand','grave'],spellbook)});effect('Temperance of Prophecy',null,(e,c)=>{specialChoice(e,c,deck(e,c.owner,m=>e.race(m)==='魔法师族'&&e.level(m)>=5&&['光','暗'].includes(e.attribute(m))),{shuffle:true});lock(e,c.owner,'maxSpecialLevel',4);},{condition:(e,c)=>locked(e,c.owner,'spellbookActivated'),cost:(e,c)=>X.tribute(e,c,[c.uid]),summons:true});
 onEnd('Justice of Prophecy',{condition:(e,c)=>locked(e,c.owner,'spellbookActivated'),once:H.once('justice'),cost:(e,c)=>moved(e,c,[c.uid],'banished','cost-banish'),resolve:(e,c)=>{search(e,c,deck(e,c.owner,m=>e.race(m)==='魔法师族'&&e.level(m)>=5&&['光','暗'].includes(e.attribute(m))));search(e,c,deck(e,c.owner,spellbook));}});sentSearch('Stoic of Prophecy',(e,m)=>prophecy(m)&&e.level(m)===3,(e,v)=>v.to==='grave');watch('Hermit of Prophecy','era-grow','era-activation',(e,v)=>spellbook({id:v.id}),{resolve:(e,c)=>{const m=self(e,c);if(m){m.levelOverride={value:e.level(m)+2};e.modify(m.uid,'atk','add',300,null,c.source);}}},{mandatory:true});
 onEntry('Reaper of Prophecy','era-spellbooks',{once:H.once('reaper'),resolve:(e,c)=>{const n=new Set(grave(e,c.owner,spellbook).map(m=>m.id)).size;if(n>=3)e.modify(c.uid,'atk','add',600,null,c.source);if(n>=4)search(e,c,deck(e,c.owner,spellbook));if(n>=5)specialChoice(e,c,deck(e,c.owner,m=>e.race(m)==='魔法师族'&&e.hasAttribute(m,'暗')&&e.level(m)>=5),{shuffle:true});}},['normal','special']);effect('Fool of Prophecy',(e,c)=>deck(e,c.owner,spellbook),(e,c)=>{moved(e,c,args(c),'grave','effect-send');e.shuffle(e.state.players[c.owner].deck);if(self(e,c))self(e,c).eraFool=e.state.turn;},{role:'send-deck'});onEnd('Fool of Prophecy',{condition:(e,c)=>self(e,c)?.eraFool===e.state.turn&&new Set(grave(e,c.owner,spellbook).map(m=>m.id)).size>=5,cost:(e,c)=>X.tribute(e,c,[c.uid]),resolve:(e,c)=>specialChoice(e,c,deck(e,c.owner,m=>e.race(m)==='魔法师族'&&e.hasAttribute(m,'暗')&&e.level(m)>=5),{shuffle:true})});
 Object.assign(X,{hieratic,madolche,spellbook,prophecy,chronomaly,heroic,gear,mermail,atlantean,heraldic,firefist,formation,hazy,fireking,millChoice,handSpecialEffect});
 if(typeof module!=='undefined'){module.exports=X;for(const part of ['monsters','extra','spells','traps'])require('./effects-2012-'+part+'.js');}
})(globalThis);
