/* D/D's Fusion, Synchro and contract economy. */
(function(root){
 'use strict';const X=root.DuelChronicle,{D,E,H,C,I,is,A,Q,passive,mark,extend,card,def,field,monster,active,allF,allM,allS,ownM,foeM,hand,deck,grave,first,args,self,src,g,choose,target,moved,destroy,onEntry,onMove,onEnd,onStandby,watch,revive,search,specialChoice,series,effect,cast,defer,lock,locked}=X;
 const Y=X.year2015,{fm,pend,live,limit,other,ps,back,send,banish,destroyed,pickSend,placeScale,fusion}=Y,dd=m=>series(m,'D/D'),ddd=m=>series(m,'D/D/D'),contract=m=>series(m,'Dark Contract'),both=m=>dd(m)||contract(m),canSend=(e,m)=>e.state.ruleMode?.id!=='liberation'&&H.canSendGY(e,m);
 A('D/D/D Dragon King Pendragon','y15-special',{zones:['hand'],summons:true,inputs:(e,c)=>[g(e,c,'dragon','选择解放的龙族',[...hand(e,c.owner),...ownM(e,c)].filter(m=>e.race(m)==='龙族'&&e.canTribute(m,c.owner)),1,1,'cost'),g(e,c,'fiend','选择另一只恶魔族',[...hand(e,c.owner),...ownM(e,c)].filter(m=>m.uid!==c.uid&&!args(c,'dragon').includes(m.uid)&&e.race(m)==='恶魔族'&&e.canTribute(m,c.owner)),1,1,'cost')],cost:(e,c)=>X.tribute(e,c,[...args(c,'dragon'),...args(c,'fiend')]),resolve:(e,c)=>revive(e,c,c.uid,{via:'effect'}),aiScore:1100});
 effect('D/D/D Dragon King Pendragon',null,(e,c)=>{e.modify(c.uid,'atk','add',500,e.state.turn,c.source);choose(e,c,'可以破坏一张魔法陷阱',allS(e),0,1,'gx-destroy',{role:'destroy'});},{mode:'y15-destroy',discard:1});
 onMove('D/D Pandora','y15-draw',{condition:(e,c)=>e.field(c.owner).length===0,resolve:(e,c)=>e.draw(c.owner,2)},(e,v)=>v.to==='grave'&&['destroy','battle'].includes(v.kind)&&(v.kind==='battle'||v.byOwner!==v.owner));
 extend('xyzValid',function(prior,p,m,ms,rankUp=false){if(rankUp&&is(m,'D/D/D Marksman King Tell')&&ms.length===1&&ddd(ms[0])&&def(ms[0]).type==='xyz'&&def(ms[0]).rank===4&&ms[0].faceUp&&this.find(ms[0].uid)?.owner===p&&fm(this.find(ms[0].uid)?.zone)&&this.canSpecial(p,m,{via:'xyz'})&&this.state.players[p].usedTurn['rankup:'+m.id]!==this.state.turn)return true;return prior.call(this,p,m,ms,rankUp);});
 E.on('damage',(e,v)=>{if(!v.battle&&v.amount>0)e.state.players[v.owner].y15EffectDamage=e.state.turn;});
 effect('D/D/D Marksman King Tell',e=>allM(e).filter(m=>m.faceUp),(e,c)=>{const m=card(e,first(c));if(m&&e.modify(m.uid,'both','add',-1000,e.state.turn,c.source))e.damage(1-c.owner,1000,'效果',c.source);},{mode:'y15-shrink',quick:true,detach:1,condition:(e,c)=>e.state.players[c.owner].y15EffectDamage===e.state.turn});
 onMove('D/D/D Marksman King Tell','y15-send',{resolve:(e,c)=>pickSend(e,c,deck(e,c.owner,both))},(e,v)=>fm(v.from)&&v.to==='grave');
 mark("D/D/D Oracle King d'Arc");
 extend('damage',function(prior,p,n,k,s,...a){if(k!=='战斗'&&live(this,"D/D/D Oracle King d'Arc",p).some(f=>fm(f.zone))){this.heal(p,n,s);return 0;}return prior.call(this,p,n,k,s,...a);});
 cast('D/D/D Contract Change',null,(e,c)=>{if(first(c,'mode')==='search')search(e,c,deck(e,c.owner,m=>dd(m)&&pend(m)&&e.level(m)<=4));else choose(e,c,'选择除外的DDD',grave(e,c.owner,m=>ddd(m)&&monster(m)),1,1,'y15-contract-shrink',{attacker:c.event.window.attack.uid,role:'banish'});},{main:false,condition:(e,c)=>c.event.window?.attack?.owner!==c.owner&&!!c.event.window?.attack,inputs:()=>[H.customGroup('mode','选择效果',[{uid:'search',label:'检索'},{uid:'shrink',label:'降低攻击力'}])],aiResponse:()=>850});
 E.op('y15-contract-shrink',(e,t)=>{const c={owner:t.owner,source:t.context.source},m=card(e,t.picks[0]);if(m){const atk=def(m).atk;banish(e,c,[m.uid]);if(e.find(m.uid)?.zone==='banished')e.modify(t.context.attacker,'atk','add',-atk,null,c.source);}});
 E.on('summon',(e,v)=>{if(is({id:v.id},'D/D/D Duo-Dawn King Kali Yuga')&&v.kind==='xyz')e.state.y15KaliYuga={uid:v.uid,turn:e.state.turn};});mark('D/D/D Duo-Dawn King Kali Yuga');
 const kali=(e,uid)=>e.state.y15KaliYuga?.turn===e.state.turn&&uid!==e.state.y15KaliYuga.uid;
 extend('earlyCanUse',function(prior,c,a){return !(kali(this,c.uid)&&(field(this.find(c.uid)?.zone)||a.cardActivation))&&prior.call(this,c,a);});
 extend('negated',function(prior,m){return !!m&&kali(this,m.uid)&&field(this.find(m.uid)?.zone)||prior.call(this,m);});
 extend('activeSpell',function(prior,m){return !(m&&kali(this,m.uid)&&field(this.find(m.uid)?.zone))&&prior.call(this,m);});
 effect('D/D/D Duo-Dawn King Kali Yuga',null,(e,c)=>destroy(e,c,allS(e).map(m=>m.uid)),{mode:'y15-wipe',quick:true,detach:1});
 effect('D/D/D Duo-Dawn King Kali Yuga',(e,c)=>grave(e,c.owner,contract),(e,c)=>X.setFrom(e,c,args(c).map(u=>card(e,u)).filter(Boolean)),{mode:'y15-set',detach:1,oncePerTurn:false,role:'search'});
 effect('D/D Berfomet',null,(e,c)=>{const m=card(e,first(c));if(m)m.levelOverride={value:Number(first(c,'level')),until:e.state.turn};lock(e,c.owner,'special',{series:'D/D'});},{mode:'y15-level',inputs:(e,c)=>[g(e,c,'target','选择另一只DD',ownM(e,c).filter(m=>m.faceUp&&m.uid!==c.uid&&dd(m)&&e.level(m)>0),1,1,'own-boost'),H.customGroup('level','宣言等级',Array.from({length:8},(_,i)=>({uid:String(i+1),label:String(i+1)})))]});
 watch('D/D/D Wave Oblivion King Caesar Ragnarok','y15-equip','attack',(e,v,f)=>[v.uid,v.target].includes(f.card.uid),{once:H.once('y15-caesar-ragnarok','card'),inputs:target('选择返回手牌的DD或契约书',(e,c)=>e.field(c.owner).filter(m=>m.uid!==c.uid&&both(m)),'self-bounce'),resolve:(e,c)=>{const u=first(c);moved(e,c,[u],'hand','effect-return');if(e.find(u)?.zone==='hand')choose(e,c,'选择装备的对方怪兽',foeM(e,c).filter(m=>m.faceUp&&m.uid!==c.event.uid&&m.uid!==c.event.target),1,1,'y15-caesar-equip',{host:c.uid,role:'destroy'});}});
 E.op('y15-caesar-equip',(e,t)=>{if(e.equipMonster(t.picks[0],t.context.host,t.owner,t.context.source)){const m=card(e,t.picks[0]);if(m)m.y15CaesarEquip=true;}});
 passive('D/D/D Wave Oblivion King Caesar Ragnarok',{stat:(e,s,m,k)=>k==='atk'&&m.uid===s.card.uid?e.activeEquip(m).filter(q=>q.y15CaesarEquip).reduce((n,q)=>n+(def(q).atk||0),0):0});
 for(const n of ['Dark Contract with Errors','Dark Contract with the Yamimakai']){cast(n,null,()=>{});onStandby(n,{mandatory:true,resolve:(e,c)=>e.damage(c.owner,1000,'效果',c.source)},{optional:false});}
 Q('Dark Contract with Errors','y15-negate',{zones:['spells'],effectType:'trap',once:H.once('y15-errors','card'),condition:(e,c)=>ownM(e,c).some(dd),resolve:(e,c)=>{e.state.y15Errors={uid:c.uid,turn:e.state.turn};},aiScore:100,aiResponse:(e,c)=>c.event.window?.chainLast?.source.effectType==='trap'?1000:0});
 extend('activeSpell',function(prior,m){return !(m&&def(m).type==='trap'&&this.state.y15Errors?.turn===this.state.turn&&this.state.y15Errors.uid!==m.uid)&&prior.call(this,m);});
 extend('earlyNegatesLink',function(prior,l,...a){return l.source.effectType==='trap'&&field(this.find(l.uid)?.zone)&&this.state.y15Errors?.turn===this.state.turn&&this.state.y15Errors.uid!==l.uid||prior.call(this,l,...a);});
 const slimeProfile=(e,c)=>({year2015:'dd',spellId:c.sourceId,zones:e.find(c.uid)?.zone==='grave'?['grave']:['hand'],destination:e.find(c.uid)?.zone==='grave'?'banished':'grave',requiredUid:c.uid,requiredZone:e.find(c.uid)?.zone,requiredGeneration:card(e,c.uid)?.generation||0});
 extend('fusionAllowed',function(prior,m,s){return (s?.year2015!=='dd'||ddd(m))&&prior.call(this,m,s);});
 for(const n of ['D/D Swirl Slime','D/D Necro Slime'])A(n,'y15-fusion',{zones:[n==='D/D Swirl Slime'?'hand':'grave'],once:limit(n),summons:true,condition:(e,c)=>e.fusions(c.owner,slimeProfile(e,c)).length>0,resolve:(e,c)=>fusion(e,c,slimeProfile(e,c)),aiScore:1300});
 A('D/D Swirl Slime','y15-recruit',{zones:['grave'],once:limit('swirl-recruit'),summons:true,cost:(e,c)=>moved(e,c,[c.uid],'banished','cost-banish'),resolve:(e,c)=>specialChoice(e,c,hand(e,c.owner,m=>dd(m)&&monster(m)),{via:'effect'}),aiScore:950});
 onStandby('D/D/D Dragonbane King Beowulf',{resolve:(e,c)=>destroy(e,c,allS(e).filter(m=>e.find(m.uid)?.zone==='spells').map(m=>m.uid))});
 extend('finishBattle',function(prior,a){const m=card(this,a.uid),t=card(this,a.target),owner=m&&this.find(m.uid)?.owner;if(m&&t?.position==='defense'&&dd(m)&&live(this,'D/D/D Dragonbane King Beowulf',owner).some(f=>fm(f.zone)))m.piercingUntil=this.state.turn;return prior.call(this,a);});
 for(const [n,kind] of [['D/D Savant Newton','trap'],['D/D Savant Copernicus','spell']]){
  Q(n,'y15-scale-negate',{zones:['spells'],effectType:'spell',main:false,condition:(e,c)=>{const m=card(e,c.uid),l=c.event.window?.chainLast;return m&&e.isPendulumScale(m)&&!m.y15SavantUsed&&l?.source.effectType===kind&&/\b(?:damage|burn)\s*\(/.test(String(E.get(l.key)?.resolve));},cost:(e,c)=>{card(e,c.uid).y15SavantUsed=true;},resolve:(e,c)=>{e.negateLink(c.responseTo,c.source,false,false);e.destroy(c.uid,c.source);},aiResponse:()=>900});
 }
 extend('canSpecial',function(prior,p,m,o={}){return !(o.via==='pendulum'&&!dd(m)&&this.scales(p).some(s=>s&&['D/D Savant Newton','D/D Savant Copernicus'].some(n=>is(s.card,n))))&&prior.call(this,p,m,o);});
 A('D/D Savant Newton','y15-recover',{zones:['hand'],once:limit('newton'),inputs:target('选择回收的DD或契约书',(e,c)=>grave(e,c.owner,m=>both(m)&&m.id!==c.sourceId),'search'),cost:(e,c)=>H.discard(e,c,[c.uid]),resolve:(e,c)=>moved(e,c,args(c),'hand','effect-return'),aiScore:850});
 onEntry('D/D Savant Copernicus','y15-send',{once:limit('copernicus'),resolve:(e,c)=>pickSend(e,c,deck(e,c.owner,m=>both(m)&&m.id!==c.sourceId))},['normal','special']);
 A('D/D Lamia','y15-special',{zones:['hand','grave'],once:limit('lamia'),summons:true,inputs:(e,c)=>[g(e,c,'cost','选择送墓的DD或契约书',[...hand(e,c.owner),...e.field(c.owner).filter(m=>m.faceUp)].filter(m=>m.id!==c.sourceId&&both(m)&&canSend(e,m)),1,1,'cost')],cost:(e,c)=>H.sendCost(e,c,args(c,'cost')),resolve:(e,c)=>{const m=revive(e,c,c.uid,{via:'effect'});if(m)m.banishOnLeave=true;},aiScore:1000});
 Q('D/D/D Cursed King Siegfried','y15-negate',{once:limit('siegfried'),inputs:target('选择无效的表侧魔法陷阱',e=>allS(e).filter(m=>m.faceUp)),resolve:(e,c)=>{const m=card(e,first(c));if(m&&!e.unaffected(m,c.source)){m.y15Siegfried=true;defer(e,c,'standby',e.state.turn+1,'y15-siegfried-clear',{uid:m.uid,generation:m.generation,anyOwner:true});}},aiScore:750,aiResponse:()=>1100});
 extend('activeSpell',function(prior,m){return !m?.y15Siegfried&&prior.call(this,m);});
 E.op('y15-siegfried-clear',(e,t)=>{const m=card(e,t.context.uid);if(m&&m.generation===t.context.generation)delete m.y15Siegfried;});
 onMove('D/D/D Cursed King Siegfried','y15-heal',{mandatory:true,resolve:(e,c)=>e.heal(c.owner,e.field(c.owner).filter(contract).length*1000)},(e,v)=>v.to==='grave'&&destroyed(e,v));
 for(const [mode,zone] of [['grave','grave'],['extra','extra']])A('Dark Contract with the Yamimakai','y15-'+mode,{zones:['spells'],effectType:'spell',once:limit('yamimakai'),condition:(e,c)=>[0,4].some(i=>!e.state.players[c.owner].spells[i]),inputs:(e,c)=>[g(e,c,'card','选择放置的DD灵摆怪兽',e.state.players[c.owner][zone].filter(m=>dd(m)&&pend(m)&&(zone!=='extra'||m.faceUpExtra)),1,1,'search')],resolve:(e,c)=>placeScale(e,c,first(c,'card')),aiScore:650});
 cast('D/D Reroll',null,()=>{});passive('D/D Reroll',{protect:(e,s,m,b,source)=>!b&&source?.owner!==s.owner&&e.find(m.uid)?.owner===s.owner&&contract(m)});
 A('D/D Reroll','y15-recycle',{zones:['grave'],inputs:target('选择洗回的除外DD',(e,c)=>e.state.players[c.owner].banished.filter(dd),'search',1,3),cost:(e,c)=>moved(e,c,[c.uid],'banished','cost-banish'),resolve:(e,c)=>back(e,c,args(c)),aiScore:500});
 ps('D/D Orthros','y15-scale-destroy',{inputs:(e,c)=>[g(e,c,'own','选择另一张DD或契约书',e.field(c.owner).filter(m=>m.uid!==c.uid&&both(m)),1,1,'self-destroy'),g(e,c,'target','选择魔法陷阱',allS(e).filter(m=>!args(c,'own').includes(m.uid)))],resolve:(e,c)=>destroy(e,c,[...args(c,'own'),...args(c)])});
 watch('D/D Orthros','y15-special','damage',(e,v,f)=>v.owner===f.owner&&v.amount>0,{summons:true,resolve:(e,c)=>revive(e,c,c.uid,{via:'effect'})},{zones:['hand']});
 onEntry('D/D Orthros','y15-lock',{resolve:(e,c)=>lock(e,c.owner,'special',{race:'恶魔族'})},['special']);
 ps('D/D/D Chaos King Apocalypse','y15-scale-special',{summons:true,inputs:(e,c)=>[g(e,c,'cost','选择除外的两只DD',grave(e,c.owner,m=>dd(m)&&monster(m)),2,2,'cost')],cost:(e,c)=>moved(e,c,args(c,'cost'),'banished','cost-banish'),resolve:(e,c)=>revive(e,c,c.uid,{via:'effect'})});
 Q('D/D/D Chaos King Apocalypse','y15-special',{zones:['hand','grave'],main:false,once:limit('apocalypse'),summons:true,condition:(e,c)=>e.state.active!==c.owner,inputs:target('选择破坏的两张表侧魔法陷阱',(e,c)=>e.spells(c.owner).filter(m=>m.faceUp),'self-destroy',2,2),resolve:(e,c)=>{lock(e,c.owner,'special',{race:'恶魔族'});if(args(c).map(u=>e.destroy(u,c.source)).filter(Boolean).length===2)revive(e,c,c.uid,{via:'effect'});},aiResponse:()=>950});
})(globalThis);
