/* GX / 5D's shared rules. All continuations carry JSON data, including delayed
 * returns and copied effects; a save may be resumed inside any selection. */
(function(root){
 'use strict';
 const X=root.Duel2005,{E,D,H,C,I,is,mark,S,T,A,Q,R,passive,allM,allS,allF,monster,face,ownM,foeM,moved,destroy,choose,g,target,pay,once,src,active,ctx,first,args,self,hand,deck,grave,extend,rule,field,has,onEnd,defer,revive,search,recruit,token,onEntry,onMove,onStandby}=X,{CARDS}=D,P=root.ModernDuelEngine.prototype;
 const series=(m,name)=>!!CARDS[m?.id]&&((CARDS[m.id].officialName||'').includes(name)||(CARDS[m.id].series||[]).includes(name));
 const destiny=m=>series(m,'Destiny HERO'),neo=m=>series(m,'Neo-Spacian'),six=m=>series(m,'Six Samurai'),alien=m=>series(m,'Alien'),crystal=m=>series(m,'Crystal Beast'),gladiator=m=>series(m,'Gladiator Beast'),lightsworn=m=>series(m,'Lightsworn');
 const groups={destinyhero:['命运英雄','Destiny HERO'],neospacian:['新空间侠','Neo-Spacian'],sixsamurai:['六武众','Six Samurai'],alien:['外星人','Alien'],crystalbeast:['宝玉兽','Crystal Beast'],gladiator:['剑斗兽','Gladiator Beast'],lightsworn:['光道','Lightsworn'],cloudian:['云魔物','Cloudian'],volcanic:['火山','Volcanic'],venom:['毒蛇','Venom'],arcana:['秘仪之力','Arcana Force'],morphtronic:['变形斗士','Morphtronic'],psychic:['念动力','Psychic'],naturia:['自然','Naturia'],genex:['次世代','Genex'],jurrac:['侏罗纪','Jurrac'],fabled:['魔轰神','Fabled'],icebarrier:['冰结界','Ice Barrier'],x_saber:['X-剑士','X-Saber'],allyjustice:['正义盟军','Ally of Justice']};
 for(const [key,[label,n]] of Object.entries(groups)){D.families[key]=label;for(const c of D.CARD_LIST)if(series(c,n)||key==='psychic'&&c.race==='念动力族')c.families=[...new Set([...(c.families||[]),key])];}
 for(const c of D.CARD_LIST.filter(c=>c.releaseYear>=2006&&c.releaseYear<=2008)){
  if(c.type==='fusion'&&/Must be Fusion Summoned/.test(c.originalDescription))c.fusionOnly=true;
  if(c.nexOnly){c.specialOnly='nex';c.noNormal=true;}
  if(c.gemini)c.earlyRules={...(c.earlyRules||{}),gemini:true};
  if(/always treated as an? "Ultimate Crystal"/.test(c.originalDescription)||['Rainbow Dragon','Rainbow Dark Dragon'].includes(c.officialName))c.series=[...(c.series||[]),'Ultimate Crystal'];
 }
 const normal=(e,m)=>!!m&&monster(m)&&CARDS[m.id].type!=='token'&&(!CARDS[m.id].effect||CARDS[m.id].gemini&&['grave','monsters','extraMonster'].includes(e.find(m.uid)?.zone)&&!e.geminiActive(m));
 P.isNormalMonster=function(m){return normal(this,m);};
 P.geminiActive=function(m){return !!m.geminiSummoned||allM(this).some(q=>q.faceUp&&is(q,'Superalloy Beast Raptinus')&&!q.effectNegated&&!this.rawEarly('Skill Drain').length);};
 // Being a Gemini Normal Monster is not effect negation. Gate its registered
 // effects separately, and let the second Normal Summon use the usual window.
 extend('earlyCanUse',function(prior,c,a){if(!prior.call(this,c,a))return false;const f=this.find(c.uid);return !f||!CARDS[f.card.id].gemini||!field(f.zone)||a.mode==='gemini-summon'||this.geminiActive(f.card);});
 extend('passiveSources',function(prior,...a){return prior.call(this,...a).filter(f=>!CARDS[f.card.id].gemini||this.geminiActive(f.card));});
 for(const c of D.CARD_LIST.filter(c=>c.gemini))A(c.officialName,'gemini-summon',{label:'二重召唤',inherent:true,summons:true,condition:(e,x)=>!!self(e,x)&&!e.state.normalUsed&&!e.geminiActive(self(e,x))&&e.canNormal(self(e,x),x.owner),resolve:(e,x)=>{const m=self(e,x);if(!m)return;e.state.normalUsed=true;m.geminiSummoned=true;m.normalSummoned=true;e.state.summons[x.owner]++;e.log('summon','二重召唤 · '+CARDS[m.id].name,x.owner,{uid:m.uid,cardId:m.id});e.emit({type:'summon',owner:x.owner,uid:m.uid,id:m.id,from:e.find(m.uid).zone,kind:'normal',materials:[],gemini:true});},aiScore:820});
 extend('move',function(prior,uid,to,o={}){const f=this.find(uid),was=f&&field(f.zone),m=f?.card;let dest=to;
  if(this._advancedReady&&to==='grave'&&!o.ignoreReplacement&&(has(this,'Macro Cosmos')||has(this,'Banisher of the Radiance')||m&&monster(m)&&(has(this,'Dimensional Fissure')||this.state.dimensionalRiftTurn===this.state.turn)))dest='banished';
  if(this._advancedReady&&was&&to==='hand'&&monster(m)&&has(this,'Degenerate Circuit'))dest='banished';
  const r=prior.call(this,uid,dest,o);if(was&&r&&r.to!==r.from&&m){delete m.geminiSummoned;delete m.alienCounters;delete m.venomCounters;delete m.fogCounters;delete m.gxFlags;}
  return r;
 });
 extend('setPosition',function(prior,uid,pos,s,down=false){const r=prior.call(this,uid,pos,s,down);if(r&&down){const m=this.find(uid)?.card;if(m){delete m.geminiSummoned;delete m.gxFlags;}}return r;});
 extend('describe',function(prior,m,...a){return {...prior.call(this,m,...a),geminiSummoned:!!m.geminiSummoned,alienCounters:m.alienCounters||0,fogCounters:m.fogCounters||0,venomCounters:m.venomCounters||0,gxFlags:m.gxFlags?X.cp(m.gxFlags):undefined};});
 extend('materialMatches',function(prior,m,s,...a){if(s.nameIncludes&&!series(m,s.nameIncludes)||s.nameIncludesAny&&!s.nameIncludesAny.some(n=>series(m,n))||s.gemini&&!CARDS[m.id].gemini||s.minLevel&&this.level(m)<s.minLevel)return false;return prior.call(this,m,s,...a);});
 extend('fusionValid',function(prior,p,m,list,s){if(!prior.call(this,p,m,list,s))return false;const d=CARDS[m.id];if(d.fusionDiversity){const walk=(i,used)=>i===d.fusionDiversity.length||list.some((q,j)=>!used.includes(j)&&d.fusionDiversity[i].some(n=>series(q,n))&&walk(i+1,[...used,j]));return walk(0,[]);}return true;});
 extend('fusionAllowed',function(prior,m,s){const d=CARDS[m.id];if(d.nexOnly||d.contactOnly&&!s?.contact||d.darkFusionOnly&&!s?.darkFusion)return false;if(s?.onlyId&&m.id!==s.onlyId||s?.series&&!series(m,s.series))return false;return prior.call(this,m,s);});
 extend('synchroValid',function(prior,p,m,list,o={}){if(!prior.call(this,p,m,list,o))return false;const s=CARDS[m.id].synchro;return list.every(q=>{if(this.isTuner(q))return (!s.tunerAttribute||this.hasAttribute(q,s.tunerAttribute))&&(!s.tunerNameIncludes||series(q,s.tunerNameIncludes));return (!s.nonAttribute||this.hasAttribute(q,s.nonAttribute))&&(!s.nonRace||this.race(q)===s.nonRace)&&(!s.nonNameIncludes||series(q,s.nonNameIncludes));});});
 extend('ritualAccepts',function(prior,id,m){return !!m&&CARDS[m.id].type==='ritual'&&!!CARDS[id]?.ritualAny||prior.call(this,id,m);});
 extend('ritualPool',function(prior,p,m,id){return CARDS[id]?.ritualAny?deck(this,p,q=>normal(this,q)&&this.level(q)>0&&H.canSendGY(this,q)):prior.call(this,p,m,id);});
 extend('performRitual',function(prior,p,uid,uids,id,s,z=null,pos='attack'){if(!CARDS[id]?.ritualAny)return prior.call(this,p,uid,uids,id,s,z,pos);const m=this.find(uid)?.card,list=uids.map(x=>this.find(x)?.card);if(!this.ritualValid(p,m,list,id))throw new root.DuelRuleError('高等仪式术必须从卡组送墓等级合计恰好相等的通常怪兽。');const mats=list.map(q=>this.describe(q));for(const q of list)this.move(q.uid,'grave',{kind:'effect-ritual-material',source:s,byOwner:p});this.shuffle(this.state.players[p].deck);return this.special(p,uid,{via:'ritual',materials:mats,position:pos,...(z!==null?{zone:z}:{})});});
 // Shared durable operations: target identity is checked again at resolution.
 const delayMove=(e,c,m,to,phase='end',turn=e.state.turn,owner=c.owner)=>defer(e,c,phase,turn,'gx-delayed-move',{uid:m.uid,generation:m.generation||0,to},owner);
 E.op('gx-delayed-move',(e,t)=>{const d=t.context,f=e.find(d.uid);if(f&&(f.card.generation||0)===d.generation){if(d.to==='destroy')e.destroy(d.uid,d.source);else moved(e,{owner:t.owner,source:d.source},[d.uid],d.to);}});
 E.op('gx-special',(e,t)=>{const o=t.context;for(const uid of t.picks){const m=revive(e,{owner:t.owner,source:o.source},uid,o);if(m){if(o.half)e.modify(m.uid,'atk','mul',.5,null,o.source);if(o.noAttack)m.yearAttackLocked=true;if(o.effectNegated)m.effectNegated=true;if(o.linked)m.gxLinked=o.linked;if(o.end)delayMove(e,{owner:t.owner,source:o.source},m,o.end);if(o.flag)m.gxFlags={...(m.gxFlags||{}),[o.flag]:true};}}if(o.shuffle)e.shuffle(e.state.players[t.owner].deck);});
 function specialChoice(e,c,list,o={}){const max=Math.min(o.max??1,e.freeMain(c.owner));if(max<1)return;choose(e,c,'选择特殊召唤的怪兽',list.filter(m=>monster(m)&&e.canSpecial(c.owner,m,{via:o.via||'revive',...o})),1,max,'gx-special',{role:'special',...o});}
 function castSearch(name,pred,n=1){S(name,{inputs:target('选择加入手牌的卡片',(e,c)=>deck(e,c.owner,m=>pred(e,m,c)),'search',n,n),resolve:(e,c)=>e.search(c.owner,args(c)),aiScore:700});}
 function castRevive(name,pred,{zones=['grave'],...o}={}){S(name,{summons:true,condition:(e,c)=>e.freeMain(c.owner)>0,inputs:target('选择特殊召唤的怪兽',(e,c)=>H.cards(e,c.owner,zones,m=>pred(e,m,c)&&e.canSpecial(c.owner,m,{via:o.via||'revive',...o})),'special'),resolve:(e,c)=>E.ops['gx-special'](e,{owner:c.owner,picks:args(c),context:{source:c.source,...o}}),aiScore:850});}
 function spellStat(name,pred,atk,def=atk){S(name,{resolve:()=>{},aiScore:300});passive(name,{stat:(e,s,m,k)=>pred(e,s,m)?(k==='atk'?atk:def):0});}
 function setFrom(e,c,list){choose(e,c,'选择盖放的卡片',list,1,1,'gx-set',{role:'search'});}
 E.op('gx-set',(e,t)=>{for(const uid of t.picks){const f=e.find(uid),p=e.state.players[t.owner],i=p.spells.indexOf(null);if(!f||i<0)continue;const m=e.remove(uid).card;m.generation=(m.generation||0)+1;m.faceUp=false;m.setTurn=e.state.turn;if(CARDS[m.id].type==='monster')m.gxSetSpell=true;delete m.asMonster;p.spells[i]=m;e.log('set','盖放「'+CARDS[m.id].name+'」',t.owner,{cardId:m.id,uid});}e.shuffle(e.state.players[t.owner].deck);});
 function respond(name,condition,resolve,{cost,inputs,score=850,...s}={}){const method=CARDS[I(name)].type==='trap'?T:Q;const def={main:false,condition:(e,c)=>!!c.event.window&&condition(e,c,c.event.window),inputs,cost,resolve,aiResponse:()=>score,...s};return method===T?T(name,def):Q(name,'response',def);}
 function negate(e,c,{destroyCard=true,banish=false}={}){const l=e.state.chain.find(l=>l.id===c.responseTo);if(!l)return;e.negateLink(l.id,c.source,true,destroyCard&&!banish);if(banish&&e.find(l.uid))moved(e,c,[l.uid],'banished','effect-banish');}
 const chainUnique=(e,n)=>e.state.chain.length>=n-1&&new Set(e.state.chain.map(l=>l.sourceId)).size===e.state.chain.length;
 const mill=(e,p,n,s=null,kind='effect-mill')=>{const list=e.state.players[p].deck.slice(0,n);for(const m of list)e.move(m.uid,'grave',{kind,source:s,byOwner:s?.owner??p});return list;};
 function handSpecial(name,condition=()=>true,pred=null,count=0,{zones=['hand'],via,only=false,...options}={}){const key=via||'year-special:'+I(name);if(only){C(name).noNormal=true;C(name).specialOnly=key;}A(name,'gx-special',{zones,inherent:true,summons:true,condition:(e,c)=>e.freeMain(c.owner)>0&&condition(e,c)&&e.canSpecial(c.owner,H.source(e,c).card,{via:key}),...(pred?{inputs:(e,c)=>[g(e,c,'cost','选择召唤素材',pred(e,c),count,count,'cost')],cost:(e,c)=>moved(e,c,args(c,'cost'),options.banish?'banished':'grave',options.banish?'cost-banish':'cost-tribute')}:{ }),resolve:(e,c)=>revive(e,c,c.uid,{via:key,...options}),aiScore:1050});}
 // Reusable, explicit effect builders. They never infer a rule from a card's display text.
 function ignite(name,pool,resolve,{discard=0,fee=0,oncePerTurn=true,role='destroy',min=1,max=min,...s}={}){return A(name,'gx-effect',{once:oncePerTurn?once():undefined,condition:(e,c)=>e.state.players[c.owner].lp>fee,inputs:(e,c)=>[...(discard?[g(e,c,'cost','选择丢弃的手牌',hand(e,c.owner,m=>m.uid!==c.uid),discard,discard,'cost')]:[]),...(pool?[g(e,c,'target','选择效果对象',pool(e,c),min,max,role)]:[])],cost:(e,c)=>{if(fee)pay(e,c,fee);if(discard)H.discard(e,c,args(c,'cost'));},resolve,aiScore:750,...s});}
 function ownStat(name,fn){passive(name,{stat:(e,s,m,k)=>s.card.uid===m.uid?fn(e,m,k,s.owner):0});}
 function tributeAction(name,pred,resolve,{n=1,...s}={}){return A(name,'gx-tribute',{once:once(),inputs:(e,c)=>[g(e,c,'cost','选择解放的怪兽',ownM(e,c).filter(m=>e.canTribute(m,c.owner)&&pred(e,m,c)),n,n,'cost')],cost:(e,c)=>{c.tributes=args(c,'cost').map(uid=>e.describe(e.find(uid).card));X.tribute(e,c);},resolve,aiScore:700,...s});}
 function counterAdd(e,uid,key,n=1){const f=e.find(uid);if(f&&field(f.zone)&&f.card.faceUp)f.card[key]=Math.max(0,(f.card[key]||0)+n);}
 function contactFusion(name,{shuffle=true}={}){const d=C(name);d.contactOnly=true;d.fusionExact=true;d.specialOnly='contact:'+d.id;mark(name);A(name,'gx-contact',{zones:['extra'],inherent:true,summons:true,label:'接触融合',condition:(e,c)=>e.fusionCombos(c.owner,H.source(e,c).card,{zones:['monsters','extraMonster'],contact:true}).length>0,inputs:(e,c)=>{const sets=e.fusionCombos(c.owner,H.source(e,c).card,{zones:['monsters','extraMonster'],contact:true});return [H.customGroup('materials','选择接触融合素材',sets.map((uids,i)=>({uid:String(i),label:uids.map(uid=>CARDS[e.find(uid).card.id].name).join(' + '),value:100-i,uids})))];},resolve:(e,c)=>{const sets=e.fusionCombos(c.owner,H.source(e,c).card,{zones:['monsters','extraMonster'],contact:true}),uids=sets[Number(first(c,'materials'))];if(!uids)return;const mats=uids.map(uid=>e.describe(e.find(uid).card));moved(e,c,uids,shuffle?'deck':'banished',shuffle?'contact-material':'cost-banish');e.shuffle(e.state.players[c.owner].deck);revive(e,c,c.uid,{via:d.specialOnly,materials:mats});},aiScore:1400});}
 const api={...X,series,destiny,neo,six,alien,crystal,gladiator,lightsworn,isNormal:normal,delayMove,specialChoice,castSearch,castRevive,spellStat,setFrom,respond,negate,chainUnique,mill,handSpecial,ignite,ownStat,tributeAction,counterAdd,contactFusion};root.Duel2006=api;
 if(typeof module!=='undefined'){module.exports=api;for(const s of ['monsters','monsters-extra','spells','traps'])require('./effects-2006-'+s+'.js');}
})(globalThis);
