(function(root){
 'use strict';
 const X=root.Duel2003,{E,D,H,C,I,is,mark,A,Q,R,allM,allS,monster,face,ownM,foeM,g,first,args,hand,deck,grave,pay,src,active,ctx,extend,rule,field,has,onStandby,onEnd,onBattleWin,guard,revive,recruit,token,cp}=X,{CARDS}=D;
 const normal=m=>monster(m)&&!CARDS[m.id].effect&&CARDS[m.id].type!=='token',lowNormal=(e,m,n=3)=>normal(m)&&e.level(m)<=n;
 const lvNext={};
 function evolution(from,to,phase,{battle=false,wait=false,condition=()=>true,only=false}={}){
  lvNext[I(from)]=I(to);C(from).lvNext=I(to);if(only){C(to).specialOnly='lv:'+I(from);C(to).noNormal=true;guard('special',to,(e,p,m,o)=>o.ignoreConditions||o.via==='lv:'+I(from));}
  const s={summons:true,leavesAsCost:true,condition:(e,c)=>!!H.self(e,c)&&(!battle||H.self(e,c).yearly?.battleWinTurn===e.state.turn)&&(!wait||H.self(e,c).summonTurn<e.state.turn)&&condition(e,c)&&H.cards(e,c.owner,['hand','deck'],m=>is(m,to)&&e.canSpecial(c.owner,m,{via:'lv:'+c.sourceId})).length>0,
   cost:(e,c)=>H.sendCost(e,c,[c.uid]),resolve:(e,c)=>{const list=H.cards(e,c.owner,['hand','deck'],m=>is(m,to));X.choose(e,c,'选择升级后的LV怪兽',list,1,1,'year-lv-summon',{via:'lv:'+c.sourceId,from:c.sourceId,role:'special'});}};
  if(phase==='standby')onStandby(from,s);else onEnd(from,s);
 }
 E.op('year-lv-summon',(e,t)=>{const m=revive(e,{owner:t.owner,source:t.context.source},t.picks[0],{via:t.context.via,ignoreConditions:!!t.context.ignoreConditions});if(m)(m.yearly||={}).lvFrom=t.context.ignoreConditions?null:t.context.from;if(m)e.shuffle(e.state.players[t.owner].deck);});
 E.on('battle-win',(e,v)=>{const m=e.find(v.uid)?.card;if(m)(m.yearly||={}).battleWinTurn=e.state.turn;});
 evolution('Armed Dragon LV3','Armed Dragon LV5','standby');evolution('Armed Dragon LV5','Armed Dragon LV7','end',{battle:true,only:true});
 evolution('Horus the Black Flame Dragon LV4','Horus the Black Flame Dragon LV6','end',{battle:true});evolution('Horus the Black Flame Dragon LV6','Horus the Black Flame Dragon LV8','end',{battle:true,only:true});
 evolution('Mystic Swordsman LV2','Mystic Swordsman LV4','end',{battle:true});evolution('Mystic Swordsman LV4','Mystic Swordsman LV6','end',{battle:true});
 evolution('Dark Mimic LV1','Dark Mimic LV3','standby');evolution('Silent Swordsman LV3','Silent Swordsman LV5','standby',{wait:true});
 evolution('Silent Swordsman LV5','Silent Swordsman LV7','standby',{condition:(e,c)=>H.self(e,c).yearly?.directDamageTurn<e.state.turn});
 for(const n of [1,3,5])evolution('Ultimate Insect LV'+n,'Ultimate Insect LV'+(n+2),'standby',{wait:true});
 for(const name of ['Mystic Swordsman LV4','Mystic Swordsman LV6']){C(name).noNormal=false;C(name).setOnly=true;}
 extend('canSpecial',function(prior,p,m,o={}){return prior.call(this,p,m,o.ignoreConditions?{...o,via:CARDS[m.id].specialOnly||o.via}:o);});
 extend('normalSummon',function(prior,a){const m=this.find(a.uid)?.card;if(m&&CARDS[m.id].setOnly&&a.mode!=='defense')throw new root.DuelRuleError('这只怪兽只能通常盖放。');return prior.call(this,a);});
 extend('actionsFor',function(prior,uid,...a){const list=prior.call(this,uid,...a),m=this.find(uid)?.card;return m&&CARDS[m.id].setOnly?list.filter(x=>x.type!=='summon'||x.mode==='defense'):list;});
 token('2004-tricky-token','魔术师衍生物','Tricky Token',5,2000,1200,'风','魔法师族');
 D.families.lv='LV升级';D.families.monarch='帝';D.families.gadget='齿轮';
 for(const c of D.CARD_LIST)for(const [family,yes] of [['lv',/ LV\d+$/.test(c.officialName)],['monarch',/Monarch$/.test(c.officialName)],['gadget',/ Gadget$/.test(c.officialName)]])if(yes)c.families=[...new Set([...(c.families||[]),family])];
 for(const n of [1,2,3])C('Harpie Lady '+n).nameAlias='Harpie Lady';
 extend('cardNameId',function(prior,m,...rest){return CARDS[m.id].nameAlias&&D.cardByName(CARDS[m.id].nameAlias)?I(CARDS[m.id].nameAlias):prior.call(this,m,...rest);});
 extend('draw',function(prior,p,n=1,...rest){if(this._advancedReady&&!this.state.inDrawPhase&&this.state.phase!=='draw'&&has(this,'Protector of the Sanctuary',1-p))return [];return prior.call(this,p,n,...rest);});
 extend('handRevealed',function(prior,p,viewer){return prior.call(this,p,viewer)||has(this,'Mind on Air',1-p);});
 extend('earlyNegatesLink',function(prior,l,probe=false){if(has(this,'The End of Anubis')&&(l.sourceZone==='grave'||Object.entries(l.targetMeta||{}).some(([k,v])=>k!=='cost'&&Object.values(v).some(t=>t.zone==='grave'))))return true;if(this.state.gorgonEyeTurn===this.state.turn&&this.find(l.uid)?.card.position==='defense'&&l.source.effectType==='monster')return true;return prior.call(this,l,probe);});
 extend('move',function(prior,uid,dest,o={}){if(dest==='grave'&&o.kind==='battle'&&has(this,'Grave Protector')){const r=prior.call(this,uid,'deck',o);this.shuffle(this.state.players[r.owner].deck);return r;}return prior.call(this,uid,dest,o);});
 extend('unaffected',function(prior,m,s){if(prior.call(this,m,s))return true;const r=CARDS[m.id].earlyRules||{},p=this.find(m.uid)?.owner;if(!s||!m.faceUp||this.negated(m))return false;const spell=(s.effectType||CARDS[s.id]?.type)==='spell';if(spell&&(r.spellImmune==='all'||r.spellImmune==='opponent'&&s.owner!==p))return true;if(spell&&normal(m)&&has(this,'Dust Barrier',p)&&s.owner!==p)return true;return false;});
 extend('canTarget',function(prior,m,s){if(!prior.call(this,m,s))return false;const p=this.find(m.uid)?.owner;if(s?.owner!==p&&m.faceUp&&(this.race(m)==='龙族'&&has(this,'King Dragun',p)||CARDS[m.id].officialName.startsWith('Horus the Black Flame Dragon')&&has(this,"Horus' Servant",p)))return false;return true;});
 extend('canAttack',function(prior,m,p=this.state.active,t=null){if(!prior.call(this,m,p,t))return false;const enemy=this.find(t)?.card;if(has(this,'Big-Tusked Mammoth',1-p)&&m.summonTurn===this.state.turn)return false;if(this.state.players[p].threateningRoarTurn===this.state.turn)return false;if(this.state.players[p].attackDeniedUntil>=this.state.turn)return false;if(enemy&&has(this,'Marshmallon Glasses',1-p)&&has(this,'Marshmallon',1-p)&&!is(enemy,'Marshmallon'))return false;if(enemy&&is(enemy,'Catnipped Kitty')&&this.monsters(1-p).some(x=>x.uid!==t&&x.faceUp&&this.race(x)==='兽族'))return false;if(enemy&&is(enemy,'Emissary of the Oasis')&&this.monsters(1-p).some(x=>x.faceUp&&lowNormal(this,x)))return false;return true;});
 extend('positionLocked',function(prior,m){return prior.call(this,m)||m.judgmentPositionLock||has(this,'Final Attack Orders')||this.activeEquip(m).some(q=>is(q,'Flint'))||this.spells(1-(this.find(m.uid)?.owner??0)).some(q=>active(this,q)&&is(q,'Swords of Concealing Light'));});
 extend('earlyCanUse',function(prior,c,a){const p=this.state.players[c.owner],d=CARDS[c.sourceId],w=c.event.window||{};if(!prior.call(this,c,a))return false;if(p.spellTrapLockedTurn===this.state.turn&&a.cardActivation)return false;if(d.type==='trap'&&(p.trapLockedTurn===this.state.turn||this.state.noTrapsTurn===this.state.turn||this.state.phase==='battle'&&(has(this,'Mirage Dragon',1-c.owner)||has(this,'Pitch-Black Warwolf',1-c.owner))))return false;if(a.cardActivation&&allS(this).some(m=>active(this,m)&&(m.xingTargets||[]).includes(c.uid)))return false;if(d.type==='trap'&&(w.kind==='summon-attempt'||w.kind==='summon')&&['Invasion of Flames','Creeping Doom Manta','Eagle Eye','Tactical Espionage Expert'].some(n=>is(this.find(w.uid)?.card,n))&&w.summonKind==='normal')return false;return true;});
 extend('zoneBlocked',function(prior,p,i){return prior.call(this,p,i)||allM(this).some(m=>active(this,m)&&(m.blockedZones||[]).some(([o,n])=>o===p&&n===i));});
 extend('damage',function(prior,p,n,kind,...a){const player=this.state.players[p],battle=this.state.frame?.attack,def=[this.find(battle?.uid),this.find(battle?.target)].find(f=>f?.owner===p);if(kind==='战斗'&&(player.hallowedLifeTurn===this.state.turn||has(this,'Spirit Barrier',p)&&this.monsters(p).length||def&&has(this,'Emissary of the Oasis',p)&&lowNormal(this,def.card)))return;if(kind!=='战斗'&&(player.pikeruCircleTurn===this.state.turn||player.hallowedLifeTurn===this.state.turn))return;return prior.call(this,p,n,kind,...a);});
 extend('continuousMaintenance',function(prior,...a){const result=prior.call(this,...a);for(const m of allM(this))if(m.faceUp&&CARDS[m.id].type!=='link'){if(has(this,'Final Attack Orders'))m.position='attack';else if(has(this,'Level Limit - Area B')&&this.level(m)>=4)m.position='defense';}return result;});
 const originalPay=E.payCost;E.payCost=function(e,c){const old=e._spellActivationCost;e._spellActivationCost=E.get(c.key).cardActivation&&CARDS[c.sourceId].type==='spell';try{return originalPay(e,c);}finally{e._spellActivationCost=old;}};
 extend('payLP',function(prior,p,n){if(this._spellActivationCost&&has(this,'Spell Economics',p))return;return prior.call(this,p,n);});
 const eventHandlers=new Map();
 function event(name,type,condition,spec,{zones=['monsters','extraMonster','spells','fieldSpell'],mandatory=false}={}){const mode='year-'+type;R(name,mode,{zones,...spec});const list=eventHandlers.get(type)||[];list.push({id:I(name),mode,zones,condition,mandatory});eventHandlers.set(type,list);if(list.length===1)E.on(type,(e,v)=>{for(const h of eventHandlers.get(type))for(const p of [0,1])for(const f of e.refs(p,h.zones))if(f.card.id===h.id&&(!['monsters','extraMonster','spells','fieldSpell'].includes(f.zone)||active(e,f.card))&&h.condition(e,v,f))e.addTrigger(f.card.uid,h.id+'::'+h.mode,v,{owner:p,mandatory:h.mandatory});});}
 const api={...X,normal,lowNormal,lvNext,evolution,event};root.Duel2004=api;
 if(typeof module!=='undefined'){module.exports=api;for(const s of ['monsters','spells','traps'])require('./effects-2004-'+s+'.js');}
})(globalThis);
