/* ZEXAL launch: actual overlays, Wind-Up resets and Inzektor equipment. */
(function(root){
 'use strict';const X=root.DuelChronicle,{D,E,H,C,I,is,A,Q,passive,mark,allM,allS,allF,monster,ownM,foeM,hand,deck,grave,first,args,self,src,active,field,has,extend,g,choose,target,moved,destroy,pay,once,onEntry,onFlip,onEnd,onStandby,onDamage,onBattleWin,revive,search,specialChoice,series,guard,defer,card,def,arch,names,gy,fromField,destroyed,discarded,noHand,effect,cast,watch,entrySearch,entryReturn,sent,sentRecruit,sentSearch,specialSelf,summonCost,aura,ownAura,protect,quickNegate,lock,locked,negateMonster,blackwing,koaki,morph,fabled,naturia,genex,worm,infernity,saber,ice,dragunity,coreMaintain,watt,scrap,karakuri,laval,gusto,gem,gishki,vylon,nordic,battleGY,steelswarm,meklord}=X,{CARDS}=D;
 const tg=arch('T.G.'),windup=arch('Wind-Up'),inzektor=arch('Inzektor'),photon=arch('Photon'),evoltile=arch('Evoltile'),evolsaur=arch('Evolsaur'),ninja=arch('Ninja'),constellar=arch('Constellar'),lswarm=arch('lswarm'),aqua=(e,m)=>['鱼族','海龙族','水族'].includes(e.race(m));
 function faceOnce(name,pool,resolve,s={}){return effect(name,pool,resolve,{once:{key:'face-effect',scope:'card',duel:true},...s});}
 for(const n of ['T.G. Warwolf','T.G. Striker','T.G. Rush Rhino','T.G. Cyber Magician'])onEnd(n,{condition:(e,c)=>card(e,c.uid)?.earlySent?.turn===e.state.turn&&['battle','destroy'].includes(card(e,c.uid)?.earlySent?.kind),resolve:(e,c)=>search(e,c,deck(e,c.owner,m=>tg(m)&&m.id!==c.sourceId))},{zones:['grave'],both:true});
 specialSelf('T.G. Striker',(e,c)=>!ownM(e,c).length&&foeM(e,c).length>0);watch('T.G. Warwolf','era-special','summon',(e,v)=>!['normal','flip','set'].includes(v.kind)&&CARDS[v.id].level<=4,{resolve:(e,c)=>revive(e,c,c.uid)},{zones:['hand']});passive('T.G. Rush Rhino',{battleStat:(e,s,m,k,a)=>k==='atk'&&s.card.uid===m.uid&&a.uid===m.uid?400:0});sent('T.G. Jet Falcon',(e,c)=>X.burn(e,c,500),(e,v)=>v.kind==='synchro-material');effect('T.G. Catapult Dragon',null,(e,c)=>specialChoice(e,c,hand(e,c.owner,m=>tg(m)&&e.isTuner(m)&&e.level(m)<=3)),{summons:true});
 for(const n of ['Inzektor Centipede','Inzektor Dragonfly','Inzektor Hornet','Inzektor Ant'])effect(n,(e,c)=>H.cards(e,c.owner,['hand','grave'],m=>inzektor(m)&&monster(m)),(e,c)=>{if(self(e,c))e.equipMonster(first(c),c.uid,c.owner,c.source);},{mode:'era-equip',role:'own-boost'});
 for(const n of ['Inzektor Centipede','Inzektor Dragonfly'])watch(n,'era-equip-sent','move',(e,v,f)=>v.from==='spells'&&v.to==='grave'&&v.previous.equipTarget===f.card.uid,{resolve:(e,c)=>{if(n==='Inzektor Centipede')search(e,c,deck(e,c.owner,inzektor));else specialChoice(e,c,deck(e,c.owner,m=>inzektor(m)&&m.id!==c.sourceId),{shuffle:true});}});
 effect('Inzektor Hornet',allF,(e,c)=>destroy(e,c,args(c)),{zones:['spells'],condition:(e,c)=>!!card(e,c.uid)?.equipTarget,cost:(e,c)=>H.sendCost(e,c,[c.uid]),oncePerTurn:false});
 for(const n of ['Inzektor Giga-Mantis','Inzektor Giga-Weevil']){effect(n,(e,c)=>ownM(e,c).filter(m=>m.faceUp&&inzektor(m)),(e,c)=>e.equipMonster(c.uid,first(c),c.owner,c.source),{zones:['hand'],oncePerTurn:false,role:'own-boost'});sent(n,(e,c)=>revive(e,c,first(c)),(e,v)=>v.to==='grave'&&v.from==='spells'&&!!v.previous.equipTarget,{once:H.once('giga-revive'),inputs:target('选择甲虫装机复活',(e,c)=>grave(e,c.owner,m=>inzektor(m)&&(n==='Inzektor Giga-Weevil'||m.id!==c.sourceId)),'special')});}
 for(const n of ['Inzektor Hornet','Inzektor Ant'])aura(n,(e,m,s)=>s.card.equipTarget===m.uid,(e,m,s,k)=>def(s.card)[k]||0,['atk','def']);aura('Inzektor Giga-Mantis',(e,m,s)=>s.card.equipTarget===m.uid,(e,m)=>2400-e.originalAttack(m));aura('Inzektor Giga-Weevil',(e,m,s)=>s.card.equipTarget===m.uid,(e,m)=>2600-e.originalDefense(m),['def']);passive('Inzektor Ant',{protect:(e,s,m)=>s.card.equipTarget===m.uid&&e.destroy(s.card.uid,src(e,s.card))});
 extend('level',function(prior,m){const n=prior.call(this,m);return n>0?n+this.activeEquip(m).filter(q=>['Inzektor Centipede','Inzektor Dragonfly','Inzektor Hornet','Inzektor Ant'].some(name=>is(q,name))).length*3:n;});
 for(const [n,l,a] of [['Wind-Up Dog',2,600],['Wind-Up Soldier',1,400]])faceOnce(n,null,(e,c)=>{const m=self(e,c);if(m){m.levelOverride={value:e.level(m)+l,until:e.state.turn};e.modify(m.uid,'atk','add',a,e.state.turn,c.source);}});
 faceOnce('Wind-Up Snail',e=>allF(e).filter(m=>!m.faceUp),(e,c)=>moved(e,c,args(c),'hand','effect-return'));faceOnce('Wind-Up Kitten',foeM,(e,c)=>moved(e,c,args(c),'hand','effect-return'));faceOnce('Wind-Up Warrior',(e,c)=>ownM(e,c).filter(m=>m.faceUp&&windup(m)),(e,c)=>{const m=card(e,first(c));if(m){m.levelOverride={value:e.level(m)+1,until:e.state.turn};e.modify(m.uid,'atk','add',600,e.state.turn,c.source);}},{role:'own-boost'});
 watch('Wind-Up Magician','era-recruit','era-activation',(e,v,f)=>v.id!==f.card.id&&windup({id:v.id}),{once:{key:'face-effect',scope:'card',duel:true},resolve:(e,c)=>specialChoice(e,c,deck(e,c.owner,m=>windup(m)&&e.level(m)<=4),{shuffle:true,position:'defense'})});
 for(const n of ['Wind-Up Rat','Wind-Up Bat'])faceOnce(n,(e,c)=>grave(e,c.owner,windup),(e,c)=>{if(e.setPosition(c.uid,'defense',c.source)){if(n==='Wind-Up Rat')revive(e,c,first(c),{position:'defense'});else moved(e,c,args(c),'hand','effect-return');}},{condition:(e,c)=>self(e,c)?.position==='attack',role:n==='Wind-Up Rat'?'special':'search',summons:n==='Wind-Up Rat'});
 faceOnce('Wind-Up Hunter',null,(e,c)=>X.randomDiscard(e,1-c.owner,1,c.source),{inputs:(e,c)=>[g(e,c,'cost','选择另一只发条解放',ownM(e,c).filter(m=>m.faceUp&&windup(m)&&m.id!==c.sourceId),1,1,'cost')],cost:(e,c)=>X.tribute(e,c,args(c,'cost'))});watch('Wind-Up Juggler','era-destroy','damage-end',(e,v,f)=>[v.attack.uid,v.attack.target].includes(f.card.uid),{once:{key:'face-effect',scope:'card',duel:true},resolve:(e,c)=>destroy(e,c,[c.event.attack.uid===c.uid?c.event.attack.target:c.event.attack.uid])});Q('Wind-Up Knight','era-negate',{main:false,once:{key:'face-effect',scope:'card',duel:true},condition:(e,c)=>card(e,c.event.window?.attack?.target)&&windup(card(e,c.event.window.attack.target)),resolve:e=>e.negateAttack(),aiResponse:()=>1000});sentRecruit('Wind-Up Honeybee',(e,m)=>windup(m)&&e.level(m)<=4,battleGY);
 C('The Supremacy Sun').specialOnly='supremacy';onStandby('The Supremacy Sun',{condition:(e,c)=>card(e,c.uid)?.earlySent?.turn===e.state.turn-1,inputs:(e,c)=>[g(e,c,'cost','选择手牌丢弃',hand(e,c.owner),1,1,'cost')],cost:(e,c)=>H.discard(e,c,args(c,'cost')),resolve:(e,c)=>revive(e,c,c.uid,{via:'supremacy'})},{both:true,grave:true});
 for(const [n,gain] of [['Meklord Army of Granel',100],['Meklord Army of Wisel',100],['Meklord Army of Skiel',200]])ownAura(n,(e,m)=>allM(e).filter(q=>q.uid!==m.uid&&meklord(q)).length*gain);onEntry('Meklord Army of Granel','era-half',{inputs:target('选择弱化的对方怪兽',(e,c)=>foeM(e,c).filter(m=>m.faceUp)),resolve:(e,c)=>e.modify(first(c),'atk','mul',.5,e.state.turn,c.source)},['normal']);sentRecruit('Meklord Army of Skiel',(e,m)=>series(m,'Meklord Army'),battleGY);passive('Meklord Army of Wisel',{piercing:(e,s,m)=>e.find(m.uid)?.owner===s.owner&&m.uid!==s.card.uid&&meklord(m)});
 protect('Morphtronic Staplen',(e,m,s,b)=>b&&m.position==='defense');watch('Morphtronic Staplen','era-position','damage-end',(e,v,f)=>v.attack.target===f.card.uid&&f.card.position==='defense',{inputs:target('选择对方攻击表示怪兽',(e,c)=>foeM(e,c).filter(m=>m.faceUp&&m.position==='attack')),resolve:(e,c)=>{e.setPosition(first(c),'defense',c.source);e.setPosition(c.uid,'attack',c.source);}});
 watch('Blackwing - Hillen the Tengu-wind','era-revive','damage',(e,v,f)=>v.owner===f.owner&&v.battle&&!v.attack?.target&&v.amount>=2000,{once:{key:'hillen',scope:'name',duel:true},inputs:target('选择3星以下黑羽',(e,c)=>grave(e,c.owner,m=>blackwing(m)&&e.level(m)<=3),'special'),resolve:(e,c)=>{revive(e,c,c.uid,{negated:true});revive(e,c,first(c),{negated:true});}},{zones:['grave']});
 effect('Mystic Piper',null,(e,c)=>{const list=e.draw(c.owner,1)||[];e.revealCards(1-c.owner,list,'神秘吹笛人');if(list[0]&&monster(list[0])&&e.level(list[0])===1)e.draw(c.owner,1);},{once:H.once('piper'),cost:(e,c)=>X.tribute(e,c,[c.uid])});specialSelf('Unknown Synchron',(e,c)=>!ownM(e,c).length&&foeM(e,c).length>0);E.get(I('Unknown Synchron')+'::gx-special').once={key:'unknown',scope:'name',duel:true};
 watch('Aurora Paragon','era-destroy','summon',(e,v,f)=>v.uid!==f.card.uid&&v.kind==='normal',{resolve:(e,c)=>destroy(e,c,[c.uid])},{mandatory:true});effect('Tradetoad',(e,c)=>grave(e,c.owner,X.frog),(e,c)=>revive(e,c,first(c)),{inputs:(e,c)=>[g(e,c,'cost','选择水族解放',ownM(e,c).filter(m=>e.race(m)==='水族'),1,1,'cost'),g(e,c,'target','选择青蛙复活',grave(e,c.owner,X.frog),1,1,'special')],cost:(e,c)=>X.tribute(e,c,args(c,'cost')),summons:true});
 effect('Karakuri Komachi mdl 224 "Ninishi"',null,(e,c)=>{e.state.normalUsed=false;lock(e,c.owner,'normalSeries','Karakuri');},{once:H.once('ninishi'),condition:e=>e.state.normalUsed});onEntry('Karakuri Ninja mdl 7749 "Nanashick"','era-draw',{resolve:(e,c)=>e.draw(c.owner,ownM(e,c).filter(m=>m.faceUp&&m.position==='defense'&&karakuri(m)).length)},['normal']);for(const n of ['Karakuri Komachi mdl 224 "Ninishi"','Karakuri Ninja mdl 7749 "Nanashick"','Karakuri Muso mdl 818 "Haipa"','Karakuri Barrel mdl 96 "Shinkuro"'])watch(n,'era-defense','attack',(e,v,f)=>v.target===f.card.uid,{resolve:(e,c)=>{const m=self(e,c);if(m)e.setPosition(c.uid,m.position==='attack'?'defense':'attack',c.source);}},{mandatory:true});
 onEntry('Hushed Psychic Cleric','era-defense',{resolve:(e,c)=>e.setPosition(c.uid,'defense',c.source)},['normal','flip']);effect('Hushed Psychic Cleric',(e,c)=>grave(e,c.owner,m=>e.race(m)==='念动力族'),(e,c)=>{const m=card(e,first(c));if(m){moved(e,c,[m.uid],'banished','effect-banish');if(self(e,c))(self(e,c).eraPsychic||=[]).push(m.uid);}},{send:(e,c)=>hand(e,c.owner),role:'special'});
 onEntry('Silent Psychic Wizard','era-banish',{inputs:target('选择念动力族除外',(e,c)=>grave(e,c.owner,m=>e.race(m)==='念动力族'),'special'),resolve:(e,c)=>{const m=card(e,first(c));if(m){moved(e,c,[m.uid],'banished','effect-banish');if(self(e,c))self(e,c).eraPsychic=[m.uid];}}},['normal']);for(const n of ['Hushed Psychic Cleric','Silent Psychic Wizard'])sent(n,(e,c)=>specialChoice(e,c,(c.event.previous.eraPsychic||[]).map(uid=>card(e,uid)).filter(m=>m&&e.find(m.uid)?.zone==='banished')));
 onEntry('Mental Seeker','era-look',{condition:(e,c)=>c.event.from==='banished',resolve:(e,c)=>{const list=deck(e,1-c.owner).slice(0,3);e.revealCards(c.owner,list,'查看对方卡组顶三张');choose(e,c,'选择除外的一张',list,1,1,'early-move',{to:'banished',kind:'effect-banish',shuffle:true,role:'destroy'});}},['special']);
 specialSelf('Meklord Astro Dragon Asterisk',(e,c)=>ownM(e,c).filter(meklord).length>=3,{only:true});onEntry('Meklord Astro Dragon Asterisk','era-send',{inputs:(e,c)=>[g(e,c,'target','选择自己其他机皇送墓',ownM(e,c).filter(m=>m.uid!==c.uid&&meklord(m)),1,5,'cost')],resolve:(e,c)=>{const n=args(c).reduce((n,uid)=>n+(def(card(e,uid)).atk||0),0);moved(e,c,args(c),'grave','effect-send');if(self(e,c))e.modify(c.uid,'atk','set',n,null,c.source);}},['special']);watch('Meklord Astro Dragon Asterisk','era-burn','summon',(e,v)=>v.kind==='synchro',{resolve:(e,c)=>e.damage(c.event.owner,1000,'效果')},{mandatory:true});
 effect('Force Resonator',(e,c)=>ownM(e,c).filter(m=>m.faceUp),(e,c)=>{if(card(e,first(c)))card(e,first(c)).eraAttackSeal=e.state.turn;},{cost:(e,c)=>H.sendCost(e,c,[c.uid]),role:'own-boost'});onEntry('Salvage Warrior','era-special',{condition:(e,c)=>c.event.materials.length>0,resolve:(e,c)=>specialChoice(e,c,H.cards(e,c.owner,['hand','grave'],m=>e.isTuner(m)))},['normal']);watch('Blackwing - Kogarashi the Wanderer','era-special','move',(e,v,f)=>v.owner===f.owner&&v.to==='grave'&&v.kind==='destroy'&&v.previous.faceUp&&blackwing({id:v.id}),{resolve:(e,c)=>revive(e,c,c.uid)},{zones:['hand']});
 C('Gladiator Beast Tygerius').cannotFusionMaterial=true;X.gladEntry('Gladiator Beast Tygerius',{inputs:(e,c)=>[g(e,c,'cost','选择剑斗兽卡丢弃',hand(e,c.owner,X.gladiator),1,1,'cost')],cost:(e,c)=>H.discard(e,c,args(c,'cost')),resolve:(e,c)=>search(e,c,deck(e,c.owner,m=>X.gladiator(m)&&monster(m)))});specialSelf('Elder of the Six Samurai',(e,c)=>!ownM(e,c).length&&foeM(e,c).length>0);
 X.union('Buster Blaster',D.CARD_LIST.filter(monster).map(c=>c.officialName),{stat:{atk:-500,def:-500},effectProtect:true});watch('Buster Blaster','era-destroy','battle-win',(e,v,f)=>v.uid===f.card.equipTarget,{resolve:(e,c)=>destroy(e,c,allM(e).filter(m=>m.faceUp&&e.race(m)===CARDS[c.event.victim.id].race).map(m=>m.uid))},{zones:['spells']});
 sent('Morphtronic Lantron',(e,c)=>lock(e,c.owner,'battleZero'),(e,v)=>battleGY(e,v)&&v.previous.position==='defense');protect('Clock Resonator',(e,m,s,b)=>{if(m.position!=='defense'||m.eraProtectTurn===e.state.turn)return false;m.eraProtectTurn=e.state.turn;return true;});effect('Necro Defender',ownM,(e,c)=>{const m=card(e,first(c));if(m){m.eraBattleProtectedUntil=e.state.turn+1;m.eraNoBattleDamage=e.state.turn+1;}},{zones:['grave'],cost:(e,c)=>moved(e,c,[c.uid],'banished','cost-banish'),role:'own-boost'});
 specialSelf('Junk Servant',(e,c)=>ownM(e,c).some(arch('Junk')));watch('Jar Turtle','era-draw','era-activation',(e,v)=>is({id:v.id},'Jar of Greed'),{resolve:(e,c)=>e.draw(c.owner,1)});onEntry('Scrap Kong','era-destroy',{resolve:(e,c)=>destroy(e,c,[c.uid])},['normal']);sent('Scrap Kong',(e,c)=>search(e,c,grave(e,c.owner,m=>scrap(m)&&m.id!==c.sourceId)),(e,v)=>v.to==='grave'&&v.kind==='destroy'&&series({id:v.source?.id},'Scrap'));
 onEntry("Shien's Advisor",'era-race',{condition:(e,c)=>ownM(e,c).some(X.six),inputs:(e,c)=>[H.customGroup('race','宣言种族',X.races.map(r=>({uid:r,label:r,value:1})))],resolve:(e,c)=>{if(self(e,c))self(e,c).eraProhibitedRace=first(c,'race');}},['normal']);
 sent('Serene Psychic Witch',(e,c)=>choose(e,c,'选择念动力族暂时除外',deck(e,c.owner,m=>e.race(m)==='念动力族'&&def(m).atk<=2000),1,1,'era-psychic-witch',{sourceUid:c.uid,role:'special'}),destroyed);E.op('era-psychic-witch',(e,t)=>{const m=card(e,t.picks[0]),c={owner:t.owner,source:t.context.source};if(m){moved(e,c,[m.uid],'banished','effect-banish');defer(e,c,'standby',e.state.turn+1,'era-psychic-return',{uid:m.uid,sourceUid:t.context.sourceUid,anyOwner:true});e.shuffle(e.state.players[t.owner].deck);}});E.op('era-psychic-return',(e,t)=>{if(e.find(t.context.sourceUid)?.zone==='grave')revive(e,{owner:t.owner,source:t.context.source},t.context.uid);});
 onEntry('Esper Girl','era-banish',{condition:(e,c)=>c.event.from==='banished',resolve:(e,c)=>{const m=deck(e,c.owner)[0];if(m){moved(e,c,[m.uid],'banished','effect-banish');m.faceUp=false;if(self(e,c))self(e,c).eraEsper=m.uid;}}},['special']);sent('Esper Girl',(e,c)=>{if(e.find(c.event.previous.eraEsper)?.zone==='banished')moved(e,c,[c.event.previous.eraEsper],'hand','effect-return');});
 protect('Metaion, the Timelord',()=>true);guard('special','Metaion, the Timelord',(e,p,m)=>e.find(m.uid)?.zone!=='deck');watch('Metaion, the Timelord','era-bounce','battle-end',(e,v,f)=>f.card.yearBattledTurn===e.state.turn||f.card.attacksMade>0,{resolve:(e,c)=>{const list=allM(e).filter(m=>m.uid!==c.uid);moved(e,c,list.map(m=>m.uid),'hand','effect-return');X.burn(e,c,list.length*300);}});onStandby('Metaion, the Timelord',{resolve:(e,c)=>{moved(e,c,[c.uid],'deck','effect-return');e.shuffle(e.state.players[c.owner].deck);}},{optional:false});
 effect('Samurai Sword Baron',(e,c)=>foeM(e,c).filter(m=>m.position==='defense'),(e,c)=>e.setPosition(first(c),'attack',c.source));onEntry('Sorciere de Fleur','era-revive',{once:H.once('sorciere'),inputs:target('选择对方墓地怪兽',(e,c)=>grave(e,1-c.owner,monster),'special'),resolve:(e,c)=>{const m=revive(e,c,first(c));if(m){m.eraCannotDirect=e.state.turn;X.delayMove(e,c,m,'destroy');}}},['normal','special']);sent('Blue Rose Dragon',(e,c)=>specialChoice(e,c,grave(e,c.owner,m=>is(m,'Black Rose Dragon')||e.race(m)==='植物族')),destroyed);sentRecruit('Necro Fleur',(e,m)=>is(m,'Sorciere de Fleur'),(e,v)=>v.to==='grave'&&v.kind==='destroy');
 for(const [n,base,zones] of [['Malefic Rainbow Dragon','Rainbow Dragon',['hand','deck']],['Malefic Cyber End Dragon','Cyber End Dragon',['extra']]])summonCost(n,(e,c)=>H.cards(e,c.owner,zones,names(base)),1,{only:true,banish:true});mark('Malefic Parallel Gear');
 specialSelf('Machina Cannon',()=>true,{only:true});const cannon=E.get(I('Machina Cannon')+'::gx-special');cannon.inputs=(e,c)=>[g(e,c,'cost','选择其他机械族手牌送墓',hand(e,c.owner,m=>m.uid!==c.uid&&e.race(m)==='机械族'),1,hand(e,c.owner).length,'cost')];cannon.cost=(e,c)=>{c.eraCount=args(c,'cost').length;H.sendCost(e,c,args(c,'cost'));};cannon.resolve=(e,c)=>{const m=revive(e,c,c.uid,{via:'year-special:'+c.sourceId});if(m)e.modify(m.uid,'atk','add',c.eraCount*800,null,c.source);};
 specialSelf('Fallen Angel of Roses',()=>true);const rose=E.get(I('Fallen Angel of Roses')+'::gx-special');rose.inputs=(e,c)=>[g(e,c,'cost','选择其他植物返回手牌',ownM(e,c).filter(m=>m.id!==c.sourceId&&e.race(m)==='植物族'),1,1,'cost')];rose.cost=(e,c)=>moved(e,c,args(c,'cost'),'hand','cost-return');rose.resolve=(e,c)=>revive(e,c,c.uid,{banishOnLeave:true});specialSelf('Junk Forward',(e,c)=>!ownM(e,c).length);
 effect('Key Man the Key Warrior',null,(e,c)=>{if(self(e,c))self(e,c).levelOverride={value:3,until:e.state.turn};});watch('Ganbara Knight','era-defense','attack',(e,v,f)=>v.target===f.card.uid&&f.card.position==='attack',{resolve:(e,c)=>e.setPosition(c.uid,'defense',c.source)});onEntry('Feedback Warrior','era-level',{inputs:target('选择3星化的怪兽',(e,c)=>ownM(e,c).filter(m=>m.faceUp),'own-boost'),resolve:(e,c)=>{if(card(e,first(c)))card(e,first(c)).levelOverride={value:3};}},['normal','special']);ownAura('Tenshin',(e,m,s)=>e.monsters(s.owner).filter(q=>q.faceUp&&e.level(q)===2).length*400);
 sent('Speed Bird',(e,c)=>{for(const uid of args(c))revive(e,c,uid,{negated:true});},battleGY,{inputs:target('选择两只2星怪兽',(e,c)=>grave(e,c.owner,m=>monster(m)&&e.level(m)===2),'special',2,2)});mark('Shine Knight');watch('Zubaba Knight','era-destroy','damage-start',(e,v,f)=>v.attack.uid===f.card.uid&&card(e,v.attack.target)?.faceUp&&card(e,v.attack.target).position==='defense',{resolve:(e,c)=>destroy(e,c,[c.event.attack.target])});
 specialSelf('Endless Decay',(e,c)=>e.state.players[c.owner].lp<=2000);onEntry('Endless Decay','era-atk',{resolve:(e,c)=>e.modify(c.uid,'atk','set',Math.floor(e.state.players[1-c.owner].lp/2),null,c.source)},['normal','special']);sent('Infernity Knight',(e,c)=>revive(e,c,c.uid),destroyed,{inputs:(e,c)=>[g(e,c,'cost','选择两张手牌丢弃',hand(e,c.owner),2,2,'cost')],cost:(e,c)=>H.discard(e,c,args(c,'cost'))});specialSelf('Sephylon, the Ultimate Timelord',(e,c)=>grave(e,c.owner,monster).length>=10,{only:true});effect('Sephylon, the Ultimate Timelord',(e,c)=>H.cards(e,c.owner,['hand','grave'],m=>e.race(m)==='天使族'&&e.level(m)>=8),(e,c)=>{const m=revive(e,c,first(c),{negated:true});if(m)e.modify(m.uid,'atk','set',4000,null,c.source);},{summons:true,role:'special'});
 Object.assign(X,{tg,windup,inzektor,photon,evoltile,evolsaur,ninja,constellar,lswarm,aqua,faceOnce});
 if(typeof module!=='undefined'){module.exports=X;for(const part of ['monsters','extra','spells','traps'])require('./effects-2011-'+part+'.js');}
})(globalThis);
