(function(root){
 'use strict';
 const X=root.Duel2004,{E,D,H,C,I,is,mark,A,Q,R,allM,allS,monster,face,ownM,foeM,g,first,args,hand,deck,grave,pay,src,active,ctx,extend,rule,field,has,guard,revive,recruit,token,cp,normal}=X,{CARDS}=D;
 const hero=m=>!!m&&(CARDS[m.id].elemental||CARDS[m.id].officialName.startsWith('Elemental HERO'));
 const darkWorld=m=>!!m&&CARDS[m.id].officialName.includes('Dark World'),gear=m=>!!m&&CARDS[m.id].officialName.startsWith('Ancient Gear'),machina=m=>!!m&&CARDS[m.id].officialName.startsWith('Machina '),batteryman=m=>!!m&&CARDS[m.id].officialName.startsWith('Batteryman');
 D.families.darkworld='暗黑界';D.families.ancientgear='古代机械';D.families.machina='机甲';D.families.charmer='灵使';D.families.batteryman='电池人';
 for(const c of D.CARD_LIST){if(hero(c)){c.elemental=true;c.families=[...new Set([...(c.families||[]),'hero'])];}for(const [family,match] of [['darkworld',darkWorld(c)],['ancientgear',gear(c)],['machina',machina(c)],['batteryman',batteryman(c)],['charmer',/Charmer|Familiar-Possessed/.test(c.officialName)]])if(match)c.families=[...new Set([...(c.families||[]),family])];}
 for(const c of D.CARD_LIST.filter(c=>c.releaseYear===2005&&c.type==='fusion')){if(/Must be Fusion Summoned/.test(c.originalDescription))c.fusionOnly=true;if(/only be (?:done|conducted) with the above/.test(c.originalDescription))c.fusionExact=true;}
 token('2005-fluff-token','绵毛衍生物','Fluff Token',1,0,0,'风','植物族');token('2005-phantasm-token','幻魔衍生物','Phantasm Token',1,1000,1000,'暗','恶魔族');token('2005-block-token','积木衍生物','Block Token',4,1000,1500,'地','岩石族');
 const multi=m=>is(m,'Elemental Mistress Doriado')||is(m,'Elemental HERO Electrum');
 const P=root.ModernDuelEngine.prototype;P.attributes=function(m){return multi(m)&&m.faceUp&&field(this.find(m.uid)?.zone)&&!this.negated(m)?[...new Set([this.attribute(m),'风','水','炎','地'])]:[this.attribute(m)];};P.hasAttribute=function(m,a){return this.attributes(m).includes(a);};
 extend('describe',function(prior,m,...a){return {...prior.call(this,m,...a),originalAtk:this.originalAttack(m),originalDef:this.originalDefense(m),counters:m.counters||0};});
 extend('unaffected',function(prior,m,s){if(prior.call(this,m,s))return true;if(!s||!active(this,m))return false;const r=CARDS[m.id].earlyRules||{},kind=s.effectType||CARDS[s.id]?.type;if(kind==='trap'&&r.trapImmune)return true;if(kind==='monster'&&this.activeEquip(m).some(q=>is(q,'Lone Wolf'))&&s.owner!==this.find(m.uid).owner)return true;return false;});
 extend('activeSpell',function(prior,m){if(!prior.call(this,m))return false;const suppressed=this.rawEarly('Skill Drain').length>0;if(!suppressed&&this.rawEarly('Silent Swordsman LV7').length&&CARDS[m.id].type==='spell')return false;if(!suppressed&&(CARDS[m.id].spellKind==='continuous'||CARDS[m.id].trapKind==='continuous')&&this.rawEarly('Silent Insect').length)return false;return true;});
 extend('earlyNegatesLink',function(prior,l,probe=false){if(l.source.effectType==='spell'&&has(this,'Silent Swordsman LV7'))return true;const f=this.find(l.uid);if(has(this,'Cyber Blader',1-l.owner)&&this.monsters(l.owner).length===3&&f&&['monsters','extraMonster','spells','fieldSpell'].includes(f.zone))return true;return prior.call(this,l,probe);});
 extend('earlyCanUse',function(prior,c,a){if(!prior.call(this,c,a))return false;const d=CARDS[c.sourceId],battle=this.state.frame?.attack,attacker=this.find(battle?.uid)?.card,last=c.event.window?.chainLast;
  if(d.type==='spell'&&this.monsters(1-c.owner).some(m=>active(this,m)&&is(m,'Mechanical Hound')&&!hand(this,1-c.owner).length))return false;
  if(a.cardActivation&&['spell','trap'].includes(d.type)&&battle?.owner!==c.owner&&attacker&&active(this,attacker)&&CARDS[attacker.id].earlyRules?.gearAttackSeal)return false;
  if(a.cardActivation&&['spell','trap'].includes(d.type)&&last?.key===I('Uria, Lord of Searing Flames')+'::destroy')return false;
  if(d.type==='trap'&&this.state.phase==='battle'&&this.state.gearCannonTurn===this.state.turn)return false;
  if(a.cardActivation&&this.find(c.uid)?.card.activationLockedUntil>=this.state.turn)return false;return true;
 });
 extend('canNormal',function(prior,m,p=this.state.active){return prior.call(this,m,p)&&!has(this,'Boss Rush',p)&&!this.monsters(1-p).some(s=>active(this,s)&&s.tualatinAttribute&&this.hasAttribute(m,s.tualatinAttribute));});
 extend('canSpecial',function(prior,p,m,o={}){return prior.call(this,p,m,o)&&!(o.via==='fusion'&&has(this,'Non-Fusion Area'))&&!this.monsters(1-p).some(s=>active(this,s)&&s.tualatinAttribute&&this.hasAttribute(m,s.tualatinAttribute))&&!(this.state.players[p].darkWorldGateTurn===this.state.turn&&o.via!=='dark-world-gate');});
 extend('canTribute',function(prior,m,p=this.state.active,kind='effect'){return prior.call(this,m,p,kind)&&!(active(this,m)&&is(m,'Summoner Monk'))&&!(kind==='normal'&&m.tributeSummonLockedTurn===this.state.turn);});
 extend('canAttack',function(prior,m,p=this.state.active,t=null){if(!prior.call(this,m,p,t))return false;const target=this.find(t)?.card;if(target){const enemy=this.monsters(1-p).filter(x=>active(this,x));if(!target.faceUp&&enemy.some(x=>is(x,'Hieracosphinx')))return false;if(is(target,'Grave Ohja')&&this.monsters(1-p).some(x=>!x.faceUp))return false;if(is(target,'Arcane Archer of the Forest')&&this.monsters(1-p).some(x=>x.faceUp&&this.race(x)==='植物族'))return false;if(machina(target)&&!is(target,'Machina Sniper')&&enemy.some(x=>is(x,'Machina Sniper')))return false;if(enemy.some(x=>is(x,'Hamon, Lord of Striking Thunder')&&x.position==='defense'&&x.uid!==target.uid))return false;if(this.activeEquip(target).some(q=>is(q,'Hero Ring')&&this.attackValue(m)>=1900))return false;}return true;});
 extend('damage',function(prior,p,n,k,...a){const battle=this.state.frame?.attack,mine=[this.find(battle?.uid),this.find(battle?.target)].find(f=>f?.owner===p);if(k!=='战斗'&&has(this,'Des Wombat',p))return;if(k==='战斗'&&(this.state.players[p].wingedProtectionTurn===this.state.turn||mine&&is(mine.card,'Monk Fighter')&&!this.negated(mine.card)))return;if(k==='战斗'&&battle?.dimensionWallOwner===p)return prior.call(this,1-p,n,k,...a);if(k!=='战斗'&&this.state.resolvingLink?.damagePrevented)return;return prior.call(this,p,n,k,...a);});
 extend('stat',function(prior,m,k,b){let n=prior.call(this,m,k,b);if(!m||!m.faceUp||!field(this.find(m.uid)?.zone))return n;if(k==='atk'&&has(this,'Water Dragon')&&(this.hasAttribute(m,'炎')||this.race(m)==='炎族'))n=0;for(const s of allM(this))if(s.uid!==m.uid&&active(this,s)&&is(s,'The Wicked Dreadroot'))n=Math.floor(n/2);return n;});
 extend('attackAllowance',function(prior,m){const n=prior.call(this,m);return m.doubleAttackTurn===this.state.turn?Math.max(2,n):n;});
 extend('cardNameId',function(prior,m,...a){if(field(this.find(m.uid)?.zone)&&!this.negated(m)){if(is(m,'Proto-Cyber Dragon'))return 'cyber-dragon';if(is(m,'Elemental HERO Neo Bubbleman'))return I('Elemental HERO Bubbleman');}return prior.call(this,m,...a);});
 extend('continuousMaintenance',function(prior,...a){const r=prior.call(this,...a);if(has(this,'Level Limit - Area A'))for(const m of allM(this))if(m.faceUp&&this.level(m)<=3&&CARDS[m.id].type!=='link')m.position='attack';return r;});
 extend('move',function(prior,uid,dest,o={}){if(dest==='grave'&&o.kind==='effect-ritual-tribute'&&has(this,'Samsara')){const r=prior.call(this,uid,'deck',o);this.shuffle(this.state.players[r.owner].deck);return r;}return prior.call(this,uid,dest,o);});
 function contact(name,materials){const via='contact:'+I(name);C(name).specialOnly=via;C(name).fusionExact=true;mark(name);A(materials[0],'contact-'+I(name),{label:C(name).name,inherent:true,summons:true,condition:(e,c)=>e.state.players[c.owner].extra.some(m=>is(m,name))&&materials.every(n=>ownM(e,c).some(m=>m.faceUp&&is(m,n))),inputs:(e,c)=>materials.map((n,i)=>g(e,c,'material'+i,'选择接触融合素材',ownM(e,c).filter(m=>m.faceUp&&is(m,n)),1,1,'cost')),cost:(e,c)=>X.moved(e,c,materials.flatMap((n,i)=>args(c,'material'+i)),'banished','cost-banish'),resolve:(e,c)=>{const m=e.state.players[c.owner].extra.find(m=>is(m,name));if(m)revive(e,c,m.uid,{via});},aiScore:1400});}
 contact('VW-Tiger Catapult',['V-Tiger Jet','W-Wing Catapult']);contact('VWXYZ-Dragon Catapult Cannon',['VW-Tiger Catapult','XYZ-Dragon Cannon']);
 const api={...X,hero,darkWorld,gear,machina,batteryman,contact};root.Duel2005=api;
 if(typeof module!=='undefined'){module.exports=api;for(const s of ['monsters','monsters-extra','spells','traps'])require('./effects-2005-'+s+'.js');}
})(globalThis);
