/* GX archetypes: Crystal Beast zones, Gladiator tag-outs, Gemini and graveyard engines. */
(function(root){
 'use strict';
 const X=root.Duel2006,{E,D,H,C,I,is,mark,A,Q,R,S,T,passive,allM,allS,allF,monster,face,ownM,foeM,moved,destroy,choose,g,target,pay,once,onEntry,onFlip,onMove,onStandby,onDamage,onBattleWin,src,active,ctx,first,args,self,hand,deck,grave,extend,rule,field,has,guard,onEnd,defer,revive,search,recruit,original,event,hero,destiny,neo,six,alien,crystal,gladiator,series,ignite,ownStat,tributeAction,counterAdd,handSpecial,contactFusion,delayMove,specialChoice,mill}=X,{CARDS}=D;
 const gyBattle=(e,v)=>v.to==='grave'&&v.kind==='battle',gyDestroyed=(e,v)=>v.to==='grave'&&['destroy','battle'].includes(v.kind),cont=m=>CARDS[m.id].spellKind==='continuous'||CARDS[m.id].trapKind==='continuous'||m.crystalSpell;
 function crystalPlace(e,c,uid){const f=e.find(uid),slot=e.state.players[c.owner].spells.indexOf(null);if(!f||slot<0||!crystal(f.card))return false;const m=e.remove(uid).card;m.generation++;m.faceUp=true;m.crystalSpell=true;m.mods=[];e.state.players[c.owner].spells[slot]=m;e.log('effect','宝玉兽置入魔法与陷阱区',c.owner,{uid,cardId:m.id});return true;}
 // Destruction replacement is optional and is chosen before changing zones.
 extend('destroy',function(prior,uid,s=null,b=false,...a){const f=this.find(uid);if(f&&field(f.zone)&&f.card.faceUp&&crystal(f.card)&&this.state.players[f.owner].spells.includes(null)&&!f.card.gxDeclineCrystal&&!this.unaffected(f.card,s)){this.queueChoice(f.owner,'宝玉兽：选择破坏后的去向',[{uid:'crystal',label:'放入魔法与陷阱区',value:20},{uid:'grave',label:'送去墓地',value:0}],1,1,'gx-crystal-replace',{source:s,uid,generation:f.card.generation,owner:f.owner,battle:b});return true;}return prior.call(this,uid,s,b,...a);});
 E.op('gx-crystal-replace',(e,t)=>{const d=t.context,f=e.find(d.uid);if(!f||f.card.generation!==d.generation)return;if(t.picks[0]==='crystal'&&crystalPlace(e,{owner:d.owner,source:d.source},d.uid))return;f.card.gxDeclineCrystal=true;try{e.destroy(d.uid,d.source,d.battle);}finally{delete f.card.gxDeclineCrystal;}});
 extend('move',function(prior,uid,to,o={}){const m=this.find(uid)?.card,r=prior.call(this,uid,to,o);if(m&&r?.to!=='spells')delete m.crystalSpell;return r;});
 for(const c of D.CARD_LIST.filter(c=>crystal(c)&&c.releaseYear===2007&&monster(c)))mark(c.officialName);
 onEntry('Crystal Beast Sapphire Pegasus','place',{inputs:target('选择置入后场的宝玉兽',(e,c)=>H.cards(e,c.owner,['hand','deck','grave'],crystal),'search'),resolve:(e,c)=>{crystalPlace(e,c,first(c));e.shuffle(e.state.players[c.owner].deck);}},['*']);
 onEntry('Crystal Beast Ruby Carbuncle','release',{resolve:(e,c)=>{for(const m of [...e.spells(c.owner)].filter(m=>m.crystalSpell))revive(e,c,m.uid);}},['special']);
 ignite('Crystal Beast Cobalt Eagle',(e,c)=>e.field(c.owner).filter(m=>m.faceUp&&crystal(m)),(e,c)=>e.putOnDeck(first(c),'top',c.source));
 ignite('Crystal Beast Emerald Tortoise',(e,c)=>ownM(e,c).filter(m=>m.attacksMade>0),(e,c)=>e.setPosition(first(c),'defense',c.source));
 guard('direct','Crystal Beast Amethyst Cat',()=>true);passive('Crystal Beast Topaz Tiger',{battleStat:(e,s,m,k,a)=>k==='atk'&&s.card.uid===m.uid&&a.uid===m.uid&&a.target?400:0});
 Q('Crystal Beast Amber Mammoth','intercept',{main:false,condition:(e,c)=>{const a=c.event.window?.attack;return a?.owner!==c.owner&&a?.stage==='declare'&&a.target!==c.uid&&crystal(e.find(a.target)?.card);},resolve:(e,c)=>{const a=e.state.frame?.attack;if(a){a.target=c.uid;a.targetGeneration=self(e,c).generation;}},aiResponse:()=>400});
 for(const [n,spell,required] of [['Zeradias, Herald of Heaven','The Sanctuary in the Sky',true],["Gravekeeper's Commandant",'Necrovalley',false],['Warrior of Atlantis','A Legendary Ocean',false],['Archfiend General','Pandemonium',true],['Harpie Queen',"Harpies' Hunting Ground",false],['Destroyersaurus','Jurassic World',false],['Elemental HERO Captain Gold','Skyscraper',true],['Neo Space Pathfinder','Neo Space',false]]){ignite(n,(e,c)=>H.cards(e,c.owner,n==='Neo Space Pathfinder'?['deck','grave']:['deck'],m=>is(m,spell)),(e,c)=>{moved(e,c,args(c),'hand','effect-search');e.shuffle(e.state.players[c.owner].deck);},{zones:['hand'],cost:(e,c)=>H.discard(e,c,[c.uid]),role:'search',oncePerTurn:false});if(required)guard('effect',n,()=>true);}
 extend('continuousMaintenance',function(prior,...a){const r=prior.call(this,...a);for(const [n,spell] of [['Zeradias, Herald of Heaven','The Sanctuary in the Sky'],['Archfiend General','Pandemonium'],['Elemental HERO Captain Gold','Skyscraper']])for(const m of allM(this).filter(m=>is(m,n)&&active(this,m)))if(!has(this,spell))this.destroy(m.uid,src(this,m));return r;});
 extend('cardNameId',function(prior,m,...a){if(is(m,'Harpie Queen')&&['grave','monsters','extraMonster'].includes(this.find(m.uid)?.zone))return I('Harpie Lady');if(is(m,'Elemental HERO Neos Alius')&&field(this.find(m.uid)?.zone)&&this.geminiActive(m))return I('Elemental HERO Neos');if(is(m,'Neo-Spacian Marine Dolphin'))return I('Neo-Spacian Aqua Dolphin');return prior.call(this,m,...a);});
 onEntry('Raiza the Storm Monarch','top',{condition:(e,c)=>c.event.materials?.length>0,inputs:target('选择放回卡组顶部的卡片',allF),resolve:(e,c)=>e.putOnDeck(first(c),'top',c.source)},['normal']);
 onEntry('Destiny HERO - Disk Commander','draw',{duelOnce:true,once:H.once('disk'),condition:(e,c)=>c.event.from==='grave',resolve:(e,c)=>e.draw(c.owner,2)},['special']);guard('special','Destiny HERO - Disk Commander',(e,p,m)=>e.find(m.uid)?.zone!=='grave'||m.earlySent?.turn!==e.state.turn);
 handSpecial('Destiny HERO - Plasma',()=>true,(e,c)=>ownM(e,c).filter(m=>e.canTribute(m,c.owner)),3,{only:true});ignite('Destiny HERO - Plasma',foeM,(e,c)=>e.equipMonster(first(c),c.uid,c.owner,c.source),{condition:(e,c)=>!e.activeEquip(self(e,c)).some(m=>m.monsterEquip)&&e.state.players[c.owner].spells.includes(null)});ownStat('Destiny HERO - Plasma',(e,m,k)=>k==='atk'?e.activeEquip(m).filter(q=>q.monsterEquip).reduce((n,q)=>n+Math.max(0,CARDS[q.id].atk||0)/2,0):0);
 extend('negated',function(prior,m){return prior.call(this,m)||!!m&&field(this.find(m.uid)?.zone)&&has(this,'Destiny HERO - Plasma',1-this.find(m.uid).owner)&&!is(m,'Destiny HERO - Plasma');});
 handSpecial('Spell Striker',()=>true,(e,c)=>grave(e,c.owner,m=>CARDS[m.id].type==='spell'),1,{banish:true});guard('direct','Spell Striker',()=>true);
 Q('Necro Gardna','protect',{zones:['grave'],condition:(e,c)=>e.state.active!==c.owner,cost:(e,c)=>moved(e,c,[c.uid],'banished','cost-banish'),resolve:(e,c)=>{if(e.state.frame?.attack)e.negateAttack();else e.state.players[c.owner].gxNegateNextAttack=e.state.turn;},aiResponse:(e,c)=>c.event.window?.attack?1000:0,aiScore:-1});E.on('attack',(e,v)=>{const p=e.state.players[1-v.owner];if(p.gxNegateNextAttack===e.state.turn){delete p.gxNegateNextAttack;e.negateAttack();}});
 ignite('Zombie Master',(e,c)=>[0,1].flatMap(p=>grave(e,p,m=>e.race(m)==='不死族'&&e.level(m)<=4)),(e,c)=>{if(self(e,c))revive(e,c,first(c));},{inputs:(e,c)=>[g(e,c,'cost','选择送墓的手牌怪兽',hand(e,c.owner,m=>monster(m)&&H.canSendGY(e,m)),1,1,'cost'),g(e,c,'target','选择复活的不死族',[0,1].flatMap(p=>grave(e,p,m=>e.race(m)==='不死族'&&e.level(m)<=4)),1,1,'special')],cost:(e,c)=>H.sendCost(e,c,args(c,'cost')),summons:true});
 for(const [n,spellOnly] of [['The Wicked Eraser',false],['Sky Scourge Invicil',false],['Diabolos, King of the Abyss',false]]){C(n).noSpecial=true;mark(n);}C('The Wicked Eraser').tributeCount=3;const eraser=(e,m)=>e.field(1-e.find(m.uid).owner).length*1000;original('The Wicked Eraser',eraser,eraser);ignite('The Wicked Eraser',null,(e,c)=>destroy(e,c,[c.uid]),{oncePerTurn:false});onMove('The Wicked Eraser','wipe',{resolve:(e,c)=>destroy(e,c,allF(e).map(m=>m.uid))},gyDestroyed);
 for(const [n,count,fee] of [['Volcanic Slicer',500,0],['Volcanic Hammerer',0,0],['King Pyron',1000,0]])ignite(n,null,(e,c)=>{X.burn(e,c,count||grave(e,c.owner,m=>series(m,'Volcanic')).length*200);if(n!=='King Pyron'&&self(e,c))self(e,c).yearAttackLocked=true;},{condition:(e,c)=>n==='King Pyron'||!self(e,c)?.attacksMade});
 ignite('Volcanic Shell',(e,c)=>deck(e,c.owner,m=>is(m,'Volcanic Shell')),(e,c)=>e.search(c.owner,args(c)),{zones:['grave'],fee:500,role:'search'});
 onMove('Volcanic Scattershot','burn',{mandatory:true,resolve:(e,c)=>{X.burn(e,c,500);if(series({id:c.event.source?.id||c.sourceId},'Blaze Accelerator')){const list=H.cards(e,c.owner,['hand','deck'],m=>is(m,'Volcanic Scattershot'));choose(e,c,'选择送墓的两只火山鹿弹',list,2,2,'gx-scatter',{role:'cost'});}}},(e,v)=>v.to==='grave');E.op('gx-scatter',(e,t)=>{H.sendCost(e,{owner:t.owner,source:t.context.source},t.picks);destroy(e,{owner:t.owner,source:t.context.source},e.monsters(1-t.owner).map(m=>m.uid));});
 onMove('Volcanic Blaster','top',{inputs:target('选择放到卡组顶的火山怪兽',(e,c)=>deck(e,c.owner,m=>series(m,'Volcanic')),'search'),resolve:(e,c)=>e.putOnDeck(first(c),'top',c.source)},gyBattle);
 handSpecial('Volcanic Doomfire',()=>true,(e,c)=>e.spells(c.owner).filter(m=>active(e,m)&&is(m,'Tri-Blaze Accelerator')),1,{only:true});onBattleWin('Volcanic Doomfire',{resolve:(e,c)=>{let n=0;for(const m of [...foeM(e,c)])if(e.destroy(m.uid,c.source))n++;X.burn(e,c,n*500);}});
 for(const [n,pool,amount] of [['Seismic Crasher',null,500],['Gravi-Crush Dragon',foeM,0],['Magna-Slash Dragon',(e,c)=>e.spells(1-c.owner),0]])ignite(n,pool,(e,c)=>amount?X.burn(e,c,amount):destroy(e,c,args(c)),{oncePerTurn:false,inputs:(e,c)=>[g(e,c,'cost','选择送墓的永续卡',e.spells(c.owner).filter(m=>active(e,m)&&cont(m)),1,1,'cost'),...(pool?[g(e,c,'target','选择破坏的卡片',pool(e,c))]:[])],cost:(e,c)=>H.sendCost(e,c,args(c,'cost'))});
 ignite('Mei-Kou, Master of Barriers',e=>allS(e).filter(m=>m.faceUp&&cont(m)),(e,c)=>destroy(e,c,args(c)),{cost:(e,c)=>X.tribute(e,c,[c.uid])});
 ownStat('Dweller in the Depths',(e,m,k,p)=>k==='atk'?e.spells(p).filter(cont).length*300:0);ownStat('Elemental HERO Heat',(e,m,k,p)=>k==='atk'?e.monsters(p).filter(hero).length*200:0);
 onDamage('Goe Goe the Gallant Ninja',{condition:(e,c)=>hand(e,1-c.owner).length>=5,resolve:(e,c)=>{if(hand(e,1-c.owner).length>=5)X.randomDiscard(e,1-c.owner,2,c.source);}});
 onStandby('Elemental HERO Woodsman',{resolve:(e,c)=>search(e,c,H.cards(e,c.owner,['deck','grave'],m=>is(m,'Polymerization')))});
 for(const [n,gain] of [['Elemental HERO Knospe',100],['Elemental HERO Poison Rose',200]])onDamage(n,{resolve:(e,c)=>{e.modify(c.uid,'atk','add',gain,null,c.source);e.modify(c.uid,'def','add',-gain,null,c.source);}});
 guard('direct','Elemental HERO Knospe',(e,m,p)=>e.monsters(p).some(q=>q.faceUp&&hero(q)&&q.uid!==m.uid));C('Elemental HERO Poison Rose').specialOnly='rose-bud';
 tributeAction('Elemental HERO Terra Firma',(e,m)=>m.faceUp&&hero(m),(e,c)=>e.modify(c.uid,'atk','add',c.tributes[0].atk||0,e.state.turn,c.source),{once:undefined});
 onEnd('Elemental HERO Lady Heat',{resolve:(e,c)=>X.burn(e,c,ownM(e,c).filter(m=>m.faceUp&&hero(m)).length*200)},{mandatory:true});
 passive('Elemental HERO Inferno',{battleStat:(e,s,m,k,a)=>s.card.uid===m.uid&&k==='atk'&&e.find(a.uid===m.uid?a.target:a.uid)&&e.hasAttribute(e.find(a.uid===m.uid?a.target:a.uid).card,'水')?1000:0});
 ignite('Plague Wolf',null,(e,c)=>{e.modify(c.uid,'atk','set',e.originalAttack(self(e,c))*2,e.state.turn,c.source);delayMove(e,c,self(e,c),'destroy');});C('Mist Archfiend').tributeCount=0;onEnd('Mist Archfiend',{condition:(e,c)=>self(e,c)?.tributeCount===0,resolve:(e,c)=>{if(e.destroy(c.uid,c.source))e.damage(c.owner,1000,'效果');}},{mandatory:true});
 onMove('Lich Lord, King of the Underworld','return',{resolve:(e,c)=>moved(e,c,[c.uid],'hand','effect-return')},(e,v)=>v.to==='grave'&&v.kind.includes('tribute')&&v.kind!=='tribute-summon');
 onEntry('Prometheus, King of the Shadows','boost',{inputs:(e,c)=>[g(e,c,'target','选择除外的暗属性怪兽',grave(e,c.owner,m=>e.hasAttribute(m,'暗')),1,grave(e,c.owner,m=>e.hasAttribute(m,'暗')).length,'cost')],resolve:(e,c)=>{moved(e,c,args(c),'banished','effect-banish');e.modify(c.uid,'atk','add',args(c).length*400,e.state.turn,c.source);}},['normal']);
 onMove('Exploder Dragon','destroy',{resolve:(e,c)=>destroy(e,c,[c.event.source?.uid])},gyBattle);
 for(const [name,needs] of [['Sky Scourge Enrise',[['光','天使族',3],['暗','恶魔族',1]]],['Sky Scourge Norleras',[['光','天使族',1],['暗','恶魔族',3]]],['Frost and Flame Dragon',[['炎',null,1],['水',null,2]]],['Desert Twister',[['风',null,2],['地',null,1]]]]){handSpecial(name,()=>true,null,0,{only:true});const a=E.get(I(name)+'::gx-special');a.inputs=(e,c)=>needs.map(([attr,race,n],i)=>g(e,c,'cost'+i,'选择除外的召唤素材',grave(e,c.owner,m=>e.hasAttribute(m,attr)&&(!race||e.race(m)===race)),n,n,'cost'));a.cost=(e,c)=>moved(e,c,needs.flatMap((_,i)=>args(c,'cost'+i)),'banished','cost-banish');}
 ignite('Sky Scourge Enrise',e=>allM(e).filter(face),(e,c)=>{moved(e,c,args(c),'banished','effect-banish');self(e,c).yearAttackLocked=true;});ignite('Sky Scourge Norleras',null,(e,c)=>{moved(e,c,[...allF(e),...hand(e,0),...hand(e,1)].map(m=>m.uid),'grave','effect-send');e.draw(c.owner,1);},{fee:1000,oncePerTurn:false});ignite('Frost and Flame Dragon',allM,(e,c)=>destroy(e,c,args(c)),{discard:1});ignite('Desert Twister',allS,(e,c)=>destroy(e,c,args(c)),{discard:1});
 for(const [n,to] of [['Chrysalis Larva','Neo-Spacian Flare Scarab'],['Chrysalis Chicky','Neo-Spacian Air Hummingbird'],['Chrysalis Pinny','Neo-Spacian Glow Moss'],['Chrysalis Mole','Neo-Spacian Grand Mole'],['Chrysalis Pantail','Neo-Spacian Dark Panther']])tributeAction(n,(e,m,c)=>m.uid===c.uid,(e,c)=>recruit(e,c,H.cards(e,c.owner,['hand','deck'],m=>is(m,to)),{shuffle:true}),{condition:e=>has(e,'Neo Space')});
 for(const [n,count,lock] of [['Venom Boa',2,true],['Venom Snake',1,true],['Venom Serpent',1,false]])ignite(n,foeM,(e,c)=>{counterAdd(e,first(c),'venomCounters',count);if(lock)self(e,c).yearAttackLocked=true;},{condition:(e,c)=>!lock||!self(e,c)?.attacksMade});
 for(const n of ['Vennominon the King of Poisonous Snakes','Vennominaga the Deity of Poisonous Snakes']){ownStat(n,(e,m,k,p)=>k==='atk'?grave(e,p,q=>e.race(q)==='爬虫类族').length*500:0);onMove(n,'revive',{inputs:(e,c)=>[g(e,c,'cost','选择除外的其他爬虫类族',grave(e,c.owner,m=>m.uid!==c.uid&&e.race(m)==='爬虫类族'),1,1,'cost')],cost:(e,c)=>moved(e,c,args(c,'cost'),'banished','cost-banish'),resolve:(e,c)=>revive(e,c,c.uid,{via:'venom'})},gyBattle);}C('Vennominaga the Deity of Poisonous Snakes').specialOnly='venom';guard('target','Vennominaga the Deity of Poisonous Snakes',()=>false);extend('unaffected',function(prior,m,s){return prior.call(this,m,s)||is(m,'Vennominaga the Deity of Poisonous Snakes')&&active(this,m)&&s?.uid!==m.uid;});onDamage('Vennominaga the Deity of Poisonous Snakes',{resolve:(e,c)=>{counterAdd(e,c.uid,'hyperVenom');if(self(e,c)?.hyperVenom>=3)e.finish(c.owner,'毒蛇神的三个超毒指示物达成胜利');}});
 for(const [n,attr] of [['Light Effigy','光'],['Dark Effigy','暗']]){mark(n);extend('tributeWeight',function(prior,m,t){return is(m,n)&&t&&this.hasAttribute(t,attr)&&X.isNormal(this,t)?2:prior.call(this,m,t);});}
 onFlip('Gravitic Orb',{resolve:(e,c)=>{for(const m of foeM(e,c).filter(face))e.setPosition(m.uid,m.position==='attack'?'defense':'attack',c.source);}});onFlip('Phantom Cricket',{inputs:target('选择放回卡组顶的盖放怪兽',e=>allM(e).filter(m=>!m.faceUp)),resolve:(e,c)=>e.putOnDeck(first(c),'top',c.source)});
 rule('Elemental HERO Darkbright',{piercing:true});event('Elemental HERO Darkbright','damage-end',(e,v,f)=>v.attack.uid===f.card.uid,{resolve:(e,c)=>e.setPosition(c.uid,'defense',c.source)});onMove('Elemental HERO Darkbright','destroy',{inputs:target('选择破坏的对方怪兽',foeM),resolve:(e,c)=>destroy(e,c,args(c))},gyDestroyed);
 original('Goggle Golem',(e,m)=>e.geminiActive(m)?2100:1500);original('Dawnbreak Gardna',(e,m)=>CARDS[m.id].atk,(e,m)=>e.geminiActive(m)?2300:500);onBattleWin('Aquarian Alessa',{resolve:(e,c)=>X.randomDiscard(e,1-c.owner,1,c.source)});onBattleWin('Lucky Pied Piper',{resolve:(e,c)=>e.draw(c.owner,1)});ignite('Shadow Delver',(e,c)=>ownM(e,c).filter(m=>m.faceUp&&e.hasAttribute(m,'暗')&&e.level(m)<=4),(e,c)=>{const m=e.find(first(c))?.card;if(m)m.directUntil=e.state.turn;});mark('Elemental HERO Neos Alius');
 for(const n of ['Elemental HERO Marine Neos','Elemental HERO Magma Neos'])contactFusion(n);ignite('Elemental HERO Marine Neos',null,(e,c)=>X.randomDiscard(e,1-c.owner,1,c.source));ownStat('Elemental HERO Magma Neos',(e,m,k)=>k==='atk'?allF(e).length*400:0);onEnd('Elemental HERO Magma Neos',{resolve:(e,c)=>{moved(e,c,[c.uid],'extra-down','effect-return');moved(e,c,allF(e).map(m=>m.uid),'hand','effect-return');}},{mandatory:true});
 handSpecial('Rainbow Dragon',(e,c)=>new Set(H.cards(e,c.owner,['monsters','extraMonster','spells','grave'],crystal).map(m=>m.id)).size>=7,null,0,{only:true});Q('Rainbow Dragon','power',{condition:(e,c)=>self(e,c)?.summonTurn<e.state.turn,inputs:(e,c)=>[],cost:(e,c)=>{const list=ownM(e,c).filter(m=>m.faceUp&&crystal(m));c.n=list.length;H.sendCost(e,c,list.map(m=>m.uid));},resolve:(e,c)=>e.modify(c.uid,'atk','add',c.n*1000,null,c.source),aiScore:700});ignite('Rainbow Dragon',null,(e,c)=>{moved(e,c,allF(e).map(m=>m.uid),'deck','effect-return');for(const p of [0,1])e.shuffle(e.state.players[p].deck);},{condition:(e,c)=>self(e,c)?.summonTurn<e.state.turn&&grave(e,c.owner,crystal).length>0,cost:(e,c)=>moved(e,c,grave(e,c.owner,crystal).map(m=>m.uid),'banished','cost-banish')});
 const api={...X,crystalPlace,cont,gyBattle,gyDestroyed};root.Duel2007=api;
 if(typeof module!=='undefined'){module.exports=api;for(const n of ['monsters','spells','traps'])require('./effects-2007-'+n+'.js');}
})(globalThis);
