(function(root){
 'use strict';
 const rows=[
 ['决斗之境','Duel Sanctuary','デュエル・サンクチュアリ'],['决斗场','Duel Field','デュエルフィールド'],['卡牌图鉴','Card Archive','カード図鑑'],['组卡工坊','Deck Builder','デッキ構築'],['玩法指南','How to Play','遊び方'],['新的决斗','New Duel','新しいデュエル'],['设置','Settings','設定'],['语言','Language','言語'],['显示语言','Display language','表示言語'],['选择界面、卡名和卡片说明的语言。','Choose the language for the interface, card names and descriptions.','画面、カード名、カードテキストの言語を選択します。'],
 ['中文','中文','中文'],['English','English','English'],['日本語','日本語','日本語'],['全部','All','すべて'],['全部系列','All archetypes','すべてのシリーズ'],['全部年代','All years','すべての年代'],['全部收录','All cards','収録カードすべて'],['可用于决斗','Playable','使用可能'],['效果待落实','Effect pending','効果未実装'],['按首次发行年','First OCG release','OCG初登場年'],['初代编年','Origins archive','初期カード年表'],['年度快照卡片','cards in yearly snapshots','年度データのカード'],['总收录','cards in the archive','総収録枚数'],['资料首发日期','Recorded first release','記録上の初登場日'],
 ['怪兽','Monster','モンスター'],['魔法','Spell','魔法'],['陷阱','Trap','罠'],['通常','Normal','通常'],['效果','Effect','効果'],['仪式','Ritual','儀式'],['融合','Fusion','融合'],['同调','Synchro','シンクロ'],['超量','Xyz','エクシーズ'],['灵摆','Pendulum','ペンデュラム'],['连接','Link','リンク'],['调整','Tuner','チューナー'],['反转','Flip','リバース'],['灵魂','Spirit','スピリット'],['卡通','Toon','トゥーン'],['衍生物','Token','トークン'],
 ['通常魔法','Normal Spell','通常魔法'],['速攻魔法','Quick-Play Spell','速攻魔法'],['永续魔法','Continuous Spell','永続魔法'],['装备魔法','Equip Spell','装備魔法'],['场地魔法','Field Spell','フィールド魔法'],['仪式魔法','Ritual Spell','儀式魔法'],['通常陷阱','Normal Trap','通常罠'],['永续陷阱','Continuous Trap','永続罠'],['反击陷阱','Counter Trap','カウンター罠'],
 ['手牌','Hand','手札'],['手卡','Hand','手札'],['卡组','Deck','デッキ'],['主卡组','Main Deck','メインデッキ'],['额外卡组','Extra Deck','エクストラデッキ'],['墓地','Graveyard','墓地'],['除外区','Banished','除外'],['场上','Field','フィールド'],['魔陷区','Spell / Trap Zone','魔法＆罠ゾーン'],['场地区','Field Zone','フィールドゾーン'],['怪兽区','Monster Zone','モンスターゾーン'],['主怪兽区','Main Monster Zone','メインモンスターゾーン'],['额外怪兽区','Extra Monster Zone','EXモンスターゾーン'],['共享额外区','Shared Extra Zone','共有EXゾーン'],['超量素材','Xyz Materials','X素材'],['素材','Materials','素材'],['连锁','Chain','チェーン'],
 ['光','LIGHT','光'],['暗','DARK','闇'],['地','EARTH','地'],['水','WATER','水'],['炎','FIRE','炎'],['风','WIND','風'],['神','DIVINE','神'],['无','None','なし'],['无种族','No Type','種族なし'],['无等级','No Level','レベルなし'],
 ['战士族','Warrior','戦士族'],['魔法师族','Spellcaster','魔法使い族'],['龙族','Dragon','ドラゴン族'],['恶魔族','Fiend','悪魔族'],['天使族','Fairy','天使族'],['不死族','Zombie','アンデット族'],['机械族','Machine','機械族'],['兽族','Beast','獣族'],['兽战士族','Beast-Warrior','獣戦士族'],['鸟兽族','Winged Beast','鳥獣族'],['水族','Aqua','水族'],['鱼族','Fish','魚族'],['海龙族','Sea Serpent','海竜族'],['雷族','Thunder','雷族'],['炎族','Pyro','炎族'],['岩石族','Rock','岩石族'],['植物族','Plant','植物族'],['昆虫族','Insect','昆虫族'],['爬虫类族','Reptile','爬虫類族'],['恐龙族','Dinosaur','恐竜族'],['念动力族','Psychic','サイキック族'],['电子界族','Cyberse','サイバース族'],['幻龙族','Wyrm','幻竜族'],
 ['卡牌详情','Card Details','カード詳細'],['每一张卡，都有它的灵魂。','Every card has a story.','すべてのカードに、物語がある。'],['构筑你的下一场胜利。','Build your next victory.','次の勝利を、その手で組もう。'],['选择与你共鸣的力量。','Choose the power that speaks to you.','自分と響き合う力を選ぼう。'],['从第一次召唤，到无限可能。','From your first Summon to endless possibilities.','最初の召喚から、無限の可能性へ。'],
 ['返回决斗','Return to Duel','デュエルに戻る'],['继续当前对局','Continue Duel','対戦を続ける'],['返回上一页','Back','戻る'],['浏览图鉴','Browse Archive','図鑑を見る'],['前往组卡工坊','Open Deck Builder','デッキ構築へ'],['查看卡牌','View Card','カードを見る'],['查看效果','Read Effect','効果を確認'],['查看卡片百科','Card Encyclopedia','カード百科を見る'],['查看内嵌卡图','View Embedded Artwork','内蔵イラストを見る'],['查看在线卡图','View Online Artwork','オンラインのイラストを見る'],['卡图','Artwork','イラスト'],
 ['显示卡图','Show artwork','イラスト表示'],['本地原版卡图','Embedded original artwork','内蔵のカードイラスト'],['在线原版卡图','Online original artwork','オンラインのカードイラスト'],['缺少内嵌图片时联网加载原版卡图。关闭后仍可离线决斗。','Load original artwork online when it is not embedded. Duels still work when this is off.','内蔵画像がない場合にオンラインでイラストを読み込みます。オフでもデュエルは可能です。'],['优先显示内嵌卡图，缺图时使用备用卡面。','Embedded artwork is preferred; missing images use a placeholder.','内蔵画像を優先し、画像がないカードには代替表示を使用します。'],['刷新卡图','Retry artwork','イラストを再読み込み'],['本地卡图','Local artwork','ローカル画像'],['本地原图','Embedded art','内蔵画像'],['在线补图','Online fallback','オンライン補完'],['离线卡面','Offline cards','オフライン表示'],['卡图加载中','Loading artwork','画像を読み込み中'],['网络可用','Online','接続中'],['当前离线','Offline','オフライン'],['原版图片尚未加载，备用卡面可正常使用。','Artwork is not loaded; the placeholder remains fully playable.','画像未読み込みでも、代替表示で通常どおりプレイできます。'],
 ['卡名、英文名、卡片编号或效果','Name, card ID or effect (any language)','カード名・番号・効果（三言語対応）'],['搜索卡名、效果或英文名…','Search card names or effects…','カード名・効果を検索…'],['搜索当前候选卡片','Search available choices','候補のカードを検索'],['搜索候选卡名…','Search candidate names…','候補のカード名を検索…'],['没有找到这张卡，试试其他名称或年份。','No matching cards. Try another name or year.','該当するカードがありません。名前や年度を変更してください。'],['没有符合条件的卡片。','No cards match these filters.','条件に合うカードがありません。'],['清空筛选','Clear filters','絞り込みを解除'],['上一页','Previous','前へ'],['下一页','Next','次へ'],['仅已编入','In deck only','採用中のみ'],['仅可用于决斗','Playable only','使用可能のみ'],
 ['从构筑开始','Start from a deck','デッキから始める'],['选择预设 / 已保存卡组','Choose a preset or saved deck','プリセット・保存デッキを選択'],['预设卡组 · 自动建立副本','Presets · create a copy','プリセット・コピーを作成'],['你的卡组','Your decks','保存したデッキ'],['空白卡组','Empty deck','空のデッキ'],['复制当前','Duplicate','複製'],['撤销','Undo','元に戻す'],['重做','Redo','やり直す'],['撤销上次编辑','Undo last change','直前の編集を戻す'],['导入','Import','インポート'],['导出','Export','エクスポート'],['删除','Delete','削除'],['确认删除？','Confirm deletion?','削除しますか？'],['卡组名称','Deck name','デッキ名'],['我的新卡组','My new deck','新しいデッキ'],['保存卡组','Save deck','デッキを保存'],['保存并出战','Save and duel','保存して対戦'],['草稿已自动保留','Draft saved automatically','下書きを自動保存しました'],['草稿暂未保存，请导出备份','Draft could not be saved. Export a backup.','下書きを保存できません。エクスポートしてバックアップしてください。'],['可继续编辑','Ready to edit','編集可能'],['已保存为可用卡组','Saved and ready to duel','保存済み・対戦可能'],['构筑合法，可以出战','Legal deck, ready to duel','デッキは有効です。対戦できます'],['继续完善你的卡组','Keep building your deck','デッキを完成させましょう'],['当前构筑','Current deck','現在のデッキ'],['牌库 · 添加卡片','Collection · add cards','カード一覧・追加'],['关闭预览','Close preview','プレビューを閉じる'],['同名卡最多可以编入3张。','You may include at most 3 cards with the same name.','同名カードは合計3枚までです。'],['卡片已全部解锁','All cards unlocked','全カード解放済み'],['本作不采用赛事禁限卡表 · 默认仅显示可用卡片','No tournament banlist · playable cards shown by default','大会の禁止・制限リストなし・使用可能なカードを標準表示'],
 ['主卡组 40—60 · 额外 0—15 · 同名最多 3','Main 40–60 · Extra 0–15 · Up to 3 of each name','メイン40～60枚・EX0～15枚・同名3枚まで'],['点击牌库卡片下方的 ＋','Use + below a card to add it.','カードの下の＋で追加できます。'],['从第一张卡开始，写下你的战术。','Your strategy starts with the first card.','最初の1枚から戦術を組み立てよう。'],['融合、同调、超量与连接怪兽','Fusion, Synchro, Xyz and Link monsters','融合・シンクロ・エクシーズ・リンクモンスター'],['会自动加入这里。仪式在主卡组。','go here. Ritual Monsters belong in the Main Deck.','はこちら。儀式モンスターはメインデッキです。'],
 ['主要阶段 1','Main Phase 1','メインフェイズ1'],['主要阶段 2','Main Phase 2','メインフェイズ2'],['战斗阶段','Battle Phase','バトルフェイズ'],['结束阶段','End Phase','エンドフェイズ'],['准备阶段','Standby Phase','スタンバイフェイズ'],['抽卡阶段','Draw Phase','ドローフェイズ'],['进入战斗阶段','Enter Battle Phase','バトルフェイズへ'],['进入主要阶段 2','Enter Main Phase 2','メインフェイズ2へ'],['结束回合','End Turn','ターン終了'],['结束','End','終了'],['你的回合','Your turn','自分のターン'],['对方回合','Opponent turn','相手ターン'],['对手的回合','Opponent turn','相手のターン'],['对方正在思考','Opponent is thinking','相手が考えています'],['对方正在行动','Opponent is playing','相手が行動中'],['决斗记录','Duel Log','デュエルログ'],['完整记录','Full log','全ログ'],['导出记录','Export log','ログを保存'],['进度自动保存','Progress saved automatically','進行を自動保存'],['对局已自动保存','Duel saved automatically','対戦を自動保存しました'],['决斗已结束','Duel complete','デュエル終了'],['决斗结束','Duel complete','デュエル終了'],['开始决斗','Start Duel','デュエル開始'],['再来一场','Duel Again','もう一度対戦'],['重新开始','Restart','やり直す'],['准备好了','Ready','準備完了'],
 ['召唤','Summon','召喚'],['通常召唤','Normal Summon','通常召喚'],['特殊召唤','Special Summon','特殊召喚'],['仪式召唤','Ritual Summon','儀式召喚'],['融合召唤','Fusion Summon','融合召喚'],['同调召唤','Synchro Summon','シンクロ召喚'],['超量召唤','Xyz Summon','エクシーズ召喚'],['连接召唤','Link Summon','リンク召喚'],['灵摆召唤','Pendulum Summon','ペンデュラム召喚'],['额外召唤','Extra Deck Summon','EX召喚'],['反转召唤','Flip Summon','反転召喚'],['上级召唤','Tribute Summon','アドバンス召喚'],['盖放','Set','セット'],['攻击表示召唤','Normal Summon (Attack)','攻撃表示で通常召喚'],['里侧守备盖放','Set (Defense)','裏側守備表示でセット'],['盖放到场上','Set on the field','フィールドにセット'],['变为守备表示','Change to Defense','守備表示に変更'],['变为攻击表示','Change to Attack','攻撃表示に変更'],['表侧攻击','Face-up Attack','表側攻撃表示'],['表侧守备','Face-up Defense','表側守備表示'],['攻击表示','Attack Position','攻撃表示'],['守备表示','Defense Position','守備表示'],['里侧表示','Face-down','裏側表示'],['出场表示','Battle position','表示形式'],['召唤区域','Summon zone','召喚するゾーン'],['直接攻击','Direct Attack','直接攻撃'],['直接攻击对方','Attack directly','直接攻撃する'],['选择攻击目标','Choose attack target','攻撃対象を選択'],['不解放通常召唤','Normal Summon without Tributing','リリースなしで通常召喚'],['不解放里侧盖放','Set without Tributing','リリースなしでセット'],
 ['未知的卡牌','Unknown card','不明なカード'],['对方的里侧卡牌','Opponent’s face-down card','相手の裏側カード'],['未公开的卡片','Unrevealed card','非公開のカード'],['身份尚未公开','Identity is hidden','正体は非公開です'],['未公开的额外怪兽','Unrevealed Extra Deck monster','非公開のEXモンスター'],['对方未公开的额外卡组卡片','Opponent’s unrevealed Extra Deck card','相手の非公開EXデッキカード'],['相信直觉，也相信你的卡组。','Trust your instincts and your deck.','直感とデッキを信じよう。'],['对方盖放的卡牌。发动或翻开后，才能查看这张卡的身份。仔细观察，谨慎出击。','This card is face-down. Its identity is revealed when it is activated or flipped face-up.','相手のセットカードです。発動または表側表示になるまで正体は分かりません。'],
 ['点击卡牌，开启你的战术','Select a card to plan your move','カードを選んで行動しよう'],['对方正在行动 · 你可以查看卡牌','Opponent is playing · you may inspect cards','相手が行動中・カードを確認できます'],['按提示完成选择 · Esc 取消','Follow the prompt · Esc to cancel','案内に従って選択・Escでキャンセル'],['决斗结束 · 每一张卡都有它的故事','Duel complete · every card has a story','デュエル終了・すべてのカードに物語がある'],['决策时机','Decision window','選択のタイミング'],['效果处理中','Resolving effect','効果を処理中'],['选择卡片','Choose cards','カードを選択'],['发动效果','Activate effect','効果を発動'],['不发动','Do not activate','発動しない'],['不连锁','Do not chain','チェーンしない'],['取消选择','Cancel selection','選択をキャンセル'],['确认选择','Confirm selection','選択を確定'],['确认连锁顺序','Confirm chain order','チェーン順を確定'],['确认素材并召唤','Confirm materials and Summon','素材を確定して召喚'],['强制','Mandatory','強制'],['必选','Required','必須'],['选择合法，可以确认','Valid selection. Ready to confirm.','選択は有効です。確定できます。'],['点选卡牌，查看效果与选择顺序。','Select a card to inspect its text and selection order.','カードを選ぶと、テキストと選択順を確認できます。'],['请选择要发动的效果。','Choose an effect to activate.','発動する効果を選んでください。'],['效果正在结算中，请完成这一步选择。','An effect is resolving. Complete this selection to continue.','効果を処理中です。この選択を完了してください。'],['先选择代价或目标，再确认发动。','Choose the cost or target, then confirm activation.','コストや対象を選び、発動を確定してください。'],['现在可以连锁发动效果，也可以保留卡片。','You may chain an effect or pass.','効果をチェーンするか、発動せずに進められます。'],['满足了诱发条件。可以发动这个效果，也可以保留。','The trigger condition is met. You may activate this effect or pass.','発動条件を満たしました。この効果を発動するか選べます。'],
 ['仪式怪兽编入主卡组，由对应仪式魔法召唤。','Ritual Monsters go in the Main Deck and use the matching Ritual Spell.','儀式モンスターはメインデッキに入れ、対応する儀式魔法で召喚します。'],['选择手牌或场上的怪兽作为解放素材。等级合计须达到目标等级，不能额外解放已不需要的素材。仪式怪兽登场于主怪兽区。','Tribute monsters from your hand or field. Meet the Ritual Spell’s Level requirement without unnecessary Tributes, then use a Main Monster Zone.','手札・フィールドのモンスターをリリースします。儀式魔法のレベル条件を満たし、余分なリリースを加えず、メインモンスターゾーンに召喚します。'],['等级不足、包含多余解放，或没有可用主怪兽区。','Not enough Levels, unnecessary Tributes, or no available Main Monster Zone.','レベル不足、余分なリリース、または空きメインモンスターゾーンがありません。'],['请选择不同的卡牌或选项。','Choose distinct cards or options.','異なるカードや項目を選んでください。'],['等级、素材类别或祭品数量不符合要求。','The Levels, material types or Tribute count do not meet the requirements.','レベル・素材の種類・リリース数が条件を満たしていません。'],['选择中有不可用的卡牌。','The selection contains an unavailable card.','選択に使用できないカードが含まれています。'],['已选满，先取消一项即可更换。','Selection is full. Deselect an item to replace it.','選択数の上限です。入れ替えるには1つ解除してください。'],['选择合法素材后显示可用区域','Available zones appear after valid materials are selected.','有効な素材を選ぶと使用可能なゾーンが表示されます。'],['必须包含强制发动的效果。','Mandatory effects must be included.','強制発動の効果を含めてください。'],['效果无效中','Effects negated','効果無効'],['表侧额外卡组','Face-up Extra Deck','表側EXデッキ'],['临时怪兽状态 · 原卡种类保留','Temporary monster · original card type retained','一時的なモンスター状態・元のカード種類も保持'],
 ['对手卡组','Opponent deck','相手のデッキ'],['对手难度','Opponent difficulty','相手の強さ'],['休闲','Casual','カジュアル'],['标准','Standard','スタンダード'],['出场顺序','Turn order','先攻・後攻'],['我先攻','Go first','先攻'],['我后攻','Go second','後攻'],['编辑这副构筑','Edit this deck','このデッキを編集'],['跨越世代的决斗，从这里开始。','Duels across generations begin here.','世代を超えるデュエルを、ここから。'],['开始新决斗会替换当前对局存档；保存的卡组与工坊草稿会保留。','A new Duel replaces the current Duel save. Saved decks and builder drafts are kept.','新しいデュエルは現在の対戦セーブを置き換えます。保存デッキと下書きは残ります。'],['8000 LP · 随机起手 5 张 · 先攻首回合不抽卡、不攻击','8000 LP · Random 5-card hand · First player skips the first draw and Battle Phase','8000 LP・初手5枚をランダムに配布・先攻1ターン目はドローと攻撃なし'],
 ['音效','Sound effects','効果音'],['背景氛围音','Ambient audio','環境音'],['背景音乐','Background music','BGM'],['音量','Volume','音量'],['动画速度','Animation speed','演出速度'],['标准速度','Normal speed','通常速度'],['快速','Fast','高速'],['减少动态效果','Reduce motion','動きを抑える'],['减少动效','Reduce motion','動きを抑える'],['全屏','Fullscreen','全画面'],['关闭','Close','閉じる'],['返回','Back','戻る'],['完成','Done','完了'],['保存','Save','保存'],['本机保存','Local saves','ローカル保存'],['高桥和希 原作','Original work: Kazuki Takahashi','原作：高橋和希'],['非官方同人致敬','Unofficial fan tribute','非公式ファン作品'],['V4 · 初代编年','V4 · Origins archive','V4・初期カード年表'],
 ['效果顺序','Effect order','効果の順序'],['代价','Cost','コスト'],['对象','Target','対象'],['目标','Target','対象'],['确认','Confirm','確定'],['自己','You','自分'],['对方','Opponent','相手'],['你','You','あなた'],['是','Yes','はい'],['否','No','いいえ'],['不复活','Do not revive','蘇生しない'],['复活全部素材','Revive all materials','素材をすべて蘇生'],['不支付，破坏此卡','Do not pay; destroy this card','支払わず、このカードを破壊'],['正面','Heads','表'],['反面','Tails','裏'],['保留结果','Keep result','結果を維持'],['重新掷全部硬币','Toss all coins again','コインをすべて投げ直す'],['留在卡组顶','Keep on top','デッキの上に戻す'],['放到卡组底','Place on bottom','デッキの下に戻す'],['正常抽卡','Draw normally','通常のドロー'],['攻击力','ATK','攻撃力'],['守备力','DEF','守備力'],['破坏','Destroy','破壊'],['除外','Banish','除外'],['检索','Search','サーチ'],['抽卡','Draw','ドロー'],['复活','Revive','蘇生'],['回收','Recover','回収'],['送墓','Send to GY','墓地へ送る'],['无效','Negate','無効'],['解放','Tribute','リリース'],['上升','Increase','アップ'],['下降','Decrease','ダウン'],['加入手牌','Add to hand','手札に加える'],['返回手牌','Return to hand','手札に戻す'],['卡名','Card name','カード名'],['回合','Turn','ターン'],['等级','Level','レベル'],['阶级','Rank','ランク'],['张卡片','cards','枚のカード'],['张手牌','cards in hand','枚の手札'],['已解锁','unlocked','解放済み'],
 ['AI 行动异常，已暂停自动行动。','An AI error paused automatic play.','AIエラーのため自動操作を停止しました。'],['这项操作现在不满足条件。','This action is not legal right now.','現在、この操作の条件を満たしていません。'],['操作未能完成，请检查当前条件和目标。','The action could not complete. Check its conditions and targets.','操作を完了できません。条件と対象を確認してください。'],
 ['E·HERO','E·HERO','E・HERO'],['黑羽','Blackwing','BF'],['废品 / 同调士','Junk / Synchron','ジャンク／シンクロン'],['希望皇','Utopia','希望皇ホープ'],['机壳','Qliphort','クリフォート'],['艾克佐迪亚','Exodia','エクゾディア'],['电子龙','Cyber Dragon','サイバー・ドラゴン'],['水晶机巧','Crystron','クリストロン'],['通用卡','Generic','汎用'],['珠泪哀歌族','Tearlaments','ティアラメンツ'],['连接 / Link','Link','リンク'],['初代编年 · 1999—2005','Origins · 1999–2005','初期カード・1999～2005'],['守墓',"Gravekeeper's",'墓守'],['亚马逊','Amazoness','アマゾネス'],['守护者','Guardian','ガーディアン'],['卡通','Toon','トゥーン'],['黑蝎','Dark Scorpion','ブラック・スコーピオン'],
 ['仪式解放','Ritual Tributes','儀式のリリース'],['选择融合素材','Choose Fusion Materials','融合素材を選択'],['选择上级召唤的祭品','Choose Tribute Summon materials','アドバンス召喚のリリースを選択'],['决定同一时点的连锁顺序','Order simultaneous triggers','同時に発動する効果の順序'],['可以发动诱发效果','Optional Trigger Effect','誘発効果を発動できます'],['连锁响应','Chain response','チェーン確認'],['战斗中的响应时机','Battle response window','戦闘中の発動タイミング'],['额外怪兽需要满足相应召唤条件。','Extra Deck monsters need their proper Summoning conditions.','EXモンスターには対応する召喚条件が必要です。']
 ];
 rows.push(
 ['查看完整卡面','View full card','カードを拡大'],['放大卡牌','Enlarge card','カードを拡大'],['查看规则','View rules','ルールを見る'],['决斗小贴士','Duel tips','デュエルのヒント'],['融合 / 初代','Fusion / Origins','融合／初期'],['初代','Origins','初期'],['加速同调','Accel Synchro','アクセルシンクロ'],['特殊胜利','Special victory','特殊勝利'],['〈 刻度 〉','〈 SCALES 〉','〈 スケール 〉'],['你的手牌','Your hand','自分の手札'],['我的回合','My turn','自分のターン'],['对手回合','Opponent turn','相手ターン'],['结束先攻回合','End the first turn','先攻ターンを終了'],['结束我的回合','End my turn','自分のターンを終了'],['查看玩法指南','Open guide','遊び方を見る'],['切换阶段','Next phase','次のフェイズ'],['每一次抉择，都改变未来','Every choice shapes the next turn.','一つひとつの選択が、未来を変える。'],['先攻回合不能攻击。召唤怪兽，布置你的战术。','You cannot attack on the first turn. Summon monsters and prepare your field.','先攻1ターン目は攻撃できません。モンスターを召喚し、場を整えましょう。'],['你先攻','You go first','あなたが先攻'],['命运的牌组已经就绪，决斗开始。','Your deck is ready. Let the Duel begin.','デッキの準備ができました。デュエル開始！'],['＋ 加入额外','＋ Add to Extra Deck','＋ EXデッキに追加'],['＋ 加入主卡组','＋ Add to Main Deck','＋ メインデッキに追加'],['特殊召唤控制','Special Summon controls','特殊召喚の操作'],['回合控制','Turn controls','ターン操作'],['查看完整决斗记录','View full Duel log','全デュエルログを見る'],['搜索卡牌','Search cards','カードを検索'],['筛选系列','Filter archetypes','シリーズで絞り込み'],['筛选发行年份','Filter release year','発売年で絞り込み'],['筛选实现状态','Filter implementation status','実装状態で絞り込み'],['搜索组卡牌库','Search deck-building collection','構築用カードを検索'],['筛选卡片系列','Filter card archetype','カードシリーズで絞り込み'],['组卡按发行年份筛选','Filter deck-building cards by release year','構築用カードを発売年で絞り込み'],['对方魔法与陷阱区域','Opponent Spell/Trap Zones','相手の魔法＆罠ゾーン'],['对方怪兽区域','Opponent Monster Zones','相手のモンスターゾーン'],['额外怪兽区域','Extra Monster Zones','EXモンスターゾーン'],['你的怪兽区域','Your Monster Zones','自分のモンスターゾーン'],['你的魔法与陷阱区域','Your Spell/Trap Zones','自分の魔法＆罠ゾーン'],['你的除外区','Your banished cards','自分の除外カード'],['对方的除外区','Opponent’s banished cards','相手の除外カード'],['你的额外卡组','Your Extra Deck','自分のEXデッキ'],['对方的额外卡组','Opponent’s Extra Deck','相手のEXデッキ'],['卡组名称需要1—40个字符。','Deck names need 1–40 characters.','デッキ名は1～40文字です。'],['再来一场决斗','Duel again','もう一度対戦'],['等待你的响应','Waiting for your response','あなたの応答待ち'],['对方思考中…','Opponent is thinking…','相手が考えています…'],['已完成','Complete','完了'],['查看决斗结果','View result','結果を見る'],['整理你的卡组，准备迎接下一次挑战。','Review your deck and prepare for the next challenge.','デッキを見直し、次の挑戦に備えましょう。'],['一个新的时机出现了。选择你的响应。','A response window is open. Choose your response.','発動タイミングです。応答を選んでください。'],['对方正在决定是否响应你的行动。','Your opponent is deciding how to respond.','相手が応答を選択しています。'],['选择攻击表示的怪兽，然后点击攻击目标。','Select an Attack Position monster, then its target.','攻撃表示のモンスターを選び、攻撃対象を指定します。'],['调整表示，布置后场，为下一回合做好准备。','Adjust positions and set your back row for the next turn.','表示形式と魔法・罠を整え、次のターンに備えましょう。'],['召唤怪兽，发动魔法，','Summon monsters, activate Spells,','モンスターを召喚し、魔法を発動して、'],['让你的战术从这里展开。','and put your strategy into motion.','ここから戦術を展開しよう。'],['对方正在展开战术，','Your opponent is making a play.','相手が戦術を展開しています。'],['留意每一次召唤与盖放。','Watch each Summon and Set.','召喚とセットに注目しましょう。']
 );
 rows.push(
 ['返回决斗场','Return to Duel Field','デュエルフィールドに戻る'],['主导航','Main navigation','メインナビゲーション'],['关闭窗口','Close dialog','ウィンドウを閉じる'],['以卡之名，改写命运','Rewrite destiny, one card at a time','カードと共に、運命を変える'],['你的决斗，随你设定。','Your Duel, your settings.','自分に合ったデュエル設定。'],['决斗音效','Duel sound effects','デュエル効果音'],['抽卡、召唤与战斗的声音。','Sounds for draws, Summons and battles.','ドロー・召喚・戦闘の効果音。'],['一点声音，让决斗更有温度。','Set your preferred sound level.','好みの音量に調整できます。'],['氛围音乐','Ambient music','環境音楽'],['缓慢的和弦，陪伴你的每次思考。','Gentle chords while you plan your next move.','次の一手を考えるための穏やかな音楽。'],['关闭粒子、震动和过渡动画。','Disable particles, shaking and transitions.','粒子・振動・画面切替の動きを抑えます。'],['对手行动速度','Opponent animation speed','相手の操作速度'],['选择适合自己的决斗节奏。','Choose a pace that suits you.','自分に合う進行速度を選択します。'],['沉浸','Normal','通常'],['完成对局','Duels played','対戦数'],['取得胜利','Wins','勝利数'],['决斗胜率','Win rate','勝率'],['保存并返回','Save and return','保存して戻る'],
 ['本场决斗已结束。','This Duel has ended.','このデュエルは終了しました。'],['观察公开信息，规划你的下一步。','Inspect public information and plan your next move.','公開情報を確認し、次の一手を考えよう。'],['请先完成当前效果或连锁选择。','Finish the current effect or chain choice first.','現在の効果・チェーン選択を先に完了してください。'],['对方回合：满足时机会自动提示快速效果。','Opponent’s turn: available Quick Effects will be offered at the correct time.','相手ターン中は、発動可能なタイミングでクイック効果が表示されます。'],['需要满足素材、等级或Link值与区域限制；融合怪兽通过相应魔法或效果登场。','Meet the material, Level or Link Rating and zone requirements. Fusion Monsters use the appropriate Spell or effect.','素材・レベル・リンク数・ゾーンの条件が必要です。融合モンスターは対応する魔法や効果で出します。'],['通常召唤已使用，可继续用特殊召唤或效果展开。','Your Normal Summon is used. You may still use Special Summons and effects.','通常召喚は使用済みです。特殊召喚や効果は引き続き使用できます。'],['当前没有可发动的效果或操作。','No actions are currently available for this card.','このカードに現在使用できる操作はありません。'],
 ['卡片说明随显示语言切换，百科链接可查看来源资料。','Card text follows the selected language. The encyclopedia link opens the source entry.','カードテキストは選択言語に切り替わります。百科リンクで元の情報を確認できます。'],['卡图优先使用本地内嵌图片。','Embedded artwork is used first.','内蔵イラストを優先します。'],['可在设置中启用在线原版卡图。','Online original artwork can be enabled in Settings.','設定でオンラインのカードイラストを有効にできます。'],['切换音效（M）','Toggle sound (M)','音声切替（M）'],['切换音效','Toggle sound','音声切替'],['全屏（F）','Fullscreen (F)','全画面（F）'],['便捷回合控制','Quick turn controls','簡易ターン操作'],['游戏与已内嵌卡图均可离线使用','The game and embedded artwork work offline','ゲームと内蔵画像はオフラインで利用できます'],
 ['已刷新本地卡图，缺失图片继续使用备用卡面。','Artwork refreshed. Missing images use placeholders.','画像を更新しました。読み込めない画像は代替表示になります。'],['新增卡图会在构建后显示。','New local artwork appears after rebuilding.','追加したローカル画像は再ビルド後に反映されます。'],['副本','Copy','コピー'],['我的卡组','My deck','自分のデッキ'],['首发年份','Release year','発売年'],['选择目标','Choose a target','対象を選択'],['请选择','Choose','選択'],['选择','Choose','選択'],['取消','Cancel','キャンセル'],['确认发动','Confirm activation','発動を確定'],['属性','Attribute','属性'],['共享','Shared','共有'],['额外区','Extra Zone','EXゾーン'],['额外','Extra','EX'],['封印的记忆','The Forbidden Pieces','封印されしパーツ'],['展开思路','Opening plan','展開のヒント'],['当前对局','Current Duel','現在のデュエル'],['双方','Both players','両プレイヤー'],['临时怪兽','Temporary monster','一時的なモンスター'],['原卡种类保留','Original card type retained','元のカード種類を保持']
 );
 rows.push(
 ['攻击','Attack','攻撃'],['伤害','Damage','ダメージ'],['回复','Recover LP','回復'],['移动','Move','移動'],['阶段','Phase','フェイズ'],['公开卡片','Reveal card','カードを公開'],['改变表示','Change position','表示形式を変更'],['丢弃','Discard','捨てる'],['叠放素材','Attach material','素材にする'],['返回场上','Return to the field','フィールドに戻る'],['装备','Equip','装備'],['设置灵摆刻度','Set Pendulum Scale','Pスケールを置く'],['魔','S','魔'],['罠','T','罠'],
 ['由卡片效果特殊召唤的衍生物；离场后消失。','A Token Special Summoned by a card effect. It ceases to exist when it leaves the field.','カード効果で特殊召喚されたトークン。フィールドを離れると消滅します。'],
 ['海马濑人','Seto Kaiba','海馬瀬人'],['暗之游戏','Yami Yugi','闇遊戯'],['游城十代','Jaden Yuki','遊城十代'],['克罗·霍根','Crow Hogan','クロウ・ホーガン'],['不动游星','Yusei Fudo','不動遊星'],['九十九游马','Yuma Tsukumo','九十九遊馬'],
 ['状态','Status','状態'],['音效开关','Sound toggle','効果音の切替'],['开启','On','オン'],['关闭音效','Mute','ミュート'],['开启音效','Unmute','ミュート解除'],['自己场上','Your field','自分フィールド'],['对方场上','Opponent field','相手フィールド'],['每回合','Each turn','毎ターン'],['结束当前回合','End this turn','このターンを終了'],['无法操作','Unavailable','操作不可'],['里侧守备','Face-down Defense','裏側守備表示'],['表侧','Face-up','表側'],['次数','Uses','回数'],['牌库','Collection','カード一覧'],['已保存','Saved','保存済み'],['规则','Rules','ルール'],['对局设置','Duel settings','対戦設定'],['观战','Watch','観戦'],['读取存档','Load save','セーブを読み込む']
 );
 rows.push(['副本','Copy','コピー'],['卡组已保存。','Deck saved.','デッキを保存しました。'],['你的决斗者','Your duelist','あなたのデュエリスト'],['自建卡组','Custom deck','自作デッキ'],['自己的战术，自己的命运。','Your strategy, your destiny.','自分の戦術、自分の運命。'],
 ['每次选择都算数','Every choice matters','一つひとつの選択が未来を変える'],['把握这一刻','Seize this moment','この瞬間をつかめ'],
 ['手牌需要主怪兽区；表侧额外灵摆需要可用的共享额外区或Link箭头指向的主怪兽区。','Hand monsters need Main Monster Zones; face-up Extra Deck Pendulums need an Extra Monster Zone or a linked Main Monster Zone.','手札はメインモンスターゾーン、表側EXのPモンスターはEXモンスターゾーンかリンク先が必要です。'],
 ['连接素材必须包含效果指定的怪兽，并满足Link值和区域条件。','Include the required monster and meet the Link Rating and zone requirements.','指定されたモンスターを含め、リンク数とゾーンの条件を満たしてください。'],
 ['融合素材的名称、属性或数量不满足这只怪兽的条件。','The Fusion Materials do not meet this monster’s name, Attribute or count requirements.','融合素材のカード名・属性・枚数が条件を満たしていません。'],
 ['这些选项需要各不相同。','Each selected option must be different.','それぞれ異なる項目を選んでください。'],
 ['必须先由万华镜特殊召唤','Must first be Special Summoned by Elegant Egotist.','最初に万華鏡－華麗なる分身－で特殊召喚する必要があります。'],
 ['战斗后适用攻击限制或延迟破坏','Applies its attack restriction or delayed destruction after battle.','戦闘後に攻撃制限または遅延破壊を適用します。'],
 ['通常融合怪兽；也视为恶魔系列卡','Non-Effect Fusion Monster; also treated as an Archfiend card.','効果を持たない融合モンスター。デーモンカードとしても扱います。'],
 ['伤害计算时使攻击怪兽攻击力归零，每次表侧存在限1次','Once while face-up: reduce the attacking monster’s ATK to 0 during damage calculation.','表側表示で存在する限り1度、ダメージ計算時に攻撃モンスターの攻撃力を0にします。'],
 ['融合素材代用：一次融合至多1张，其他素材必须准确','Use at most 1 Fusion substitute; all other materials must match exactly.','融合素材の代用は1枚まで。他の素材は正規のものが必要です。'],
 ['卡名在所有区域视为鹰身女妖，并共用同名3张限制','Always treated as Harpie Lady and shares its 3-copy deck limit.','全ての場所でハーピィ・レディとして扱い、合計3枚制限を共有します。'],
 ['盖卡不符发动时机则破坏；可发动的陷阱经后续连锁执行，之后本卡洗回卡组','If the Set card cannot activate at this timing, destroy it. This simulator resolves an activatable Trap through a subsequent Chain, then shuffles this card into the Deck.','発動タイミングが不適切なセットカードは破壊します。本作では発動できる罠を後続チェーンで処理し、その後このカードをデッキに戻します。'],
 ['只能由通灵盘依顺序放置','Can only be placed in order by Destiny Board.','ウィジャ盤の効果で順番に置くことだけができます。'],
 ['本作先指定替代除外的场上怪兽顺序，随后按该顺序替代墓地怪兽的除外；离场对象自动跳过','Simulator adaptation: choose the field monsters’ replacement order first. They replace Graveyard banishments in that order; monsters that have left the field are skipped.','本作の適用方法：代わりに除外する場のモンスターを先に順序指定します。その順で墓地からの除外を置き換え、場を離れたものは飛ばします。'],
 ['无效以自身为对象的魔法；抽卡阶段可用4星以下战士族检索替代通常抽卡','Negates Spells targeting itself. During the Draw Phase, search a Level 4 or lower Warrior instead of the normal draw.','自身を対象とする魔法を無効にします。ドローフェイズに通常のドローの代わりにレベル4以下の戦士族をサーチできます。'],
 ['对方攻击宣言时，由此卡控制者选择合法攻击对象','When the opponent declares an attack, this card’s controller chooses a legal attack target.','相手の攻撃宣言時、このカードのコントローラーが適切な攻撃対象を選びます。']
 );
 rows.push(
 ['对战模式','Match mode','対戦モード'],['我 vs 机器人','Me vs Robot','自分 vs ロボット'],['机器人 vs 机器人','Robot vs Robot','ロボット vs ロボット'],['机器人 A','Robot A','ロボットA'],['机器人 B','Robot B','ロボットB'],['机器人 A 的卡组','Robot A deck','ロボットAのデッキ'],['机器人 B 的卡组','Robot B deck','ロボットBのデッキ'],['机器人 A 的手牌','Robot A hand','ロボットAの手札'],['机器人难度','Robot difficulty','ロボットの強さ'],
 ['为机器人 A 和机器人 B 各选一副卡组。观战时双方手牌与盖牌全部公开，先后手由猜拳决定。','Pick a deck for Robot A and Robot B. While spectating, both hands and Set cards are revealed; rock-paper-scissors decides who goes first.','ロボットAとロボットBのデッキを選びます。観戦中は両者の手札とセットカードが公開され、じゃんけんで先攻を決めます。'],
 ['✊ ✌️ 🖐️ 先后手由猜拳决定','✊ ✌️ 🖐️ Rock-paper-scissors decides turn order','✊ ✌️ 🖐️ じゃんけんで先攻・後攻を決定'],['让两位机器人一决高下。','Let two robots settle it.','2体のロボットに決着をつけさせよう。'],['开始观战','Start spectating','観戦開始'],['猜拳','Rock-paper-scissors','じゃんけん'],['石头','Rock','グー'],['剪刀','Scissors','チョキ'],['布','Paper','パー'],['机器人 A 先攻','Robot A goes first','ロボットAが先攻'],['机器人 B 先攻','Robot B goes first','ロボットBが先攻'],
 ['观战模式','Spectator mode','観戦モード'],['观战中','Spectating','観戦中'],['暂停','Pause','一時停止'],['继续','Resume','再開'],['单步','Step','1手進む'],['更换机器人','Change robots','ロボットを変更'],['观战模式：机器人自动行动','Spectator mode: robots act automatically','観戦モード：ロボットが自動で行動します'],['观战模式 · 点击可查看卡牌','Spectator mode · click to inspect cards','観戦モード・カードをクリックで確認'],
 ['已暂停。可以逐步观察每一次结算，或继续自动播放。','Paused. Step through each resolution, or resume automatic play.','一時停止中。1手ずつ確認するか、自動再生を再開できます。'],['机器人 A 正在决定是否响应。','Robot A is deciding whether to respond.','ロボットAが応答するか判断しています。'],['机器人 B 正在决定是否响应。','Robot B is deciding whether to respond.','ロボットBが応答するか判断しています。'],['机器人 A 正在行动，双方手牌与盖牌全部可见。','Robot A is acting. Both hands and Set cards are visible.','ロボットAが行動中。両者の手札とセットカードはすべて公開されています。'],['机器人 B 正在行动，双方手牌与盖牌全部可见。','Robot B is acting. Both hands and Set cards are visible.','ロボットBが行動中。両者の手札とセットカードはすべて公開されています。'],['决斗已经结束，可以查看记录或开始新的对战。','The duel is over. Review the log or start a new match.','デュエル終了。記録を確認するか、新しい対戦を始められます。'],
 ['观战模式下双方的手牌与盖牌都是公开的；暂停后可以逐步查看每一次结算。','In spectator mode both hands and Set cards are public; pause to step through each resolution.','観戦モードでは両者の手札とセットカードが公開されます。一時停止すれば1手ずつ確認できます。'],['机器人 A 先攻，观战开始。','Robot A goes first. Spectating begins.','ロボットAが先攻。観戦開始。'],['机器人 B 先攻，观战开始。','Robot B goes first. Spectating begins.','ロボットBが先攻。観戦開始。'],['已暂停观战。','Spectating paused.','観戦を一時停止しました。'],['继续观战。','Spectating resumed.','観戦を再開しました。'],
 ['机器人没有可执行的行动，已暂停。','The robot has no legal action; paused.','ロボットに実行できる行動がないため一時停止しました。'],['机器人行动遇到错误，已暂停观战。','A robot action failed; spectating paused.','ロボットの行動でエラーが発生したため観戦を一時停止しました。'],['机器人 A 获胜','Robot A wins','ロボットAの勝利'],['机器人 B 获胜','Robot B wins','ロボットBの勝利'],['决斗平局','Draw','引き分け'],['赢下了这场机器人对决。','won this robot duel.','がロボット対決を制しました。'],['A 造成伤害','Damage by A','Aの与ダメージ'],['B 造成伤害','Damage by B','Bの与ダメージ'],['机器人 A 的回合','Robot A turn','ロボットAのターン'],['机器人 B 的回合','Robot B turn','ロボットBのターン'],['机器人 A 的手牌：','Robot A hand: ','ロボットAの手札：'],['机器人 B 的手牌：','Robot B hand: ','ロボットBの手札：'],['机器人 A 的','Robot A’s ','ロボットAの'],['机器人 B 的','Robot B’s ','ロボットBの'],['平局后重猜','Rethrow after a tie','あいこで再戦']
 );
 const messages=Object.fromEntries(rows.map(([zh,en,ja])=>[zh,{en,ja}]));
 const patterns=[
 ['^(.+)抽了([0-9]+)张卡$','$1 drew $2 card(s)','$1が$2枚ドローした'],
 ['^(.+)将卡组顶([0-9]+)张卡送墓$','$1 sent the top $2 cards to the Graveyard','$1がデッキの上から$2枚を墓地へ送った'],
 ['^(.+)受到 ([0-9]+) 点(.+)伤害$','$1 took $2 $3 damage','$1が$2の$3ダメージを受けた'],
 ['^(.+)回复 ([0-9]+) (?:LP|点生命值)$','$1 recovered $2 LP','$1が$2 LP回復した'],
 ['^(.+)支付 ([0-9]+) LP$','$1 paid $2 LP','$1が$2 LP払った'],
 ['^(.+)将「(.+)」加入手牌$','$1 added "$2" to the hand','$1が「$2」を手札に加えた'],
 ['^(.+?)(通常召唤|特殊召唤|仪式召唤|融合召唤|同调召唤|超量召唤|连接召唤|灵摆召唤|盖放)「(.+)」$','$1: $2 "$3"','$1：「$3」を$2'],
 ['^(.+)发动「(.+)」$','$1 activated "$2"','$1が「$2」を発動した'],
 ['^(.+)攻击「(.+)」$','$1 attacks "$2"','$1が「$2」に攻撃'],
 ['^(.+)攻击里侧怪兽$','$1 attacks a face-down monster','$1が裏側モンスターに攻撃'],
 ['^(.+)发动直接攻击$','$1 attacks directly','$1が直接攻撃'],
 ['^(.+)的攻击被无效$','$1’s attack was negated','$1の攻撃が無効になった'],
 ['^「(.+)」的(发动|效果)被无效$','The $2 of "$1" was negated','「$1」の$2が無効になった'],
 ['^「(.+)」的效果未能适用$','The effect of "$1" was not applied','「$1」の効果は適用されなかった'],
 ['^(.+)变为(攻击|守备)表示$','$1 changed to $2 Position','$1が$2表示になった'],
 ['^(.+)盖放了1张魔法(?:／|或)陷阱卡$','$1 Set a Spell/Trap','$1が魔法・罠を1枚セットした'],
 ['^(.+)结束了回合$','$1 ended the turn','$1がターンを終了した'],
 ['^(.+)进入结束阶段$','$1 entered the End Phase','$1がエンドフェイズへ進んだ'],
 ['^(.+)的回合$','$1’s turn','$1のターン'],
 ['^里侧怪兽是「(.+)」$','The face-down monster was "$1"','裏側モンスターは「$1」だった'],
 ['^(.+)成为「(.+)」的超量素材$','$1 became an Xyz Material of "$2"','$1が「$2」のX素材になった'],
 ['^需选 ([0-9]+) 项 · 已选 ([0-9]+)$','Choose $1 · Selected $2','$1項目選択・選択済み$2'],
 ['^需要选择([0-9]+)个选项。$','Choose $1 option(s).','$1項目を選択してください。'],
 ['^由你亲手构筑的([0-9]+)张主卡组，包含([0-9]+)张额外卡组。$','Your own deck of $1 Main Deck and $2 Extra Deck cards.','自分で構築したメイン$1枚・EX$2枚のデッキです。'],
 ['^([0-9]+) 张$','$1 cards','$1枚'],
 ['^查看(.+)$','View $1','$1を見る'],['^移除(.+)$','Remove $1','$1を取り除く'],['^加入(.+)$','Add $1','$1を追加'],['^([0-9]+) 张主卡组$','$1 Main Deck cards','メインデッキ$1枚'],['^([0-9]+) 张额外$','$1 Extra Deck cards','EXデッキ$1枚'],['^主卡组需要40—60张，当前([0-9]+)张。$','Main Deck needs 40–60 cards; currently $1.','メインデッキは40～60枚です（現在$1枚）。'],['^额外卡组最多15张，当前([0-9]+)张。$','Extra Deck may contain at most 15 cards; currently $1.','EXデッキは15枚までです（現在$1枚）。'],['^对方有([0-9]+)张手牌$','Opponent has $1 cards in hand','相手の手札$1枚'],['^对方的卡组，剩余([0-9]+)张$','Opponent’s Deck: $1 cards remaining','相手デッキ：残り$1枚'],['^你的卡组，剩余([0-9]+)张$','Your Deck: $1 cards remaining','自分のデッキ：残り$1枚'],['^你的墓地，([0-9]+)张$','Your Graveyard: $1 cards','自分の墓地：$1枚'],['^对方的墓地，([0-9]+)张$','Opponent’s Graveyard: $1 cards','相手の墓地：$1枚'],
 ['^([0-9]+) · 首年$','$1 · First year','$1・初年度'],['^([0-9]+) · 第二年$','$1 · Year two','$1・2年目'],['^([0-9]+) · 第三年$','$1 · Year three','$1・3年目'],['^截至 ([0-9]+)$','Through $1','$1年まで'],
 ['^第 ([0-9]+) 回合$','Turn $1','$1ターン目'],['^第([0-9]+)回合$','Turn $1','$1ターン目'],['^([0-9]+) 星$','Level $1','レベル$1'],['^等级 ?([0-9]+)$','Level $1','レベル$1'],['^阶级 ?([0-9]+)$','Rank $1','ランク$1'],['^素材 ([0-9]+)$','$1 materials','素材$1'],['^魔力指示物 ([0-9]+)$','$1 Spell Counters','魔力カウンター$1'],['^楔指示物 ([0-9]+)$','$1 Wedge Counters','楔カウンター$1'],
 ['^([0-9]+) / ([0-9]+) 张卡片.*$','$1 / $2 cards','$1 / $2枚'],['^([0-9]+) 张卡片 / ([0-9]+) 张已解锁$','$1 cards / $2 unlocked','$1枚 / $2枚解放済み'],['^主怪兽区 ([0-9]+)$','Main Monster Zone $1','メインモンスターゾーン$1'],['^共享额外区 (.+)$','Shared Extra Zone $1','共有EXゾーン$1'],['^灵摆刻度 ([0-9]+)$','Pendulum Scale $1','Pスケール$1'],['^上级召唤 · ([0-9]+)份祭品$','Tribute Summon · $1 Tributes','アドバンス召喚・$1体リリース'],
 ['^已选 ([0-9]+) 项$','$1 selected','$1項目選択'],['^需选 ([0-9]+)(?:—([0-9]+))? 项 · 已选 ([0-9]+)$','Choose $1–$2 · Selected $3','$1～$2項目・選択済み$3'],['^需要选择([0-9]+)(?:—([0-9]+))?个选项。$','Choose $1–$2 options.','$1～$2項目を選択してください。'],['^解放等级合计 ([0-9]+) / 仪式魔法要求 ([0-9]+) 星$','Tribute Levels: $1 / required: $2','リリースのレベル合計 $1 / 必要レベル $2'],
 ['^支付 ([0-9]+) LP$','Pay $1 LP','$1 LPを払う'],['^选择(.+)的([0-9]+)张手牌$','Choose $2 cards from $1 hand','$1の手札を$2枚選択'],['^([0-9]+)套预设，或一副亲手构筑的卡组。$','$1 presets, or a deck of your own.','$1種類のプリセット、または自分で構築したデッキ。'],['^已选择 · (.+)$','Selected · $1','選択中・$1'],['^合法组合 · 共 ([0-9]+) 种$','$1 legal combinations','有効な組み合わせ：$1通り'],['^原本 (.+)$','Original $1','元々の$1']
 ];
 const deckNames={
  blue:['Blue-Eyes Awakening','青眼の覚醒'],dark:['Legacy of the Dark Magician','ブラック・マジシャンの継承'],hero:['E·HERO · Sunrise','E・HERO・夜明け'],blackwing:['Blackwing · Wings of the Storm','BF・嵐の翼'],junk:['Junk · Beyond Acceleration','ジャンク・加速の彼方'],utopia:['Utopia · Light of Hope','希望皇・希望の光'],qliphort:['Qliphort · System Reboot','クリフォート・再起動'],exodia:['Exodia · The Forbidden One','エクゾディア・封印されし力'],cyber:['Cyber Dragon · Evolution','サイバー・ドラゴン・進化'],crystron:['Crystron · Resonance','クリストロン・共鳴'],tearlaments:['Tearlaments · Echoes of the Abyss','ティアラメンツ・壱世壊の歌声'],'early-ritual':['Ritual · The First Oath','儀式・混沌の降臨'],'early-fusion':['Fusion · The First Bonds','融合・始まりの絆']
 };
 const deckDescriptions={
  blue:['Summon Blue-Eyes White Dragon and combine its power through Fusion.','青眼の白龍を呼び出し、融合でその力を束ねよう。'],dark:['Build magical resources and support the Dark Magician with Spells and Traps.','魔力を蓄え、魔法・罠でブラック・マジシャンを支えよう。'],hero:['Search HERO allies and use Fusion or Mask Change to respond to the field.','HEROをサーチし、融合とマスク・チェンジで戦局に対応しよう。'],blackwing:['Combine Blackwing Tuners and allies for successive Synchro Summons.','BFのチューナーと仲間を組み合わせ、シンクロ召喚をつなごう。'],junk:['Revive small monsters and tune their Levels for powerful Synchro plays.','小型モンスターを蘇生し、レベルを合わせてシンクロ召喚しよう。'],utopia:['Build matching Levels, Xyz Summon Utopia and upgrade its materials.','レベルを揃えてホープをX召喚し、素材を引き継いで進化させよう。'],qliphort:['Set Pendulum Scales, summon Qli monsters and turn them into Tribute resources.','Pスケールを揃え、クリフォートを展開してリリースにつなげよう。'],exodia:['Draw and search carefully to gather all five different Exodia pieces.','ドローとサーチで、異なる5種類のエクゾディアパーツを集めよう。'],cyber:['Use Cyber Dragon names and Machine combinations for Fusion and Xyz Summons.','サイバー・ドラゴンのカード名と機械族の連携で、融合・X召喚を狙おう。'],crystron:['Prepare Tuners, the Graveyard and banished cards for Synchro Summons on either turn.','チューナー・墓地・除外カードを整え、相手ターンにもシンクロ召喚しよう。'],tearlaments:['Send Tearlaments by card effects, recycle Fusion Materials, and extend through Link Monsters.','効果でティアラメンツを墓地へ送り、素材を戻して融合し、リンクにつなげよう。'],'early-ritual':['Senju finds Ritual Monsters and Sonic Bird finds Ritual Spells. Tribute the required Levels to summon Black Luster Soldier or Relinquished.','センジュ・ゴッドで儀式モンスター、ソニックバードで儀式魔法をサーチ。必要なレベルをリリースし、カオス・ソルジャーやサクリファイスを呼ぼう。'],'early-fusion':['Use classic named materials, Polymerization and Flip Effects to build your first Fusion strategy.','初期の指定素材・融合・リバース効果を活用して、融合戦術を組み立てよう。']
 };
 root.DuelUITranslations={messages,patterns,deckNames,deckDescriptions};if(typeof module!=='undefined')module.exports=root.DuelUITranslations;
})(globalThis);
