(function(root){
  'use strict';
  const D=root.DuelData?.expansionLoaded?root.DuelData:require('./expansion-cards.js');
  if(D.linkExpansionLoaded){if(typeof module!=='undefined')module.exports=D;return;}
  const {CARDS,CARD_LIST,DECKS}=D;
  const add=c=>{if(CARDS[c.id])throw new Error('Duplicate card '+c.id);c.en=c.officialName.toUpperCase();c.art=c.id;c.expansion=true;c.tearlaments=/^Tearlaments\b/.test(c.officialName);CARDS[c.id]=c;CARD_LIST.push(c);return c;};
  const M=(id,name,officialName,level,atk,def,attribute,race,description,extra={})=>add({id,name,officialName,type:'monster',level,atk,def,attribute,race,family:'tearlaments',description,effect:id,...extra});
  const S=(id,name,officialName,description,extra={})=>add({id,name,officialName,type:'spell',attribute:'魔',family:'tearlaments',spellKind:'normal',description,effect:id,...extra});
  const T=(id,name,officialName,description,extra={})=>add({id,name,officialName,type:'trap',attribute:'罠',family:'tearlaments',trapKind:'normal',description,effect:id,...extra});
  const F=(id,name,officialName,level,atk,def,attribute,race,description,fusion,extra={})=>M(id,name,officialName,level,atk,def,attribute,race,description,{type:'fusion',fusion,...extra});
  const L=(id,name,officialName,rating,atk,attribute,race,arrows,link,description)=>M(id,name,officialName,0,atk,null,attribute,race,description,{type:'link',family:'link',linkRating:rating,arrows,link});
  const tearFusion='此卡被效果送去墓地时，可以将自己手牌、场上、墓地的素材放回卡组最下方进行融合召唤，必须包含墓地的此卡。两个效果各每回合只能使用1次。';
  M('tear-reinoheart','珠泪哀歌族·雷诺哈特','Tearlaments Reinoheart',4,1500,2100,'水','战士族','召唤或特殊召唤时，可以将卡组中此卡以外的1只「珠泪哀歌族」送墓。被效果送墓时，可特殊召唤此卡（离场时除外），并将手牌1张「珠泪哀歌族」送墓。每个效果每回合1次。',{aiValue:4000,normalPriority:850});
  M('tear-scheiren','珠泪哀歌族·塞壬人鱼','Tearlaments Scheiren',4,1800,1300,'暗','水族','自己的主要阶段，可以从手牌特殊召唤此卡，再将手牌1只怪兽送墓，然后将卡组顶3张送墓。'+tearFusion,{aiValue:4200});
  M('tear-havnis','珠泪哀歌族·哈弗人鱼','Tearlaments Havnis',3,1600,1000,'暗','水族','对方发动场上怪兽的效果时（快速效果），可从手牌特殊召唤此卡，然后将自己卡组顶3张送墓。'+tearFusion,{aiValue:3600});
  M('tear-merrli','珠泪哀歌族·梅洛人鱼','Tearlaments Merrli',2,800,2000,'暗','水族','召唤或特殊召唤时，可以将自己卡组顶3张送墓。'+tearFusion,{aiValue:3800,normalPriority:800});
  M('tear-kashtira','珠泪哀歌族·俱舍怒威族','Tearlaments Kashtira',7,2300,1200,'水','念动力族','双方主要阶段（快速效果），可以从手牌特殊召唤此卡，并除外手牌或墓地1张「俱舍怒威族」或「珠泪哀歌族」。召唤或特殊召唤时，可将任意一方卡组顶3张送墓。被效果送墓时，可将自己卡组顶2张送墓。每个效果每回合1次。',{aiValue:3900});
  F('tear-kitkallos','珠泪哀歌族·水仙女人鱼','Tearlaments Kitkallos',5,2300,1200,'暗','水族','「珠泪哀歌族」怪兽＋水族怪兽。特殊召唤时，可将卡组1张「珠泪哀歌族」加入手牌或送墓。以自己1只怪兽为对象，从手牌或墓地特殊召唤1只「珠泪哀歌族」，再把对象送墓。被效果送墓时，可以将卡组顶5张送墓。每个效果每回合1次。',[{tearlaments:true},{race:'水族'}],{aiValue:7000});
  F('tear-rulkallos','珠泪哀歌族·鲁莎卡人鱼','Tearlaments Rulkallos',8,3000,2500,'水','水族','「水仙女人鱼」＋「珠泪哀歌族」怪兽。自己的其他水族怪兽不会被战斗破坏。每回合各1次：对方发动包含特殊召唤的效果时，无效发动并破坏，然后将自己手牌或表侧场上1张「珠泪哀歌族」送墓；融合召唤的此卡被效果送墓时，可特殊召唤此卡。',[{id:'tear-kitkallos'},{tearlaments:true}],{aiValue:7500});
  F('tear-kaleido-heart','珠泪哀歌族·卡雷多哈特','Tearlaments Kaleido-Heart',9,3000,3000,'暗','恶魔族','「雷诺哈特」＋水族怪兽2只。不能作为融合素材。特殊召唤时，或自己水族怪兽被效果送墓时，可以将对方场上1张卡洗回卡组。此卡被效果送墓时，可特殊召唤此卡，再将卡组1张「珠泪哀歌族」送墓。每个效果每回合1次。',[{id:'tear-reinoheart'},{race:'水族'},{race:'水族'}],{cannotFusionMaterial:true,aiValue:7500});
  S('perlereino','壹世坏－珍珠世界','Primeval Planet Perlereino','发动时，可检索1只「珠泪哀歌族」或「维萨斯－斯塔弗罗斯特」。自己的融合怪兽及「珠泪哀歌族」怪兽攻击力上升500。每回合1次，自己场上或墓地的「珠泪哀歌族」怪兽返回卡组或额外卡组时，可破坏场上1张卡。此卡名每回合只能发动1张。',{spellKind:'field'});
  S('tear-scream','壹世坏劈开的弦声','Tearlaments Scream','怪兽召唤或特殊召唤时，若自己控制「珠泪哀歌族」或「维萨斯－斯塔弗罗斯特」，可以将自己卡组顶3张送墓，使对方全体怪兽本回合攻击力下降500。此卡被效果送墓时，可以检索1张「珠泪哀歌族」陷阱。每个效果每回合1次。',{spellKind:'continuous'});
  S('tear-heartbeat','壹世坏摇荡的鼓动','Tearlaments Heartbeat','以场上1张魔法／陷阱为对象（控制「维萨斯－斯塔弗罗斯特」时可以选2张），洗回卡组，再将手牌1张卡送墓。被效果送墓时，可以回收墓地1张「珠泪哀歌族」陷阱。每个效果每回合1次。',{spellKind:'quick'});
  S('tear-grief','珠泪哀歌族的悲恸','Tearlaments Grief','从卡组特殊召唤1只「珠泪哀歌族」或「维萨斯－斯塔弗罗斯特」，再将自己1只与其种族或属性相同的怪兽送墓（可以选择刚召唤的怪兽）。被效果送墓时，可将1张除外的「珠泪哀歌族」陷阱加入手牌。每个效果每回合1次。');
  T('tear-sulliek','壹世坏奏响的哀唱','Tearlaments Sulliek','控制「珠泪哀歌族」或「维萨斯－斯塔弗罗斯特」时，以对方1只表侧怪兽为对象，无效其效果，再将自己1只怪兽送墓。此卡被效果送墓时，可以检索1只「珠泪哀歌族」。每个效果每回合1次。',{trapKind:'continuous'});
  T('tear-metanoise','壹世坏摩擦的爪音','Tearlaments Metanoise','控制「珠泪哀歌族」或「维萨斯－斯塔弗罗斯特」时，使对方1只表侧怪兽变为里侧守备，再将卡组1只「珠泪哀歌族」送墓。Link怪兽及衍生物不能成为此效果的对象。被效果送墓时，可回收墓地1只「珠泪哀歌族」。每个效果每回合1次。');
  T('tear-cryme','壹世坏清澈的残响','Tearlaments Cryme','控制「珠泪哀歌族」或「维萨斯－斯塔弗罗斯特」时，无效魔法／陷阱卡或怪兽效果的发动，并将那张卡洗回卡组，再将手牌1只怪兽送墓。被效果送墓时，可将1只除外的「珠泪哀歌族」加入手牌。每个效果每回合1次。',{trapKind:'counter'});
  M('supreme-sea-mare','绝海之马','Supreme Sea Mare',4,1700,200,'水','水族','召唤或特殊召唤时，可以将卡组中此卡以外的1只水族送墓。自己的结束阶段，可以解放此卡，以墓地中此卡以外的1只水族为对象，将其加入手牌。每个效果每回合1次。',{family:'generic',normalPriority:700});
  M('dd-crow','异次元乌鸦','D.D. Crow',1,100,100,'暗','鸟兽族','快速效果：从手牌丢弃此卡，以对方墓地1张卡为对象，将其除外。丢弃是发动代价。',{family:'generic',aiValue:2200});
  S('terraforming','星球改造','Terraforming','从卡组将1张场地魔法加入手牌。',{family:'generic'});
  M('abyss-dweller','深渊的潜伏者','Abyss Dweller',0,1700,1400,'水','海龙族','2只4星怪兽。持有原本是水属性的素材时，自己的水属性怪兽攻击力上升500。每回合1次（快速效果），移除1个素材，本回合对方不能发动墓地的卡片效果。已经发动的效果不会因此无效。',{type:'xyz',rank:4,xyzCount:2,family:'generic'});
  L('linkuriboh','连接栗子球','Linkuriboh',1,300,'暗','电子界族',['B'],{min:1,max:1,level:1},'1只1星怪兽。对方怪兽攻击宣言时，可以解放此卡，使那只攻击怪兽本回合攻击力变为0。在墓地时（快速效果），可以解放自己1只1星怪兽，特殊召唤此卡；这个墓地效果每回合1次。');
  L('ip-masquerena','I：P 伪装舞会莱娜','I:P Masquerena',2,800,'暗','电子界族',['BL','BR'],{min:2,max:2,nonLink:true},'2只Link怪兽以外的怪兽。每回合1次，对方主要阶段（快速效果），可以用包含此卡的自己怪兽进行连接召唤。用此卡作为素材连接召唤的怪兽，不会被对方的效果破坏。');
  L('knightmare-phoenix','梦幻崩影·凤凰','Knightmare Phoenix',2,1900,'炎','恶魔族',['T','R'],{min:2,max:2,differentNames:true},'2只卡名不同的怪兽。连接召唤时，可以丢弃1张手牌，以对方1张魔法／陷阱为对象破坏；发动时处于互相连接状态则再抽1张。该效果每回合1次。自己互相连接的怪兽不会被战斗破坏。');
  L('knightmare-unicorn','梦幻崩影·独角兽','Knightmare Unicorn',3,2200,'暗','恶魔族',['L','B','R'],{min:2,differentNames:true},'2只以上卡名不同的怪兽。连接召唤时，可以丢弃1张手牌，以场上1张卡为对象洗回卡组；发动时处于互相连接状态则再抽1张。该效果每回合1次。场上互相连接的「梦幻崩影」有2种以上时，自己的通常抽卡张数改为那些怪兽的种类数。');
  L('dharc-charmer','暗灵使 达克','Dharc the Dark Charmer, Gloomy',2,1850,'暗','魔法师族',['BL','BR'],{min:2,max:2,attribute:'暗'},'包含暗属性怪兽的2只怪兽。每回合各1次：将对方墓地1只暗属性怪兽特殊召唤到此卡箭头指向的自己区域；连接召唤的此卡在原持有者控制下被战斗或对方效果破坏时，检索1只守备力1500以下的暗属性怪兽。');
  L('eria-charmer','清冽之水灵使 艾莉娅','Eria the Water Charmer, Gentle',2,1850,'水','魔法师族',['BL','BR'],{min:2,max:2,attribute:'水'},'包含水属性怪兽的2只怪兽。每回合各1次：将对方墓地1只水属性怪兽特殊召唤到此卡箭头指向的自己区域；连接召唤的此卡在原持有者控制下被战斗或对方效果破坏时，检索1只守备力1500以下的水属性怪兽。');
  L('cross-sheep','交织绵羊','Cross-Sheep',2,700,'地','兽族',['BL','BR'],{min:2,max:2,differentNames:true},'2只卡名不同的怪兽。每回合1次，怪兽在此卡箭头指向的区域特殊召唤时，依结算时指向怪兽的类型顺序处理：仪式，抽2张卡并丢弃2张手牌；融合，复活墓地1只4星以下怪兽；同调，自己怪兽攻击力上升700；超量，对方怪兽攻击力下降700。');
  L('apollousa','召命之神弓－阿波罗萨','Apollousa, Bow of the Goddess',4,0,'风','天使族',['T','BL','B','BR'],{min:2,differentNames:true,noTokens:true},'2只以上卡名不同且不是衍生物的怪兽。此卡的原本攻击力变为连接素材数量×800。每条连锁只能发动1次：对方发动怪兽效果时，可以使此卡攻击力下降整800，并无效那个发动。');
  L('accesscode-talker','访问码语者','Accesscode Talker',4,2300,'暗','电子界族',['T','L','R','B'],{min:2,effect:true},'2只以上效果怪兽。对方不能连锁此卡的效果。连接召唤时，以作为这次连接素材的1只Link怪兽为对象，攻击力上升其Link值×1000。可除外自己场上或墓地1只Link怪兽，破坏对方场上1张卡；此效果适用后，本回合不能再以相同属性支付这个效果的代价。');
  const expand=pairs=>pairs.flatMap(([id,n])=>Array(n).fill(id));
  DECKS.tearlaments={id:'tearlaments',name:'珠泪 · 壹世坏的回响',en:'TEARLAMENTS · ECHOES OF THE ABYSS',ace:'tear-rulkallos',player:'壹世坏的歌者',avatar:'tearlaments',mechanic:'融合 / Link',preset:true,description:'让被效果送墓的珠泪唤起融合，用交织绵羊续接资源，再由I：P、独角兽与访问码把连接转为胜机。',subtitle:'沉入墓地的，是下一段歌声。',combo:['雷诺哈特送墓梅洛或塞壬，用墓地珠泪洗回素材融合水仙女人鱼。水仙送自身并拉出梅洛，触发合计8张堆墓。','两只不同名怪兽连接交织绵羊，再把融合怪兽召唤到箭头指向区，复活低星怪兽。I：P可在对方主要阶段连接独角兽；访问码利用Link素材提升攻击力。'],cards:expand([['tear-reinoheart',3],['tear-scheiren',3],['tear-havnis',3],['tear-merrli',3],['tear-kashtira',3],['supreme-sea-mare',3],['dd-crow',2],['perlereino',3],['tear-scream',3],['tear-heartbeat',2],['tear-grief',2],['foolish-burial',1],['monster-reborn',1],['terraforming',1],['tear-sulliek',3],['tear-cryme',2],['tear-metanoise',2]]),extra:expand([['tear-kitkallos',2],['tear-rulkallos',2],['tear-kaleido-heart',2],['abyss-dweller',1],['ip-masquerena',1],['knightmare-phoenix',1],['knightmare-unicorn',1],['dharc-charmer',1],['eria-charmer',1],['cross-sheep',1],['apollousa',1],['accesscode-talker',1]])};
  D.families.tearlaments='珠泪哀歌族';D.families.link='连接 / Link';D.linkExpansionLoaded=true;D.rulesVersion=3;
  root.DuelData=D;if(typeof module!=='undefined'&&module.exports)module.exports=D;
})(globalThis);
