(function(root){
  'use strict';
  const tr=(zh,en,ja)=>root.DuelI18n.language==='en'?en:root.DuelI18n.language==='ja'?ja:zh;
  function setup(format='bo1',prefix='choose-match-format'){
    return '<div class="setup-mode match-format"><label class="setting-label">'+tr('赛制','Match format','対戦形式')+'</label><div class="segmented-control">'+[['bo1',tr('一局定胜负','Best of one','シングル戦')],['bo3',tr('三局两胜','Best of three','マッチ戦')]].map(([v,label])=>'<button type="button" data-action="'+prefix+'" data-value="'+v+'" class="'+(format===v?'active':'')+'" aria-pressed="'+(format===v)+'">'+label+'</button>').join('')+'</div><p>'+tr('三局两胜：败者选择先后攻，局间自由换备；平局补赛，连续三平结束。','BO3: loser chooses turn order; side between games. Draws are replayed; three consecutive draws end the match.','マッチ戦：敗者が先後攻を選択。局間にサイド変更。同点は再戦、3連続引き分けで終了。')+'</p></div>';
  }
  function history(m,prefix='match-'){return '<table class="match-history"><thead><tr><th>'+tr('局','Game','デュエル')+'</th><th>'+tr('先攻','First','先攻')+'</th><th>'+tr('结果','Result','結果')+'</th><th>'+tr('回合','Turns','ターン')+'</th></tr></thead><tbody>'+m.games.map(g=>'<tr><td>'+g.index+'</td><td>'+(g.first===0?tr('我方','You','自分'):tr('对手','Opponent','相手'))+'</td><td>'+(g.winner==='draw'?tr('平局','Draw','引き分け'):g.winner===0?tr('胜','Win','勝利'):tr('负','Loss','敗北'))+'</td><td>'+g.turn+' <button data-action="'+prefix+'journal" data-game-id="'+g.id+'">'+tr('记录','Journal','記録')+'</button></td></tr>').join('')+'</tbody></table>';}
  function title(m){return m.phase==='playing'?tr('比赛进行中','Match in progress','マッチ進行中'):m.phase!=='finished'?tr('局间准备','Between games','局間の準備'):m.result?.status==='aborted'?tr('比赛中止','Match aborted','マッチ中止'):m.result?.winner==='draw'?tr('整场平局','Match drawn','マッチ引き分け'):m.result?.winner===0?tr('整场胜利','Match won','マッチ勝利'):tr('整场告负','Match lost','マッチ敗北');}
  function panel(m,prefix='match-'){
    return '<div class="match-score">'+m.score.join(' : ')+'</div>'+history(m,prefix)+(m.phase==='choosing-first'?'<p>'+tr('上一局败者选择下一局先后攻。','The previous loser chooses the next first player.','前局の敗者が次の先後攻を選びます。')+'</p>'+(m.round.chooser===0?'<div class="match-actions"><button class="primary-button" data-action="'+prefix+'first" data-value="0">'+tr('我先攻','Go first','先攻')+'</button><button class="secondary-button" data-action="'+prefix+'first" data-value="1">'+tr('我后攻','Go second','後攻')+'</button></div>':'<p>'+tr('等待对手选择','Waiting for opponent','相手の選択を待っています')+'</p>'):m.phase==='siding'?'<p>'+tr('下一局先攻：','Next first player: ','次の先攻：')+(m.round.nextFirst===0?tr('我方','You','自分'):tr('对手','Opponent','相手'))+'</p><div class="match-actions"><button class="primary-button" data-action="'+prefix+'side">'+(m.round.ready[0]?tr('已确认 · 查看构筑','Confirmed · view deck','確定済み・デッキを確認'):tr('换备 / 保持构筑并准备','Side deck / ready unchanged','サイド変更 / 変更せず準備'))+'</button></div><p>'+tr('对手：','Opponent: ','相手：')+(m.round.ready[1]?tr('已准备','Ready','準備完了'):tr('准备中','Preparing','準備中'))+'</p>':'')+
      (m.round?'<p data-match-clock>'+tr('PVE可随时继续；PVP以服务器计时为准。','PVE has no intermission timer; PVP uses the server clock.','PVEの局間は時間制限なし。PVPはサーバー時計を使用。')+'</p>':'');
  }
  function help(){return '<section class="help-section"><h3>BO1 / BO3 · '+tr('副卡组','Side deck','サイドデッキ')+'</h3><p>'+tr('可在开局或联机大厅选择三局两胜。先赢两局获胜；平局补赛，连续三平结束。上一局败者选择先后攻，再用报名副卡换备。点卡片下方 ⇄ 选择换入和换出，一次应用；允许合法单向移动。三分区总清单保持不变，调整不覆盖原保存卡组。','Choose BO3 in game setup or the online lobby. First to two wins; draws are replayed, with three consecutive draws ending the match. The previous loser chooses turn order. Select ⇄ below cards and apply transfers together; legal one-way transfers are allowed. Every registered card stays in the match, and saved decks remain unchanged.','対戦設定またはオンラインロビーでBO3を選択できます。2勝先取。同点は再戦、3連続引き分けで終了します。前局の敗者が先後攻を選択。カード下の⇄で入替を選び、一括適用します。適正な片方向移動も可能です。登録カード総数を維持し、保存デッキは変更しません。')+'</p></section>';}
  root.DuelMatchUI={setup,history,title,panel,tr,help};
})(globalThis);
