(function(root){
'use strict';
const D=root.DuelData,T=root.DuelDecks,E=root.DuelDeckEditor,V=root.DuelView,I=root.DuelI18n,esc=V.escape,CARDS=I.cards;
const cards=D.CARD_LIST.filter(c=>!c.notCollectible),DRAFT='duel-sanctuary-workshop-draft-v3',clone=v=>JSON.parse(JSON.stringify(v));
const tr=(zh,en,ja)=>I.language==='en'?en:I.language==='ja'?ja:zh,zn=z=>I.term(z==='cards'?'主卡组':z==='extra'?'额外卡组':'副卡组');
const types=[['all','全部'],['monster','怪兽'],['spell','魔法'],['trap','陷阱'],['ritual','仪式'],['fusion','融合'],['synchro','同调'],['xyz','超量'],['link','连接'],['pendulum','灵摆'],['tuner','调整']];
function create(host){
let draft={name:I.term('我的新卡组'),cards:[],extra:[],side:[]},normalDraft=null,siding=null,draftRecovery=null,query='',family='all',year='all',type='all',page=0,focus='hero-sunrise',onlyIncluded=false,onlyPlayable=true,undo=[],redo=[],savedNote='',mobileView='build',addZone='auto',plan=[],deleteArmed=false;
try{const d=JSON.parse(localStorage.getItem(DRAFT)??localStorage.getItem('duel-sanctuary-workshop-draft-v2')??'null');if(d)draft=E.normalize(d);}catch{draftRecovery=localStorage.getItem(DRAFT);savedNote=tr('草稿读取失败，原数据已保留','Draft unreadable; original retained','下書きを読み込めません。元データは保存済み');}
const $=s=>document.querySelector(s),count=id=>E.zones.flatMap(z=>draft[z]).filter(x=>T.identity(x)===T.identity(id)).length;
function persist(){if(siding){siding.change?.(clone(draft));return;}try{if(draftRecovery!==null)localStorage.setItem(DRAFT+'-recovery',draftRecovery);localStorage.setItem(DRAFT,JSON.stringify(draft));draftRecovery=null;savedNote=I.term('草稿已自动保留');}catch{savedNote=I.term('草稿暂未保存，请导出备份');}}
function remember(){undo.push(clone(draft));if(undo.length>80)undo.shift();redo=[];plan=[];}
function changes(){persist();renderBuild();renderCollection();renderToolbar();renderInspector();}
function show(id=null){
 if(id&&siding)exitSiding();
 if(id&&D.DECKS[id]){remember();const d=D.DECKS[id];draft=d.custom?E.normalize(d):T.copy(id);focus=d.ace;persist();}
 const recovery=T.getDiagnostics().length?'<div class="ws-recovery" role="alert">'+tr('部分保存的卡组需要恢复，原数据已保留。','Some saved decks need recovery. Originals are retained.','保存デッキの一部は復旧が必要です。元データを保持しています。')+'<button data-action="ws-recovery">'+tr('导出恢复备份','Export recovery backup','復旧バックアップを出力')+'</button></div>':'';
 const body=recovery+'<div class="ws-toolbar" id="ws-toolbar"></div><div class="workshop-layout'+(siding?' ws-siding':'')+'"><aside class="ws-inspector" id="ws-inspector"></aside><section class="ws-build"><div class="ws-build-title"><small>'+(siding?'SIDE DECKING':'YOUR DECK')+'</small><span id="ws-draft-status"></span></div><label class="ws-name-label">'+I.term('卡组名称')+'<input id="ws-name" maxlength="40" data-user-content value="'+esc(draft.name)+'"'+(siding?' readonly':'')+'></label><div id="ws-build-content"></div>'+(!siding?'<label class="ws-notes">'+I.term('导入备注')+'<textarea id="ws-notes" maxlength="16000" data-user-content>'+esc(draft.notes||'')+'</textarea></label>':'')+'</section>'+
 (!siding?'<section class="ws-collection"><button class="ws-filter-toggle" id="ws-filter-toggle" data-action="ws-toggle-filters" aria-expanded="false"><span>'+I.term('筛选与搜索')+'</span><b id="ws-filter-result"></b></button><div class="ws-filter-content"><div class="ws-search"><label class="search-box"><input id="ws-search" type="search" placeholder="'+I.term('搜索卡名、效果或英文名…')+'" value="'+esc(query)+'" aria-label="'+I.term('搜索组卡牌库')+'"></label><select id="ws-family" aria-label="'+I.term('筛选卡片系列')+'">'+Object.entries(D.families).map(([id,label])=>'<option value="'+id+'"'+(family===id?' selected':'')+'>'+I.term(label)+'</option>').join('')+'</select><select id="ws-year" aria-label="'+I.term('组卡按发行年份筛选')+'">'+V.yearOptions(year)+'</select></div><div class="ws-filters" id="ws-filters"></div><div class="ws-collection-meta"><span id="ws-result-count"></span><label><input id="ws-included" type="checkbox"'+(onlyIncluded?' checked':'')+'>'+I.term('仅已编入')+'</label><label><input id="ws-playable" type="checkbox"'+(onlyPlayable?' checked':'')+'>'+I.term('仅可用于决斗')+'</label></div><button class="ws-filter-done" data-action="ws-toggle-filters">'+I.term('显示筛选结果')+'</button></div><label class="ws-add-target">'+tr('加入位置','Add to','追加先')+'<select id="ws-add-zone"><option value="auto">'+zn('cards')+' / '+zn('extra')+'</option><option value="side"'+(addZone==='side'?' selected':'')+'>'+zn('side')+'</option></select></label><div class="ws-card-grid" id="ws-card-grid"></div><div class="ws-pagination" id="ws-pagination"></div></section>':'')+'</div><input id="ws-import-file" type="file" accept=".json,.ydk,.txt,.ydke" hidden>';
 host.open('workshop',siding?tr('局间换备','Between games','サイドチェンジ'):I.term('构筑你的下一场胜利。'),'THE DECK ATELIER',body,
 '<span class="ws-footer-note">'+(siding?tr('报名卡池守恒 · 不修改原卡组','Registered cards only · original deck preserved','登録カードのみ・元デッキは変更しません'):I.term('本作不采用赛事禁限卡表 · 默认仅显示可用卡片'))+'</span><button class="secondary-button" data-action="close-modal">'+I.term('返回决斗')+'</button><button class="secondary-button" data-action="ws-save" id="ws-save">'+(siding?tr('确认换备并准备','Confirm & ready','確定して準備'):I.term('保存卡组'))+'</button>'+(!siding?'<button class="primary-button" data-action="ws-play" id="ws-play">'+I.term('保存并出战')+'</button>':''),'workshop-modal');
 renderToolbar();renderBuild();renderCollection();renderInspector();wireDrag();
}
function renderToolbar(){
 const el=$('#ws-toolbar');if(!el)return;
 el.innerHTML=(!siding?'<div class="ws-source"><label for="ws-source">'+I.term('从构筑开始')+'</label><select id="ws-source"><option value="">'+I.term('选择预设 / 已保存卡组')+'</option>'+T.list().map(d=>'<option '+(d.custom?'data-user-content ':'')+'value="'+d.id+'">'+esc(I.deck(d).name)+'</option>').join('')+'</select></div>':'')+'<div class="ws-tools">'+(!siding?'<button data-action="ws-new">'+I.term('＋ 空白卡组')+'</button><button data-action="ws-clone">'+I.term('复制当前')+'</button>':'')+'<button data-action="ws-undo"'+(!undo.length||siding?.locked?' disabled':'')+'>↶ '+I.term('撤销')+'</button><button data-action="ws-redo"'+(!redo.length||siding?.locked?' disabled':'')+'>↷ '+I.term('重做')+'</button>'+(!siding?'<button data-action="ws-import">'+I.term('导入')+'</button><button data-action="ws-ai-import">✧ '+I.term('AI 导入')+'</button><button data-action="ws-export">'+I.term('导出')+'</button>'+(draft.id?'<button data-action="ws-delete">'+I.term(deleteArmed?'确认删除？':'删除')+'</button>':''):'<button data-action="ws-reset-siding"'+(siding.locked?' disabled':'')+'>'+tr('恢复本轮开始','Reset this round','このラウンドをリセット')+'</button>')+'</div>'+(!siding?'<div class="ws-mobile-tabs"><button data-action="ws-view" data-view="build" class="'+(mobileView==='build'?'active':'')+'">'+I.term('当前构筑')+' '+draft.cards.length+' / '+draft.extra.length+' / '+draft.side.length+'</button><button data-action="ws-view" data-view="collection" class="'+(mobileView==='collection'?'active':'')+'">'+I.term('牌库 · 添加卡片')+'</button></div>':'');
 $('.workshop-layout').dataset.mobileView=siding?'build':mobileView;
}
function renderInspector(){
 const el=$('#ws-inspector');if(!el)return;const c=CARDS[focus]||CARDS[cards[0].id];focus=c.id;
 el.innerHTML='<button class="ws-mobile-close" data-action="ws-close-preview">'+I.term('关闭预览')+' ×</button><span class="ws-panel-kicker">CARD SPOTLIGHT</span><div class="ws-preview">'+V.card(c.id)+'</div><div class="ws-card-details">'+V.details(c.id)+'</div><div class="ws-location-counts">'+E.zones.map(z=>zn(z)+' '+draft[z].filter(id=>id===focus).length).join(' · ')+'</div>'+(!siding?'<div class="ws-preview-actions">'+['auto','side'].map(z=>'<button data-action="ws-add" data-zone="'+z+'" data-id="'+c.id+'"'+(count(c.id)>=3||c.implementationStatus==='pending'?' disabled':'')+'>＋ '+zn(z==='auto'?(D.isExtra(c)?'extra':'cards'):'side')+'</button>').join('')+'</div>':'');
}
function filtered(){const q=query.trim().normalize('NFKC').toLowerCase();return cards.filter(c=>V.yearMatch(c,year)&&(!onlyPlayable||c.implementationStatus!=='pending')&&(family==='all'||D.isFamily(c,family))&&(type==='all'||type==='monster'&&D.isMonster(c)||type==='tuner'&&c.tuner||c.type===type)&&(!onlyIncluded||count(c.id))&&(!q||I.searchText(c.id).includes(q)));}
function renderCollection(){
 if(!$('#ws-card-grid'))return;const size=host.getPageSize?.()||24,list=filtered(),pages=Math.max(1,Math.ceil(list.length/size));page=Math.max(0,Math.min(page,pages-1));
 $('#ws-filters').innerHTML=types.map(([id,label])=>'<button data-action="ws-filter" data-filter="'+id+'" class="'+(type===id?'active':'')+'">'+I.term(label)+'</button>').join('');
 $('#ws-result-count').textContent=list.length+' / '+cards.length;$('#ws-filter-result').textContent=String(list.length);
 $('#ws-card-grid').innerHTML=list.slice(page*size,page*size+size).map(raw=>{const c=CARDS[raw.id],n=count(c.id);return '<article class="ws-card'+(focus===c.id?' focused':'')+'" draggable="true" data-library-id="'+c.id+'"><button class="ws-card-face" data-action="ws-inspect" data-id="'+c.id+'" aria-label="'+esc(c.name)+'">'+V.card(c.id)+'</button><button class="ws-card-name" data-action="ws-inspect" data-id="'+c.id+'"><strong>'+esc(c.name)+'</strong><small>'+V.kind(c)+'</small><span>'+E.zones.map(z=>draft[z].filter(id=>id===c.id).length).join(' / ')+'</span></button><div class="ws-count-controls"><span>'+n+'/3</span><button data-action="ws-add" data-id="'+c.id+'" aria-label="'+I.term('加入')+' '+esc(c.name)+'"'+(n>=3||c.implementationStatus==='pending'?' disabled':'')+'>＋</button></div></article>';}).join('')||'<div class="empty-state">'+I.term('没有符合条件的卡片。')+'<button data-action="ws-reset-filters">'+I.term('清空筛选')+'</button></div>';
 $('#ws-pagination').innerHTML='<label class="page-size-control">'+I.term('每页')+' <select id="ws-page-size">'+root.DuelExperience.PAGE_SIZES.map(n=>'<option value="'+n+'"'+(size===n?' selected':'')+'>'+n+'</option>').join('')+'</select></label><div class="page-navigation"><button data-action="ws-page" data-delta="-1"'+(!page?' disabled':'')+'>←</button><label><input id="ws-page-jump" type="number" min="1" max="'+pages+'" value="'+(page+1)+'"> / '+pages+'</label><button data-action="ws-page" data-delta="1"'+(page>=pages-1?' disabled':'')+'>→</button></div>';
}
function pile(zone){
 const list=draft[zone];return '<section class="ws-pile" data-zone="'+zone+'"><div class="ws-pile-heading"><h3>'+zn(zone)+'</h3><b>'+list.length+' <small>/ '+(zone==='cards'?'40–60':'15')+'</small></b></div><div class="ws-deck-rows">'+(list.map((id,index)=>{const selected=plan.some(m=>m.from===zone&&m.index===index),c=CARDS[id],name=c?.name||id;return '<article class="ws-deck-row'+(selected?' planned':'')+'" draggable="true" data-zone="'+zone+'" data-index="'+index+'"><button data-action="ws-inspect" data-id="'+esc(id)+'" class="ws-deck-card" aria-label="'+esc(name)+'">'+(c?V.card(id):esc(id))+'</button><div class="ws-row-controls"><button data-action="ws-plan" data-zone="'+zone+'" data-index="'+index+'" aria-label="'+tr('选择换卡','Select transfer','入替を選択')+' '+esc(name)+'" aria-pressed="'+selected+'"'+(siding?.locked?' disabled':'')+'>'+(selected?'✓':'⇄')+'</button>'+(!siding?'<button data-action="ws-remove" data-zone="'+zone+'" data-index="'+index+'" data-id="'+esc(id)+'" aria-label="'+I.term('删除')+' '+esc(name)+'">−</button>':'')+'</div></article>';}).join('')||'<div class="ws-empty-pile">'+tr('从牌库添加，或从其他分区移入','Add from the library or transfer cards','ライブラリから追加、または他の区分から移動')+'</div>')+'</div></section>';
}
function renderBuild(){
 if(!$('#ws-build-content'))return;const check=E.check(draft,siding?.registered),s=check.stats||{};let info='',valid=false;
 if(plan.length)try{const n=E.move(draft,plan,{registered:siding?.registered,strict:!!siding||T.analyze(draft).valid});valid=true;info=n.cards.length+' / '+n.extra.length+' / '+n.side.length;}catch(e){info=e.message;}
 $('#ws-build-content').innerHTML='<div class="ws-type-counts"><span>'+I.term('怪兽')+' '+(s.monsters||0)+'</span><span>'+I.term('魔法')+' '+(s.spells||0)+'</span><span>'+I.term('陷阱')+' '+(s.traps||0)+'</span></div><div class="ws-validity '+(check.valid?'valid':'')+'" role="status"><b>'+I.term(check.valid?'✓ 构筑合法，可以出战':'◇ 继续完善你的卡组')+'</b><p>'+(check.valid?'40–60 / 0–15 / 0–15 · '+tr('三分区同名合计 ≤3','Up to 3 copies across all sections','全区分合計で同名3枚まで'):check.errors.map(e=>esc(I.text(e))).join('<br>'))+'</p></div><div class="ws-edit-bar"><span>'+tr('点 ⇄ 选择换入和换出，再应用。支持单向移动。','Select ⇄ on cards, then apply. One-way transfers allowed.','⇄で入替カードを選び、適用。片方向の移動も可能。')+'</span><button data-action="ws-sort"'+(siding?.locked?' disabled':'')+'>'+tr('排序','Sort','並べ替え')+'</button></div>'+(plan.length?'<div class="ws-plan" role="status"><b>'+plan.length+' ⇄ '+esc(I.text(info))+'</b><button data-action="ws-apply-plan"'+(!valid?' disabled':'')+'>'+tr('应用换卡','Apply transfers','入替を適用')+'</button><button data-action="ws-clear-plan">'+I.term('取消')+'</button></div>':'')+E.zones.map(pile).join('')+(siding?'<div class="ws-side-diff">'+E.diff(siding.baseline,draft).map(d=>'<p>'+zn(d.zone)+' '+(d.delta>0?'+':'')+d.delta+' '+esc(CARDS[d.id]?.name||d.id)+'</p>').join('')+'</div>':'');
 $('#ws-draft-status').textContent=siding?.locked?tr('已确认，等待对手','Confirmed; waiting for opponent','確定済み・相手を待機'):savedNote;
 for(const id of ['ws-save','ws-play'])if($('#'+id))$('#'+id).disabled=!check.valid||!!siding?.locked||plan.length>0;
}
function add(id,zone=addZone){if(siding)return;const c=CARDS[id];if(!c||c.notCollectible||c.implementationStatus==='pending')return;zone=zone==='side'?'side':D.isExtra(c)?'extra':'cards';if(count(id)>=3||draft[zone].length>=(zone==='cards'?60:15)){host.toast(tr('超过分区或同名上限','Section or copy limit reached','枚数または同名上限です'),true);return;}remember();draft[zone].push(id);focus=id;changes();}
function remove(id,zone,index){if(siding)return;zone=zone||(D.isExtra(CARDS[id])?'extra':'cards');const at=index===undefined?draft[zone].lastIndexOf(id):Number(index);if(at<0||draft[zone][at]!==id)return;remember();draft[zone].splice(at,1);changes();}
function applyPlan(){try{const next=E.move(draft,plan,{registered:siding?.registered,strict:!!siding||T.analyze(draft).valid});remember();draft=next;changes();}catch(e){host.toast(e.message,true);}}
async function save(play=false){try{if(siding){if(plan.length||siding.locked)return;await siding.submit(clone(draft));return;}draft=T.save(draft);persist();savedNote=I.term('已保存为可用卡组');renderToolbar();renderBuild();host.toast(I.term('卡组已保存。'));if(play)host.play(draft.id);}catch(e){host.toast(e.message,true);}}
function download(){try{const text=T.exportJSON(draft),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=draft.name.replace(/[<>:"/\\|?*]/g,'_')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}catch(e){host.toast(e.message,true);}}
function handle(action,b){
 if(!action.startsWith('ws-'))return false;
 if(siding&&['ws-new','ws-clone','ws-import','ws-ai-import','ws-delete','ws-play'].includes(action))return true;
 if(siding?.locked&&['ws-plan','ws-apply-plan','ws-sort','ws-undo','ws-redo','ws-reset-siding'].includes(action))return true;
 switch(action){
 case 'ws-toggle-filters':{const el=$('.ws-collection');mobileView='collection';renderToolbar();const open=el.classList.toggle('filters-open');$('#ws-filter-toggle').setAttribute('aria-expanded',String(open));break;}
 case 'ws-view':mobileView=b.dataset.view;renderToolbar();break;
 case 'ws-add':add(b.dataset.id,b.dataset.zone||addZone);break;
 case 'ws-remove':remove(b.dataset.id,b.dataset.zone,b.dataset.index);break;
 case 'ws-inspect':focus=b.dataset.id;renderInspector();$('#ws-inspector').classList.add('mobile-open');break;
 case 'ws-close-preview':$('#ws-inspector').classList.remove('mobile-open');break;
 case 'ws-plan':{const from=b.dataset.zone,index=Number(b.dataset.index),at=plan.findIndex(m=>m.from===from&&m.index===index);if(at>=0)plan.splice(at,1);else plan.push({from,index,to:from==='side'?(D.isExtra(CARDS[draft[from][index]])?'extra':'cards'):'side'});renderBuild();break;}
 case 'ws-apply-plan':applyPlan();break;case 'ws-clear-plan':plan=[];renderBuild();break;
 case 'ws-sort':remember();for(const z of E.zones)draft[z].sort((a,b)=>(CARDS[a]?.type||'').localeCompare(CARDS[b]?.type||'')||a.localeCompare(b));changes();break;
 case 'ws-reset-siding':if(siding){remember();draft=clone(siding.baseline);changes();}break;
 case 'ws-filter':type=b.dataset.filter;page=0;renderCollection();break;
 case 'ws-reset-filters':query='';family='all';year='all';type='all';onlyIncluded=false;onlyPlayable=true;page=0;show();break;
 case 'ws-page':page+=Number(b.dataset.delta);renderCollection();$('#ws-card-grid').scrollTop=0;break;
 case 'ws-new':remember();draft={name:I.term('我的新卡组'),cards:[],extra:[],side:[]};persist();show();break;
 case 'ws-clone':remember();draft={...clone(draft),name:(draft.name+' · '+I.term('副本')).slice(0,40)};delete draft.id;persist();show();break;
 case 'ws-undo':if(undo.length){redo.push(clone(draft));draft=undo.pop();plan=[];persist();show();}break;
 case 'ws-redo':if(redo.length){undo.push(clone(draft));draft=redo.pop();plan=[];persist();show();}break;
 case 'ws-recovery':{const values={};for(const key of [T.STORAGE,T.STORAGE+'-recovery','duel-sanctuary-custom-decks-v2',DRAFT,DRAFT+'-recovery'])values[key]=localStorage.getItem(key);const url=URL.createObjectURL(new Blob([JSON.stringify(values,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='deck-recovery.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);break;}
 case 'ws-save':save();break;case 'ws-play':save(true);break;case 'ws-export':download();break;case 'ws-import':$('#ws-import-file').click();break;case 'ws-ai-import':host.aiImport();break;
 case 'ws-delete':if(draft.id){if(!deleteArmed){deleteArmed=true;renderToolbar();setTimeout(()=>{deleteArmed=false;renderToolbar();},4500);}else try{T.remove(draft.id);delete draft.id;deleteArmed=false;persist();renderToolbar();}catch(e){host.toast(e.message,true);}}break;
 }return true;
}
function input(el){if(el.id==='ws-search'){query=el.value;page=0;renderCollection();return true;}if(!siding&&el.id==='ws-name'){draft.name=el.value;persist();renderBuild();return true;}if(!siding&&el.id==='ws-notes'){draft.notes=el.value;persist();return true;}return false;}
async function change(el){
 if(el.id==='ws-add-zone'){addZone=el.value;return;}if(el.id==='ws-page-size'){host.setPageSize?.(el.value);page=0;}if(el.id==='ws-page-jump')page=Math.max(0,Math.floor(Number(el.value)||1)-1);
 if(el.id==='ws-year'){year=el.value;page=0;}if(el.id==='ws-family'){family=el.value;page=0;}if(el.id==='ws-playable'){onlyPlayable=el.checked;page=0;}if(el.id==='ws-included'){onlyIncluded=el.checked;page=0;}
 if(el.id==='ws-source'&&el.value){show(el.value);return;}
 if(el.id==='ws-import-file'&&el.files?.[0]&&!siding){try{const file=el.files[0];if(file.size>100000)throw Error(I.term('卡组文件过大，请选择导出的 JSON 卡组。'));const text=await file.text();let imported;if(text.trim().startsWith('{')){const obj=JSON.parse(text);if(Array.isArray((obj.deck||obj).cards))imported=E.normalize(obj.deck||obj);}if(!imported){const parsed=root.DuelDeckParse.parse(text),resolver=root.DuelCardResolver.create();imported=resolver.draft(resolver.resolveDeck(parsed.decks[0])).deck;}importDraft(imported);}catch(e){host.toast(e.message,true);}finally{el.value='';}return;}renderCollection();
}
function importDraft(value){if(siding)exitSiding();remember();draft=E.normalize(value);persist();show();}
function showSiding(config){if(!siding){normalDraft=clone(draft);undo=[];redo=[];}if(siding?.roundId!==config.roundId){draft=E.normalize(config.draft||config.baseline);plan=[];undo=[];redo=[];}siding=config;show();}
function exitSiding(){if(!siding)return;siding=null;draft=normalDraft;normalDraft=null;plan=[];undo=[];redo=[];}
function wireDrag(){
 const layout=$('.workshop-layout');layout.ondragstart=e=>{if(siding?.locked)return;const row=e.target.closest('.ws-deck-row'),card=e.target.closest('[data-library-id]');if(row||card)e.dataTransfer.setData('application/x-duel-card',JSON.stringify(row?{from:row.dataset.zone,index:Number(row.dataset.index)}:{id:card.dataset.libraryId}));};
 layout.ondragover=e=>{if(e.target.closest('.ws-pile'))e.preventDefault();};
 layout.ondrop=e=>{const target=e.target.closest('.ws-pile');if(!target||siding?.locked)return;e.preventDefault();try{const m=JSON.parse(e.dataTransfer.getData('application/x-duel-card'));if(m.id){if(target.dataset.zone!=='side'&&(D.isExtra(CARDS[m.id])?'extra':'cards')!==target.dataset.zone)throw Error(tr('分区类型不匹配','Wrong card section','カード区分が違います'));add(m.id,target.dataset.zone);return;}const next=E.move(draft,[{...m,to:target.dataset.zone}],{registered:siding?.registered,strict:!!siding||T.analyze(draft).valid});remember();draft=next;changes();}catch(error){host.toast(error.message,true);}};
}
return {show,showSiding,exitSiding,handle,input,change,importDraft,get draft(){return clone(draft);}};
}
root.DuelWorkshop={create};
})(globalThis);
