/* Representative annual builds. Sources and adaptations: docs/decks-2006-2008.md. */
(function(root){
 'use strict';const D=root.DuelData;if(D.yearDecksLoaded)return;
 const id=n=>{const c=D.cardByName(n);if(!c)throw new Error('Missing annual deck card: '+n);return c.id;},expand=p=>p.flatMap(([n,c])=>Array(c).fill(id(n)));
 function add(key,year,title,en,ace,description,pairs,extra=[],combo=[]){const cards=expand(pairs),ex=expand(extra);if(cards.length!==40)throw new Error(key+' has '+cards.length+' cards');for(const cid of [...cards,...ex])if(!D.CARDS[cid].releaseYear||D.CARDS[cid].releaseYear>year)throw new Error('Future card in '+key+': '+cid);D.DECKS[key]={id:key,name:title+' · '+year,en,ace:id(ace),mechanic:year+' / '+title,description,player:title,avatar:'early',subtitle:'重返这一年的决斗现场。',preset:true,year,sourceKind:'representative-adaptation',cards,extra:ex,combo};}
 add('chaos-return-2006',2006,'混沌回归','CHAOS RETURN','Chaos Sorcerer','2006 世界赛前三均围绕混沌展开。用光暗墓地和异次元归还组织反击，保留除外资源完成最后一击。',[
 ['Chaos Sorcerer',3],['Cyber Dragon',2],['Jinzo',1],['Airknight Parshath',1],['Dark Magician of Chaos',1],['Dekoichi the Battlechanted Locomotive',3],['Magician of Faith',2],['Shining Angel',2],['Sangan',1],['Spirit Reaper',1],["Gravekeeper's Spy",2],['Tsukuyomi',1],
 ['Graceful Charity',1],['Heavy Storm',1],['Mystical Space Typhoon',1],['Nobleman of Crossout',1],['Book of Moon',1],['Snatch Steal',1],['Premature Burial',1],['Scapegoat',1],['Enemy Controller',2],['Pot of Avarice',1],['Smashing Ground',1],
 ['Return from the Different Dimension',2],['Sakuretsu Armor',2],['Torrential Tribute',1],['Mirror Force',1],['Call of the Haunted',1],['Bottomless Trap Hole',1]],[],['光与暗各除外一只，呼唤混沌巫师。','异次元归还支付一半生命值，结束阶段会再次除外召回的怪兽。']);
 add('frog-monarch-2006',2006,'黄泉帝','FROG MONARCH','Thestalos the Firestorm Monarch','以树黄泉提供解放资源，炎帝、雷帝与冰帝分别处理手牌、怪兽和后场。与混沌、融合两套构筑形成不同节奏。',[
 ['Thestalos the Firestorm Monarch',3],['Zaborg the Thunder Monarch',2],['Mobius the Frost Monarch',1],['Cyber Dragon',2],['Treeborn Frog',1],['Sangan',1],['Apprentice Magician',2],['Old Vindictive Magician',1],['Magician of Faith',1],['Dekoichi the Battlechanted Locomotive',3],['Spirit Reaper',1],["Gravekeeper's Spy",2],
 ['Brain Control',2],['Soul Exchange',2],['Graceful Charity',1],['Heavy Storm',1],['Mystical Space Typhoon',1],['Nobleman of Crossout',1],['Premature Burial',1],['Book of Moon',1],['Snatch Steal',1],
 ['Sakuretsu Armor',2],['Bottomless Trap Hole',2],['Torrential Tribute',1],['Mirror Force',1],['Call of the Haunted',1],['Raigeki Break',2]],[],['清空自己的魔法陷阱区，让树黄泉在准备阶段复活。','帝的效果需要真正解放召唤；普通特殊召唤不会触发。']);
 add('chimeratech-2006',2006,'嵌合超载','CHIMERATECH OVERLOAD','Chimeratech Overdragon','机械族积累墓地，超载融合将电子龙和机械素材除外。力量焊接提供另一条融合路线，需要计算结束阶段的生命值代价。',[
 ['Cyber Dragon',3],['Proto-Cyber Dragon',3],['Dekoichi the Battlechanted Locomotive',3],['Blowback Dragon',2],['Cyber Phoenix',2],['Drillroid',2],['Card Trooper',2],['Cyber-Stein',1],['Magician of Faith',1],['Sangan',1],
 ['Power Bond',2],['Overload Fusion',2],['Future Fusion',1],['Limiter Removal',1],['Heavy Storm',1],['Giant Trunade',1],['Mystical Space Typhoon',1],['Graceful Charity',1],['Scapegoat',1],['Premature Burial',1],
 ['Mirror Force',1],['Torrential Tribute',1],['Call of the Haunted',1],['Sakuretsu Armor',2],['Threatening Roar',3]], [['Chimeratech Overdragon',3],['Cyber Twin Dragon',2],['Cyber End Dragon',2],['Gatling Dragon',1]],['卡片炮击士以送墓代价积累机械素材。','未来融合使用当前卡文，需要等到后续两个准备阶段。']);
 add('trooper-monarch-2007',2007,'卡炮帝','TROOPER MONARCH','Raiza the Storm Monarch','参考 2007 世界冠军 Andres Toro 的卡炮帝思路改编。炮击士、黄泉和夺取控制权的魔法支撑帝的解放召唤。',[
 ['Raiza the Storm Monarch',3],['Thestalos the Firestorm Monarch',2],['Mobius the Frost Monarch',1],['Cyber Dragon',3],['Card Trooper',3],['Treeborn Frog',1],['Sangan',1],['Dekoichi the Battlechanted Locomotive',2],["Gravekeeper's Spy",2],['Spirit Reaper',1],['Magician of Faith',1],
 ['Brain Control',3],['Soul Exchange',2],['Pot of Avarice',2],['Mystical Space Typhoon',1],['Heavy Storm',1],['Premature Burial',1],['Enemy Controller',1],['Snatch Steal',1],
 ['Sakuretsu Armor',2],['Bottomless Trap Hole',2],['Mirror Force',1],['Torrential Tribute',1],['Call of the Haunted',1],['Trap Dustshoot',1]],[],['风帝将卡片放回卡组顶，压缩对手下一回合的选择。','贪欲之壶回收五只怪兽，必须在结算时仍有五个对象。']);
 add('machine-gadget-2007',2007,'机械齿轮','MACHINE GADGET','Cyber Dragon','参考 2007 世界亚军机械强攻与当年八强齿轮构筑。三色齿轮持续检索，机械复制术和限制解除制造进攻窗口。',[
 ['Green Gadget',2],['Red Gadget',2],['Yellow Gadget',2],['Cyber Dragon',3],['Card Trooper',3],['Dekoichi the Battlechanted Locomotive',3],['Cyber Phoenix',2],['Drillroid',2],['Sangan',1],
 ['Machine Duplication',3],['Shrink',3],['Limiter Removal',1],['Heavy Storm',1],['Mystical Space Typhoon',1],['Brain Control',1],['Pot of Avarice',1],['Overload Fusion',1],
 ['Sakuretsu Armor',2],['Bottomless Trap Hole',2],['Mirror Force',1],['Torrential Tribute',1],['Call of the Haunted',1],['Solemn Judgment',1]], [['Chimeratech Overdragon',2],['Chimeratech Fortress Dragon',2]],['召唤齿轮获得下一种颜色，维持手牌资源。','机械复制术要求目标当前攻击力不超过500，强化炮击士前先判断顺序。']);
 add('burn-2007',2007,'连锁削血','CHAIN BURN','Lava Golem','参考 2007 世界季军 Adam Corn 的削血路线改编。熔岩魔神处理双怪，隐形鸟和波动加农炮施压，防御陷阱争取回合。',[
 ['Lava Golem',2],['Stealth Bird',3],['Des Koala',3],['Outstanding Dog Marron',1],['Spirit Reaper',1],['Marshmallon',1],['Magician of Faith',1],['Mask of Darkness',1],['D.D. Crow',1],['Cyber Dragon',1],
 ['Level Limit - Area B',1],['Wave-Motion Cannon',3],['Messenger of Peace',2],['Book of Moon',1],['Swords of Revealing Light',1],['Mystical Space Typhoon',1],['Chain Strike',1],
 ['Secret Barrel',3],['Just Desserts',3],['Threatening Roar',3],['Reckless Greed',2],['Gravity Bind',1],['Mirror Force',1],['Torrential Tribute',1],['Accumulated Fortune',1]],[],['对方控制两只怪兽时，用熔岩魔神解放它们。','连锁爆击和积累的幸福有连锁层数与同名限制，不能当作普通抽卡牌随时发动。']);
 add('gladiator-2008',2008,'剑斗凯旋','GLADIATOR BEAST','Gladiator Beast Gyzarus','2008 世界冠亚军都是剑斗兽；这里保留一套剑斗，并用光道与 TeleDAD 补足三种玩法。战后换人与凯撒融合是核心。',[
 ['Gladiator Beast Laquari',3],['Gladiator Beast Bestiari',2],['Gladiator Beast Equeste',2],['Gladiator Beast Darius',2],['Gladiator Beast Murmillo',1],['Gladiator Beast Hoplomus',1],['Gladiator Beast Secutor',1],['Test Tiger',3],['Elemental HERO Prisma',2],['Rescue Cat',1],['Gladiator Beast Samnite',1],['Sangan',1],
 ['Gladiator Proving Ground',3],['Book of Moon',2],['Smashing Ground',1],['Mystical Space Typhoon',1],['Heavy Storm',1],['Monster Reborn',1],['Cold Wave',2],['Enemy Controller',1],
 ['Gladiator Beast War Chariot',3],['Solemn Judgment',3],['Mirror Force',1],['Torrential Tribute',1]], [['Gladiator Beast Gyzarus',3],['Gladiator Beast Heraklinos',2],['Gladiator Beast Gaiodiaz',1],['Chimeratech Fortress Dragon',1]],['战斗后把剑斗兽洗回卡组，换入具有登场效果的同伴。','凯撒使用剑斗兽 枪斗和另一只剑斗兽接触融合；战车要求场上有表侧剑斗兽。']);
 add('lightsworn-2008',2008,'光道审判','LIGHTSWORN','Judgment Dragon','参考 2008 世界季军光道与当年主流构筑。太阳交换与结束阶段送墓积累四种光道，审判之龙清场。',[
 ['Judgment Dragon',2],['Lumina, Lightsworn Summoner',3],['Lyla, Lightsworn Sorceress',3],['Ryko, Lightsworn Hunter',2],['Wulf, Lightsworn Beast',3],['Garoth, Lightsworn Warrior',2],['Jain, Lightsworn Paladin',2],['Celestia, Lightsworn Angel',2],['Honest',3],['Necro Gardna',3],['Plaguespreader Zombie',1],['Card Trooper',1],
 ['Solar Recharge',3],['Monster Reincarnation',2],['Card Destruction',1],['Foolish Burial',2],['Monster Reborn',1],['Heavy Storm',1],['Mystical Space Typhoon',1],['Beckoning Light',2]], [['Stardust Dragon',1],['Black Rose Dragon',1],['Brionac, Dragon of the Ice Barrier',1],['Colossal Fighter',1],['Thought Ruler Archfiend',1],['Magical Android',1],['Ally of Justice Catastor',1]],['沃尔夫从卡组送墓会特殊召唤；从手牌丢弃没有这个效果。','光道会不断消耗卡组，及时转入进攻并留意剩余张数。']);
 add('teledad-2008',2008,'念动力暗武','TELE-DAD','Dark Armed Dragon','2008 下半年的 TeleDAD 代表构筑：命运抽卡、紧急瞬间移动和恶意人连接同调路线，暗黑武装龙要求墓地恰好三只暗属性怪兽。',[
 ['Dark Armed Dragon',2],['Destiny HERO - Malicious',3],['Elemental HERO Stratos',1],['Destiny HERO - Diamond Dude',1],['Dark Grepher',2],['Armageddon Knight',2],['Krebons',3],['Plaguespreader Zombie',1],['Sangan',1],['D.D. Crow',1],['Tragoedia',1],['The Dark Creator',1],['Breaker the Magical Warrior',1],
 ['Destiny Draw',3],['Allure of Darkness',3],['Emergency Teleport',3],['Reinforcement of the Army',2],['Monster Reborn',1],['Heavy Storm',1],['Mystical Space Typhoon',1],['Brain Control',1],['Foolish Burial',1],['Pot of Avarice',1],['Crush Card Virus',1],['Mirror Force',1],['Torrential Tribute',1]], [['Stardust Dragon',2],['Colossal Fighter',2],['Thought Ruler Archfiend',1],['Red Dragon Archfiend',1],['Black Rose Dragon',1],['Goyo Guardian',1],['Magical Android',1],['Ally of Justice Catastor',1],['Gaia Knight, the Force of Earth',1]],['恶意人从墓地除外展开，克雷本斯提供2星调整。','紧急瞬间移动的怪兽结束阶段除外；提前作为同调素材可利用其等级。']);
 D.yearDecksLoaded=true;if(typeof module!=='undefined')module.exports=D;
})(globalThis);
